### ISSUE TITLE
Defunct?

### ISSUE THREAD

**Issue by Theaxiom** [RocketChat/Rocket.Chat.Android#1]
Is this repo defunct, or deprecated by the Cordova repo?

**Comment by rodrigok** [comment]
No, we are looking for developers that want to help us to create the Rocket.Chat native app for Android.

**Comment by 3mpty** [comment]
If you're still looking for help with native Android version mail me

**Comment by graywolf336** [comment]
@3mpty Join us on the demo server and we can talk about it.

**Comment by prohde** [comment]
Should the native app for Android be able to connect to other servers than the demo server one day?
