### ISSUE TITLE
[v1.0-beta] Permissions

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat.Android#100]
The app should ask for any permission it may need.

**Comment by YusukeIwaki** [comment]
* Recording (for voice call)
* Camera (for video meeting)
* Location (for sharing current location)

for using these feature, asking permission is required in API 23+.

Do we support these features in v1.0-beta?

**Comment by laggedHero** [comment]
Yes, we need it. Otherwise, the app will just crash.

But, as of now, we only need local storage access. I was trying to send a file yesterday and the app crashed because of that.

Since we do not have anything using the camera, voice or location... we don't need to ask for that ones.

**Comment by YusukeIwaki** [comment]
Ah stroage access. I see.
