### ISSUE TITLE
[NEW] Make the "tracking" of Fabric/Analytics optional in "Settings"

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1001]
All kind of tracking in our app needs to be a user's choice. By default this flag is TRUE now, because we want to track the crashes, but if someone wants to disable it, the user needs to be able to disable via settings.

**Comment by localguru** [comment]
I personally support tracking, but for data protection reasons I do not consider it permissible to switch it on by default. The more polite option would be to ask the user nicely during/after the installation if he wants to enable tracking to support the project.

In my environment of a public institution I therefore have to inform the users. I would therefore be pleased if the feature is not activated automatically.

**Comment by rafaelks** [comment]
@localguru All kind of tracking that we do is anonymous and do not have any sensitive content on it, just "actions" that the user is doing, such like sending message, reactions, etc. Also this specific issue can be closed already because the tracking is already optional in Preferences. Let me know if you've other suggestions, I'm sure we can improve it! This one that you just gave looks like a good idea.
