### ISSUE TITLE
[CRASH][v2-beta1] App crashes on opening

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#1004]
Your Rocket.Chat.Android version: 2.0.0-beta1

Mobile device model and OS version: Samsung S8 Android 8.0

As soon as start the app, the app crashes. But before the crash i can see the pop up error related to this issue and PR.
https://github.com/RocketChat/Rocket.Chat.Android/pull/999  
https://github.com/RocketChat/Rocket.Chat.Android/issues/978

**Comment by mmarif4u** [comment]
I went ahead, and cleared the app data and cache. Which at least bring up the server url page, and after that login screen. After login, the app crashed.

**Comment by rafaelks** [comment]
@mmarif4u Thank you for reporting the crash! We already saw what's happening and it's related to versions of the servers below 0.63 (in RC right now). We'll work today to release another build containing the fixes. 👍

**Comment by mmarif4u** [comment]
Thanks @rafaelks, I believe 0.63 is not released yet. Maybe disable the features which requires that version for now. And use the currently available APIs of 0.62.2.

Waiting for the fix release. :+1:

**Comment by rafaelks** [comment]
Issue was closed by #1005.
