### ISSUE TITLE
[FEATURE REQUEST/IMPROVEMENT] Alternating Chat Bubbles

### ISSUE THREAD

**Issue by Drangleic** [RocketChat/Rocket.Chat.Android#1006]
Description:
One of the features we'd like to see is to have chats (both DMs and group chats) come from alternating sides of the window based on who is sending it. As in Google Hangouts (and numerous other chat applications), a user's own chats appear on the right hand side of the window, and chats from other users appear on the left. We would highly appreciate the ability to toggle this on or off (would be great if it was a user setting), as it really improves clarity and speed when reading chats. This is especially true if you are reading back through a long conversation.

Please let us know if you would like additional description as to what we're talking about, or if this should be posted elsewhere.

Thanks!

**Comment by Shailesh351** [comment]
Yes @Drangleic I was also thinking on the same. Have you checked Telegram X providing option for toggling Bubble mode? It is really nice.
Thanks!!

**Comment by rafaelks** [comment]
Closing per my comment on your issue for iOS project.

**Comment by HammyHavoc** [comment]
Would like to see bubbles as an option. This is a must for glancing at the chat whilst on the move in the field.
