### ISSUE TITLE
[QUESTION][OAUTH] GitLab self hosted logins

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#1010]
Your Rocket.Chat.Android version: 2.0.0 beta1

GitLab authentication is implemented in the beta, and i can see it works with gitlab.com. Is there any plan to support on premise hosted version. Which reads RC Oauth methods enabled and based on that allow logins.

Our RC currently authenticate through our self hosted GitLab instance. This was the feature i was looking forward to, but it seems its not there yet.

**Comment by rafaelks** [comment]
@mmarif4u Yes, this is going to be implemented on this issue: https://github.com/RocketChat/Rocket.Chat.Android/issues/322.

I'm gonna close the issue now so we don't keep things duplicated. 👍

**Comment by mmarif4u** [comment]
Thanks @rafaelks. Sorry for the duplicate.
