### ISSUE TITLE
[BUG] Adding emoji and emoji touch doesn't work in pinned activity

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1012]
**Your Rocket.Chat.Android version: (make sure you are running the latest)**

versionCode 2001
versionName "2.0.0-beta1"

**Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")**
Nexus 6 - Android 7.1

![](https://im.ezgif.com/tmp/ezgif-1-ec8a8fcefa.gif)

**Comment by rafaelks** [comment]
@divyanshub024 This issue happens when you're not running 0.63.rc-2 or greater, the API doesn't exists.
