### ISSUE TITLE
Can not Build in Android studio.

### ISSUE THREAD

**Issue by kdnwnd0527** [RocketChat/Rocket.Chat.Android#1018]
Android Studio Version 3.1
Gradle Version 3.1.0
Kotlin Version 1.2.31
Java Version 1.8.0_161

download Rocket.Chat.Android-devleop-2.x  from github.
https://github.com/RocketChat/Rocket.Chat.Android

I unzipped the file and imported it from the Android studio.

1. I modified the information in the kotlin version of the dependencies.gradle file.
ext {
       version {
              kotlin : '1.21.31' Existing : 1.2.30 / After change : 1.2.31
              ....

2. I did a build, but failed, and the error appeared as shown below.

![image](https://user-images.githubusercontent.com/36613638/38288227-57e487a6-380a-11e8-8469-8c4f73a762de.png)

I would like to know how to solve these problems.

**Comment by mmarif4u** [comment]
Hi, 
Have you followed this https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/README.md. Its quite straight forward. I am not sure if you downloaded the SDK too.

**Comment by kdnwnd0527** [comment]
@mmarif4u The same error occurs when I try to follow the method you gave me. And after downloading the SDK, do I just need to build it after importing it to the Android studio?

**Comment by mmarif4u** [comment]
@kdnwnd0527 you have to clone/download the sdk and app in one folder like, `rocket/android-app` and `rocket/android-sdk-kotlin`. Then follow how to build,https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/README.md#v2. 

I would prefer(Linux), cd to the sdk dir and build it there by `./gradlew clean && ./gradlew assemble`, after that import the Android project to studio and build. Hope this help.

**Comment by kdnwnd0527** [comment]
@mmarif4u I appreciate your reply.
I want to work in Windows environment, is it impossible to work?

**Comment by mmarif4u** [comment]
@kdnwnd0527 sorry i cant help in that regard. But i believe it will require to setup all the prerequisites.

**Comment by kdnwnd0527** [comment]
@mmarif4u Thank you. I will run it in Linux environment.

**Comment by rafaelks** [comment]
Closing the issue for now @kdnwnd0527. Thanks for the help @mmarif4u!
