### ISSUE TITLE
[V2.0BETA3][CONNECTION] App connection issue to the RC server

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#1019]
Your Rocket.Chat.Android version: 2.0.0 beta 3

Last time i bring this issue to the RC open chat android channel too. And that issue continues, where the app trying to connect to the RC server. While connecting it crash the RC server instance too. I have checked the server logs and found this at the time when it was attempting to connect.

```
"http://127.0.0.1:3000/avatar/@CHANNEL?format=jpeg", host: "team.WEBSITE.com"
2018/04/04 13:06:05 [error] 8297#8297: *121687 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.yy.xxx.yy, server: team.WEBSITE.com, request: "GET /avatar/@CHANNEL?format=jpeg HTTP/1.1", upstream: "http://127.0.0.1:3000/avatar/@CHANNEL?format=jpeg", host: "team.WEBSITE.com"
2018/04/04 13:06:05 [error] 8297#8297: *121687 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.yy.xxx.yy, server: team.WEBSITE.com, request: "GET /avatar/@CHANNEL?format=jpeg HTTP/1.1", upstream: "http://127.0.0.1:3000/avatar/@CHANNEL?format=jpeg", host: "team.WEBSITE.com"
```

Something to do with retrieving channel/user avatars?. The app also some time shows JSON errors while connecting. Which i assume is related to the json output from the API call.

Android logs, https://open.rocket.chat/channel/androidnativeapp?msg=ACg2JZC6EdKpKcgYi

@rafaelks

**Comment by mmarif4u** [comment]
RC snap is updated to 0.63.0, and after checking this morning, this is the error now:

`
2018/04/05 10:48:02 [error] 8297#8297: *135538 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.yyy.xx.yy, server: team.WEBSITE.com, request: "GET /sockjs/info?cb=izp3r5sdg2eh HTTP/1.1", upstream: "http://127.0.0.1:3000/sockjs/info?cb=izp3r5sdg2eh", host: "team.WEBSITE.com", referrer: "https://team.WEBSITE.com/channel/CHANNEL-NAME"
`

**Comment by HammyHavoc** [comment]
I get endless "connecting" with countdown messages on my Android phone before it eventually crashes.

**Comment by ccfiel** [comment]
same here :(

**Comment by rafaelks** [comment]
@mmarif4u @HammyHavoc @ccfiel Thank you guys for opening the issue! So the problem is that your instance is dying when connecting to the Android app? I'm imagining that the issue related to the request that we're doing for the image in *JPEG* format. If that's the case, I'll move this issue to our back-end repository. Can you please confirm?

**Comment by HammyHavoc** [comment]
@rafaelks Spot on! :- ) This is correct.

**Comment by rafaelks** [comment]
Issue moved to [RocketChat/Rocket.Chat #10363](https://github.com/RocketChat/Rocket.Chat/issues/10363) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mmarif4u** [comment]
@rafaelks yes thats right. As @HammyHavoc mentioned above, the app shows count down message. While it is happening the rc server also shows the same count down. Could be some malformed json. But not so sure. This same app was working until dev7 without any change to the server.

**Comment by rafaelks** [comment]
@mmarif4u Yes, looks like the instance is crashing and the reason is probably because we started requesting the assets in JPEG instead of SVG. 👍

**Comment by rafaelks** [comment]
@mmarif4u What version of the server are you guys using?

**Comment by mmarif4u** [comment]
We are on 0.63.0 via snap.

**Comment by ccfiel** [comment]
same here snap 0.63.0

**Comment by rafaelks** [comment]
Great, thanks for the feedback! We'll be looking into the issue in our back-end team. 👍
