### ISSUE TITLE
[BUG] Lost of gcm token

### ISSUE THREAD

**Issue by mrhenryl** [RocketChat/Rocket.Chat.Android#1020]
2.0.0-alpha1
Mobile device model and OS version: (Samsung Galaxy S8 - Android 7)

1. Logout
2. GCM token will be removed in "push_app_tokens"
3. Login again
4. GCM token cannot be registered in "push_app_tokens", unless to remove the app and install again.

Problem: cannot receive push notification after logging out and login again.

**Comment by rafaelks** [comment]
@mrhenryl Do you see some error message?

**Comment by mrhenryl** [comment]
There is no error message. Just cannot receive push notification after a logout/login operation in Android phone. And it was found that the gcm token in "push_app_tokens" table was gone after logout.

**Comment by rafaelks** [comment]
@mrhenryl We'll confirm if this is happening in latest build, can you also give it a try please? Thank you!

**Comment by rafaelks** [comment]
Closing it for non-activity.

**Comment by rafaelks** [comment]
@leonardoaramaki This was reproduced again... need to fix it.

**Comment by rafaelks** [comment]
This one is fixed on 2.3.0 already.
