### ISSUE TITLE
[QUESTION] develop-2.0 branch doesn't build

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#1021]
Logfile attached. I'm using the `develop` branch of the SDK.
[gradle.log](https://github.com/RocketChat/Rocket.Chat.Android/files/1874985/gradle.log)

**Comment by antgel** [comment]
@rafaelks Any clues on this? Surely it builds for everyone else? :laughing:

**Comment by mmarif4u** [comment]
I have just build it from the sources and all is good.

Maybe you can pull from both repos, and run `clean project` and `rebuild project` in Android Studio under Build.

**Comment by antgel** [comment]
Indeed it's fine now. Weird. Thanks.
