### ISSUE TITLE
[IMPROVEMENT] Area for long-press context-menu too small

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat.Android#1022]
Your Rocket.Chat.Android version: 2.0.0-rc1
Mobile device model: Xiaomi Redmi Note 3 (kate)
OS version: Lineage OS 14.1, latest nightly

**Description (screenshot below description)**

Right now the context menu for long-pressing a message (e.g. to react with an emoji or to "reply") is only working for the **green area**. If I long-press the **red area** I would expect the same to happen, but it's just not happening anything (except for the light grey which indicates I'm pressing)

Especially with one-line messages the green area is pretty hard to "hit" (at least with my "sausage-fingers", as we say in Germany).

Concerning the **blue area** (which seems to be a quote, right) I'm not quite sure whether the user would expect that his long-press refers to the post containing the quote or the original quote...

**Screenshot**

![screenshot_20180404-131531](https://user-images.githubusercontent.com/179595/38328109-4de4c672-384a-11e8-8bbf-1a6955391494.png)

**Comment by rafaelks** [comment]
@TwizzyDizzy Thanks for opening the issue, this one will certainly be addressed soon. 👍

**Comment by TwizzyDizzy** [comment]
BTW: The mattermost Android App has this issue, too, so this is the time to leave them behind ;)

**Comment by rafaelks** [comment]
Closed by #1227

**Comment by TwizzyDizzy** [comment]
Ahhhh... finally possible :tada: :)
