### ISSUE TITLE
[INVESTIGATE] Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by GezimSejdiu** [RocketChat/Rocket.Chat.Android#1023]
### **Description**:
The Android version ([Beta 3](https://github.com/RocketChat/Rocket.Chat.Android/releases/tag/v2.0.0-beta3)) not able to read the channels properly (#random and #general channel). It throws `Cannot read property 'includes' of undefined`.

### **Server Setup Information**:
Rocket.Chat Server: 0.63.0
Operating System: Linux

### **Mobile device model and OS version**: 
* Nexus 5 - Android 6.0.1

### **Steps to reproduce**:
I'm not able to reproduce the steps since the exception seems to be related to the content of the respective channels. The same works with open.rocket.chat server.

**Comment by rafaelks** [comment]
@GezimSejdiu Thanks for opening the issue. What channel is possible to see the issue in `open.rocket.chat`?

**Comment by GezimSejdiu** [comment]
Hi @rafaelks ,
many thanks for the reply. I was trying some channels on the `open.rocket.chat` but couldn't get the same error. 
When I open [#androiddeveloper](https://open.rocket.chat/channel/androiddeveloper) it stops working. If I will find some time during next days to debug by my self would be better I guess. 

Seems that there is something on the channel (content-wise) which can't be read by the app (not able to share the content of the channel :) sorry).

Best regards,

**Comment by rafaelks** [comment]
Reported again from another user:

![screenshot_20180405-203230](https://user-images.githubusercontent.com/551004/38418784-357232b6-3974-11e8-8620-7cac68bc224c.png)

**Comment by JackNWeems** [comment]
I'm having the same issue, I get this error when I connect to any public channel on our self hosted rocket chat server. Interestingly private channels seem to work just fine. I'm willing to help debug or test if needed.

**Comment by luciofm** [comment]
@JackNWeems can you confirm the server version and the app version please.

**Comment by JackNWeems** [comment]
Server version 0.63.1 App version 2.0.1 Build#2001

**Comment by rafaelks** [comment]
Guys, we just discovered that this is a bug in our back-end and this is going to be addressed very soon! Thank you all for the feedback!
