### ISSUE TITLE
[BUG] The words written using swype (Google keyboard) are not always displayed in the text box

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1025]
Your Rocket.Chat.Android version: 2.0.0-beta3
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.3.22) , Developer ROM

When I write with swype something in the russian layout on the Google keyboard, the words written in this way are not always inserted into the text field. Sometimes they just disappear as if I did not print (swype) them.
![20180405_105725](https://user-images.githubusercontent.com/18574776/38353853-6e3f4e4e-38c0-11e8-8891-a4ce02219488.gif)

**Comment by jenisgrindstaff** [comment]
I see this issue as well with the Gboard keyboard and the English (US) layout. 

Rocket.Chat.Android version: 2.0.0-beta3
Mobile device model: Pixel 2
OS version: 8.1.0
Rocket.Chat.Server 0.63.0

**Comment by rafaelks** [comment]
@Pitstopper @jenisgrindstaff Thank you for reporting the issue, we also noticed the issue happening. This is going to be addressed soon. 👍
