### ISSUE TITLE
Facebook Messenger style rich chatbot messages/menus

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#1027]
https://github.com/RocketChat/Rocket.Chat/issues/6786

The above issue is in the main rocketchat repo. It appears that the plan is to get it done as a Google Summer of Code project see https://rocket.chat/docs/contributing/google-summer-of-code-2018/.

> Rich Messages and Payloads for Buttons and Cards
Mentors: @diego.dorgam, @timkinnnae, @john.szaszvari (Contributing Guest Mentor)
Description: Create UI components and develop the handling of message payloads to support new interactions for bots, like buttons, cards, images and more. Follow existing conventions to let bot developers migrate pre-built solutions to be delivered via Rocket.Chat. This opens the door for enhanced user experience and interaction flows in automated messaging, letting bots provide a much greater variety of utility; such as business apps, team workflows, even games and interactive narratives.

This issue is about the Android implementation of this, including probably an update to the Kotlin SDK to support these message schema enhancements. The important point to keep in mind is we'd want to be architecturally aligned with the main repo implementation.

**Comment by bizzbyster** [comment]
See https://forums.rocket.chat/t/supporting-fb-messenger-style-rich-chatbot-messages-menus/528 for discussion about this issue.

**Comment by rafaelks** [comment]
Closing this one here, let's keep the discussion in our forums.
