### ISSUE TITLE
[BUG] Chat rooms are not reset when you close the search

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1044]
Your Rocket.Chat.Android version:
- versionCode 2007
- versionName "2.0.0-beta5"

Mobile device model and OS version: Nexus 6 - Android 7.1

### Steps to reproduce
- Search some chat rooms
- clear the search 
- close the search

![search](https://user-images.githubusercontent.com/16731434/38593888-4aaab1b2-3d61-11e8-94d7-22eb233f41bf.gif)

**Comment by rafaelks** [comment]
@divyanshub024 Image link is broken for me... can you try updating it?

**Comment by divyanshub024** [comment]
@rafaelks done. Please check it again.
