### ISSUE TITLE
[BUG] "Invalid file" error when attaching files

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1047]
Your Rocket.Chat.Android version: 2.0.1
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.12) , Developer ROM

 When I try to attach a file (any format), I get an error "Invalid file".
![gifeditor_20180407_162327](https://user-images.githubusercontent.com/18574776/38455492-d8d966a0-3a81-11e8-985b-41cc8a3e3370.gif)

**Comment by divyanshub024** [comment]
@Pitstopper its working fine for me. Can you share some logs?

**Comment by Pitstopper** [comment]
@divyanshub024 Hi. Where i can get them?

**Comment by divyanshub024** [comment]
You can use [Logcat](https://developer.android.com/studio/debug/am-logcat.html) in Android Studio or you can use [Pidcat](https://github.com/JakeWharton/pidcat)

**Comment by Pitstopper** [comment]
It's my fail, sorry. On another device it's works well.

**Comment by Pitstopper** [comment]
I decided to re-open the issue because the error is not only in my possession. When I try to attach a file (any format), I get an error "Invalid file". In some cases (on another Xiaomi devices) - double attaching same file. Some logs from my device:


04-19 12:30:01.400 24338-24338/? D/MiuiGallery2_PickGalleryActivity: Picker capacity: 1, result 1 items
04-19 12:30:01.400 4177-4196/? D/MiuiPerfServiceClient: interceptAndQueuing:24338|com.miui.gallery|360|340|uninterruptible|null|com.miui.gallery/com.miui.gallery.picker.PickGalleryActivity|318830488346082|Slow handle traversal
04-19 12:30:01.410 24338-24338/? D/MiuiGallery2_PickGalleryActivity: picked file: 1, pending: 0
04-19 12:30:01.410 24338-24338/? D/MiuiGallery2_PickGalleryActivity: parse raw results[[file:///storage/sdcard1/DCIM/Camera/IMG_20180414_152824.jpg]] for LEGACY_GENERAL
04-19 12:30:01.430 24338-24338/? D/MiuiGallery2_ImageLoader: paused
04-19 12:30:01.440 30242-30242/? D/Documents: onActivityResult() code=-1
04-19 12:30:01.440 3983-4531/? I/WtProcessController: MOVE TO FOREGROUND: com.android.documentsui 10050
04-19 12:30:01.440 3983-4531/? I/StatusController: Last foreground:com.miui.gallery uid:10023 Current foreground:com.android.documentsui uid:10050
04-19 12:30:01.440 3983-4531/? I/WtProcessController: FOREGROUND INFO: name=com.android.documentsui uid=10050 pid=30242 TaskId:7981
04-19 12:30:01.440 2339-3316/? I/Timeline: Timeline: App_transition_ready time:318831859
04-19 12:30:01.480 2339-4330/? I/Timeline: Timeline: App_transition_ready time:318831891

**Comment by rafaelks** [comment]
@Pitstopper Do you know if this file is allowed on your server? What's the extension of the file you're trying to attach?

**Comment by Pitstopper** [comment]
On our server are allowed all types of files. Specifically this file was .jpg. Allowed file size is up to 100 mb.

**Comment by rafaelks** [comment]
@Pitstopper Got it! We'll take a look ASAP.

**Comment by Pitstopper** [comment]
Thanks!

**Comment by luciofm** [comment]
@Pitstopper can you please attach here this .jpg, for testing. Thanks

**Comment by Pitstopper** [comment]
It looks like the problem is in the gallery application, because photos from "Google photo" are attached normally. But I can be wrong. This happens with any photo from the gallery and any file from the File Explorer. Files and photos from "Google Drive", for example, are attached normally. Here is the photo from the logs:
![img_20180414_152824](https://user-images.githubusercontent.com/18574776/39003886-85264de8-4404-11e8-8864-6a65378f1411.jpg)

**Comment by luciofm** [comment]
@Pitstopper we are releasing 2.0.2 later today, can you please test with the gallery application once it is released. Thanks.

**Comment by Pitstopper** [comment]
I'll check it out, thanks!

**Comment by Pitstopper** [comment]
It's work. Thanks!
