### ISSUE TITLE
[BUG] Wrong link recognition

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1049]
Your Rocket.Chat.Android version: 2.0.0-beta5
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.3.22) , Developer ROM

If there is no spaces between words and points, then part of the message is recognized as a link.
![screenshot_2018-04-07-21-25-48-240_chat rocket android](https://user-images.githubusercontent.com/18574776/38459041-7ae0b19e-3aad-11e8-8f72-849fda724733.png)

**Comment by leonardoaramaki** [comment]
Closed by #1745

**Comment by Pitstopper** [comment]
Hi, folks! The bug has not gone away. It still shows itself.

Your Rocket.Chat.Android version: 3.0.0 Build 2044 - 0ddd70df - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.69.2

![screenshot_2018-10-11-09-09-31-235_chat rocket android](https://user-images.githubusercontent.com/18574776/46784664-adf1cb00-cd37-11e8-873e-56ed92142849.png)

**Comment by rafaelks** [comment]
@Pitstopper Thank you! This is fixed but not in the latest beta yet, will be available on the next one!

**Comment by Pitstopper** [comment]
Sorry for disturb :+1:
