### ISSUE TITLE
[BUG] Search to DM a friend

### ISSUE THREAD

**Issue by lucasmontano** [RocketChat/Rocket.Chat.Android#1051]
**Your Rocket.Chat.Android version:** 2.0.0-beta5
**Mobile device model and OS version:** Google Nexus 5 - 6.0.0 - API 23
**Server Version:** 0.63.1

**Expected**

- As a Rocket.Chat Android User 
- I need to search for a friend in the search box
- I expect a search result with a unique username
- I expect to jump into the conversation on click @ **username**

**Bug**

- I can't identify my friend by the search result
- A "Join Chat" button appears when clicked @ **name**
- The button doesn't work and shouldn't be there: it's not needed to join in DMs, only in channels. For DMs, I’m supposed to open the chat and be able to start the conversation.

**SS**
Searching Filipe Alvarenga
![screenshot-2018-04-07_19 09 36 476](https://user-images.githubusercontent.com/7559318/38460791-91b8fc98-3a97-11e8-92ff-25b7cc189ae9.png)

On Click on an item the Join Button doesn't work, hence should be displayed.
![screenshot-2018-04-07_19 09 51 616](https://user-images.githubusercontent.com/7559318/38460800-ba449320-3a97-11e8-8bf8-86516506a82a.png)

On back to home, the conversation already started
![screenshot-2018-04-07_19 10 05 772](https://user-images.githubusercontent.com/7559318/38460805-da4b2ecc-3a97-11e8-99d3-1edb52f5701c.png)

**Comment by rafaelks** [comment]
This one is fixed by #1321.
