### ISSUE TITLE
[IMPROVEMENT] Difficulties in reading the message history with activity on the channel

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1056]
Your Rocket.Chat.Android version: 2.0.0-beta5
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.3.22) , Developer ROM

It's not possible to read the message history when active chatting in the channel. The focus is shifted down to new messages. If you scroll up and someone writes a new message, then you are rejected to this new message.

**Comment by leonardoaramaki** [comment]
@Pitstopper this is a known issue. It's going to be solved soon.

**Comment by rafaelks** [comment]
@leonardoaramaki Is this one addressed already?

**Comment by philipbrito** [comment]
This is already improved on the current app version. Thanks for opening!
