### ISSUE TITLE
Can't open channels ERROR Use JsonReader.setLenient(true) to accept malformed JSON at path $

### ISSUE THREAD

**Issue by donzavitz** [RocketChat/Rocket.Chat.Android#1057]
Galaxy S7 Android OS 7.0
Rocket.Chat.Android Version 2.0.0-beta5 Build #2007
Rocket.Chat Server 0.63.0 Ubuntu 17.10 snap package

https://i.imgur.com/yHNwUGO.png

After logging in I get the error shown in the picture above.  This happens everytime I login.  It also happens in either chat groups or direct messages, without ever showing messages.  This is the only error message I see in the entire app, and nowhere to view logs?

A quick google search shows that this might be related to dates and or calendar...maybe something to do with the post time strings?

Am I missing something?

**Comment by mmarif4u** [comment]
Most probably the same.

https://github.com/RocketChat/Rocket.Chat/issues/10363

**Comment by renuraj18** [comment]
Getting the same error with 0.64.0-develop version
Rocket.Chat Version: 0.64.0-develop
"JsonReader.setLenient(true) to accept malformed JASON at path $"

**Comment by rafaelks** [comment]
This error is not happening in 2.1.0 anymore.

**Comment by serra92** [comment]
Hello there, I'm having this issue with server using RocketChat 0.74 and android app on version 3.2.0
