### ISSUE TITLE
[FIX] Avatar URL 

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#1059]
The avatar url should include the `%23` (for channels/groups) in the url, like:

https://open.rocket.chat/avatar/%23general

**Comment by marvennsuson** [comment]
hello sir how can i add group image or avatar on chat details or how can i get avatar on chat details

**Comment by reetp** [comment]
@marvennsuson this Issue is closed and this repo is now not used.

Please follow this to ask your question.

https://rocket.chat/docs/getting-support/
