### ISSUE TITLE
[BUG] Duplicate Notification 

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.Android#1063]
Your Rocket.Chat.Android version: 2.0.0 - Beta6
Mobile device model and OS version: OnePlus 3T - Android 8.0
Rocket.Chat Server: 0.62.2

I get two notification items about the same message in the Android Info Center.
I dont know if there a really two notifications, or maybe they are only displayed twice.
The message was send once to a private channel.

I will update this issue after the update to 0.63.1 via snap is available.

![screenshot_20180410-101330](https://user-images.githubusercontent.com/26709898/38545326-14ae47ca-3caa-11e8-8d90-3095c57a25f2.jpg)

Update: Still present after the server update to 0.63.1
Not present on an samsung galaxy a3 2017 with android 7.

**Comment by mmarif4u** [comment]
I can confirm that the message shown twice in the notification.

**Comment by leonardoaramaki** [comment]
@ArchimedesFM @mmarif4u Are you logged in on more than one server?

**Comment by mmarif4u** [comment]
Sorry for not coming back on this. It is working for some time now. I guess after snap 0.63 release.

**Comment by ArchimedesFM** [comment]
@leonardoaramaki no im only logged in on one Server and the problem is still present on Rocket.Chat Android 2.2.0 and Server 0.63.3. Sometimes i get the notification 3 times. I reinstalled the latest beta today and i will check if the problem still occurs after that.

**Comment by mmarif4u** [comment]
Somewhere @rafaelks said that it was because of the two apps token in the server, 1.x and 2.x.

**Comment by rafaelks** [comment]
This one is fixed on 2.3.0 already.
