### ISSUE TITLE
[IMPROVEMENT] Update user status after opening the app 

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#1065]
Your Rocket.Chat.Android version: 2.0.0 beta 6

Currently if i am not online on web(browser) and i open the app, my status is offline. Which i assume would go online or busy etc(whichever is set on web or app) after opening the app.

**Comment by Pitstopper** [comment]
Yes, the same thing.

**Comment by rafaelks** [comment]
This is already implemented in `develop-2.x` branch, thank you @mmarif4u 👍
