### ISSUE TITLE
[IMPROVEMENT] Don't show signup link if signup is disabled on the server

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#1067]
We only allow login via GSuite, so registration is disabled. On desktop, we only see the red G+. On mobile (`develop-2.0` build from today), after typing the server name, above the red G+ button, there is a signup link.

**Comment by philipbrito** [comment]
Could you confirm if this issue still happens? I tried here and don't get it.

**Comment by antgel** [comment]
Yes, still see it. Using last night's `develop-2.0`. Let me know if I need to check something server-side.

**Comment by philipbrito** [comment]
Could you tell me your server address? Feel free to contact in another way if is the case.

**Comment by antgel** [comment]
You have email. :)
