### ISSUE TITLE
Adaptative icon for newer Android Version

### ISSUE THREAD

**Issue by teolemon** [RocketChat/Rocket.Chat.Android#1075]
(Latest Rocket.Chat.Android version)

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

It would be great that Rocket Chat can have a rounded/or square/or squirkle icon like the other apps (the OS sends the required shape, and the application honors it).

![image](https://user-images.githubusercontent.com/1689815/38677105-8990bcda-3e5d-11e8-89ea-fb4d0119edc9.png)

**Comment by rafaelks** [comment]
@teolemon Thanks for opening the issue, this one is already done in branch `develop-2.x` 👍
