### ISSUE TITLE
Can't send messages in 2.0.0-beta6 (error-invalid-room)

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#1077]
Your Rocket.Chat.Android version: 2.0.0-beta6. Using server 0.63.

When I type a message, it doesn't get sent, and I get an error message "channel-not-found".

![rocketchat-android-no-message](https://user-images.githubusercontent.com/295571/38688477-de410e14-3e81-11e8-983a-a2818153de6f.png)

**Comment by antgel** [comment]
(Edited attachment in original message.)

**Comment by leonardoaramaki** [comment]
@antgel Are you using the Beta version or have you compiled from source?

**Comment by antgel** [comment]
@leonardoaramaki Oops, my bad. It was `develop-2.0` with HEAD 82db7cd0, which I think was beta 3.

**Comment by leonardoaramaki** [comment]
@antgel We have changed the message sending on both SDK and here in the app. 
I'd suggest that you try updating the SDK to the latest version if you haven't already done this.

**Comment by antgel** [comment]
Just built `develop-2.0`, looking good! Sorry for the noise.
