### ISSUE TITLE
[BUG] Orientation change in settings reset the fragment to chats

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1090]
Your Rocket.Chat.Android version:
- versionCode 2009
- versionName "2.0.0-rc1"

Mobile device model and OS version: Nexus 6 - Android 7.1

![settings-rotation](https://user-images.githubusercontent.com/16731434/38770224-14c19eb6-402d-11e8-9e6b-3d4ae29d28a8.gif)

**Comment by rafaelks** [comment]
@divyanshub024 Do you want to work on this one?

**Comment by divyanshub024** [comment]
@rafaelks sure, please assign it to me.

**Comment by divyanshub024** [comment]
This issue could be resolve from #831
