### ISSUE TITLE
[NEW] Delete/Hide channels

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1091]
Your Rocket.Chat.Android version: 2.0.0-RC1
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.3.22) , Developer ROM

There is no option to delete direct messages in channel list.
![img_20180415_092801](https://user-images.githubusercontent.com/18574776/38775632-32f5c426-4090-11e8-9611-dc992ac75b03.jpg)

**Comment by rafaelks** [comment]
Just renamed the issue and added the feature tag! 👍

**Comment by philipbrito** [comment]
Let's track the status of this issue from the already https://github.com/RocketChat/Rocket.Chat.Android/issues/1055
Thank you!
