### ISSUE TITLE
[PROJECT] git rebase > git merge when updating feature branches

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#1092]
Hi all,

Very excited to see the RC for 2.0. :)

It would be great to see more rebasing and less merging of upstream branches into feature branches. It makes the git log hard to read, and merge commits are often problematic (breaking bisect, etc).

Just a suggestion...

**Comment by rafaelks** [comment]
@antgel That makes sense, thanks for the suggestion! 👍

**Comment by antgel** [comment]
It's still happening:
![image](https://user-images.githubusercontent.com/295571/47093096-1f96b100-d231-11e8-88f5-55074fc312bd.png)
