### ISSUE TITLE
[IMPROVEMENT] Change password layout

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1097]
Presently in change password user will see the done/save icon in action bar to save new password only when the user enters the correct password in "confirm new password", which should not be the case as it would confuse them how to change the password in case of the wrong password.

It is better to show the button always and then show error/alert to enter the correct password.  

ps: we should also ask for current password.

**Comment by rafaelks** [comment]
@divyanshub024 Do you want to work on this one?

**Comment by divyanshub024** [comment]
@rafaelks sure, please assign it to me.

**Comment by divyanshub024** [comment]
@rafaelks should I ask the user for current password?

**Comment by rafaelks** [comment]
@divyanshub024 No, asking the current password is not required.

**Comment by philipbrito** [comment]
Let's close this issue since the new layout is coming to version 3.0.0 (so we'll track for the respective issue from that [milestone](https://github.com/RocketChat/Rocket.Chat.Android/milestone/23)).
