### ISSUE TITLE
Feature Request: Implement WebRTC

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/Rocket.Chat.Android#11]
WebRTC works with the Android Chrome browser it would be great to have it on the Android app too! I guess that WebRTC broadcasts should probably also be using Push notifications.

**Comment by graywolf336** [comment]
@jmatsushita I am going to assume you're talking about the current Android application in the Play Store, if so do you mind opening the issue https://github.com/RocketChat/Rocket.Chat.Cordova/issues as that's the correct repository for the current Android application. This is the start of the native implementation.

If I am mistaken, please feel free to open this issue again.
