### ISSUE TITLE
[QUESTION] All conversations says "No messages yet"

### ISSUE THREAD

**Issue by Eiken** [RocketChat/Rocket.Chat.Android#1100]
Your Rocket.Chat.Android version: 2.0.0
Mobile device model and OS version: Moto G5S, 7.1.1

It appears the app never loads any conversations for all the channels. This also makes "Sort by activity" not work which I think is dependent on whatever has been fed into there.

**Comment by samsimpson1** [comment]
Also getting this on a OnePlus 3T on Android 8.0 and an Essential Phone on Android 8.1

**Comment by iprok** [comment]
Fully confirm this. Also on Samsung Galaxy S8 and LG g6 (Android 7.0)

**Comment by wagesj45** [comment]
I believe this is related: the app continuously tries to reconnect.
[recording.zip](https://github.com/RocketChat/Rocket.Chat.Android/files/1922037/recording.zip)

**Comment by rafaelks** [comment]
@Eiken @TopHattedCat @iprok @wagesj45 Sorry for the late response. This is related to a setting that's disabled on your servers. Here's a screenshot of it:

![rocketchat_2018-apr-14](https://user-images.githubusercontent.com/551004/38905510-7a7ec6a0-4287-11e8-9fa2-59bf40422823.jpg)

You can access it from:

> Administration > General

Once you enable it, all conversations after that will have an updated "last message" object inside of it, then you'll be able to see on the Android application. 👍

**Comment by rafaelks** [comment]
@antgel @dimm0 Mentioning you guys also here, because you've reacted to the issue.

**Comment by antgel** [comment]
@rafaelks Interesting, thanks. I changed the setting, no difference yet. Perhaps it will only start to save "last messages" from here on in. Also, I don't remember changing it from the default, but apparently I did. :man_shrugging:

**Comment by Eiken** [comment]
@rafaelks Works when enabled.
Will the default setting change in the server application?

**Comment by der-eismann** [comment]
I guess `false` is the default setting... should probably be changed in a feature server release.

**Comment by antgel** [comment]
Opened server issue.
