### ISSUE TITLE
[FEATURE] Slide in conversation list from old app

### ISSUE THREAD

**Issue by Eiken** [RocketChat/Rocket.Chat.Android#1101]
Your Rocket.Chat.Android version: 2.0.0
Mobile device model and OS version: Moto G5S, 7.1.1

The old apps way with a slide in menu with a compact list of conversations/rooms is much more effective for switching between channels when you have a lot of channels. With the current behavior I end up scrolling forever for something that was done with one thumb stroke in the old app.

PS: Otherwise new app looks and feels really nice DS.

**Comment by Eiken** [comment]
Or maybe not change and more of an add to support both behaviors.

**Comment by rafaelks** [comment]
We don't plan to support this right now, let's close it for now.
