### ISSUE TITLE
creating channels

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#1103]
Hello Devs.

First of all, thanks for the great version 2.0.0 release. It's really fast. 

One question though. Do I miss the setting where I can create channels? If not, is this feature planned?

thanks and cheers

**Comment by Shailesh351** [comment]
@himbeere Yes. There is open PR for it https://github.com/RocketChat/Rocket.Chat.Android/pull/891. It  will be added in next release i think.

**Comment by ghost** [comment]
Ah, great! Thanks.
