### ISSUE TITLE
[BUG] Conversation list ordered upside down when using Activity

### ISSUE THREAD

**Issue by der-eismann** [RocketChat/Rocket.Chat.Android#1105]
Your Rocket.Chat.Android version: 2.0.0

Mobile device model and OS version: 
- LG G6 - Android 7.0
- OnePlus 3T - Android 8.0

The chats shown after opening the app are ordered upside down when using `Activity` - the latest conversations are at the bottom, the oldest ones on the top. `Alphabetical` is ordering correctly. 
#1100 guessed it is connected to the previews showing "No messages yet", but imho it's just upside down.

(Btw: Thanks for the great update! The app is running really smooth now. Some polishing and it's perfect!)

**Comment by iprok** [comment]
Fully confirm this. Also on Samsung Galaxy S8

**Comment by reetp** [comment]
Confirm on Samsung S6

**Comment by reetp** [comment]
Tell a lie.
Had to use:
https://github.com/RocketChat/Rocket.Chat.Android/issues/1100
Set Admin/General/Store Last Message Yes
Restart Server
v 2.01 and new chats go to the top

However, no phone notifications and the number of unreads are inconsistent (another bug)

**Comment by reetp** [comment]
For reference, phone notifications related to:
https://github.com/RocketChat/Rocket.Chat.Android/issues/1111
https://github.com/RocketChat/Rocket.Chat.Android/issues/1100
https://github.com/RocketChat/Rocket.Chat.Android/issues/864

**Comment by Shailesh351** [comment]
@der-eismann @iprok @reetp Thanks for reporting. This issue will be fixed along with https://github.com/RocketChat/Rocket.Chat.Android/pull/995

**Comment by rafaelks** [comment]
Let's close this one now, since we figured out the reason of the order. 2.1.0 also supports a decent order without the setting enabled. 👍
