### ISSUE TITLE
[BUG] Chats broken in 2.0.1

### ISSUE THREAD

**Issue by ceeram** [RocketChat/Rocket.Chat.Android#1110]
Your Rocket.Chat.Android version: 2.0.1

Mobile device model and OS version: Samsung Galaxy S7

When opening rocketchat after upgrade to 2.0.1 i got this error:
![screenshot_20180418-082007](https://user-images.githubusercontent.com/111448/38915733-135a112e-42e5-11e8-96f8-a90cea103991.png)

Tried re-install, clearing cache, to no avail. Profile and settings do work, this error happens when i go to Chats. All my channels are also gone, when trying to find channels, I can not search and only select a few channels in the list. Those channels are the only ones i can join.

**Comment by rafaelks** [comment]
@ceeram Thanks for the report, we'll be working on this fix very soon and sending a hotfix build. 👍

**Comment by rafaelks** [comment]
@luciofm Assigned this one to you.

**Comment by rafaelks** [comment]
This one is fixed in 2.0.2. 👍

**Comment by ceeram** [comment]
Thanks!

Op do 19 apr. 2018 19:07 schreef Rafael Kellermann Streit <
notifications@github.com>:
