### ISSUE TITLE
[BUG] Date missing and Time display inconsistent

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.Android#1113]
Your Rocket.Chat.Android version:
2.0.1
Rocket version 0.63.1 - Docker install

Phone:

Samsung S6 - Android 7.0

Chat only shows time but no date, or Date separator like desktop.

Pinned messages only show time as well (Starred are unavailable unfortunately)

Desktop shows Time in 12 hour am/pm but App in 24 hr format.

**Comment by mmarif4u** [comment]
There is a PR for chatroom dates. https://github.com/RocketChat/Rocket.Chat.Android/pull/845

**Comment by reetp** [comment]
Thanks. Funny how the eyes go blank when looking for bugs !

**Comment by rafaelks** [comment]
Closing the issue, since the PR is already open and there's already one issue for that. 👍

**Comment by reetp** [comment]
Hope https://github.com/RocketChat/Rocket.Chat.Android/pull/845 gets incorporated soon - this is a real pain.
