### ISSUE TITLE
SSO not working

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat.Android#1114]
We've configured our server to allow Single Sign On (SSO) as login method but when trying to log in only an empty black screen "Log in" gets shown.

Steps to reproduce:
- Start App
- Enter Rocket.Chat server URL and hit "connect"
- Ends in an empty black screen just showing "Log in" on the top

Rocket.Chat version: 0.62.2
Your Rocket.Chat.Android version: 2.0.1

Mobile device model and OS version: Nexus 5X (Android 8.1.0)

**Comment by rafaelks** [comment]
This issue duplicates this one: https://github.com/RocketChat/Rocket.Chat.Android/issues/322#issuecomment-381963441.

Please take a look on my comments there.
