### ISSUE TITLE
[QUESTION] Message: connecting in X seconds

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat.Android#1116]
Your Rocket.Chat.Android version: 2.0.1 (Build #2011)

Mobile device model and OS version: Samsung Galaxy S7 - Android 7.0

After using the Cordova-based app (which worked decent for a good while) I got a notice to upgrade to the native Android app, which I did. Everything seemed to work including connecting to the server and logging in. 

However, the app keeps saying "connecting in X seconds..." and messages are not delivered in a timely manner. What could be the cause? Desktop apps do not have this issue, neither did the Cordova legacy app.

**Comment by rafaelks** [comment]
@bkraul Thanks for opening the issue. What's your server URL/version please?

**Comment by bkraul** [comment]
URL: https://rocketchat.belmankraul.com

### Docker
rocketchat/rocket.chat:latest

### Rocket.Chat

| Version                 | 0.63.2                                                    |
| ----------------------- | --------------------------------------------------------- |
| Database Migration      | 109                                                       |
| Database Migration Date | Tue Apr 17 2018 14:34:24 GMT-0500 (Central Daylight Time) |
| Installed at            | Mon Jan 29 2018 11:26:38 GMT-0600 (Central Standard Time) |
| Uptime                  | 18 hours, 59 minutes, 52 seconds                          |
| Deployment ID           | **************                                            |
| PID                     | 1                                                         |
| Running Instances       | 1                                                         |
| OpLog                   | Enabled                                                   |

### Commit

| Hash    | 05ae7d6c44ca00722b610a168dbfd41da26e05b9 |
| ------- | ---------------------------------------- |
| Date    | Tue Apr 17 02:06:10 2018 -0500           |
| Branch  | HEAD                                     |
| Tag     | 0.63.2                                   |
| Author  | Bradley Hilton                           |
| Subject | Release 0.63.2 (#10476)                  |

**Comment by leonardoaramaki** [comment]
Hi @bkraul!
A few questions so we can narrow down the issue a little bit better for us:
_"The messages are not been delivered in a timely manner"_ 
- You mean sending the message or receiving them?
- They (messages) are sent and received on time on the web client but not at the same time on the app?
- The timestamps are wrong?
- The sent messages are been sent out of order?

**Comment by rockneverdies55** [comment]
Also seeing the same issue.

![image](https://user-images.githubusercontent.com/4588562/38942635-51e5a33c-42fd-11e8-83e9-6c822c01aaf7.png)

I can see all the channels after logging in and am even able to post messages. 

So not sure why the app thinks it's not connected to the server.

**Comment by rafaelks** [comment]
@rockneverdies55 What's your serve URL?

@bkraul Looks like it's not possible to connect over WebSocket into your server:

```
➜  ~  curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: rocketchat.belmankraul.com" -H "Origin: rocketchat.belmankraul.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://rocketchat.belmankraul.com/websocket
HTTP/1.1 400 Bad Request
Date: Wed, 18 Apr 2018 15:45:57 GMT
Server: nginx/1.13.12
Strict-Transport-Security: max-age=31536000
Connection: close
Transfer-Encoding: chunked

Not a valid websocket request
```

**Comment by bkraul** [comment]
@leonardoaramaki The messages are "queued" (messages show in gray), and as the connection appears intermittent, they are eventually delivered, it seems in order. I think @rafaelks is on point. I run rocketchat through a docker container, but the outside world first hits a vps (apache 2.4) which uses reverse proxy to the actual box. The curl call works perfectly in my internal network, which is calling the docker box directly.

And as I said, it works perfectly through web-based apps (which I supposed the Cordova-based app was web). But if the native app is using websockets, I would have to factor that into the proxy. I already have installed and enabled ```mod_proxy_wstunnel```, but I am having to figure out the proper configuration, as I am seeing mixed information on that.

What I currently have does not seem to work:
```
ProxyPass /websocket/ ws://rocketchat.belmankraul.com:443/websocket/
ProxyPassReverse /websocket/ ws://rocketchat.belmankraul.com:443/websocket/
```

**Comment by bkraul** [comment]
All right...thanks to @rafaelks , I was able to solve my issue. To recap:

* Rocket.Chat runs on a docker container.
* The outside world hits a VPS machine with apache2, which then uses ReverseProxy to direct requests to the instance.
* Because the native app appears to use WebSocket the requests were being dropped by the proxy, causing connection issues.

**To solve:**
* Enable the ```mod_proxy_wstunnel``` mod on the apache vps by running:
```
a2enmod proxy_wstunnel
service apache2 restart
```
* Add the WebSocket reverse proxy instructions alongside the web proxy ones. In my case:
```
# Enable the SSL proxy engine
ProxyRequests Off
SSLProxyEngine On
ProxyPreserveHost On

<Proxy *>
    Order deny,allow
    Allow from all
</Proxy>

 # Handle WebSocket protocol requests
ProxyPass /websocket wss://rocketchat.belmankraul.com/websocket
ProxyPassReverse /websocket wss://rocketchat.belmankraul.com/websocket

 # Handle web requests
ProxyPass / https://rocketchat.belmankraul.com/
ProxyPassReverse / https://rocketchat.belmankraul.com/
```

I will let you guys close the issue as needed. Just needed to bring some feedback in case it helps someone else.

**Comment by rockneverdies55** [comment]
My apache configuration is identical to the one at https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/ (Running behind an Apache SSL Reverse Proxy) section...

```
<VirtualHost *:443>

ServerAdmin it@domain.com
ServerName chat.domain.com
ErrorLog /var/log/chat.domain.com_error.log
TransferLog /var/log/chat.domain.com_access.log
LogLevel info
SSLEngine On
SSLCertificateFile /etc/ssl/certs/chat.domain.com.crt
SSLCertificateKeyFile /etc/ssl/private/chat.domain.com.key
SSLCertificateChainFile /etc/ssl/certs/intermediate.ca.pem

<Location />
        Order allow,deny
        Allow from all
</Location>

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:3000/$1 [P,L]

ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

Should I change it?

**Comment by rockneverdies55** [comment]
Never mind. I had `http` instead of `ws` in this line: `RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]` of the configuration. Recognized after comparing to what I copy pasted here 🙂. Replacing http to ws fixed the problem for me as well.

Thank you @rafaelks.

**Comment by rafaelks** [comment]
Amazing guys! I’m glad it worked for you all. Closing the issue now.

**Comment by leviwheatcroft** [comment]
For the googlers... my reverse proxy is a linuxserver/letsencrypt container, no need to enable any mods as shown above, just add the two `proxy_set_header` lines in the location stanza:

```
server {
  listen 443 ssl;
  root /config/www;
  index index.html index.htm index.php;
  server_name hello.*;
  include /config/nginx/ssl.conf;
  client_max_body_size 0;
  
  location / {
    include /config/nginx/proxy.conf;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://rocket:3000;
  }
}
```

**Comment by bkraul** [comment]
@leviwheatcroft Those mods are only needed for an apache2 setup. You are using nginx which supports reverse proxy out of the box.

**Comment by pavee251** [comment]
Message: connecting in X seconds in Linux CentOS-7-x86_64-Minimal-1708
same issue facing in Linux CentOS es xi  machine how can fix in so please can you brief me where can i changed i am  Rocketchat server 0.74.3 using desktop client version  2.15.1 
==================


Version | 0.74.3
-- | --
1.4.0
137
Wed Apr 10 2019 15:39:27 GMT+0500 (Pakistan Standard Time)
Thu Mar 28 2019 23:46:20 GMT+0500 (Pakistan Standard Time)
6 days, 6 hours, 1 minutes, 58 seconds
wNtg9cMds5eWGMNtd
5341
1
Disabled

**Comment by bkraul** [comment]
What is your web server setup? Are you running rocketchat behind a reverse proxy? and if so, is it apache or nginx or something else?

**Comment by pavee251** [comment]
Dear sir,

I am Using this local server and facing issue windows desktop client ….

 

Rocket.Chat


Version

0.74.3


Apps Engine Version

1.4.0


Database Migration

137


Database Migration Date

Wed Apr 10 2019 15:39:27 GMT+0500 (Pakistan Standard Time)


Installed at

Thu Mar 28 2019 23:46:20 GMT+0500 (Pakistan Standard Time)


Uptime

6 days, 7 hours, 1 minutes, 58 seconds


Deployment ID

wNtg9cMds5eWGMNtd


PID

5341


Running Instances

1


OpLog

Disabled

Commit


Hash

202a465f1c0700b2decd5f904f11794f286aae76


Date

Wed Feb 13 23:18:51 2019 -0200


Branch

HEAD


Tag

0.74.3


Author

Diego Sampaio


Subject

Merge pull request #13474 from RocketChat/release-0.74.3

Runtime Environment


OS Type

Linux


OS Platform

linux


OS Arch

x64


OS Release

3.10.0-957.10.1.el7.x86_64


Node Version

v8.11.3


OS Uptime

6 days, 7 hours, 37 minutes,


OS Load Average

0.01, 0.13, 0.24


OS Total Memory

3.70 GB


OS Free Memory

138.60 MB


OS CPU Count

2

Build Environment


OS Platform

linux


OS Arch

x64


OS Release

4.4.0-141-generic


Node Version

v8.11.4


Date

February 14, 2019 6:24 AM

Usage


Total Users

74


Active Users

74


Inactive Users

0


Online Users

57


Away Users

9


Offline Users

8


Total Rooms

655


Total Channels

1


Total Private Groups

35


Total Direct Message Rooms

619


Total Livechat Rooms

0


Total Messages

24732


Total Messages in Channels

101


Total Messages in Private Groups

3857


Total Messages in Direct Messages

20823


Total Messages in Livechats

0


Total Uploads

1270


Total Uploads Size

1.56 GB

**Comment by bkraul** [comment]
If you run this command on the CentOS server (preferably as root):

(I am assuming you are not running it on port 3000 for the outside world)
```
netstat -ntlp | grep "80\|443"
```
What is the result?

**Comment by pavee251** [comment]
Dear sir,

I am using localserver:3000 port

**Comment by bkraul** [comment]
I am trying to understand your set up here. You say you have an esxi vm that is running CentOS. I am assuming you are calling it `localserver`, and that you are accessing it from a Windows machine that is on the same LAN? or is it outside? 

I am also assuming that the URL you are putting on the Windows desktop app is precisely localserver:3000...?

**Comment by pavee251** [comment]
Absolutely right sir and I am facing Message: connecting in X seconds issue some time

**Comment by bkraul** [comment]
What about your Windows firewall? Is that on and blocking LAN traffic? Or do you have a firewall active on the CentOS machine? Also, do you have SElinux enabled on the CentOS server (If so, I'd stop and disable).
