### ISSUE TITLE
[INVESTIGATE] Push Notifications Are Not Received

### ISSUE THREAD

**Issue by pfunk1978** [RocketChat/Rocket.Chat.Android#1117]
Rocket.Chat.Android version: 2.0.1 #2011
Rocket.Chat Version 0.63.1 ac16e938693aa04740758f180f2ea6d7a0337280

Android System: 8.1.0 on Nexus 5x

## Reproduction
1. Login with rocket.chat.android as an admin user
1. login with rocket.chat.ReactNative as same user
2. login with Chrome on desktop as same user
1. Go to `Administration` -> `Push`. Keep default settings and click on `SEND A TEST PUSH TO MY USER`
1. Will get a toast success message that push has been sent to 2 devices.

## Expected Results
2 Push Notifications. One for rocket.chat.android, and one for rocket.chat.Reactnative
## Actual Results
Only one notification for ReactNative client. Rocket.chat.android push never received.

**Comment by rafaelks** [comment]
@pfunk1978 If you *kill* the app, do you receive the notification?

**Comment by rafaelks** [comment]
@pfunk1978 BTW, do you receive notifications on normal usage? Because the app is not showing the "TEST MESSAGE" notification right now.

**Comment by agreenbhm** [comment]
@rafaelks Not OP, but yes, if I remove the app from recents THEN I will get notifications. Ideally notifications would come through regardless of whether it's in recents or not, and especially if it is in recents.

**Comment by rafaelks** [comment]
@agreenbhm Good, because then this issue duplicates this one: https://github.com/RocketChat/Rocket.Chat.Android/issues/1078. Thank you for clarifying! 👍

**Comment by pfunk1978** [comment]
@rafaelks Sorry about getting back so late to you on this.

I am not having the same resolution. I'm not attempting any @ notifications as we are still in testing right now. Just using the test push button.

Steps I've tried
1. Swipe away the app from recent apps does not allow notifications.
1. Clearing app data and reconnecting does not work either.
1. Performing step above and then clearing from recent apps does not work.
1. Uninstalling, reinstalling does not work
1. `Settings` -> `Apps & notifications` -> `Rocket.Chat` -> `App notifications`:
   * Main switch is ON
   * Allow Notification dot switch is on

Effectively, I'm just not getting any notifications on android native, but the RN version gets them every time.

**Comment by rafaelks** [comment]
@pfunk1978 The reason is: the native app is curating the notifications before presenting them right now. Since the test notification is not a valid chat notification, we're not presenting it to the user. This is going to be fixed soon. 👍
