### ISSUE TITLE
[NEW] Support permissions to write on a read-only room for admins

### ISSUE THREAD

**Issue by martinszy** [RocketChat/Rocket.Chat.Android#1118]
The app needs to allow users with permission to write on the room to do it.

These are the things that need to be checked in order to accomplish:

1. Is the room read only? (already being done)
2. Is the user the owner of the room? (If yes, allow to write on the room)
3. Does the user have the permission `post-readonly`? (If yes, allow to write on the room)

**Comment by rafaelks** [comment]
@martinszy Thank you for opening the issue, we're going to address this one soon. 👍
