### ISSUE TITLE
includes' of undefined" error

### ISSUE THREAD

**Issue by sjk303** [RocketChat/Rocket.Chat.Android#1119]
Your Rocket.Chat.Android version: 2.0.1

Server version: 0.63.1 

Since the new version of the Android app got pushed to the PlayStore we've encountered Bug #1023 in which some channels return: "Cannot read property 'includes' of undefined" error. It appears this bug was closed.

**Comment by rafaelks** [comment]
As you just commented, here's the issue being tracked/fixed in our back-end: https://github.com/RocketChat/Rocket.Chat/issues/10484#issuecomment-382522693

**Comment by graywolf336** [comment]
Rocket.Chat v0.63.3 is out now which includes the fix for this: https://github.com/RocketChat/Rocket.Chat/releases/tag/0.63.3
