### ISSUE TITLE
audio and video messages are not working

### ISSUE THREAD

**Issue by srinivas3120** [RocketChat/Rocket.Chat.Android#112]
able to send audio and video messages. but are not visible in chat conversation(showing as a empty message)
 and not able to play them on web at https://demo.rocket.chat.

**Comment by laggedHero** [comment]
We still need to work on showing audio and video support (sending the file is easier).

I'll open two tickets (one for audio, the other for video).

@srinivas3120 
About the third issue: not able to play on the web; could you guide me to message?

**Comment by laggedHero** [comment]
Audio support #113 
Video support #114

**Comment by srinivas3120** [comment]
@laggedHero i have uploaded them through the app. not able to play them on web. i have them on my account. if you want i can share credentials.

**Comment by rafaelks** [comment]
Closing this issue, since it's duplicated to #113 and #114.
