### ISSUE TITLE
[BUG] Cannot access public channels

### ISSUE THREAD

**Issue by thepowerprocess** [RocketChat/Rocket.Chat.Android#1122]
Version: 2.0.1 Build #2011
Device: Galaxy S6 (Android 7.0)

I am logged in as Admin with all permissions.  When I try to access a public channel, it show this error "cannot read property 'includes' of undefined".  This error appears for all public channels, regardless if they're read-only or not.

**Comment by rafaelks** [comment]
@jberberick Thanks for opening the issue. This problem is fixed in version 0.63.3 of our server: https://github.com/RocketChat/Rocket.Chat.Android/issues/1119#issuecomment-382618463.
