### ISSUE TITLE
[IMPROVEMENT] Do not show delete and edit option in bottom sheet when message is from other user

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1132]

**Comment by rafaelks** [comment]
@divyanshub024 That actually depends on the permissions and roles.

**Comment by divyanshub024** [comment]
@rafaelks may be we can hide both the option?

**Comment by rafaelks** [comment]
@divyanshub024 Yes, we need hide it, if the user doesn't have the permission to do that.

**Comment by philipbrito** [comment]
Let's track the status of this issue from https://github.com/RocketChat/Rocket.Chat.Android/issues/778
