### ISSUE TITLE
Cannot locate unread messages

### ISSUE THREAD

**Issue by magnetic5355** [RocketChat/Rocket.Chat.Android#1137]
## Description

Since update to version 2 it is extremely difficult to locate unread messages. Please add unread option.

## Devices and Versions

.63.3

2.0.2

## Steps to reproduce

Attempt to locate unread channels or dms with hundreds of options.

**Comment by rafaelks** [comment]
@caesarcxiv The messages have a blue badge and different colors when unread. Please, be more specific about what you're looking for. I'm closing the issue for now.

**Comment by magnetic5355** [comment]
Unread on top as an option when sorted alphabetically
