### ISSUE TITLE
[QUESTION] Continuously Reconnecting

### ISSUE THREAD

**Issue by wagesj45** [RocketChat/Rocket.Chat.Android#1138]
## Description

The app never stops trying to reconnect, even though it seems like messages are coming in and displaying in the rooms and conversations.

## Devices and Versions

Your Rocket.Chat.Android version: 2.0.2 Build #2012
Your Rocket.Chat Server version: 0.63.3

Mobile device model and OS version: Google Pixel 2 XL - Android 8.1.0

## Steps to reproduce

Do a fresh install of the app. Connect to an instance of RocketChat server.

## Logs

No logs available, but I have a video.
[screen_recording.zip](https://github.com/RocketChat/Rocket.Chat.Android/files/1930529/screen_recording.zip)

**Comment by brase** [comment]
>The app never stops trying to reconnect, even though it seems like messages are coming in and displaying in the rooms and conversations.

Same here.

> Your Rocket.Chat.Android version: 2.0.2 Build #2012
> Your Rocket.Chat Server version: 0.63.3

Same here. I am using the docker image of rocket chat.

> Mobile device model and OS version: Google Pixel 2 XL - Android 8.1.0

Sony Xperia X Compact with Android 8.0

**Comment by brase** [comment]
I should mention that I am using LDAP-Authentication.

**Comment by XF9** [comment]
Got the same behavior when connecting to the same server @brase is using. Open.Rocket.Chat works fine though.

Blackberry Priv, Android 6.0.1, App Version 2.0.2

**Comment by wagesj45** [comment]
For what it is worth, I'm not using LDAP.

**Comment by rafaelks** [comment]
Guys, the problem is that your server does not support WebSocket apparently. Take a look on this issue: https://github.com/RocketChat/Rocket.Chat.Android/issues/1116

**Comment by wagesj45** [comment]
@rafaelks Thanks for your quick response. Hopefully I can get my nginx reverse proxy fixed.

**Comment by wagesj45** [comment]
For people having this problem, fixing the nginx configuration per the [documentation on rocket.chat's site](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/) fixed the issue.
