### ISSUE TITLE
The menu item "Recent" is always empty

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1146]
Your Rocket.Chat.Android version: 2.0.0 - 2.0.2
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.12) , Developer ROM
Your Rocket.Chat Server version: 0.63.0 - 0.63.3

When i'm sending attachments and selecting a source, the menu item "Recent" is always empty.

![screenshot_2018-04-20-15-48-33-387_com android documentsui](https://user-images.githubusercontent.com/18574776/39052061-57f3b3a6-44b3-11e8-944d-218303566168.png)
![screenshot_2018-04-20-15-49-17-661_com android documentsui](https://user-images.githubusercontent.com/18574776/39052069-5e6d354a-44b3-11e8-937d-080d37dc396e.png)

**Comment by MariusVolkhart** [comment]
@Pitstopper We have no control over what shows up in the "Recents" list. Each of the Providers you see on the left (Downloads, Google Drive, SD Card, etc.) have the option of telling the Android operating system (OS) that the OS can ask them for a list of recently modified documents. If none say they can be asked, no documents will appear there.

Those providers that do provider a list of recently modified documents then tell the OS when each document was modified. The OS can now choose which of those files to display in the "Recents" list. On a test device I'm using, files that were last changed over 45 days ago do not get displayed. This might change on other devices.

If you're familiar with Android development, you can experiment yourself using this [sample app](https://github.com/googlesamples/android-StorageProvider). Find the line `row.add(Document.COLUMN_LAST_MODIFIED, file.lastModified());` in `MyCloudProvider.java` and change the value.

I hope this helps!

**Comment by Pitstopper** [comment]
I got it, thanks!

**Comment by rafaelks** [comment]
@MariusVolkhart Thanks for the clarification! 👍
