### ISSUE TITLE
Local files cache

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat.Android#115]
In order to better support images, audios, and videos, we need to have a local (in disk) cache.

@YusukeIwaki let's discuss here a solution for that!

Relates/dependency of: #113, #114

**Comment by YusukeIwaki** [comment]
Yes, we have to store files especially for playing video or audio in offline.
It would be feasible by extrnding Attachment model to observe the status of DownloadProvider.

**Comment by laggedHero** [comment]
We should limit how much space we're going to use. Maybe use an in-disk LRU cache.

Are you thinking about something like that?

**Comment by YusukeIwaki** [comment]
I think that the limitation of local file is not necessary when user explicitly download attachments.
Only the files that is automatically loaded in browsing messages in rooms (such as images), should be stored in finite cache.

**Comment by laggedHero** [comment]
I'll leave it here, since it's an implementation of an in-disk LRU cache.

https://github.com/JakeWharton/DiskLruCache

Jake, as always. xD

**Comment by laggedHero** [comment]
Maybe changing to Fresco will be enough for images (http://frescolib.org/docs/caching.html)

**Comment by YusukeIwaki** [comment]
Thank you for good information!

**Comment by YusukeIwaki** [comment]
#181 and this issue are partially similar.

The scope of this issue would be solving the issue as below:

* user cannot view attachment image in detail.
* user cannot view uploaded Video
* user cannot play uploaded Audio

Supporting GIF (and SVG? etc...) is now in the scope of #181.

**Comment by laggedHero** [comment]
Cache and viewing are different things.

Having a cache won't make the app exhibit the video, play the audio or whatever.

Having the cache would save up on data transfer. A lot.

**Comment by laggedHero** [comment]
Fresco pretty much took care of this for images.

We still need to find out a solution for video and audio.

**Comment by aenonGit** [comment]
For images would it help Jake Wharton's Picasso library?
link to GH repo -> https://github.com/square/picasso

**Comment by rafaelks** [comment]
Closing it for now, looking forward to 2.0.0.
