### ISSUE TITLE
[NEW] Option to disable vibration for push notification

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#1158]
Your Rocket.Chat.Android version: 2.0.3
Your Rocket.Chat Server version: 0.64.0-rc0

Mobile device model and OS version: Android 7.1.2

Hello Devs.

Correct me if i am wrong but it is not possible to disable vibration for push notification. Is that right? It is my understanding this is a setting which is to be adjusted from within the app like for example the SMS app.

thanks and best regards

**Comment by leonardoaramaki** [comment]
@himbeere Yes, it's currently not possible but it'll be implemented along with many other settings.

**Comment by philipbrito** [comment]
This is something that we'll deliver in the future. For tracking its status lets follow the issue number https://github.com/RocketChat/Rocket.Chat.Android/issues/186

Thank you.

**Comment by ShreyasZare** [comment]
Hi. What is the status of this issue? Is the option available? I don't seem to find it anywhere. This option is really needed as the device vibrating every few minutes on desk is really irritating.

**Comment by philipbrito** [comment]
As said above track the status os this feature here: #186

Try changing your device settings by disabling its vibration while this feature isn't available yet.
