### ISSUE TITLE
[DOCS] README is out of date

### ISSUE THREAD

**Issue by MariusVolkhart** [RocketChat/Rocket.Chat.Android#1159]
## Description

The README mentions the `develop-2.x` branch which no longer exists. Has `master` replaced it? Should all new contributions target `develop` or something else? Are two versions still being maintained?

> Currently, the app is maintained in two branches, namely v1+ and v2+. The v1+ is maintained in the develop branch and the v2+ is maintained in the develop-2.x branch. The older version is written partially in java and kotlin, but we intend to write the latest version completely in kotlin.

**Comment by antgel** [comment]
I'm not a core team member, but yes, I believe that 2.x is now the only maintained version, having been released to the Play Store a few days ago.

**Comment by rafaelks** [comment]
You guys are right. We should change it to `develop` instead. 👍
