### ISSUE TITLE
[NEW] Support for messaging typing status

### ISSUE THREAD

**Issue by srinivas3120** [RocketChat/Rocket.Chat.Android#116]
- [x] Sending typing status.
- [x] Listening to typing changes.

**Comment by alexfdz** [comment]
@rafaelks @filipedelimabrito do you have any timeline for this feature?

**Comment by rafaelks** [comment]
@alexfdz This is not our highest priority right now for internal development, but if someone is willing to send us a PR it would be super welcome! If there's no PR, I would say that version 2.2.0 (end of May) will have it.

**Comment by alexfdz** [comment]
thanks for your reply @rafaelks! Is unlikely I will have time before 2.2.0, but probably I could help with some testing if you need a hand.
