### ISSUE TITLE
[BUG][INVESTIGATE] "Open failed: EACCES (Premission denied)" error when attaching files 

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1162]
Your Rocket.Chat.Android version: 2.0.3
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.19) , Developer ROM

When I try to attach a file (any format), I get an error "open failed: EACCES (Premission denied)". In version 2.0.2 after #1047 everything worked fine. But in 2.0.3 it's broke again.

![img_20180423_150343](https://user-images.githubusercontent.com/18574776/39125418-8ee1edf0-4707-11e8-87b7-1f60ba4d3592.jpg)

**Comment by rafaelks** [comment]
@Pitstopper Is this still happening for you?

**Comment by Pitstopper** [comment]
Problem solved, thanks!
