### ISSUE TITLE
When app Background -> Foreground, it didn't work.

### ISSUE THREAD

**Issue by cheonjoosung** [RocketChat/Rocket.Chat.Android#117]
![screenshot_2016-12-28-10-27-56](https://cloud.githubusercontent.com/assets/13310269/21511867/5866ed3c-cce9-11e6-859b-0562b1a36148.png)

When app Background -> Foreground, it didn't work.
Avatar is not view because user is null. When i click room, no change.
After logout & login, this problem disappears for a while.
Then, When back -> fore, this proble appears. 
PS) demo.rocket.chat no problem, our server has problem.

**Comment by laggedHero** [comment]
We have an issue to redo the connectivity. Please follow #147
