### ISSUE TITLE
[BUG] Login not working for our private server

### ISSUE THREAD

**Issue by apomp** [RocketChat/Rocket.Chat.Android#1174]
## Description

Hello,

we set up a fresh instance of rocket chat on our servers for testing purposes. When using the Legcay Version of the Android application, login works fine. When using the newest version of the current application, login does not work on our server. However, connection to the offical rocket chat server is working fine. We get the error message: Use JsonReader.setLenient(true) to accept malformed JSON at path $

However, login works well with the web version, the desktop client and the Android Legacy version available in the PlayStore. 

## Devices and Versions

Android Version: 2.0.4
Rocket Chat Server Version: 0.63.0

Device Model and OS: Android 8.0 on HTC U11 Life

## Steps to reproduce

1) Enter URL of server (HTTPS)
2) Get Exception 

## Logs
Error Message:
Use JsonReader.setLenient(true) to accept malformed JSON at path $

**Comment by philipbrito** [comment]
Hi @apomp Sorry for the delay. We shipped other app versions since your issue here. Is it still happening?

**Comment by rayphi** [comment]
@apomp 
Same error with
Android version 3.2.0
Rocket.Chat Server version 0.74.3

Honor 6X / Android 7

**Comment by serra92** [comment]
Hello there, I'm having this issue with server using RocketChat 0.74 and android app on version 3.2.0

Cellphone is Xiaomi Mi A2

**Comment by maxdwit** [comment]
Logged in ( months ago ) with the old client. logged out. login error from above.
Installed: Rocket Chat Android Experimental 
logged in: works
Also verified with android browser version of firefox: works.

Conclusion: rocket chat app ( non experimental ) is broken regarding the login process.

**Comment by philipbrito** [comment]
@maxdwit What is the Android native app version you are using and what is your server version?
