### ISSUE TITLE
[BUG] Use Real Name instead of username for Direct Messages in channel list 

### ISSUE THREAD

**Issue by thepowerprocess** [RocketChat/Rocket.Chat.Android#1175]
- Your Rocket.Chat.Android app version: 2.0.4 Build #2014

- Your Rocket.Chat server version: 63.3

- Device model (or emulator) you're running with: Galaxy S6, Android 7.0

- Steps to reproduce:
1) Under 'Administration' > 'Layout' set "Use Real Name" to true
2) create a Direct Message
3) in the channel list the Direct Message will use the user's username, not their "Real Name"

**Comment by leonardoaramaki** [comment]
Duplicated of #1102
