### ISSUE TITLE
[BUG] Infinite scroll with pinned messages 

### ISSUE THREAD

**Issue by thepowerprocess** [RocketChat/Rocket.Chat.Android#1178]
- Your Rocket.Chat.Android app version: 2.0.4 Build #2014

- Your Rocket.Chat server version: 63.3

- Device model (or emulator) you're running with: Galaxy S6, Android 7.0

- Steps to reproduce:
1) have about 12 pinned messages in channel
2) go to pinned messages tab and scroll through, but the pinned messages keep looping so it looks like there is an infinite number of pinned messages.

**Comment by philipbrito** [comment]
Hi @cloudsandladders I have more than 12 pinned message and going to the pinned message view does not produce this issue in the current app version. I believe that this issue is gone, but as always feel free to reopen again if it is happening on your side.
