### ISSUE TITLE
[BUG] Upload PDFs are staying as "blank" message

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1183]
## Description

When you upload a PDF file, it appears like a blank message.

## Devices and Versions

Your Rocket.Chat.Android version: 2.0.4
Your Rocket.Chat Server version: 0.63.3

## Steps to reproduce

1. Connect to the server;
2. Upload a PDF file;
3. See the result is a blank message;

## Expected results

It should display the file name, file description and pressing on it should download the file and open.

**Comment by mvp-sales** [comment]
Related to #936

**Comment by rafaelks** [comment]
Closed by #1195
