### ISSUE TITLE
[BUG] Reactions are missing after closing a chat view

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1184]
## Description

User no longer see the reactions after they are cached.

## Devices and Versions

Your Rocket.Chat.Android version: 2.0.4
Your Rocket.Chat Server version: 0.63.3+

## Steps to reproduce

1. Connect to any server;
2. React to a message;
3. See that reaction appears and network requests is success;
4. Get back to chats list;
5. Open the conversation again;
6. Reaction is no longer there;

**Comment by mmarif4u** [comment]
@rafaelks maybe the same, https://github.com/RocketChat/Rocket.Chat.Android/issues/1149?

**Comment by rafaelks** [comment]
@mmarif4u Right!!! Thanks for looking into it. 👍
