### ISSUE TITLE
[NEW] Keep the app in EN and make a menu to choose app language

### ISSUE THREAD

**Issue by TehPeGaSuS** [RocketChat/Rocket.Chat.Android#1185]
I'd like to know if it's possible to keep the app in EN and make a menu to choose another app language.
I'm used to use the Cordova Legacy one, where we can keep it in EN and it's not `auto translated` to system language.

**Comment by philipbrito** [comment]
We can add an option to change the app language in the app but keeping it in English as default language isn't a good idea IMO. 

Just think about big countries like Brazil and India with millions of speakers (not all people speak english). Also, if the users choice a language from the system it means that they like to use their applications with that language (not the imposed by the developers/organizations).

FYI: If there isn't a language supported by the app, the default is English in that case.

**Comment by TehPeGaSuS** [comment]
Well, that makes sense indeed.
The option to change app language seems fine to me in that case.
:+1:

**Comment by rafaelks** [comment]
Duplicates #747
