### ISSUE TITLE
[BUG] Can't use SSO Login on new App

### ISSUE THREAD

**Issue by sophieqc** [RocketChat/Rocket.Chat.Android#1189]
## Description

Using the new rocket.chat app we can't login into our rocket.chat instance that only permit SSO Login. Cordova and ReactNative apps don't have this problem.

## Devices and Versions

Your Rocket.Chat.Android version: 2.0.4 (from play store)
Your Rocket.Chat Server version: 0.63.3

Mobile device model and OS version: Blackberry Priv, Android 6.0.1 ; Nexus 5X, Android 7.0.1

## Steps to reproduce

Login into our instance on the mobile app, login is empty : https://tof.cx/image/O6s8G

On the Cordova App, we can login with SSO : https://tof.cx/image/O69sh

Thank you

**Comment by sophieqc** [comment]
We use SAML, so it might be a duplicate from https://github.com/RocketChat/Rocket.Chat.Android/issues/798

**Comment by philipbrito** [comment]
@0noon1 Thanks for specify that your server uses SAML. It will be implemented soon.
You can track the update from the issue above.
