### ISSUE TITLE
Support for opening links in other browsers

### ISSUE THREAD

**Issue by brnbs** [RocketChat/Rocket.Chat.Android#119]
Please consider adding option for selecting an external app which is used for opening the clicked URL instead of displaying inside the app.

**Comment by laggedHero** [comment]
Hello @brnbs.

That's an issue on the Cordova app too.

There's an issue there about it: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/142

Could please add to the discussion in that issue?

(I'll close this one since it's not related to this project)
