### ISSUE TITLE
display read receipt info in direct messages

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat.Android#1190]
Not sure if it's possible but can be useful at times if read receipt data can be shown in the chat board directly (next to message time for example) in direct messages. One of the best things about whatsapp, you can precisely see when the other side receives the message and if they read it or not (single tick, double tick and colored double tick).

I'm sure the development team has more important things to work on nowadays but I believe that could be a nice enhancement to the app.

**Comment by mmarif4u** [comment]
This maybe related: https://github.com/RocketChat/Rocket.Chat.Android/issues/788

**Comment by rockneverdies55** [comment]
I guess that's right. Closing in favor of the other issue.
