### ISSUE TITLE
[I18N] UA translation

### ISSUE THREAD

**Issue by CrimsonAndrew** [RocketChat/Rocket.Chat.Android#1197]
## Description

Ukrainian version translated really bad, a lot of mistypes and just wrong translation. How I can help with improving?

## Devices and Versions

All devices.

## Steps to reproduce

I can help with checking the translation if someone provide me xslx file (English-Ukrainian). I have HUGE experience in translating (games. apps etc).

**Comment by philipbrito** [comment]
Thanks for your interest in helping! I'll create a file and notify you!

**Comment by CrimsonAndrew** [comment]
Thanks for response!


>Четверг, 26 апреля 2018, 19:09 +08:00 от Filipe de Lima Brito <notifications@github.com>:
>
>Thanks for your interest in helping! I'll create a file and notify you!
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
С наилучшими пожеланиями,
Евгений

**Comment by rafaelks** [comment]
@filipedelimabrito Did you create the file?

**Comment by CrimsonAndrew** [comment]
no. he didn't
--
从Mail.Ru的Android专用app所发送 星期五, 04 五月 2018, 06:53上午 +08:00 发件人 Rafael Kellermann Streit  notifications@github.com :
