### ISSUE TITLE
[NEW] Attachments list of the channel

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1205]
- [x] Show the attachments list;
- [x] Allow the user to open the file;

**Comment by rafaelks** [comment]
Refer to https://github.com/RocketChat/Rocket.Chat.iOS/pull/1523 when creating the list @filipedelimabrito. List layout needs to be same as iOS.

**Comment by philipbrito** [comment]
Got it!
