### ISSUE TITLE
Pictures do not load on the app, but do on the desktop program

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#1215]
## Description

Although pictures can be uploaded via the app without an issue, they can't be viewed. The thumbnail is a generic thumbnail picture - a small picture icon on a blue background - and clicking it just brings up a black area rather than the photo. This is a problem on my device, as well as anybody else's device who is on my server. I haven't found anyone who can load pictures on their phone.

## Devices and Versions

Rocket.Chat.Android version: 2.0.4
Rocket.Chat Server version: 0.63.3

**Comment by leonardoaramaki** [comment]
Can you provide the URL for your server?

**Comment by ghost** [comment]
Sure - https://c.scd31.com

**Comment by ghost** [comment]
Turns out it was because the Site URL under general had a trailing slash.
