### ISSUE TITLE
[BUG] Avatars not being updated on android app when changed via desktop app/web browser

### ISSUE THREAD

**Issue by TehPeGaSuS** [RocketChat/Rocket.Chat.Android#1217]
## Description

Avatars not being updated when changed via desktop app/web browser
## Devices and Versions

Your Rocket.Chat.Android version: 2.0.4 (Build #2014)

Mobile device model and OS version: Huawei Y6 Pro 2017 - Android 7.0

## Steps to reproduce

Just update your avatar via desktop app/web browser and open your android app. The avatar in use on android will be the previous one.
Opening Android Applications Manager and cleaning app cache seems to solve the problem.

**Comment by elin-y** [comment]
Is there any news, workaround etc. on this issue?

**Comment by flowli** [comment]
We have the same issue. Also when avatars are changed in the mobile app, other users won't see the new avatar (but rather the old one).

**Comment by lorek123** [comment]
app is caching avatars and updates it unknown way. To force an update, user needs to delete application data ( which forces him to log in again).

**Comment by localguru** [comment]
I can confirm this with 3.1.1. Stop the app, cleaning cache and starting again updates the avatar.

**Comment by localguru** [comment]
> app is caching avatars and updates it unknown way. To force an update, user needs to delete application data ( which forces him to log in again).

Cleaning cache is sufficient. Deleting data will remove access data and settings too.

**Comment by seitsu** [comment]
This applies to the iOS app on my iPhone XS as well.

iOS Version 12.1.2
RocketChat iOS App Version 3.2.0 (223)
RocketChat Server Version 0.70.4

Logging off and then reconnecting to the server doesn't change anything.

**Comment by philipbrito** [comment]
@seitsu Not sure if there is a related issue for the iOS side. If not, feel free to open that on the [respective repository](https://github.com/RocketChat/Rocket.Chat.iOS/issues).

**Comment by rockneverdies55** [comment]
Having the same issue. Another user has changed his avatar; the app shows blank instead of his new avatar. I've changed mine and the app shows the old avatar image of mine.

**Comment by rockneverdies55** [comment]
Tried clearing cache workaround that is suggested in this thread however after trying that I see no avatars at all for any users. Even tried uninstalling and reinstalling the app from scratch but very strangely that didn't help either.

**Comment by hfeky** [comment]
@filipedelimabrito I confirm this is fixed via #2231.
