### ISSUE TITLE
Looking app? or SDK?

### ISSUE THREAD

**Issue by Naguchennai** [RocketChat/Rocket.Chat.Android#122]
WE are Developers we looking SDK not app... i am right???????????

**Comment by YusukeIwaki** [comment]
@naguchennai could you tell us what you want to do with the "SDK" more concretely?

**Comment by Naguchennai** [comment]
All developer need SDK for develop our own designed app. What ever you did in this app. all we need for our own design .. i am right?

1. register/login
2. getuser details.
3. get room details
4. get room msg
5. get private msg and what u have in app all we need in SDK
u know? there is no one using this app right now what u developing. is there any app published using this code? because developer need SDK, not source. I think U wasting your time for developing this good app.. Try to develop SDK.

If i am wrong i am sorry.... I know value of your and my TIME...

**Comment by geekgonecrazy** [comment]
A good SDK will come about by making a good app.  Most people don't want to make their own app.  So to us it's actually the opposite.  ;-). App is most important.  SDK is something that will happen eventually

**Comment by YusukeIwaki** [comment]
It seems that the requirements are almost met by the enhancement of [REAT APIs](https://rocket.chat/docs/developer-guides/rest-api/).

Even Slack doesn't provide any "SDK" but they have rich [APIs](https://api.slack.com/methods), and many users are satisfied with them.

**Comment by laggedHero** [comment]
Adding up: [The Realtime API](https://rocket.chat/docs/developer-guides/realtime-api) may help you, too.

And you could always fork the project and do your thing. :)

PS.: Is it ok to close this issue?
