### ISSUE TITLE
[NEW] Create an interface to manage users in a channel/group

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1230]
- [ ] Button to add new members to the channel/group
  - [ ] List of all members [(API)](https://rocket.chat/docs/developer-guides/rest-api/miscellaneous/directory/)
  - [ ] Search on all members [(API)](https://rocket.chat/docs/developer-guides/rest-api/miscellaneous/directory/)
  - [ ] Add a new member to channel/group [(API)](https://rocket.chat/docs/developer-guides/rest-api/channels/invite/)
- [ ] Allow user to remove an user from a channel/group [(API)](https://rocket.chat/docs/developer-guides/rest-api/channels/kick/)

~~Blockers:~~

~~https://github.com/RocketChat/Rocket.Chat/pull/10607~~

**Comment by Akronix** [comment]
I am missing this feature, how is it going?

**Comment by rafaelks** [comment]
@Akronix We still didn't have the time to work on that, but it's planned to start in 1 or 2 releases. 👍

**Comment by dabbler011** [comment]
@rafaelks can I work on this issue?

**Comment by AlexDJNInovae** [comment]
@rafaelks as we are considering Rocket.Chat for a project needing both iOS and Android Native apps, we came across this requirement. I noticed that [milestone 3.3.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/29) is **closed** but that this issue is still open.

Is it still being worked on? If so, do you have an idea of when it may be implemented?

I hope you're well. Thank you.

**Comment by rafaelks** [comment]
@AlexDJNInovae Thanks for the heads up! We're not currently working on that right now. Currently our focus in on Discussions and Threads and then, after that we will look into other things, like managing the members of a room. On iOS this is already implemented.

**Comment by philipbrito** [comment]
Update: Feature is in progress and soon a PR will come in.
Thanks for your patience!

**Comment by Shailesh351** [comment]
Update: DONE

- [x] Add API for invite and remove user in Kotlin SDK (https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/249)
- [x] Permission Check for remove user (Show only when user have permission to remove)
- [x] Add Remove User Feature
- [x] Permission Check for invite user (Show only when user have permission to invite)
- [x] Add invite user feature(Using spotlight)
