### ISSUE TITLE
[IMPROVEMENT] Reconnect when app gets focus

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#1234]
Often I switch back to Rocket.chat app on Android and I see this:

![image](https://user-images.githubusercontent.com/4001792/39501103-e7e253c4-4d86-11e8-8b5d-2cc3981c5306.png)

Ideally either A) the app would reconnect when it gets focus or B) it would not tell me that it was waiting to reconnect.

**Comment by reetp** [comment]
Same here.
Rocket 0.63.3
Android 2.0.4
Takes the full 15 seconds....
