### ISSUE TITLE
[QUESTION] How (or where) i can see the status of everybody?

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1243]
Your Rocket.Chat.Android version: 2.1.0 build 2019
Rocket Chat server version: 0.64.0
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.19) , Developer ROM

In the description of 2.1.0 release says: - You now can see the status of everyone. Where can I see it? In the Member List I do not see this.

**Comment by philipbrito** [comment]
Updated [release notes](https://github.com/RocketChat/Rocket.Chat.Android/releases/tag/v2.1.0).
