### ISSUE TITLE
[BUG] Message is not quoted when using Reply

### ISSUE THREAD

**Issue by iprok** [RocketChat/Rocket.Chat.Android#1244]
## Devices and Versions

Your Rocket.Chat.Android version: 2.1.0
Your Rocket.Chat Server version: 0.64.0

Mobile device model and OS version: 
LG g6 (Android 8)

After using "Reply" on the message I see original message quote on top of input area, but when I send my message original message is not quoted at all.

**Comment by leonardoaramaki** [comment]
@iprok Does it happen all the time or can you identify a more specific situation when this behavior occur?

**Comment by iprok** [comment]
Oh, sorry. Just noticed that it's quoted but quote is hidden behind virtual keyboard on my mobile. And quote is revealed after new message in channel or after getting keyboard out and back. And I'm attaching 2 screenshots to display the issue.

Just after send
![capture _2018-05-07-16-28-45](https://user-images.githubusercontent.com/9906715/39710468-8a8f035e-5225-11e8-8428-98acfa69d7bf.png)

After hiding keyboard and get it back
![capture _2018-05-07-16-29-47](https://user-images.githubusercontent.com/9906715/39710508-aae56aa8-5225-11e8-9df3-cf47fefb71f8.png)

**Comment by leonardoaramaki** [comment]
@iprok Thanks for reporting back and for the screenshots. 
If the message is always being quoted, but it appears underneath the keyboard/composer, then it's intended behavior, the message is just not scrolled to the end of message list but to the beginning of the last message. Is that what's happening?

**Comment by iprok** [comment]
It's that what's happening. But it's a bit confusing. I can't see quotation just after I send a message with it. And if it's intended behavior, then why it's scrolled like on the last screenshot?

**Comment by leonardoaramaki** [comment]
@iprok bug confirmed. Thanks
