### ISSUE TITLE
[BUG] Push notifications doesn't work without setting "Always notify mobile".

### ISSUE THREAD

**Issue by iprok** [RocketChat/Rocket.Chat.Android#1245]
## Description

First of all, sending push notification using "Send a test push to my user button" never works regardless any other settings. I press it, see records in logs but see no action on my android clients.

Regular push notifications (for example when some message in private chat) doesn't work without setting "Always notify mobile".

Settings on the server regarding Push notifications are set to defaults. Only "Debug" is switched to true.

## Devices and Versions

Your Rocket.Chat.Android version: 2.1.0 from Play Market
Your Rocket.Chat Server version: 0.64.0 in docker.

Mobile device model and OS version: 
LG g6 - Android 7.0
Huawei MediaPad M3 Lite 10 - Android 7.0
Different phones of my collegues - Android 7.0 - 8.0.

## Logs on the server

[34mI20180504-10:36:04.399(0) Push: send message "@iprok" via query { userId: '3o6...npb' } 
[34mI20180504-10:36:04.400(0) Push: send to token { gcm: 'c0sb...U05A' } 
[34mI20180504-10:36:04.401(0) Push: send to token { gcm: 'cr2F...MSQ' } 
[34mI20180504-10:36:04.401(0) Push: send to token { gcm: 'c0s...05A' }

**Comment by xenithorb** [comment]
"Always notify mobile" ? Where's that?

**Comment by iprok** [comment]
> "Always notify mobile" ? Where's that?
Rocket chat server Administration -> General -> Notifications

**Comment by xenithorb** [comment]
Ok, I can confirm this behavior and can add that it also applies to server:
0.64.1

2x OnePlus One on LineageOS 14.1 - One with microG instead of gapps, and the other with gapps.

They both exhibit the behavior of not receiving push messages without the above-mentioned setting being on. When it was turned on, the gapps phone I needed to reset data for rocket.chat.android and re-login for it to start working after enabling the always notify setting. (could be coincidental)

**Comment by xenithorb** [comment]
I can also add that notifications whether "Always notify mobile" is on or not always seem to work for `rocket.chat.cordova` and `rocket.chat.reactnative` - So I think it's safe to say this is a client issue?

**Comment by iprok** [comment]
And for now (I have not got exact moment, sorry) push notifications stop working at all. Rocket chat for android 2.3.2 and rocket chat 0.65.1.

Have tried cleaning app data and relogin. Doesn't help.

**Comment by rafaelks** [comment]
@iprok Do you use our gateway?

**Comment by iprok** [comment]
> Do you use our gateway?

Yes

**Comment by apomp** [comment]
We are facing the same problem.

* Android 2.4.0
* 0.65.2

**Comment by rafaelks** [comment]
@apomp @iprok You don't receive even notifications for mentions? Or just the ones nobody is mentioned?

**Comment by apomp** [comment]
Our users don't receive any notifications on the Android client (neither with mentions nor without mentions (setting is set to "send notification for all messages") when they are posted on public channels. When they are posted on private channels the notifications appear sometimes (but not always).

**Comment by rafaelks** [comment]
@apomp We're investigating... can you troubleshoot what notifications do you receive and what you don't? Here's a few questions that will help us with the investigation. Can you please also send a screenshot of your notification preferences?

1. Do you receive notifications with no mention at all, in public channels?
2. Do you receive notifications with no mention at all, in private channels?
3. Do you receive notifications with no mention at all, in direct messages?
4. Do you receive notifications with mentions to the user, in public channels?
5. Do you receive notifications with mentions to the user, in private channels?
6. Do you receive notifications with mentions to the user, in direct messages?
7. Do you receive notifications with mentions to the `@all`, in public channels?
8. Do you receive notifications with mentions to the `@all`, in private channels?
9. Do you receive notifications with mentions to the `@all`, in direct messages?

**Comment by iprok** [comment]
Seems that updating rocket chat to 0.65.2 make things as described at start of the issue:
"Send a test push to my user button" never works regardless any other settings.

Regular push notifications (for example when some message in private chat) doesn't work without setting "Always notify mobile".

If "Always notify mobile" is set, push notifications work normally.

**Comment by rafaelks** [comment]
Our gateway was having some issues this week... can you guys try it again and leave us some feedback?

Thanks!

**Comment by apomp** [comment]
Do you receive notifications with no mention at all, in public channels?
No

Do you receive notifications with no mention at all, in private channels?
No

Do you receive notifications with no mention at all, in direct messages?
No

Do you receive notifications with mentions to the user, in public channels?
No

Do you receive notifications with mentions to the user, in private channels?
No

Do you receive notifications with mentions to the user, in direct messages?
No

Do you receive notifications with mentions to the @all, in public channels?
No

Do you receive notifications with mentions to the @all, in private channels?
No

Do you receive notifications with mentions to the @all, in direct messages?
No

We are using the gateway. Is there any other option?

**Comment by rafaelks** [comment]
@apomp Just confirmed that our gateway is having issues again (we had issue migrating from GCM to FCM). We're working to fix it.

**Comment by rafaelks** [comment]
@apomp We just restarted back our gateway service... can you try again please?

**Comment by apomp** [comment]
@rafaelks Unfortunately, we still have the same problems.

**Comment by iprok** [comment]
@rafaelks for now with rocketchat 0.66.3 and android app 2.4.0 push notifications started working withOUT setting "Always notify mobile". But still not very good. They works only if I completely close rocket chat on my desktop. I usually just block my workspace when I go away. If I do so without closing the rocketchat on desktop, I will have no push notifications on mobile. Is it the way push notifications should work?

**Comment by iprok** [comment]
@rafaelks ping. Can you please answer my question in previous comment?

**Comment by rafaelks** [comment]
@iprok Yes, this is by design. If you are connected in your desktop client (online), you won't receive notifications on the other clients.

**Comment by phlegx** [comment]
@rafaelks we  do not get notifications on the android app when offline and setting "Always notify mobile" to true. It only works when I'm online in my android client.  I'm not running any desktop stuff simultaneously when testing.
