### ISSUE TITLE
[BUG] Status indicator grey

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.Android#1246]
The newly added user status is not correct most of the time.
Sometimes the status appears, but most of the time the balls are just grey even if the users are online.
Sometimes single status indicators are correct, but others are not.
I dont know if this feature depends on 0.64. (not available via snap).

Your Rocket.Chat.Android version: 2.1.0 Build 2019
Your Rocket.Chat Server version: 0.63.3
OnePlus 3T - Android 8.0

## Steps to reproduce

Open Android App Rocket.Chat and check the status indicator.
![screenshot_20180504-132547](https://user-images.githubusercontent.com/26709898/39626028-98e39280-4fa0-11e8-9685-7519fe83436c.jpg)

**Comment by magnetic5355** [comment]
+1

**Comment by rafaelks** [comment]
Fixed already.
