### ISSUE TITLE
[BUG] Send button sometimes stays hidden (hard to reproduce)

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1266]
## Description

Here's a video that demonstrates it: https://drive.google.com/file/d/1HLTJHasMWiASDao9pJgt50D5FdtpFULv/view?usp=sharing.

**Comment by Pitstopper** [comment]
Yes, same here.

**Comment by leonardoaramaki** [comment]
Closed by #1320
