### ISSUE TITLE
Error:(215, 13) No value passed for parameter 'broadcast' 

### ISSUE THREAD

**Issue by blaZ3** [RocketChat/Rocket.Chat.Android#1268]
## Description

I just pulled the Android repository and the Kotlin SDK repository and did the build. The common and core jar files were generated in the libs folder also but when I try to run the Android project I get the following error in ChatRoomsPresenter while initializing ChatRoom object. Both the Android project and the SDK project are in the develop branch.

> Error:(215, 13) No value passed for parameter 'broadcast' 

## Steps to reproduce

Follow how to build instructions in the Android repository Readme.
https://github.com/RocketChat/Rocket.Chat.Android#how-to-build

**Comment by leonardoaramaki** [comment]
@blaZ3 the build problem should be solved on the develop branch. Can you update it and confirm?

**Comment by eByteTheDust** [comment]
I had the same problem, I updated my development branch and the problem has been resolved. 
(FYI: it compiles and runs, but there are 67 warnings though)

**Comment by leonardoaramaki** [comment]
This has been fixed on develop branch. Thanks for updating here @efleisc
