### ISSUE TITLE
[BUG] (edited) is showing on system messages when deleting a message

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#1272]
@RocketChat/android

**Comment by divyanshub024** [comment]
@leonardoaramaki I can't see "(edited)" on system message.
<img src="https://user-images.githubusercontent.com/16731434/40109740-aec8c42e-591b-11e8-9509-03a853633da9.png" width="320">

**Comment by leonardoaramaki** [comment]
@divyanshub024 Can you logout and login, then check again. Here it always shows.
