### ISSUE TITLE
'All Messages' push notifications not working

### ISSUE THREAD

**Issue by eByteTheDust** [RocketChat/Rocket.Chat.Android#1273]
## Description

I have setup RocketChat server on Ubuntu and the Android Client, setup push notifications according to the documentation.

I only receive push notifications when using @all @here or @user_name.  Changing the setting at
**Notification Preferences / Mobile / Alerts** to **All Messages** doesn't make any difference. Is this an expected behavior?  I thought that by changing the setting to 'all messages' users would be notified regardless of the @ being used.

The same thing happens when the app is opened at the Chats screen, I can see the number of unread messages (in blue) only when messages are sent using the @. Otherwise I need to enter the chat room to see unread messages.

Please let me know if this is expected behavior, and why changing the setting 'all messages' makes no difference. 
 
Thank you

## Devices and Versions

Android and Server versions. Develop latest from today.

**Comment by eByteTheDust** [comment]
Complementing the original post. Actually the Notification Preferences "Mobile" inside chat rooms is completely ignored. Changing between "all messages", "default", "nothing" makes no difference. However if you go to **Administration / Accounts/ User Preferences** and change **Mobile Notifications Default Alert** to 'all messages' it will work even when you don't use @all or @here @username... so it looks like a bug, the settings inside the chat rooms is being ignored.

**Comment by rafaelks** [comment]
@efleisc What's your server version?

**Comment by rafaelks** [comment]
@efleisc `develop`? If yes, then there's a PR that fixes it AFAIK: https://github.com/RocketChat/Rocket.Chat/pull/10760

**Comment by eByteTheDust** [comment]
0.63.3

**Comment by rafaelks** [comment]
This is a bug on back-end, going to be fixed for 0.64.2 release (later this week or early next week). 👍
