### ISSUE TITLE
Error when verifying the version of your server

### ISSUE THREAD

**Issue by cristiandley** [RocketChat/Rocket.Chat.Android#1274]
## Description

Trying to set up app, but no able to do it. Cant set server URL because it does not identify server version.

## Devices and Versions

Your Rocket.Chat.Android version: 5.0.1
Your Rocket.Chat.Android version: 6.0.1
Your Rocket.Chat Server version: 0.64.1

Mobile device model and OS version: Huawei p8 Lite - Android 5.0.1
Mobile device model and OS version: Moto G - Android 6.0.1
Mobile device model and OS version: Moto G Play - Android 6.0.1

## Steps to reproduce

- Download Rocket Chat
- Try setting URL (HTTPS)
- Connect

_(error notification)_ ...Error when verifying the version of your server...

## Works okey on:

iOS: 11.3
Android: 7.0

**Comment by rafaelks** [comment]
@cristiandley Are you running version 2.1.1 of the app?

**Comment by cristiandley** [comment]
@rafaelks The one that is in the play store. Tried uninstalling and installing again. No Luck.

**Comment by rafaelks** [comment]
@cristiandley What's your server URL?

**Comment by cristiandley** [comment]
@rafaelks  https://chat.jusneuquen.gov.ar

**Comment by luciofm** [comment]
Seems that we are having some issues parsing the colors...

```
                         D  {"services":[{"_id":"yQQcxuR9ZdYQ2ar2K","service":"dgipjn","authorizePath":"/dialog/authorize","buttonColor":"#000","buttonLabelColor":"#fff","buttonLabelText":"INGRESAR","clientId":"xyz123","custom":true,"identityPath":"http://sinupoj:3023/api/userinfo","identityTokenSentVia":"default","loginStyle":"redirect","mergeUsers":true,"scope":"openid","serverURL":"https://sec.jusneuquen.gov.ar","tokenPath":"http://sinupoj:3023/oauth/token","tokenSentVia":"payload","usernameField":"id"}],"success":true}
                         D  <-- END HTTP (500-byte body)
           TimberLogger  D  SDK(https://chat.jusneuquen.gov.ar): Successful HTTP request: GET - https://chat.jusneuquen.gov.ar/api/v1/settings.oauth: 200 OK
               StringKt  E  java.lang.IllegalArgumentException: Unknown color
                         E      at android.graphics.Color.parseColor(Color.java:1391)
                         E      at chat.rocket.android.util.extensions.StringKt.parseColor(String.kt:41)
                         E      at chat.rocket.android.authentication.login.presentation.LoginPresenter.getCustomOauthServiceNameColor(LoginPresenter.kt:365)
                         E      at chat.rocket.android.authentication.login.presentation.LoginPresenter.access$getCustomOauthServiceNameColor(LoginPresenter.kt:35)
                         E      at chat.rocket.android.authentication.login.presentation.LoginPresenter$setupOauthServicesView$1.doResume(LoginPresenter.kt:238)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
                         E      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
                         E      at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                         E      at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
                         E      at android.os.Handler.handleCallback(Handler.java:789)
                         E      at android.os.Handler.dispatchMessage(Handler.java:98)
                         E      at android.os.Looper.loop(Looper.java:172)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6637)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

We will fix it, but in the mean time can you ask the server admin to change `buttonColor` to `#000000` and `buttonLabelColor` to `#FFFFFF`

**Comment by cristiandley** [comment]
@luciofm Ready !

**Comment by luciofm** [comment]
@cristiandley still not working? I can get to the authentication page now.

**Comment by cristiandley** [comment]
@luciofm which android version are you using ? Im not able on 5.0.x and 6.0.x.

**Comment by luciofm** [comment]
```
CheckServerPresenter$ch  D  Error getting server info
                         D  chat.rocket.common.RocketChatNetworkErrorException: Network Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not
                             found.(url='https://chat.jusneuquen.gov.ar/api/info')
                         D      at chat.rocket.core.internal.rest.RestClientKt$handleRequest$$inlined$suspendCancellableCoroutine$lambda$1.onFailure(RestClient.kt:91)
                         D      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:161)
                         D      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                         D      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                         D      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                         D      at java.lang.Thread.run(Thread.java:818)
```

This usually means that the server is missing the Intermediate Certificate configuration (or it is misconfigured)

https://developer.android.com/training/articles/security-ssl#MissingCa

**Comment by cristiandley** [comment]
Weird... only happening on old sdks ?. @luciofm 
The SSL are setted as nginx demands :-(

**Comment by luciofm** [comment]
@cristiandley on Android 5.0 and 6.0 (still need to check 7.0) `COMODO RSA Certification Authority` was not a trusted CA. Only the `AddTrust External CA Root` (it's parent certificate) so in order to work on older versions, NGINX needs to have the all the trust chain configured.

https://www.sslchecker.com/sslchecker?su=15fb3e1137f89f8ef0b82bddc9343d08

**Comment by himpich** [comment]
@luciofm How can we (Enduser) obtain such debug Output?

nevermind, found it via logcat

**Comment by cristiandley** [comment]
@luciofm that was the issue :)
i did a `cat` of my `www-certificate` and my `ca-bundle`. (to obtain the chain certificates).

**Comment by diginote** [comment]
I have the same issue with letsencrypt certificates.

server version: **0.65.0**
android app version: **2.2.0** (build 2021)
android version: **7.0**


![error](https://user-images.githubusercontent.com/4537971/40300136-a51744b6-5ce8-11e8-8d88-4f1dac86f675.png)

```I've updated my android version to 8.0. Now the app works.```

**Comment by murilolobato** [comment]
I run over the same problema, and solved it accordingly to https://github.com/RocketChat/Rocket.Chat.Android/issues/1291

**Comment by rafaelks** [comment]
Fixed already.

**Comment by f-the-architect** [comment]
I fixed my server SSL issue then the APP works fine. Thanks everyone!
