### ISSUE TITLE
[BUG] Connecting hangs indefinitely

### ISSUE THREAD

**Issue by alarixnia** [RocketChat/Rocket.Chat.Android#1276]
## Description

Our server is https://chat.hypatiasoftware.org. Login through web and the legacy app works. Connecting through the new Android app hangs indefinitely. If http is selected, the server will log an access and redirect to https, so the server not being reachable is not the problem.

## Devices and Versions

Your Rocket.Chat.Android version: 2.1.1
Your Rocket.Chat Server version: 0.64.1
Mobile device model and OS version: Android 7.1.2

## Steps to reproduce

Attempt to connect to https://chat.hypatiasoftware.org.

## Logs

The server's logs don't contain anything interesting.

![waiting](https://user-images.githubusercontent.com/29542929/40080749-ddde96d2-5883-11e8-9b08-85eb5cd6885b.jpeg)

**Comment by luciofm** [comment]
Hi @ensra, do you have contact with the server admin?

```
      {
         "type" : "int",
         "_id" : "FileUpload_MaxFileSize",
         "value" : null
      },
```

We have a bug on our SDK that won't accept a numeric field with a `null` value.

This will be fixed on the next release, but as a workaround changing this field to 0 would work

**Comment by alarixnia** [comment]
@luciofm Yes, with FileUpload_MaxFileSize set and a change to the OAuth settings to remove the base URL from the paths, login works :) Thank you for the quick fix!
