### ISSUE TITLE
[DUPLICATED] New app doesn't work

### ISSUE THREAD

**Issue by deogracia** [RocketChat/Rocket.Chat.Android#1277]
## Description
I upgraded to the new app.
I tried with 0.63.3 et 0.64.1 server side, but I still got theses issues:
NB: App is in french, so are my error messages. I'll try my best to give what I see and an approximatively english translation.

1. after entering my login/password, I immediatly got "Connexion en N secondes" (Trying reconnect in N seconds")
2. in an existing room or direct message, my messages are sent/ But no answer is displayed. Answers are displayed on the web interface
3. when I try to start a new direct message with someone:
 In the web interface, I see it on the left
 In the android app, nothing happens
 in server log (taken from stagging env), I have
`
May 16 12:56:42 chat-dev RocketChat[26450]: rocketchat_logger.js:278 API v1 Logger ➔ debug POST: /api/v1/channels.join
May 16 12:56:42 chat-dev RocketChat[26450]: rocketchat_logger.js:278 API v1 Logger ➔ debug post channels.join threw an error: Error: The required "roomId" or "roomName" param provided does not match any channel [error-room-not-found]
May 16 12:56:42 chat-dev RocketChat[26450]: at findChannelByIdOrName (/home/rocketchat/0.64.1/programs/server/packages/rocketchat_api.js:891:11)
May 16 12:56:42 chat-dev RocketChat[26450]: at Object.post (/home/rocketchat/0.64.1/programs/server/packages/rocketchat_api.js:1336:24)
May 16 12:56:42 chat-dev RocketChat[26450]: at Object._internalRouteActionHandler [as action] (/home/rocketchat/0.64.1/programs/server/packages/rocketchat_api.js:185:39)
May 16 12:56:42 chat-dev RocketChat[26450]: at Route.share.Route.Route._callEndpoint (/home/rocketchat/0.64.1/programs/server/packages/nimble_restivus.js:347:32)
May 16 12:56:42 chat-dev RocketChat[26450]: at /home/rocketchat/0.64.1/programs/server/packages/nimble_restivus.js:236:33
May 16 12:56:42 chat-dev RocketChat[26450]: at packages/simple_json-routes.js:98:9
May 16 12:56:42 chat-dev RocketChat[26450]: rocketchat_logger.js:278 API ➔ debug Failure { statusCode: 400,
May 16 12:56:42 chat-dev RocketChat[26450]: body:
May 16 12:56:42 chat-dev RocketChat[26450]: { success: false,
May 16 12:56:42 chat-dev RocketChat[26450]: error: 'The required "roomId" or "roomName" param provided does not match any channel [error-room-not-found]',
May 16 12:56:42 chat-dev RocketChat[26450]: errorType: 'error-room-not-found' } }
`

## Devices and Versions

Your Rocket.Chat.Android version: 2.1.1 build 2020
Your Rocket.Chat Server version: 0.64.1

My Mobile device model and OS version: Oneplus 3 / oxygenOS 5.0.1

## Steps to reproduce

* switch from android app legacy to new app

## Logs

Only identifiable by me relevant log are for my third issue

**Comment by rafaelks** [comment]
@deogracia Thanks for opening the issue. The reason of your issue is because your server doesn't support WebSockets. Please, add support to WebSockets and try again. You can see more information about it here: https://github.com/RocketChat/Rocket.Chat.Android/issues/1116.

**Comment by deogracia** [comment]
thanks @rafaelks . I didn't  see #1116 

I checked my apache conf before opening this issue. I'll try again with the help of #1116 

I'll give an update later.

**Comment by rafaelks** [comment]
@deogracia Thank you very much. I understand that this issue is very confusing. Please let us know if that works for you! 👍

**Comment by deogracia** [comment]
Strange, even when I use "Running behind an Apache SSL Reverse Proxy" https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/; I still got the same issues.

I'll check #1116  and contiue testing later.

**Comment by deogracia** [comment]
hi,

took me some time.

On my staging envronment, following https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/ solves my problems

I only had `ProxyPassMatch ^/sockjs/(.*)/websocket ws://HOST:PORT/sockjs/$1/websocket retry=5`. 

When it'll be live, I'll give this issue another update.

Thanks!

**Comment by deogracia** [comment]
Done in production. App works correctly now.

Thanks!
