### ISSUE TITLE
I get this message immediately after entering my Server Hostname: "There is a connection error"

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat.Android#1278]
## Description

Connecting with Rocket.Chat+, right after submitting my hostname, I get an error "There is a connection error."

## Devices and Versions

Rocket.Chat+ Android: 1.0.15
Server: 0.62.1
Note: also have Rocket.Chat Cordova 

Mobile device model and OS version: 
Galaxy Tab A

## Steps to reproduce

Open app, enter hostname:  https://punmessenger.peerunschooling.net
Error immediately appear

## Logs

Don't have logs for it.  But some notes.

The Android Codova app seems to connect just fine, it is the Rocket.Chat+ that gives the error.  Another issue, I created an app in the app store called "PUN Messenger" out of the Cordova app.  This connects fine, but brings up a gray screen after logging in.  Can't get away from it.

**Comment by philipbrito** [comment]
Issue is gone in the current app version. You should only get a warn about not using the minimum recommended server version with the app (0.64.2, yours is 0.64.1)
