### ISSUE TITLE
[NEW] Support Custom Room Types as "Public Channels" by default

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat.Android#1282]
## Description

Once custom room types are defined, rooms of this type are not displayed at all in the Android app

## Devices and Versions

Your Rocket.Chat.Android version: 2.1.1
Your Rocket.Chat Server version: build 2020

## Steps to reproduce

see https://github.com/RocketChat/Rocket.Chat.iOS/issues/1212 . Create a custom room type using the server side API, create a room of this type. It won't be shown neither in the search nor in the chats-list (of subscriptions).

## Expected behaviour

The rooms are listed with the particular icon.
Workaround: Define a fallback-icon and just list the rooms as if they were channels. This is the way it's implemented currently in iOS and seemingly in ReactNative as well

**Comment by rafaelks** [comment]
Just changed the title of this one... if the channel has anything different from the default behaviour, let's understand it as a public channel, like iOS is doing. This way we allow the user to use the channel.

**Comment by rafaelks** [comment]
@luciofm Added the question to the API guys here: https://github.com/RocketChat/Rocket.Chat/issues/11715

**Comment by piotrkochan** [comment]
What are these "new channel types"? Could someone explain?

**Comment by mrsimpson** [comment]
@piotrkochan it’s Not about new room types in standard RC. There‘s an API which allows to define custom room types in one‘s own fork. If you do this, those rooms are currently not even listed in the mobile app

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rodrigok** [comment]
@mrsimpson these apis for channel types registering does not allow custom implementations at server side without custom implementations on mobile apps since it's impossible to define the behavior this new type of channel should have.

Can you explain who you use this custom room type and the room behavior? Then we can discuss better a solution for that.

Thanks

**Comment by mrsimpson** [comment]
@rodrigok Understood - in general. In our case, we used custom room types for some sort of threading and at the same time providing a dedicated toolset in the tabbar. The behavior was very similar to private groups. 

On mobile, there has been a different behavior about subscribed rooms of a custom type on Android and iOS: While they were listable on iOS and behaved like normal rooms, they were totally absent on Android. This issue was about making them at least read- and writable.

I know of other forms with custom room types providing a similar scope (e. g. courses in the educational area).

As you said, the real power of custom rooms only comes with a dedicated mobile UI. In many cases however, the basic need for interaction (writing and reading message) is sufficient when being on the road.

WDYT about introducing metadata on the room types API providing something like inheritance: On the API, one could specify a room type from which the basic behavior (including the mobile one)is being copied (this majorly affects visibility and the power to invite users).

P.s.: We are currently killing our custom room types since this caused complexity and some frustration, particularly because of the rooms not showing up on mobile.

**Comment by rodrigok** [comment]
> WDYT about introducing metadata on the room types API providing something like inheritance: On the API, one could specify a room type from which the basic behavior (including the mobile one)is being copied (this majorly affects visibility and the power to invite users).

Indeed, I was thinking about this some time ago, to be able to create new types of room but defining the original behavior for compatibility when necessary.

**Comment by rafaelks** [comment]
Let's close this issue for now until we've a solution.

**Comment by mrsimpson** [comment]
@rafaelks usually, if you want to find a solution, you leave issues open until then ;-)

**Comment by rafaelks** [comment]
@mrsimpson Well... we don't know if this is actually going to be supported in the core yet, right? I believe that once we know that, we can reopen this issue and add specific information to both iOS and Android. What do you think?

**Comment by mrsimpson** [comment]
@rafaelks _I_ think that iOS and Android should behave equally (currently, they don’t). And _I_ think there should be some mechanism to at least perform messaging in custom room types on mobile without having to fork all the apps. 
Myself and @rodrigok outlined some ideas (e. G. „Inheritance“ or a minimal „only write messages if you are subscribed“).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rafaelks** [comment]
@mrsimpson Agreed, also want to support this, but currently there's no way to do that client-side because there's no API to fetch values from custom rooms/subscription from my understanding. The only reason iOS is working different is because the iOS is still using a very old RealTime method to fetch messages, but this is going to change in near future, where we're going to change the implementation to use the same methods that Android is using.

What about we find a mid-term solution? One idea would be having a `custom.*` API for any kind of custom rooms... this way we don't break compatibility with current clients and in the next API we think about something "unified".

**Comment by mrsimpson** [comment]
The question is how those custom room types behave. Who can see them, who can write or add users? Imho, this should be somewhat described, so that the apps can interpret this data. As I said, being able to message in subscribed rooms is key, the rest is kind-of-bonus
