### ISSUE TITLE
[I18N] RU translation

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1285]
Hi! I performed the translation into Russian. I would like to share it with you. The question is how to do this better? I can attach a .xml translation file right here or edit an existing.

Upd. @filipedelimabrito @rafaelks Could you help me create a strings.xml (in /values-uk-RU or other directory) file for translation into Russian? The translation is ready, I would like to place it in a file.

[strings_RU_xml.tar.gz](https://github.com/RocketChat/Rocket.Chat.Android/files/2053587/strings_RU_xml.tar.gz) Translation has been updated to the current Github version (30/05/2018)

**Comment by rafaelks** [comment]
@Pitstopper That's great! We're going to add this translation soon into the project. Thank you very much! 👍

**Comment by Pitstopper** [comment]
I am glad to help.
