### ISSUE TITLE
Slow opening channel with external links

### ISSUE THREAD

**Issue by dimm0** [RocketChat/Rocket.Chat.Android#1288]
## Description

I have 2 channels containing a bunch of external links. Opening ones on android phone takes ~20-30 seconds. Mac OS version opens one instantly.

## Devices and Versions

Your Rocket.Chat.Android version: 2.1.1
Your Rocket.Chat Server version: 0.64.1

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")
OnePlus 3

## Steps to reproduce
Create a channel with lots of external links, like a notifications about new releases

**Comment by dimm0** [comment]
I'm starting to think the issue is external links. I have another channel with just a few tens of messages, but bunch of external links, and it's opening even slower on my phone – 30-40 seconds

**Comment by lorek123** [comment]
It is still observable on v2.5.1, and users on server that I'm using are quite dissatisfied when they need to wait so long to open the channel.

**Comment by rafaelks** [comment]
This one should be fixed already.
