### ISSUE TITLE
[bug] save message before send it

### ISSUE THREAD

**Issue by mohanadrefaai** [RocketChat/Rocket.Chat.Android#1289]
Messages not saved locally before send it because `client.sendMessage` is suspend function
                        messagesRepository.save(newMessage)

                        val message = client.sendMessage(id, chatRoomId, text)

                        view.showNewMessage(mapper.map(newMessage, RoomViewModel(
                            roles = chatRoles, isBroadcast = chatIsBroadcast)))

                        message

**Comment by leonardoaramaki** [comment]
Closed by #1316
