### ISSUE TITLE
[QUESTION] Not able to connect to server

### ISSUE THREAD

**Issue by earlng** [RocketChat/Rocket.Chat.Android#1291]
## Description

I am having trouble connecting to my self-hosted instance of RocketChat via the mobile Android App.

When I open the app, it prompts me for the server URL, which I provide. But after clicking "submit", it returns the error: "_An error has occurred while checking your server version, please try again_".

I am able to connect to the server from the same mobile phone via browser. I am also able to connect from the desktop and the RocketChat+ desktop program. I also checked with a colleague, and she is able to connect via the iPhone iOS app.

This server that I'm connecting to is using a GoDaddy SSL wildcard cert, with a PEM Phrase.

I had previously provisioned another RocketChat server (same version) with a LetsEncrypt SSL cert. I am able to connect to that server via the mobile app (or at least, I'm prompted for a login).

In both instances, the method of installation was roughly following this: https://rocket.chat/docs/installation/paas-deployments/aws/

I have also confirmed that the Nginx settings are correct.

## Devices and Versions

Rocket Chat Version: 0.64.2
Android App Version: 2.1.1

**Comment by rafaelks** [comment]
@earlng Can you share your server URL? And what version is it? If you wanna share in private with me: `rafael.kellermann at rocket.chat`.

**Comment by earlng** [comment]
Hi @rafaelks, unfortunately, i'm not at liberty to share the URL of the server/grant you access. But I've mentioned that the rocketchat version is 0.64.2

**Comment by perchibald** [comment]
It's also a problem.

Rocket Chat Version: 0.64.2
Android App Version: 2.2

"An error has occurred while checking your server version, please try again"

**Comment by rafaelks** [comment]
@perchibald What's your server URL?

**Comment by perchibald** [comment]
https://chat.shininvest.ru

**Comment by perchibald** [comment]
do I need to grant access?

**Comment by rafaelks** [comment]
@perchibald I believe you're having issues to access because of your SSL:

![screen shot 2018-05-22 at 10 13 49](https://user-images.githubusercontent.com/551004/40364517-e9c5b37a-5da8-11e8-8da2-219e82c510be.png)

**Comment by perchibald** [comment]
what's wrong with the certificate?
in the browser works, in the native application on Linux works, and on Windows too

**Comment by luciofm** [comment]
@perchibald 
Your server is lacking the Intermediate Certificates configuration (or is misconfigured) (https://developer.android.com/training/articles/security-ssl#MissingCa)

https://knowledge.geotrust.com/support/knowledge-base/index?page=content&actp=CROSSLINK&id=SO17664
![screen shot 2018-05-22 at 10 50 26 am](https://user-images.githubusercontent.com/224255/40366714-3b933100-5dae-11e8-98d1-e9135d62ff37.png)

**Comment by luciofm** [comment]
@earlng I'm almost sure you have the same problem. If you could run https://www.sslchecker.com/sslchecker on your domain to check.

This is an example of a misconfigured host
![screen shot 2018-05-22 at 10 54 40 am](https://user-images.githubusercontent.com/224255/40366902-9f82ab82-5dae-11e8-94c3-64600830f2f6.png)
And here what you should get for a host with the Intermediate Certificates configured
![screen shot 2018-05-22 at 10 54 55 am](https://user-images.githubusercontent.com/224255/40366936-b0ca9cba-5dae-11e8-8bb1-368c4d0bdda5.png)

You are able to connect via iPhone probably because iOS already trusts this intermediate certificate, and the web browser caches them. So if you ever accessed a url that uses the same certificate chain, it will work even with misconfigured hosts...

http://nginx.org/en/docs/http/configuring_https_servers.html#chains

**Comment by perchibald** [comment]
thanks guys! everything worked out))

**Comment by earlng** [comment]
Yeap! We fixed our certs on our end, the vendor signed is now yes, and the Android app is now able to connect to server. Closing issue.

**Comment by ksericpro** [comment]
HI, I am having the same problem connecting andriod app to

https://ebcweb.certissecurity.com

**Comment by myllymik-zz** [comment]
We're also experiencing this issue on private server. Certificate is from Let's Encrypt and passes all SSL tests. Some Android versions seems to be working ok but e.g. mine gives the same error, "error checking while checking the server version". Android version 7.0, Rocket.chat client version 2.6.1 and server 0.69.2.

Rocket chat installed with dockerc-compose and located behind Nginx-proxy. Web version works fine.

**Comment by myllymik-zz** [comment]
Fixed it in my case by removing 

`ssl_ecdh_curve secp384r1;`

from nginx configuration. Not sure why this is issue for some Androids but looks like it is.

**Comment by mahdigholipoor** [comment]
i don't have this line in my Nginx configuration.
ssl_ecdh_curve secp384r1;

how can i resolve the same problem?

**Comment by myllymik-zz** [comment]
Have you checked from any included configuration files? In my case I found it out by simply disabling all ssl-related configuration parameters (except the critical ones, ie. cert paths etc.) and then re-enabling them one by one while reloading configuration every time and testing. Ended up with this line that broke it.

**Comment by nodje** [comment]
Same problem with Android8 with v3.0.0 and server setup with snap and Caddy v0.70.4.
Followed https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/ for SSL setup and get this chain detail:

**Comment by elcolie** [comment]
@earlng How did you solve this?
I got lost `ROOT 1 missing` at the last circle

**Comment by muganwas** [comment]
> @earlng How did you solve this?
> I got lost `ROOT 1 missing` at the last circle

Same here, I have a feeling it's got something to do with ROOT_URL variable.
