### ISSUE TITLE
[QUESTION] Can't connect to Rocket.Chat hosted on Sandstorm instance

### ISSUE THREAD

**Issue by takkaria** [RocketChat/Rocket.Chat.Android#1292]
## Description

With the old client, you could connect to a Sandstorm-hosted Rocket.Chat instance.  But with the new one, you type in the API key that Sandstorm gives you and you get the error "Invalid server URL".

## Devices and Versions

Your Rocket.Chat.Android version: Don't know, can't sign in so there is no side menu
Your Rocket.Chat Server version: 0.53.0-develop

Mobile device model and OS version: Motorola Moto G6 - Android 8

## Steps to reproduce

1. Type in the API key from Sandstorm's web interface
2. Click connect
3. Error message appears, connection fails

**Comment by rafaelks** [comment]
@takkaria Server version 0.53.0-delevop is too old (more than 1 year old maybe?). Can you update it to the latest and try again?

**Comment by takkaria** [comment]
Ah, Sandstorm doesn't have a more recent version.  I think the old client had special behaviour though configured for Sandstorm because you need to pass a token in to auth (the URL format is `https://api-<blahblah>.sandcats.io#<token>`).
