### ISSUE TITLE
[BUG] Unread Messages Indication View Doesn't Appear When It Should

### ISSUE THREAD

**Issue by Amirko28** [RocketChat/Rocket.Chat.Android#1302]
## Description
I've noticed a bug concerning the unread messages feature.
When device A sends a message to device B, sometimes the "unread messages" view doesn't appear when I enter the chatroom from device B. Additionally, it does a delayed animation of showing the new message fade in (at first, the new message doesn't appear, but then it fades in the chatroom). However, sometimes it DOES show the unread messages view. I couldn't recreate the case where the view did appear consistently.

## Devices and Versions

Your Rocket.Chat.Android version: 2.2.0
Your Rocket.Chat Server version: 0.65.0-rc.1

Mobile device model and OS version: Galaxy S7 Edge - Android 7.0

## Steps to reproduce
 Most of the time the view doesn't appear when it should. However, sometimes it does appear when it should.

**Comment by rafaelks** [comment]
This is fixed already on #1615.
