### ISSUE TITLE
Push notifications when self hosted RC

### ISSUE THREAD

**Issue by maniac777** [RocketChat/Rocket.Chat.Android#1303]
## Description

Android application do have hardcoded google api notifications sender id in  ./app/src/main/res/values/api_keys.xml. Because of that it is not possible when to have android push notifications when running in self hosted environment. I believe it should be ideal get sender_id from rocket chat server and not having this as hardcoded. In ideal world application should aquire this information from rocket chat server at login time.

I've recompiled chat application with my own sender_id in api_keys.xml and it worked but I believe that there is no point in doubling chat app in play store.

## Devices and Versions

Rocket.Chat.Android version: 8.0
Rocket.Chat Server version: 0.63.1

Mobile device model and OS version: Sony Xpiera XZ1

## Steps to reproduce

1. setup own server with own gcm_server_id and api key
2. try to use push notifications.

## Logs

Push: Send message "john.smith" via query { userId: '_REMOVED_' }
send to token { gcm: '_REMOVED_' }
sendGCM [ '_REMOVED_' ] { _id: '_REMOVED_',
  createdAt: 2018-05-23T17:26:39.077Z,
  createdBy: '<SERVER>',
  from: 'push',
  title: 'john.smith,
  text: 'test 5',
  payload: 
   { host: 'https://example.com/',
     rid: '_REMOVED_',
     sender: 
      { _id: '_REMOVED',
        username: 'john.smith',
        name: 'John Smith' },
     type: 'd',
     name: null },
  badge: 6,
  sound: 'default',
  notId: 1960705544,
  apn: { category: 'MESSAGE' },
  gcm: 
   { image: 'https://example.com/images/logo/android-chrome-192x192.png',
     style: 'inbox',
     summaryText: '%n% new messages' },
  query: { userId: '_REMOVED_' },
  sent: false,
  sending: 0,
  image: 'https://example.com/images/logo/android-chrome-192x192.png',
  style: 'inbox',
  summaryText: '%n% new messages' }
Create GCM Sender using "_REMOVED_"
A:Send message to: _REMOVED_
Push: Sent message "john.smith" to 0 ios apps 1 android apps
Push, GUIDE: The "Push.appCollection" - No APN clients have registred on the server yet...
ANDROID: Result of sender: {"multicast_id":5719301360367011000,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}

**Comment by zalloy** [comment]
My company is in the process of switching over to a self-hosted Rocket.Chat, and it's going to be very annoying (to say the least) that the push notifications to mobile are not working properly. :man_facepalming: 
This needs to be prioritized for a fix asap. I've got version 2.0.2 of the mobile app for Android

**Comment by maniac777** [comment]
I've located ./app/src/main/java/chat/rocket/android/push/FirebaseTokenService.kt where there is sender_id provided from api_keys.xml:

```
    override fun onTokenRefresh() {
        //TODO: We need to use the Cordova Project gcm_sender_id since it's the one configured on RC
        // default push gateway. We should register this project's own project sender id into it.
        try {
            val gcmToken = InstanceID.getInstance(this)
                    .getToken(getString(R.string.gcm_sender_id), GoogleCloudMessaging.INSTANCE_ID_SCOPE, null)

```
Then I've tried to locate sender_id in Rocket.Chat's API but couldn't find the way to get it for non-admin users. So it is possible that this requires changes in both Rocket.Chat and Rocket.Chat.Android.

**Comment by rafaelks** [comment]
@zalloy @maniac777 Thanks for opening the issue guys, we're migrating our app to use FCM instead of GCM on this PR: #1306. After we merge this one, you can simply override the Firebase JSON file and it should work with any external server. 👍
