### ISSUE TITLE
[BUG] Lost account after change name

### ISSUE THREAD

**Issue by kaoecoito** [RocketChat/Rocket.Chat.Android#1308]
## Description

Lost account after change display name of my user in App

## Devices and Versions

Your Rocket.Chat.Android version: 2.2.0
Your Rocket.Chat Server version: 0.64.2

Mobile device model and OS version: Sansung J7 Android 5.1.1

## Steps to reproduce

I installed a rocketchat using docket. After that I accessed it using the Android App, I logged into the user profile and changed my display name, not my username, he said he had changed successfully and then he said he should be logged in.
After this I could no longer access my rocketchat, the function of recovering the password did not work either, whenever I tried to change it informed that there was an error, and even trying to change the password directly in mongodb also had no result.
To confirm the problem I removed the docker installation, deleted the database on the mongo and installed it again.
I tried changing the display name inside the web panel and it worked without problems, then I did the process again using the Android App and totally lost the access again.
I started testing rocketchat 2 days ago so I still do not know the project enough to give more details of what may be causing this problem.

**Comment by kaoecoito** [comment]
I was able to analyze the problem in more detail, and I was able to generate a valid password to recover the password directly in the database.

From what I noticed the problem occurs at line 61 of ProfilePresenter.kt

The call of it is client.updateProfile (myselfId, email, name, username)

However looking in the User.kt class from Rocketkit's Kotlin SDK I saw that the method signature is
suspend fun RocketChatClient.updateProfile (
     userId: String,
     email: String? = null,
     name: String? = null,
     password: String? = null,
     username: String? = null
):
The fourth parameter is password and not username, this way every time the user's profile is changed by android the password becomes the user's name.

**Comment by rafaelks** [comment]
@kaoecoito Thanks for investigating the issue, we're going to fix this one soon 👍

**Comment by leonardoaramaki** [comment]
Closed by #1331

**Comment by rockneverdies55** [comment]
Just had a similar issue today on server version 0.69.2 and the app version 2.6.0. In the profile settings page within the app, I recognized that the email field was missing so I filled it in with my account email address and saved; it worked out successfully. However then I couldn't login anymore either in app or using web...
