### ISSUE TITLE
[Question] How to limit the app to one server?

### ISSUE THREAD

**Issue by abdellahaski** [RocketChat/Rocket.Chat.Android#1315]
## Description

Hello,
How can I limit the app to only my self hosted server ?
It's not an issue It just a question everything else works perfectly I just want to limit it to only my server. 

## Devices and Versions

Your Rocket.Chat.Android version: 2.3.0 Build 2022
Your Rocket.Chat Server version: 0.64.2

**Comment by dachnikrus** [comment]
Hi, there is no such functionality yet. But you can try to hardcode your URL.

**Comment by rafaelks** [comment]
@abdellahaski There's no way to do that today, but PRs are welcome, we really want to have a this support.

**Comment by dachnikrus** [comment]
@abdellahaski One way to do this right now, without PR is: app -> res -> layout -> fragment_authentication_server.xml 
There you can hide http:// https:// choose and EditText with addres, but there type in your URL in android:hint="you.url.com"

This way, for the first start of app you tap connect and it uses your server

**Comment by abdellahaski** [comment]
Thank you so much guys for your help, I'll try it.
