### ISSUE TITLE
[BUG] Error when i tap on file list

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1323]
Your Rocket.Chat.Android version: 2.3.0
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.12) , Developer ROM
Your Rocket.Chat Server version: 0.64.2

When I tap on the file list, I get an error:

![screenshot_2018-05-30-11-38-09-804_chat rocket android](https://user-images.githubusercontent.com/18574776/40709668-5c008026-63ff-11e8-9aae-3349e253d985.png)

**Comment by mmarif4u** [comment]
I am getting different error on some rooms.  
`the following properties were null : uploadedAt`

**Comment by Pitstopper** [comment]
Yes, I also have this and also not on all channels

**Comment by rafaelks** [comment]
@Pitstopper @mmarif4u Thanks for the report guys, we're going to take a look! 👍

**Comment by philipbrito** [comment]
@Pitstopper and @mmarif4u This is something with our API that we can track from here: https://github.com/RocketChat/Rocket.Chat/issues/10969

Regarding `the following properties were null : uploadedAt` message, this was fix in [our side](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/175).

**Comment by Pitstopper** [comment]
Thanks!

**Comment by rafaelks** [comment]
@filipedelimabrito Bug still happens with other fields, just reproduced in our own server (#important):

![screenshot_20180601-192018](https://user-images.githubusercontent.com/551004/40865857-08174b56-65d1-11e8-8ecc-68adc22ea7d3.png)

**Comment by philipbrito** [comment]
@rafaelks As I said [above](https://github.com/RocketChat/Rocket.Chat.Android/issues/1323#issuecomment-393909276), this is a backend issue (not a client issue). Please take a look on https://github.com/RocketChat/Rocket.Chat/issues/10969
