### ISSUE TITLE
[IMPROVEMENT] Google Smart Lock is too intrusive in 2.3.0

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1324]
## Description

Let's add a button to call Google Smart Lock instead of opening by itself.

## Devices and Versions

Your Rocket.Chat.Android version: 2.3.0.

## Steps to reproduce

1. Today, only opens the Authentication screen and Google Smart Lock will show;

## Expected Results

1. Open the authentication screen;
2. See Google Smart Lock icon and press it to be prompted;

**Comment by philipbrito** [comment]
Closed by #1334
