### ISSUE TITLE
Indicator of channels with unread messages

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#134]
Related to #126 and #97 it would be useful to have an indicator that there are unread messages in other channels.  As well as a count on how many mentions.   

This is what we have on our web view and our cordova app:

![image](https://cloud.githubusercontent.com/assets/51996/21831145/593a6f3a-d767-11e6-838f-4535f06d7461.png)

**Comment by YusukeIwaki** [comment]
I suspect that the budge is not usually used in Android app.
It is iOS's culture, and web ui (including Cordova app) just imitate it.


First, I will try implementing it with #97

**Comment by geekgonecrazy** [comment]
I'm not super partial to it.  But for sure need some way of indicating in any view that there are unread.  For me I find it useful to have that combo of unread - low priority.  Mentions - higher priority.  But both very useful.  If we need to convey that some other way?

Does seem pretty common though.  Here is discord for example:
![screenshot_20170110-221050](https://cloud.githubusercontent.com/assets/51996/21835315/ad79060a-d781-11e6-8950-030c9d997050.png)
