### ISSUE TITLE
Connecting the Sandstorm version to the Android version

### ISSUE THREAD

**Issue by Jeangleur** [RocketChat/Rocket.Chat.Android#1341]
When connecting a rocket chat that is installed on a sandstorm from its own app-market with the android rocket chat app, it asks me to install a later version.

I am using a Google-Store free Android (copperhead) and Ubuntu Linux Firefox Browser where I access the latest version of sandstorm on a VPS. With Rocket chat open, I choose "share grain" and add this link to the adroid app when it asks for server link.

Your Rocket.Chat Server version: (e.g. 0.52.0)

**Comment by rafaelks** [comment]
Check our supported versions here: https://rocket.chat/docs/developer-guides/mobile-apps/supported-servers-versions/#supported-servers-versions
