### ISSUE TITLE
[QUESTION] Attachments field is not an object, but an String

### ISSUE THREAD

**Issue by Skvortsovg** [RocketChat/Rocket.Chat.Android#1343]
## Description

See screenshot

## Devices and Versions
Your Rocket.Chat.Android version: 2.2.2 (build 2021)
Your Rocket.Chat Server version: 0.65.1

Mobile device model and OS version: 
Samsung Galaxy S7 - Android 7.0

## Steps to reproduce
The error occurs after connecting to the server. Chats are searched for, but you can't write anything in them. Also tested on Iphone 6s with the latest version of the app-everything works
![rocketbug](https://user-images.githubusercontent.com/10686156/40984197-f2334206-68e9-11e8-9757-46b29951de32.jpg)

Before updating the application there was no error.

**Comment by philipbrito** [comment]
Is it still happening? We just released a 2.3.0 beta version to the Store (you can also get it here). Could you test again and tell us if is it still happening?

**Comment by rafaelks** [comment]
@Skvortsovg The error is happening because we don't expect the `attachments` property to be an array of Strings... please confirm to us if that's still happening? Is this a new message in your server or a very old one? We would like to know how you end up having this values.

**Comment by Skvortsovg** [comment]
The problem persists on the version 2.3.1 too.
The problem was solved by re-creating group chats. There may be a problem escaping some characters in the message

**Comment by rafaelks** [comment]
This is suppose to be fixed in 3.1.0.
