### ISSUE TITLE
No date separator in message list

### ISSUE THREAD

**Issue by cmassi** [RocketChat/Rocket.Chat.Android#1346]
## Description

There is no date separator between messages

## Devices and Versions

Your Rocket.Chat.Android version: 2.2.0 build 2021
Your Rocket.Chat Server version: 0.65.1 

Mobile device model and OS version: (e.g. "Huawei P8 Lite- Android 7.0")

## Steps to reproduce

Open #general to see the issue

**Comment by cmassi** [comment]
"[UI] Day marker or date with time. #865" still to be merged in 2.2.0

**Comment by philipbrito** [comment]
This will be shipped soon. There is an opened PR to do that. I'm closing this issue since you can track/interact from #865

Thanks.
