### ISSUE TITLE
[NEW] Larger Image Preview

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#135]
When images are posted, being able to quickly view them is often important.  In our current web app and cordova app tapping enlarges it to conveniently view it.

**Comment by Artraxon** [comment]
someone knows what the status on that is?
Would be a really important feature if you really want people to move from slack to rocketchat.

**Comment by geekgonecrazy** [comment]
I would recommend using the other app if you need this feature right away.   Its fully functional.  Just not as shiny :)  This native app is still in beta.
