### ISSUE TITLE
[INVESTIGATE] Use JsonReader.setLenient(true) to accept malformed JSON at path$ on sending a file

### ISSUE THREAD

**Issue by perchibald** [RocketChat/Rocket.Chat.Android#1352]
## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.3.1)
Your Rocket.Chat Server version: (e.g. 0.65.1-develop)

Mobile device model and OS version: (e.g. "Xiaomi Redmi Note 4X - Android 7.0")

## Steps to reproduce
when sending a file, an error pops up.
"Use JsonReader.setLenient(true) to accept malformed JSON at path$"

**Comment by philipbrito** [comment]
@perchibald What kind of file were you sending?

**Comment by perchibald** [comment]
any

**Comment by rafaelks** [comment]
@perchibald What's your server URL?

**Comment by perchibald** [comment]
chat.shininvest.ru

**Comment by bnngld** [comment]
I have this same error when attempting to upload any files from my phone to Rocket.Chat.

Devices and Versions:

Rocket.Chat Android Version 2.4
Rocket.Chat Service Version .65.2
Mobile Device Model and OS Version: Pixel 2 XL Android P Build # PPP3.180510.008

This is also happening on other phones in my department that are not running the Android P Dev Preview. 

Please advise.

**Comment by bnngld** [comment]
Any news?

**Comment by philipbrito** [comment]
@bnngld As soon as we got news/fixes we'll cite or reference it here.

**Comment by philipbrito** [comment]
We're able to send any file format successfully now. Also, just for information, before sending a file a dialog is show and you can send that with a description too.

**Comment by fromage9747** [comment]
I get this issue on the Android app with video files only.  They are not very big either.  Even having a description included still causes the issue

**Comment by reetp** [comment]
@fromage9747 
Test on latest version 0.70.0 with the latest app and if the bug still exists open a new bug and reference this one please.

**Comment by fromage9747** [comment]
@reetp Confirmed that I am running the latest version of the Mobile APP and the server.  I tested this again on the legacy app and the video upload works without any issue.  The issue is present in the latest Mobile APP.  I will create a new bug and reference this one.

**Comment by luckenbach** [comment]
I have a end user also getting this on a 0.70.4 when attempting to send pictures

**Comment by vampirismtrueblood** [comment]
I'm having the exact same issue ... I cannot upload any kind of file ... using the Normal Android way, I need to select File Upload way.
Also ... I cannot Upload from Recent files ... I need to navigate to images after I click the '+' sign on the app.
I'm using latest EVERYTHING.
Specs:
Note 8: Android 8.0.0
Android app: V 3.1.1 Nov 5, 2018
Server: 
    Ver: 0.71.1
    Commit: e73dc78ffda9555fb98465ed94632473e6d63240

**Comment by rafaelks** [comment]
@vampirismtrueblood Please check this comment to see the solution: https://github.com/RocketChat/Rocket.Chat.Android/issues/1862#issuecomment-440640888.

**Comment by vampirismtrueblood** [comment]
@rafaelks, thanks for the response, however I highly doubt I'm hitting max_body on nginx ... I'll give it a try though .. 

The reason being that 
1. It's working great on older app version
2. The same file could be uploaded using "Images" category as opposed to using "Recent" ... Seems like perms problem.

Also notice that I can upload file using Non-Android way ... I.e you're always given an option to upload file the "Normal way" or the "File upload way" ...
I'll feedback once I get to it though.

Thanks @rafaelks

**Comment by joside** [comment]
I have the same problem on the latest Android App: Uploading using Files from the "Recent..." Folder is not possible and gives us that JsonReader.setLenient Message. Uploading on Desktop Client is working, uploading from the Android App with a direct Path is also possible.
