### ISSUE TITLE
[BUG] Closing keyboard also close the chatroom activity in landscape view

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1358]
![ezgif-3-140476b6e1](https://user-images.githubusercontent.com/16731434/41280945-dba40a5c-6e4d-11e8-8ea2-89c41ada7c80.gif)

**Comment by philipbrito** [comment]
Would you like to work on this bug @divyanshub024 ?

**Comment by divyanshub024** [comment]
Sure :+1:
