### ISSUE TITLE
[QUESTION] Android App not Working for RocketChat

### ISSUE THREAD

**Issue by nwd3** [RocketChat/Rocket.Chat.Android#1360]
Description:
I have rocketchat version 0.65.1 installed(this issue also occurs for version 0.60.1) and the rocketchat android app does not work. I tried multiple versions of the app. It always errors out giving messages like: "this is not a valid rocketchat instance" and other error messages. The server works fine on the ios app. SSL is enabled behind an apache server.

Server Setup Information:
Version of Rocket.Chat Server: .65.1
Operating System: Centos 7
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 1
DB Replicaset Oplog: not enabled
Node Version: not sure
mongoDB Version: not sure
Steps to Reproduce:
open rocketchat app
type in server address
error message shows
Expected behavior:
rocketchat android app to work.

Actual behavior:
App errors out

Relevant logs:
not available

**Comment by rafaelks** [comment]
@nwd3 Can you provide us your server URL?

**Comment by philipbrito** [comment]
No response since one month ago. Closing it, but as always feel free to reopen again if the problem persists.
