### ISSUE TITLE
Image uploads show as giant in other clients

### ISSUE THREAD

**Issue by karrots** [RocketChat/Rocket.Chat.Android#1361]
## Description

Image uploads show as giant (unscaled). Other clients like iOS and the desktop fat client seem to scale the photos to they don't need scrolling at upload.

## Devices and Versions

Your Rocket.Chat.Android version: 2.3.2
Your Rocket.Chat Server version: 0.65.1

Mobile device model and OS version: Android 8.1 on Pixel 2 and LG V20

## Steps to reproduce

1. Upload image with android client

**Comment by ArchimedesFM** [comment]
I have the same problem but with the iOS App. There is no difference between a new picture taken in the upload process and an "old" picture. 
Your Rocket.Chat.Android version: 2.4.1
Your Rocket.Chat Server version: 0.65.1

https://github.com/RocketChat/Rocket.Chat.iOS/issues/1766

**Comment by rafaelks** [comment]
Looks like this is a bug on the web displaying the image, fixed here: https://github.com/RocketChat/Rocket.Chat/pull/10998.
