### ISSUE TITLE
OTR Support on Android

### ISSUE THREAD

**Issue by brunolopes446** [RocketChat/Rocket.Chat.Android#1373]
Hi all.

I have the latest Rocket Chat android version up to the moment (2.3.2), and I see no OTR support.

Is there a way of having secure communications between two mobile (Android) devices?

I know that through the web there is OTR support.

Although using HTTPS, the server admin is able to read the conversations from the DB - and OTR avoids  this.

**Comment by philipbrito** [comment]
This is a duplicate from https://github.com/RocketChat/Rocket.Chat.Android/issues/691
