### ISSUE TITLE
[IMPROVEMENT] The layout of the attachment messages needs to be improved

### ISSUE THREAD

**Issue by ubarsaiyan** [RocketChat/Rocket.Chat.Android#1381]
## Description
The image attachment's title is not properly displayed and the description is not displayed at all in the Rocket.Chat android app. I have attached a screenshot too. 

![screenshot from 2018-06-15 19-39-25](https://user-images.githubusercontent.com/22556377/41472476-27a990c4-70d4-11e8-91d4-6b01487d0c83.png)

## Devices and Versions

Your Rocket.Chat.Android version: 2.3.2 Build 2026
Your Rocket.Chat Server version: open.rocket.chat

Mobile device model and OS version: Oneplus 3 Oreo 8.0

## Steps to reproduce
Send an image attachment with desc and title from web and see it on the android app.

I would love to work on this issue. It would be really helpful if someone can also give some pointers. :)

EDIT:
This is the log of `Message` Object that the `translate` function is receiving in the file chatroom/uimodel/UiModelMapper.kt
```
Message(id=jJseXdiGGXK97e6pz, roomId=L73ECFoZSeDJsBMsJWMRzgjyHDBQYhJ7h7, message=, timestamp=1528990675967, sender=SimpleUser(id=L73ECFoZSeDJsBMsJ, username=RichMessageTestBot, name=RichMessageTestBot), updatedAt=1528991058827, editedAt=null, editedBy=null, senderAlias=null, avatar=null, type=null, groupable=false, parseUrls=false, urls=null, mentions=[], channels=[], attachments=[ImageAttachment(title=Lauri M, description=null, titleLink=https://www.basketball-reference.com/players/m/markkla01.html, titleLinkDownload=false, imageUrl=http://www.trbimg.com/img-5b04c449/turbine/ct-spt-bulls-lauri-markkanen-all-rookie-team-20180522, imageType=null, imageSize=null, imagePreview=null)], pinned=false, starred=null, reactions={:mouse:=[utkarsh.barsaiyan]}, role=null, isTemporary=null, unread=null)
```
The above object does not contain a `text` field but has a `description` field in the image attachment set to `null`.

But in the following log the `text` field can be seen:
```
06-18 09:38:36.391 3231-3314/chat.rocket.android.dev D/TimberLogger: SDK(https://dev.veranda.viasat.io): Received text message: {"msg":"changed","collection":"stream-notify-user","id":"id","fields":{"eventName":"DmZw72BAjmsZGQ5YR/rooms-changed","args":["updated",{"_id":"DmZw72BAjmsZGQ5YRL73ECFoZSeDJsBMsJ","t":"d","_updatedAt":{"$date":1529329117013},"lastMessage":{"rid":"DmZw72BAjmsZGQ5YRL73ECFoZSeDJsBMsJ","attachments":[{"title":"Lauri M","title_link":"https://www.basketball-reference.com/players/m/markkla01.html","text":"Should have been rookie of the year","image_url":"http://www.trbimg.com/img-5b04c449/turbine/ct-spt-bulls-lauri-markkanen-all-rookie-team-20180522","color":"#164FA5"}],"ts":{"$date":1529329117000},"u":{"_id":"L73ECFoZSeDJsBMsJ","username":"RichMessageTestBot","name":"RichMessageTestBot"},"msg":"","mentions":[],"channels":[],"_updatedAt":{"$date":1529329117002},"_id":"Krp5pAjNDjxWyDrNh","sandstormSessionId":null}}]}}, channel: RendezvousChannel@f28520{EmptyQueue}
```
So, the text field gets lost between the JSON fetched from the server and the Image Attachment that is displayed. And there is some ambiguity between text and description fields. The description field is not mentioned in the docs of the image attachment. If anyone can provide any information to solve the issue, it would be of great help.

**Comment by divyanshub024** [comment]
@ubarsaiyan It's true that description is not displayed in android app but I think title is displayed properly, if not, then what do you think how title should be displayed.

**Comment by ubarsaiyan** [comment]
@divyanshub024 I think the title should be darker and a slightly bigger font and may be above the photo. Though the description not being visible is the primary issue.

**Comment by bizzbyster** [comment]
I'd like to take a step back and summarize how this works today on the web client and how it works on Android, which will identify we have multiple issues.

`"attachments": [
    {
      "title": "Lauri M(title field)",
      "title_link": "https://www.basketball-reference.com/players/m/markkla01.html",
      "text": "Should have been rookie of the year (text field)",
      "description": "What a great player! (description field)",
      "image_url": "http://www.trbimg.com/img-5b04c449/turbine/ct-spt-bulls-lauri-markkanen-all-rookie-team-20180522",
      "color": "#164FA5"
    }
  ]`

The above is the attachments json sent by https://dev.veranda.viasat.io/direct/RichMessageTestBot in response to the word "attachment". In the web client this results in:

![image](https://user-images.githubusercontent.com/4001792/41661274-4dd6959e-746c-11e8-91f1-61b01fb9a5ad.png)

On Android, this results in:
![image](https://user-images.githubusercontent.com/4001792/41661351-8b4c652a-746c-11e8-8d59-2584aafc1703.png)

The title_link is ignored so there is no way to click and go to the title_link as there is in web client.

Assuming we want the Android client attachment to look like and act like the web client (which I think is debatable):
1) the title field is at the bottom of the image
2) the description field is dropped
3) the text field is dropped
4) the title_link is dropped

To do a brute force fix, all of the above would be addressed in a way that is similar to the web client.

This is what slack does. So for the same attachments json above, slack on the web client looks like this:
![image](https://user-images.githubusercontent.com/4001792/41663641-e52d3754-7471-11e8-8ac7-f5908186e114.png)

And on the android client looks like this:
![image](https://user-images.githubusercontent.com/4001792/41663663-f45e00aa-7471-11e8-8c1a-2659c9e0ae14.png)

Note that Slack does not display either the text or the description field in either the web client or the Android client. So as a wider team (@Sing-Li @rodrigok @engelgabriel @timkinnane @JSzaszvari @rafaelks ), we need to decide what our design is here for attachments.

**Comment by rafaelks** [comment]
@bizzbyster We're going to improve the layout for all the message components, and the message attachment is one of them, thanks for the examples. The idea is to replicate what the web is doing with the data today, but in a format that fits in a mobile device. 👍 

When I have more information about this here I'm gonna share you with you guys.

**Comment by bizzbyster** [comment]
@rafaelks do you agree that we (@ubarsaiyan)  should fix the issue where the "text" field is not transferred from the receipt of the message json in the Kotlin SDK but it does not show up in the ImageAttachment? That this will be needed in any event. Also, can we be included in the discussion around the layout improvements? Thanks!

**Comment by rafaelks** [comment]
@bizzbyster Yes, that can be fixed! Sure I can show you and include you in the discussion, we're still drawing the first components, when we've something I'll share with you. 👍
