### ISSUE TITLE
[CRASH] Completely crashes if GApps are not installed

### ISSUE THREAD

**Issue by vynmera** [RocketChat/Rocket.Chat.Android#1383]
Since a few versions now, the app crashes upon startup. I am running a GAppsless phone, so I am missing Firebase, and new code has caused this to crash the app.

Logcat:
```
06-15 19:33:25.120 E/AndroidRuntime(23328): java.lang.RuntimeException: Unable to instantiate service com.google.android.gms.measurement.AppMeasurementService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementService" on path: DexPathList[[zip file "/data/app/chat.rocket.android-HYGTQFUiHwzXBCS2OSKv0g==/base.apk"],nativeLibraryDirectories=[/data/app/chat.rocket.android-HYGTQFUiHwzXBCS2OSKv0g==/lib/arm64, /data/app/chat.rocket.android-HYGTQFUiHwzXBCS2OSKv0g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
``` 

My device is a OnePlus 3T running Lineage (Android 8.1.0).

**Comment by luciofm** [comment]
@vynmera this is a known issue...

There is a user working a FOSS version of the app -> https://github.com/RocketChat/Rocket.Chat.Android/pull/1232

Soon we will have a flavor that doesn't depends on the PlayStore and will publish it on f-droid

**Comment by himpierre** [comment]
Any news on the f-droid version?

**Comment by rafaelks** [comment]
@himpierre You can follow the progress here: https://github.com/RocketChat/Rocket.Chat.Android/pull/1232.

**Comment by rafaelks** [comment]
Fixed already.
