### ISSUE TITLE
[BUG] The bottom row of emojis is not displayed

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1385]
Your Rocket.Chat.Android version: 2.3.0 - 2.4.0
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.12) , Developer ROM
Your Rocket.Chat Server version: 0.65.2

![img_20180618_111502](https://user-images.githubusercontent.com/18574776/41525239-f6bd9610-72e8-11e8-93b3-858f6e825fc5.jpg)

![screenshot_2018-06-18-11-12-40-326_chat rocket android](https://user-images.githubusercontent.com/18574776/41525254-02fa05d0-72e9-11e8-8d28-bdbc4264aec9.png)

**Comment by divyanshub024** [comment]
@Pitstopper Good catch!!
