### ISSUE TITLE
Deleted images still showing on android - still in app's cache

### ISSUE THREAD

**Issue by thashaw** [RocketChat/Rocket.Chat.Android#1390]
## Description

Images still showing in chat after deletion from web/desktop or another mobile app.
Basically, it's still stored on the local phone app's cache system. After clearing the cache, then the images will disappear but placeholders are still present.

## Devices and Versions
Your Rocket.Chat.Android version: 2.4.0 (Build 2027) and Experimental (2018-06-18)
Your Rocket.Chat Server version: 0.65.1 

Mobile device model and OS version: Samsung S9+ and Samsung S8 - Android 8.0.0 

## Steps to reproduce

1. User 1 and 2 both uploads a image, from mobile
2. Both users will see each other's image on desktop and mobile
3. User 1 deletes image on desktop, it clears.
4. User 2 - desktop / mobile's image is cleared
5. User 1's mobile app still has the deleted image.
6. User 1, closes app, restarts, Image is still in chat
7. User 1's image only clears after going to phone/settings/apps/rocket.chat/clear cache
8. User 1's mobile app - will have a place holder - as attached
![screenshot_20180619-124924_rocketchat](https://user-images.githubusercontent.com/40378741/41577601-5bbcb6ae-73c0-11e8-8c3c-c8073879c59d.jpg)

**Comment by Pitstopper** [comment]
@thashaw Hi! It's duplicate #1142 ?

**Comment by thashaw** [comment]
Hi @Pitstopper 
Thanks for linking to the other bug, I missed that one when I was searching under images not cleared.

For the beta version of the Rocket.chat, User 2 was able to see the image that User 1 deleted.
So it's not only the owner of the message that can still see the deleted image/message, though not always.

**Comment by thepowerprocess** [comment]
@pitstopper I am seeing this as well.  I do not think this is a duplicate because if a different user delete's the image/msg, other users can still see it through the app.  If they access the server through the browser, the image/message is shown to be deleted, however.

**Comment by Pitstopper** [comment]
@cloudsandladders  Yes you are right. This is not a duplicate.

**Comment by rafaelks** [comment]
This issue is blocked because there's no way to get deleted messages via API. Also, duplicated from #1142
