### ISSUE TITLE
Attaching large images via the Android App

### ISSUE THREAD

**Issue by earlng** [RocketChat/Rocket.Chat.Android#1392]
## Description

We are experiencing some issues when we try to send large images (>1 MB) through the android app. Simply put, when I try to attach any large image, the chat app refuses to accept it, and then it just returns some sort of "JSON error".

This problem does not occur when I try to send smaller sized files (like phone screenshots), which are typically smaller than 1 MB.

I already checked if its caused by the File Upload limits, and I can rule that out. I set the limit to 20 MB, and the same images can be sent via the RocketChat desktop app, as well as the legacy Rocket Chat Android App.

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.4.0)
Your Rocket.Chat Server version: (e.g. 0.64.2)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

## Steps to reproduce

Try to take a picture using your phone app. And then send the image via the RocketChat App.

**Comment by rafaelks** [comment]
This is suppose to be fixed right now.

**Comment by kusakv** [comment]
Same issue on iOS App. Small files are OK

**Comment by rafaelks** [comment]
@kusakv Please check here for a solution: https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754.

**Comment by kusakv** [comment]
> @kusakv Please check here for a solution: [RocketChat/Rocket.Chat.iOS#2184 (comment)](https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754).

You are awesome! Thanks a lot!
