### ISSUE TITLE
[NEW] Notify new message in the chat room

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#1394]
When seeing older messages the users are unable to know when a new message arrives in the chat room. It will be nice if, when not showing the most recent message (i.e the scroll isn't at the bottom of the view), notify the user about a new message arrival.

**Comment by shubhsherl** [comment]
Hi, I would like to contribute to this issue, I have some experience with Android, could you guide me further.

**Comment by philipbrito** [comment]
That's great @shubhsherl !

We have a channel in our server that we discuss everything related to the Android app. Could you [join us](https://open.rocket.chat/channel/androidnativeapp) there?

Here are the orientation of how we think about the behaviour of this feature: https://open.rocket.chat/channel/androidnativeapp?msg=ceGsrnJFtoFz3E6Lt

This is important too: https://open.rocket.chat/channel/androidnativeapp?msg=K9hN7WRZzT2D6Kyx5

Thanks for you interest!
