### ISSUE TITLE
[NEW] Group chats by favorites

### ISSUE THREAD

**Issue by moriccelli** [RocketChat/Rocket.Chat.Android#1395]
The app only allows grouping the chats room by type. Grouping by favorites should be possible to the user too.

**Comment by philipbrito** [comment]
The feature to star/unstar a chat room will be implemented soon. You can track its status [here](https://github.com/RocketChat/Rocket.Chat.Android/issues/1009).
Regarding the "Group by Favorite"  I changed your issue title/description so as soon as we implement it we'll close this issue.

Thanks for opening!

**Comment by FaizanZahid** [comment]
waiting patiently for this feature.
