### ISSUE TITLE
Notifications messages mobile

### ISSUE THREAD

**Issue by CH1PSET1** [RocketChat/Rocket.Chat.Android#1398]
## Description

Notifications messages

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.4.0)
Your Rocket.Chat Server version: (e.g. 0.65.2-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")
Xiaomi mi6 - Android 8.0, Samsung Galaxy S7 Edge - Android 7.1, Samsung A5 - Android 7.

## Steps to reproduce

Hello. Tell me, please, like everything worked fine yesterday, today notifications and pop-up messages on the phone have stopped coming. On the computer application, everything is fine. With what it can be connected? Checked on different phones. In different rooms, with different rights and settings.

And, if you go to the application, then all messages reach and hang unread.

**Comment by rafaelks** [comment]
There was an outage on the push notification service, everything should be fine now.
