### ISSUE TITLE
[Issue/current develop-Branche] chatroom_actions & Read Receipt don't work

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat.Android#1400]
Rocket.Chat.Android version: (Develop)
Rocket.Chat Server version: (0.66.0-rc0)

Chatroom Action's don't work in my own compile :( is this an issue from my GIT Repo or a knowing bug ? 

**Update:**
I created a clean GIT Branch with the current origin/develop without success, the Read Receipt don't work & the Action switching to Members/Files and so on.... are empty aka Listview or so....

**Comment by leonardoaramaki** [comment]
Thanks for opening this one!
I'll assume that the read receipts setting is enabled for your server, so can you explain exactly what's happening? The checkmark is not showing at all or it's just no showing the read state?
