### ISSUE TITLE
App not connecting to server on Android < 8.0

### ISSUE THREAD

**Issue by AdrianM2** [RocketChat/Rocket.Chat.Android#1409]
## Description
I'm not able to connect to our RocketChat server using any device with android version below 8.0.
There is always error saying "An error occurred while checking your server version"

## Devices and Versions
Your Rocket.Chat.Android version: 2.4.0
Your Rocket.Chat Server version: 0.65.2

## Steps to reproduce
Problem exists on every device with android version below 8.0
On Android 8.0 adding server is working fine.

Someone suggested that it might be SSL certificate issue but I checked it using digicert.com and it says that everything is ok.

**Comment by dachnikrus** [comment]
Faced the same issue

**Comment by rafaelks** [comment]
@dachnikrus @AdrianM2 Can you provide us your server URL?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iprok** [comment]
I also have problems with android client on android < 8. I can login but can't load any content after it. Just getting 3 dots (as like when content is loading). Client version 2.4.0 and 2.3.2 rocket chat server 0.66.0. Rocketchat installed at https://tut.chat

**Comment by AdrianM2** [comment]
@rafaelks just sent you an email with server URL.

**Comment by AdrianM2** [comment]
Problem solved. It was caused by wrong firewall configuration on network with rocketchat server.

**Comment by asadmukhtar28** [comment]
After adding my host and SSL certificate IOS app is working fine but Android App signin, signup not working?
