### ISSUE TITLE
Password can't be changed

### ISSUE THREAD

**Issue by dachnikrus** [RocketChat/Rocket.Chat.Android#1418]
## Description

I'm trying to change it, after that I have a notification, which says "Password changed successfully", but in fact it isn't changed

P.S. In any case, it will be great to enter current password, before changing it for more security. Because in other case it is better to use "Forgot Password"

## Devices and Versions

Your Rocket.Chat.Android version: 2.4.0
Your Rocket.Chat Server version: open.rocket.chat

Mobile device model and OS version: Pixel 2 API 24

## Steps to reproduce

Menu -> Settings -> Change Password -> Type the new one -> confirm -> Logout -> Login to server with new password -> Unathorized

**Comment by rafaelks** [comment]
@dachnikrus Is this still reproducible?
