### ISSUE TITLE
java compiler 

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.Android#1423]
## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

## Logs

null |  
-- | --
the '-d' option with a directory destination is ignored because '-Xbuild-file' is specified |  
classpath entry points to a non-existent location: D:\Project\Rocket.Chat.Android-2.4.0\app\src\debug\java |  
classpath entry points to a non-existent location: D:\Project\Rocket.Chat.Android-2.4.0\app\src\main\kotlin |  
classpath entry points to a non-existent location: D:\Project\Rocket.Chat.Android-2.4.0\app\src\debug\kotlin |  
note: Processing module RocketChatLibraryModule |  
note: Processing module RocketChatServerModule |  
note: Processing class RealmBasedServerInfo |  
note: Processing class RealmEmail |  
note: Processing class RealmPreferences |  
note: Processing class RealmPublicSetting |  
note: Processing class RealmSession |  
note: Processing class RealmSettings |  
note: Processing class RealmUser |  
note: Version 5.3.1 of Realm is now available: https://static.realm.io/downloads/java/latest |  
warning: Supported source version 'RELEASE_7' from annotation processor 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' less than -source '1.8' |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\server\infraestructure\ConnectionManager.java:7: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\server\infraestructure\ConnectionManager.java:8: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\server\infraestructure\ConnectionManager.java:32: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\server\infraestructure\ConnectionManager.java:37: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatroom\presentation\ChatRoomPresenter.java:17: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatroom\presentation\ChatRoomPresenter.java:19: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatroom\presentation\ChatRoomView.java:127: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatroom\ui\ChatRoomFragment.java:295: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatrooms\ui\ChatRoomsFragment.java:141: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatrooms\presentation\ChatRoomsView.java:24: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatrooms\presentation\ChatRoomsPresenter.java:12: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatrooms\presentation\ChatRoomsPresenter.java:15: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\server\infraestructure\ConnectionManagerKt.java:16: error: State is not public in kotlin.collections; cannot be accessed from outside package |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatroom\presentation\ChatRoomPresenter.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatroom\ui\ChatRoomFragment.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatrooms\presentation\ChatRoomsPresenter.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\chatrooms\ui\ChatRoomsFragment.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |  
d:\Project\Rocket.Chat.Android-2.4.0\app\build\tmp\kapt3\stubs\debug\chat\rocket\android\dagger\AppComponent.java:8: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. |

**Comment by philipbrito** [comment]
Invalid issue.

**Comment by almuwahhid** [comment]
i have same problem too
