### ISSUE TITLE
i dont know what is this 

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.Android#1425]
CURRENT DIR: /home/mahmoud/Desktop/Project/Rocket.Chat.Android-2.0.2/app
SDK DIR: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK
./build-sdk.sh: line 36: : command not found
./build-sdk.sh: line 74: cd: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK: No such file or directory
./build-sdk.sh: line 31: cd: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK: No such file or directory
CURRENT SHA: 0.1-SNAPSHOT
./build-sdk.sh: line 18: cd: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK: No such file or directory
./build-sdk.sh: line 25: cd: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK: No such file or directory
is dirty
./build-sdk.sh: line 91: cd: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK: No such file or directory
./build-sdk.sh: line 92: cd: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK: No such file or directory
rm: cannot remove '/home/mahmoud/Desktop/Project/Rocket.Chat.Android-2.0.2/app/libs/common*': No such file or directory
rm: cannot remove '/home/mahmoud/Desktop/Project/Rocket.Chat.Android-2.0.2/app/libs/core*': No such file or directory
cp: cannot stat '/home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK/common/build/libs/common-0.1-SNAPSHOT.jar': No such file or directory
cp: cannot stat '/home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK/core/build/libs/core-0.1-SNAPSHOT.jar': No such file or directory
./build-sdk.sh: line 100: /home/mahmoud/Desktop/Project/Rocket.Chat.Kotlin.SDK/.last_commit_hash: No such file or directory

**Comment by philipbrito** [comment]
Invalid issue.
