### ISSUE TITLE
build-sdk.sh Error 

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.Android#1428]
![screenshot from 2018-07-03 04-37-24](https://user-images.githubusercontent.com/20915259/42196084-4be79c6e-7e7c-11e8-9975-1159aa96865f.png)

**Comment by philipbrito** [comment]
Why creating two identical issues (https://github.com/RocketChat/Rocket.Chat.Android/issues/1429)?
What is the issue that should we reply you?

**Comment by philipbrito** [comment]
Invalid issue.
