### ISSUE TITLE
Attachment options UI not full width

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Android#143]
Your Rocket.Chat.Android version: alpha from Jan 11

This is how it looks on Android 6.0.1:
![2017-01-12 02 42 20](https://cloud.githubusercontent.com/assets/8591547/21875067/4cf308a0-d860-11e6-8f9a-b8cb172bb743.png)

**Comment by geekgonecrazy** [comment]
Making this the same type of drawer like the member list I think would look good.
