### ISSUE TITLE
[IMPROVEMENT] Typing status doesn't show Real Name

### ISSUE THREAD

**Issue by dachnikrus** [RocketChat/Rocket.Chat.Android#1432]
Typing status shows username, while "Use Real Name" enabled
![capture](https://user-images.githubusercontent.com/2556359/42270829-7766a4d4-7f8a-11e8-9b32-4bc913f7ce01.PNG)

**Comment by vynmera** [comment]
This will be fixed by https://github.com/RocketChat/Rocket.Chat/pull/11164 .

**Comment by rafaelks** [comment]
@vynmera Great, thanks!

**Comment by rafaelks** [comment]
Let me close the issue for now, since it'll be fixed in the back-end.
