### ISSUE TITLE
[BUG] Android push notifications only work with opened app

### ISSUE THREAD

**Issue by ctel** [RocketChat/Rocket.Chat.Android#1440]
## Description
Android push notifications only work, if the app is opened (background mode). If the app is in the foreground, everything works as expected: no notification. If the app is closed, notifications aren't shown anymore.
It is assumed that this is only on Android: IOS push works flawlessly on the same server.
Push setting on the server is set to: https://gateway.rocket.chat
Privacy setting is set to show the username/group, but not the content of the message. It is not known, if the problem still persists for other combinations of those last two settings.
This problem occours on normal messaging, but even the "test button for sending a notification" shows the same errorneous behaviour. If this test button is triggered, it replies with a green box acknowledging the push notification to one device (only one device had been registered, so it must be the correct one!). If the app is closed no push notification pops up. If you open the app later, already enqueued notifications may arrive late, but only if the app is open.

## Devices and Versions
Your Rocket.Chat.Android version: 2.4.0
Your Rocket.Chat Server version: 0.65.1

Mobile device model and OS version: "Hihonor Honor 8 - Android 7.0", "OnePlus3t - Android 8.0.0"

## Steps to reproduce
It is the normal docker installation, but port forwarding through an nginx proxy. A limited test account on our server can be provided, if needed.

**Comment by MasterMNB** [comment]
Same here with the Snap Server Version 0.66.3

**Comment by ruihildt** [comment]
I also have reports from users that push aren't reliable. Docker, version 0.69.2

**Comment by rafaelks** [comment]
Hey guys! The problem for you is that you download the app from Google Play, and sometimes you don't receive push notification? The more detailed information you have, the better for us to understand the problem. 👍

**Comment by leonardoaramaki** [comment]
Push messages are still not reliable. I can also confirm that. It's part of a more intricate problem though, that also includes the push gateway itself - since it gets overloaded, probably.

**Comment by MasterMNB** [comment]
**Still the same with this configuration:**
Snap server version 0.69.2 with gateway https://gateway.rocket.chat (debug mode disabled/enabled)
Newest Google Play version 2.6.1 and disabled power saving mode for that app.
Tested this on multiple smartphones from  Samsung, Asus and Oneplus with Android version 7.0 - 8.0

Everything looks fine in the debug log on the server. 
The push messages aren't reliable with an open app (probably gateway overloaded).
And if the app is closed i don't get any messages.

**Comment by ruihildt** [comment]
> Hey guys! The problem for you is that you download the app from Google Play, and sometimes you don't receive push notification? The more detailed information you have, the better for us to understand the problem. +1

Yes, from Google Play or from Appstore. I don't know how to debug further, as it's inconsistent.

**Comment by rafaelks** [comment]
Guys, I'm closing this issue because it's not related to the app right now... let's reopen if needed.

**Comment by all3kcis** [comment]
I don't know if the problem is the same but regularly we don't receive notifications.
Do you have any research leads?
