### ISSUE TITLE
[BUG] There are opportunities to click an edit and a delete buttons in messages sent by other users in chats.

### ISSUE THREAD

**Issue by TheSergeX** [RocketChat/Rocket.Chat.Android#1442]
## Description

You won't get result. It's Ok. But it is still sad and strange.

## Devices and Versions

Rocket.Chat.Android version: 2.4.0
Mobile device model and OS version: Meizu M3 Note - Android 5.1

## Steps to reproduce

You should click any message from other user in Channels, Private Groups, Direct Messages then you'll see the opportunity to click an edit or a delete a message button. 

![1](https://user-images.githubusercontent.com/34273859/42329743-1e232564-807a-11e8-95d6-80612ee320a8.jpg)

**Comment by philipbrito** [comment]
There was the same issue regarding this problem here: https://github.com/RocketChat/Rocket.Chat.Android/issues/1132

But I'm closing this issue in favor of https://github.com/RocketChat/Rocket.Chat.Android/issues/778 (let's track its status from there).
