### ISSUE TITLE
[BUG] SAML Login Button is not shown

### ISSUE THREAD

**Issue by ctel** [RocketChat/Rocket.Chat.Android#1443]
## Description
Third party authentication button is not shown. IOS shows the SAML button, Android does not. How shall Android users login?

## Devices and Versions
Your Rocket.Chat.Android version: 2.4.0
Your Rocket.Chat Server version: 0.65.1

Mobile device model and OS version: any (I guess?)

## Steps to reproduce
Setup SAML. Open Android app. Enter server Url with activated SAML auth method. No third party button is shown.

**Comment by ChessSpider** [comment]
So SAML support is added w/ https://github.com/RocketChat/Rocket.Chat.Android/pull/1326 and it is due for version 2.5.0 :  https://github.com/RocketChat/Rocket.Chat.Android/milestone/21

**Comment by rafaelks** [comment]
This is being supported in the next release (currently in Beta), closing it for now.
