### ISSUE TITLE
[BUG] Reply with attachments and the new drawing feature does not work

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#1447]
@RocketChat/android 

Reply to any message, attach an image or any other file or draw something and hit send.
The message with the attachment/drawing is sent as a normal message, not as a reply.

**Comment by shubhsherl** [comment]
Hi, I would like to work on this issue.

**Comment by avzverkov** [comment]
Hi rafaelks !
Pls tell  about this issue, when you could relese it?
