### ISSUE TITLE
[IMPROVEMENT] Improve connecting logic

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#1448]
![image](https://user-images.githubusercontent.com/4001792/42578624-b54bbf2c-84f4-11e8-822c-c411a58b977c.png)

Too often when I switch to Rocket.chat Android I am forced to wait many seconds before it tries to get a connection to the server. I don't know the existing logic but it seems like it should try to connect when the app gets focus instead of waiting on a timer.

I wonder also if we should not use up screen real estate in the "inbox" by just changing the top level title to "Connecting" the way that Telegram does.

![image](https://user-images.githubusercontent.com/4001792/42411192-cd98e230-81c5-11e8-84cb-e103310ab081.png)

The second point is less important in my opinion.

**Comment by rafaelks** [comment]
@bizzbyster The banner is not intrusive anymore in release 2.5.0, we're going to improve that later sending it to the action bar. Let's close it for now.
