### ISSUE TITLE
[QUESTION][INVESTIGATE] Error: The following properties were null: name

### ISSUE THREAD

**Issue by Michelle011997** [RocketChat/Rocket.Chat.Android#1449]
## Description

Yesterday i have installed Rocket.Chat on my Ubuntu Server.
Everything works fine but today the Android App got this Error: The following properties were null: name
and does not show anymore Rooms or Chats.

## Devices and Versions

Your Rocket.Chat.Android version: (2.4.0)
Your Rocket.Chat Server version: (0.66.2)

Huawei P9 Lite with Android 7.0
Samsung Galaxy S5 with Android 6.0.1

## Steps to reproduce

When is start the Android App i got this Error: The following properties were null: name
Only during search button i found the members of the chat but no channel anymore

## Logs

[34mI20180707-02:48:15.316(2) [34mAPI ➔ debug GET: /api/v1/settings.public?count=0&fields=%7B%22type%22%3A%201%7D&query=%7B%22_id%22%3A%20%7B%22%24in%22%3A%20%5B%22LDAP_Enable%22%2C%22CAS_enabled%22%2C%22CAS_login_url%22%2C%22Accounts_RegistrationForm%22%2C%22Accounts_ShowFormLogin%22%2C%22Accounts_PasswordReset%22%2C%22Accounts_CustomFields%22%2C%22Accounts_OAuth_Google%22%2C%22Accounts_OAuth_Facebook%22%2C%22Accounts_OAuth_Github%22%2C%22Accounts_OAuth_Linkedin%22%2C%22Accounts_OAuth_Meteor%22%2C%22Accounts_OAuth_Twitter%22%2C%22Accounts_OAuth_Wordpress%22%2C%22Accounts_OAuth_Gitlab%22%2C%22API_Gitlab_URL%22%2C%22Site_Url%22%2C%22Site_Name%22%2C%22Assets_favicon_512%22%2C%22Assets_favicon_192%22%2C%22UI_Use_Real_Name%22%2C%22UI_Allow_room_names_with_special_chars%22%2C%22Favorite_Rooms%22%2C%22FileUpload_Storage_Type%22%2C%22FileUpload_MaxFileSize%22%2C%22FileUpload_MediaTypeWhiteList%22%2C%22Message_HideType_uj%22%2C%22Message_HideType_ul%22%2C%22Message_HideType_au%22%2C%22Message_HideType_mute_unmute%22%2C%22Message_HideType_ru%22%2C%22Message_AllowDeleting%22%2C%22Message_AllowEditing%22%2C%22Message_AllowPinning%22%2C%22Message_AllowStarring%22%2C%22Message_ShowDeletedStatus%22%2C%22Message_ShowEditedStatus%22%2C%22Assets_tile_310_wide%22%2C%22Store_Last_Message%22%2C%22Message_Read_Receipt_Enabled%22%2C%22Message_Read_Receipt_Store_Users%22%5D%7D%7D 
[34mI20180707-02:48:15.319(2) [34mAPI ➔ debug Success { statusCode: 200,   body:     { settings:        [ [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object],         [Object] ],      count: 41,      offset: 0,      total: 41,      success: true } } 
[34mI20180707-02:48:15.329(2) [34mAPI ➔ debug GET: /api/v1/rooms.get?updatedAt=1970-01-01T00%3A00%3A00.000Z 
[34mI20180707-02:48:15.330(2) [34mMeteor ➔ method rooms/get -> userId: 5bn5RLtWRzd2H6i5H , arguments:  { '0': undefined } 
[34mI20180707-02:48:15.334(2) [34mAPI ➔ debug Success { statusCode: 200,   body:     { update: [ [Object], [Object], [Object], [Object], [Object], [Object] ],      remove: [],      success: true } } 
[34mI20180707-02:48:15.339(2) [34mAPI ➔ debug GET: /api/v1/subscriptions.get?updatedAt=1970-01-01T00%3A00%3A00.000Z 
[34mI20180707-02:48:15.340(2) [34mMeteor ➔ method subscriptions/get -> userId: 5bn5RLtWRzd2H6i5H , arguments:  { '0': undefined } 
[34mI20180707-02:48:15.341(2) [34mAPI ➔ debug Success { statusCode: 200,   body:     { update: [ [Object], [Object], [Object], [Object], [Object], [Object] ],      remove: [],      success: true } }

**Comment by exceed73** [comment]
Same configuration and same problem.

**Comment by bullfroghrr** [comment]
Help same thing

**Comment by rafaelks** [comment]
@Michelle011997 @exceed73 Can you please paste the JSON response from the `rooms.get` and `subscriptions.get` API? There are probably some Subscription or Room object without a property `name` and that should never happen.

**Comment by exceed73** [comment]
Fixed since 2.5.0 Build 2034 (update this morning).

Thanks @rafaelks for your interest.

**Comment by rafaelks** [comment]
@exceed73 Do you have any room with live chat? This may be causing the problem.

**Comment by exceed73** [comment]
That's right @rafaelks, and some of them have no name since... a version I don't remember.
Yesterday, Rocket.chat 0.66.3 arrived via snap package on my server. + Client 2.5.0 : Everything is fine now.

**Comment by Michelle011997** [comment]
Yes the problem is solved with the Update v2.5.0

**Comment by rafaelks** [comment]
Great! Closing the issue in this case. Thank you guys!
