### ISSUE TITLE
Profile picture is being cached and won't change

### ISSUE THREAD

**Issue by lennartgrunau** [RocketChat/Rocket.Chat.Android#1452]
## Description

When a profile pic is being changed on both desktop and mobile, the Android app does not recognize it and thus doesn't change it. This affects **both** the users' and other users profile picture. 

## Devices and Versions

Your Rocket.Chat.Android version: 2.4.0
Your Rocket.Chat Server version: 0.66.2

Mobile device model and OS version: (tested and confirmed on)
LG G6 Android 8.0.0
Samsung Galaxy S8+ Android 8

## Steps to reproduce

Change your profile picture. Desktop client will realize it. Android App won't.
Resetting the Apps' Cache and Storage will fix the problem. 

## Logs

No logs.

**Comment by chatnl** [comment]
Same problem here. Android 8 on a Moto G5S+

**Comment by philipbrito** [comment]
Duplicate issue. Let's track its status from here: https://github.com/RocketChat/Rocket.Chat.Android/issues/1217
