### ISSUE TITLE
[NEW] Redesign Onboarding

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1454]
![screen shot 2018-07-09 at 11 15 45](https://user-images.githubusercontent.com/551004/42455748-7541938e-8369-11e8-9a2f-59952e66ec38.png)
![screen shot 2018-07-09 at 11 15 52](https://user-images.githubusercontent.com/551004/42455749-7563f97e-8369-11e8-93b7-298ec911f889.png)

**Comment by divyanshub024** [comment]
@rafaelks I love these designs. :100: :1st_place_medal:

**Comment by divyanshub024** [comment]
@rafaelks There is no design for login with email.

**Comment by rafaelks** [comment]
@divyanshub024 Will provide that for you in a few! 👍

**Comment by rafaelks** [comment]
@divyanshub024 Sent you in private.
