### ISSUE TITLE
[IMPROVEMENT] Add clear/x button on input fields

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.Android#1457]
Environment:
Rocket Chat App version 2.4.0 Build 2027
Device (or simulator) you're running with: Samsung S8 version 8.0.0

Pre-Condition:
Rocket.Chat app is installed

Steps:
1. Launch Rocket Chat app
2. Type valid URL on Server URL field
3. Verify clear/x button should be seen on input field

Expected Result
Add a clear/x button on input fields to easily delete characters.

Actual Result
Input fields do not have clear/x button yet

Please see attached photo
![screenshot](https://user-images.githubusercontent.com/38445437/42485019-53689810-8428-11e8-954e-e0cd0a9c7319.png)

**Comment by leonardoaramaki** [comment]
Do you mean adding a clear button to this specific input field?
