### ISSUE TITLE
[BUG] "Or continue using social accounts" disappeared after resetting password

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.Android#1458]
Environment:
Rocket Chat App version 2.4.0 Build 2027
Device (or simulator) you're running with: Samsung S8 version 8.0.0

Pre-Condition:
Connected to open.rocket.chat server
User is in open.rocket.chat Login page

Steps:
1. On "Forgot password?" Tap Reset link
2. Input valid details on Email field
3. Tap Reset Password button
4. Verify "Or continue using social media accounts" should be seen

Expected Result
"Or continue using social media accounts" should be seen without any issue

Actual Result
"Or continue using social media accounts" disappeared only letter O remained.

Please see attached video
https://www.dropbox.com/s/u1k1rmoh39sk8a6/20180710_110742.mp4?dl=0

**Comment by philipbrito** [comment]
Thanks for opening this issue (as well as attaching the video - very useful).
