### ISSUE TITLE
[BUG] Can't login to any server

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.Android#1460]
Environment:
Rocket Chat App version 2.4.0 Build 2027
Device (or simulator) you're running with: Samsung S8 version 8.0.0
Server Site: cloudstaffqa.rocket.chat
Server Version: 0.65.2

Pre-Condition:
Rocket.Chat app installed

Steps:
1. Launch Rocket.Chat app
2. Enter valid URL on Server URL field (open.rocket.chat)
3. Tap Connect button
4. Type valid details on email and password field
5. Tap login

Expected Result
User should be able to login

Actual Result
Login unsuccessful. Error message "Unauthorized" displays

Note:
Was able to login on Rocket Chat IOS Beta version 3.0.0 (188) with the credentials used on the attached video

Please see attached video
https://www.dropbox.com/s/6ngzxcod30mazqu/20180710_132030.mp4?dl=0

**Comment by rafaelks** [comment]
Should be fixed in 3.1.0.
