### ISSUE TITLE
[BUG] Custom OAuth not working if authorize path is full URL

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.Android#1462]
Ref: https://github.com/RocketChat/Rocket.Chat.iOS/issues/1838
Fix: https://github.com/RocketChat/Rocket.Chat.iOS/pull/1929

**Comment by philipbrito** [comment]
Sending a fix soon!
Thanks @cardoso! 👍

**Comment by cardoso** [comment]
@filipedelimabrito we also do the same check for token path, so that might be required as well.
