### ISSUE TITLE
[IMPROVEMENT] Connecting view hides the chat room name

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#1463]
The connecting view is currently hiding the chat room name as show bellow:

![sc](https://user-images.githubusercontent.com/11776825/42508086-b51879a0-841d-11e8-83e9-7e769d395da3.png)

It'd be better to don't hide that chat room name

**Comment by shubhsherl** [comment]
I will do it.

**Comment by philipbrito** [comment]
Great! Thanks @shubhsherl! 👍

**Comment by bizzbyster** [comment]
Many chat apps replace the text "Chats" (in the above screenshot) with the word "Connecting" so that no additional screen real estate needs to be used.

An example of this can be seen here: https://github.com/RocketChat/Rocket.Chat.Android/issues/1448.

**Comment by philipbrito** [comment]
I just left a comment about doing so [here](https://github.com/RocketChat/Rocket.Chat.Android/pull/1468#issuecomment-404246146) @bizzbyster 

Thanks.
