### ISSUE TITLE
[BUG] Message should retain in message-composer

### ISSUE THREAD

**Issue by shubhsherl** [RocketChat/Rocket.Chat.Android#1464]
## Description
While replying a message, shouldn't the message be retained in message-composer if I cancel the message_action_bar(i.e. cancel the reply), as it happens in web browser..? 

## Devices and Versions

Your Rocket.Chat.Android version: 2.4.0

Mobile device model and OS version: Xiaomi Redmi Note 4 - Android 7.0

## Steps to reproduce
Reply a message and write in the message box, and then cancel reply

**Comment by leonardoaramaki** [comment]
Thanks for opening this! Indeed, the typed message should be retained on the composer.
