### ISSUE TITLE
[v1.0-beta] alternative WebSocket connectivity management

### ISSUE THREAD

**Issue by YusukeIwaki** [RocketChat/Rocket.Chat.Android#147]
Managing websocket connectivity with ServerConfig  is not good.
It is really complicated to handle every usecase with mapping it to a exclusive state, and really buggy now... (#117, #137, #142, ...)

Let's introduce clean architecture partially just for managing the WebSocket connectivities.

---
![slice](https://cloud.githubusercontent.com/assets/11763113/22061001/63c044d4-ddb6-11e6-837e-f080e0eaf88f.png)

**Comment by geekgonecrazy** [comment]
Might also be worth investigating the rest api in some instances.  Like if a websocket is not established and a message is sent.  Waiting on a websocket might not best.  Might be good to just fire of quick http request and be done with it.  Just a thought

**Comment by YusukeIwaki** [comment]
> Like if a websocket is not established and a message is sent. Waiting on a websocket might not best.

Yes, exactly.
A piece of REST API code seems introduced in #153 and I expect them to be extended in future.

**Comment by laggedHero** [comment]
I've just closed the other issues since everything seems to be related. :)

**Comment by geekgonecrazy** [comment]
:+1: makes sense.  For sure what they are all related to.
