### ISSUE TITLE
[IMPROVEMENT] Edit Profile > Keyboard should hide when user taps outside the input field

### ISSUE THREAD

**Issue by GeTadle** [RocketChat/Rocket.Chat.Android#1470]
Environment:
Rocket Chat App version 2.4.0 Build 2027
Device (or simulator) you're running with: Samsung S8 version 8.0.0

Pre-Condition:
User is logged in.

Steps:
1. Tap the hamburger menu icon on the upper left corner of the page
2. On the menus Tap Profile
3. Tap on any of the input fields (name, username, email or avatar url)
4. Verify keyboard should appear
5. Tap outside the input field or tap the hamburger menu then select Settings or Chats

Expected Result
Keyboard should hide

Actual Result
Keyboard stays open 

Please see attached video
https://www.dropbox.com/s/5uopkjo1hgk587o/20180711_150113.mp4?dl=0

**Comment by rafaelks** [comment]
We don't plan to touch this at this point, but PRs are welcome. 👍
