### ISSUE TITLE
Image description not visible

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.Android#1471]
## Description

Image description is not visible in the android app.

## Devices and Versions
Your Rocket.Chat.Android version: 2.4.0
Your Rocket.Chat Server version: 0.66.2
OnePlus 3T with Android 8.0 Security Patch-Level May 2018
Samsung A3 2017 with Android 8.0

## Steps to reproduce

Upload a picture via web oder desktop app und write an image description text. 
You can not read the text on android - on iOS you can.

Android:
![screenshot_20180711-090355](https://user-images.githubusercontent.com/26709898/42556080-b4ee52d8-84ea-11e8-8604-d9e956f89f99.jpg)

PC:
![11-07-_2018_09-14-00](https://user-images.githubusercontent.com/26709898/42556186-151bc00a-84eb-11e8-907a-6dec4cdf9c61.jpg)

**Comment by rafaelks** [comment]
This is fixed in 3.1.0.
