### ISSUE TITLE
[BUG] File description broken in android

### ISSUE THREAD

**Issue by shubhsherl** [RocketChat/Rocket.Chat.Android#1476]
## Description
There is a problem in file description, when you upload it via web the image description is one in blue circle `Get out`, while if you upload via android device, description while uploading is in green box `yep`, but it will never be updated as actual file description is orange one `IMG-20180712-WA0004.jpg`, so while editing you will get the green text in message composer but update the orange one.
![fil](https://user-images.githubusercontent.com/34231951/42616242-1f7def56-85cb-11e8-8a6e-27fd6da06e67.jpg)

## Devices and Versions
Your Rocket.Chat.Android version: 2.4.0

Mobile device model and OS version:
Xiaomi Redmi Note 4 - Android 7.0

## Steps to reproduce
Upload file via desktop and android and try to edit the file description of both.

**Comment by rafaelks** [comment]
Fixed in 3.1.0.
