### ISSUE TITLE
[NEW] Add option to add and remove members from channel

### ISSUE THREAD

**Issue by yohai109** [RocketChat/Rocket.Chat.Android#1491]
## Description

After creating the channel there is no option for the manager to add or remove members.
Also a member can't leave a channel that he is a member of.

## Devices and Versions

Your Rocket.Chat.Android version: 2.4.0
Your Rocket.Chat Server version: 0.64.2 - develop

Mobile device model and OS version: Xiaomi Redmi Note 4 - Android 7.0

**Comment by philipbrito** [comment]
Thanks for opening. Let's track the status of this issue from already existing https://github.com/RocketChat/Rocket.Chat.Android/issues/1230 and https://github.com/RocketChat/Rocket.Chat.Android/issues/1055

**Comment by filipedelimabrito** [comment]
For `Also a member can't leave a channel that he is a member of` I created this issue: https://github.com/RocketChat/Rocket.Chat.Android/issues/1514
