### ISSUE TITLE
Can we integrate Rocket chat (kotlin sdk) with already existing java based android application ? If yes then what might be the challenges ?? 

### ISSUE THREAD

**Issue by JerushaSMendonza** [RocketChat/Rocket.Chat.Android#1493]
I am new to Android Development and Kotlin. I was planning to integrate Rocket chat with my existing app only for one to one chat communication in my project. But the existing app was built with older android sdk's. If I have to integrate rocket chat in my application which is written completely in java, what might be the challenges and hurdles I need to overcome? And can I integrate it without any compatibility issues. Any help on this would be appreciated. 
Thank you in advance.

**Comment by philipbrito** [comment]
https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/issues/169
