### ISSUE TITLE
gradle sync failed for rocket chat

### ISSUE THREAD

**Issue by JerushaSMendonza** [RocketChat/Rocket.Chat.Android#1494]
I was trying to build rocket chat app in android studio 3.2- beta 1, but the gradle build fails due to this below error. Can anybody help me out with this issue?

sync failed | 44 m 15 s 249 ms
-- | --
Starting Gradle Daemon | 7 s 388 ms
Run build | 44 m 3 s 250 ms
Load build | 1 s 210 ms
Configure build | 20 m 38 s 944 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.0-beta01/gradle-3.2.0-beta01-sources.jar | 21 s 13 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.0-beta01/builder-3.2.0-beta01-sources.jar | 21 s 28 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.2.0-beta01/tracker-26.2.0-beta01-sources.jar | 21 s 47 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.2.0-beta01/shared-26.2.0-beta01-sources.jar | 21 s 34 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.2.0-beta01/crash-26.2.0-beta01-sources.jar | 20 s 894 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.2.0-beta01/lint-gradle-api-26.2.0-beta01-sources.jar | 1 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.2.0-beta01/gradle-api-3.2.0-beta01-sources.jar | 1 ms
Metadata of https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.2.0-beta01/databinding-compiler-common-3.2.0-beta01-sources.jar | 1 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.2.0-beta01/manifest-merger-26.2.0-beta01-sources.jar | 2 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.2.0-beta01/sdk-common-26.2.0-beta01-sources.jar | 2 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.2.0-beta01/builder-test-api-3.2.0-beta01-sources.jar | 3 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.2.0-beta01/ddmlib-26.2.0-beta01-sources.jar | 2 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.2.0-beta01/sdklib-26.2.0-beta01-sources.jar | 41 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.2.0-beta01/layoutlib-api-26.2.0-beta01-sources.jar | 30 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.2.0-beta01/dvlib-26.2.0-beta01-sources.jar | 4 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.2.0-beta01/repository-26.2.0-beta01-sources.jar | 3 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/common/26.2.0-beta01/common-26.2.0-beta01-sources.jar | 57 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/transform-api/2.0.0-deprecated-use-gradle-api/transform-api-2.0.0-deprecated-use-gradle-api-sources.jar | 34 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-alpha07/jetifier-processor-1.0.0-alpha07-sources.jar | 26 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.4.2/bundletool-0.4.2-sources.jar | 46 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-alpha07/jetifier-core-1.0.0-alpha07-sources.jar | 59 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.2.0-beta01/builder-model-3.2.0-beta01-sources.jar | 59 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.2.0-beta01/protos-26.2.0-beta01-sources.jar | 29 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.2.0-beta01/apkzlib-3.2.0-beta01-sources.jar | 55 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.2.0-beta01/apksig-3.2.0-beta01-sources.jar | 60 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.2.0-beta01/annotations-26.2.0-beta01-sources.jar | 53 ms
Metadata of https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.2.0-beta01/databinding-common-3.2.0-beta01-sources.jar | 21 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.2.0-beta01/baseLibrary-3.2.0-beta01-sources.jar | 56 ms
Metadata of https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1-sources.jar | 59 ms
allprojects | 4 ms
Cross-configure project : |  
Cross-configure project :app | 1 ms
Cross-configure project :player | 1 ms
Metadata of https://jcenter.bintray.com/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9-javadoc.jar | 26 ms
Metadata of https://jcenter.bintray.com/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9-javadoc.jar | 23 ms
null |  
D:/Rocket.Chat.Android-develop |  
app/build.gradle |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-measurement-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.firebase:firebase-analytics-impl:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.firebase:firebase-common:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.firebase:firebase-iid:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-api-phone:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-measurement-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.firebase:firebase-analytics-impl:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.firebase:firebase-common:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.firebase:firebase-iid:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-api-phone:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-measurement-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-analytics-impl:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-common:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-iid:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-api-phone:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.gms:play-services-measurement-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.firebase:firebase-analytics-impl:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.firebase:firebase-common:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.firebase:firebase-iid:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-api-phone:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-measurement-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-analytics-impl:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-common:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-iid:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-api-phone:[15.0.0,16.0.0). Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-auth-base:[15.0.0]. Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0,16.0.0). Open FileShow Details |

**Comment by philipbrito** [comment]
Please, make sure to follow the instructions to build the project [here](https://github.com/RocketChat/Rocket.Chat.Android#how-to-build).
