### ISSUE TITLE
while running ./build-sdk.sh

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.Android#1499]
CURRENT DIR: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Android-2.4.0/app
SDK DIR: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
./build-sdk.sh: line 74: cd: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK: No such file or directory
./build-sdk.sh: line 31: cd: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK: No such file or directory
CURRENT SHA: 0.1-SNAPSHOT
./build-sdk.sh: line 18: cd: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK: No such file or directory
./build-sdk.sh: line 25: cd: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK: No such file or directory
is dirty
./build-sdk.sh: line 91: cd: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK: No such file or directory
./build-sdk.sh: line 92: cd: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK: No such file or directory
rm: cannot remove '/home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Android-2.4.0/app/libs/common*': No such file or directory
rm: cannot remove '/home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Android-2.4.0/app/libs/core*': No such file or directory
cp: cannot stat '/home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK/common/build/libs/common-0.1-SNAPSHOT.jar': No such file or directory
cp: cannot stat '/home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK/core/build/libs/core-0.1-SNAPSHOT.jar': No such file or directory
./build-sdk.sh: line 100: /home/mahmoud_sallam/Desktop/mahmoud/Rocket.Chat.Kotlin.SDK/.last_commit_hash: No such file or directory
elopers indentifying the cause in case it's a bug. -->

**Comment by philipbrito** [comment]
Please, again, **follow** the instructions given [here](https://github.com/RocketChat/Rocket.Chat.Android#how-to-build).
