### ISSUE TITLE
Sidebar glitch

### ISSUE THREAD

**Issue by infinitnet** [RocketChat/Rocket.Chat.Android#15]
The icons on the right sidebar randomly disappear. If I kill and restart the app or switch rooms a few times the icons are come back. Issue appear to happen randomly. Using latest release from Play Store on a Sense 7 ROM, Android 5.0.2.
![screenshot_2016-01-06-17-43-24](https://cloud.githubusercontent.com/assets/6189915/12151343/fc06f184-b4ae-11e5-8817-c79e097de836.png)

**Comment by sampaiodiego** [comment]
thanks for reporting @infinitnet 
but the app on the play store is actually the cordova app (https://github.com/RocketChat/Rocket.Chat.Cordova)
I'll move this issue :wink:
