### ISSUE TITLE
[discussion] Introduce UseCase (or interactor) layer

### ISSUE THREAD

**Issue by YusukeIwaki** [RocketChat/Rocket.Chat.Android#150]
![slice](https://cloud.githubusercontent.com/assets/11763113/21953830/b2a15c12-da84-11e6-8133-2ea7a707d7b6.png)

Current app architecture is like above.

There are major 2 obvious problem for scaling app.

## Every UI component need to know the protocol (how to insert, what kind of format is required) for request or observing

For example, when we want to observe "unread room count", 

```
realmHelper
  .createListObserver(realm ->
     realm.where(RoomSubscription.class).equalsTo("open", true).equalsTo("alert", true).findAll())
  .setOnUpdateListener(results -> {
     // handle as you like.
  });
```

we have to add such code.

* Maybe someone fail to add the condition `open == true`
* Another person would mistake the condition `alert == true` with `unread > 0`

Such detailed protocol is really hard to understand for most people even if it is well documented. 
It would be much better if we can write the logic simply as below:

```
roomSubscriptionHelper.getUnreadRoom(rooms -> {
    // handle as you like
  });
```

**=> Better to introduce some wrappers for protocols to request or observe**

## boilerplate codes for implementing `distinctUntilChanged`, `map` operation

Current RealmListObserver just have two methods `sub()` and `unsub()` for enable/disabling the observing behavior.

However in many cases, `map`, `distinctUntilChanged`, `takeUntil` Rx operators would help simplifying our source codes.

**=> Better to enable the observer to be used as Rx.Observable**

**Comment by geekgonecrazy** [comment]
I definetely agree that realm should be abstracted away.  Implementation details like that would be great to be hidden away.  This way things under the hood can be changed with out having to go in and change the code in a bunch of different UI elements.  This will likely lead to some getting missed.

That way a UI piece can call a method, and not have to worry about how its happening.  We know that calling this method will do what its supposed to.

**Comment by laggedHero** [comment]
We do have a channel in demo with some initial discussion. It would be quite nice if Yusuke would talk with the guys there.

A lot of conceptual stuff fits with iOS too. Just saying.

**Comment by rakaramos** [comment]
@laggedHero came up with a great architecture.
We are going to use it on iOS, and would be nice if Android could do the same...

https://gist.github.com/rakaramos/e123faae1f46e54c5b831bdf1ccf0aa1

Further on this I would refer to #native-dev on Rocket Chat Demo

**Comment by YusukeIwaki** [comment]
Thank you for information, 
I close this issue and continue in `#native-dev`.

However the channel is private, so it would be better to share the discussion for developers at times.
