### ISSUE TITLE
kotlin-stdlib jre7 is depricated please use jdk instead 

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.Android#1505]
i have got this error while running the prject 
I have jdk-8 
android studio 3.2 Beta 4 
and the latest gradle version 
what  i have to do ???????????????

**Comment by mahmodsallam** [comment]
i am using fedora 28 as a main operating system

**Comment by leonardoaramaki** [comment]
Hi, @mahmodsallam. This is not an error, just a warning.
