### ISSUE TITLE
[IMPROVEMENT] Improvements to room list last messages

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Android#1506]
## Description

The room list is showing different (and not clever) information regarding the last message as on desktop. 

## Devices and Versions

Your Rocket.Chat.Android version: 2.5.0
Your Rocket.Chat Server version: open server

Mobile device model and OS version: Moto Maxx

## Steps to reproduce

Just open the app and look at your rooms list:

* If the last message is a file upload, it shows just the username. On desktop it shows "Sent an attachment"
* If the last message was sent by me it shows my **name** (to everyone else it shows the username). On desktop it shows `You` (which I think is the best/common approach).
* On direct messages it shows either my name or the open person's username. As on desktop it just needs to show either `You` (which is me 😅 ) or just the message, because I know if it wasn't sent by me it was sent by the other person on DM)

The image bellow shows all three items:
![image](https://user-images.githubusercontent.com/8591547/42880249-12ca326c-8a6a-11e8-807d-62369fc4c9d2.png)

**Comment by rafaelks** [comment]
This one was fixed in #1510.
