### ISSUE TITLE
[BUG]There is no way to change the language to Russian

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1507]
Your Rocket.Chat.Android version: 2.5.0 build 2031
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.12) , Developer ROM
Your Rocket.Chat Server version: 0.66.2

It is not possible to change the language to Russian. Uninstalling the application and resetting the settings with the android tools do not work.

**Comment by philipbrito** [comment]
We're supporting Russian for a specific region only: Ukraine. I see that you'd submitted PR's to improve that language, but honestly I do not know how it differs by setting for general region (I mean, not setting only to the Ukraine, Modolva, Belarus, etc.)

What do you think?

**Comment by Pitstopper** [comment]
@filipedelimabrito Ukraine, Moldova and Belarus certainly speak Russian, but they also have national languages. Russian is not the main language for them. I would like the Russian language to be included for the region of the Russian Federation.

**Comment by philipbrito** [comment]
I see. I'll change the current [language](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/app/src/main/res/values-uk-rRU/strings.xml) to not support only the Ukraine region but the Russian Federation. Doing that you'll see the app in Russian (in the case of your device language is set up with that language too). Ok?

**Comment by Pitstopper** [comment]
Yeah, it would be great! Thanks.

**Comment by Pitstopper** [comment]
@filipedelimabrito Version 2.5.0, Build 2033. The language stil does not change to Russian. System language - Russian, region - Russian Federation.

**Comment by philipbrito** [comment]
@Pitstopper It's showing here (`develop` branch):

![russian-support](https://user-images.githubusercontent.com/11776825/43090755-a4f21d0e-8e7e-11e8-8188-cd046e6c6177.jpg)

**Comment by Pitstopper** [comment]
@filipedelimabrito  How i can test this version? Could you share this build to me please?

**Comment by philipbrito** [comment]
It's is from the `develop` branch (that's going to be released with the 2.6.0 version). In the case of needing help to build that follow the steps [here](https://github.com/RocketChat/Rocket.Chat.Android#how-to-build) or [contact me](https://open.rocket.chat/direct/filipe.brito)
