### ISSUE TITLE
why ???

### ISSUE THREAD

**Issue by mahmodsallam** [RocketChat/Rocket.Chat.Android#1511]
i am asking my self why this project dont work smoothly , there is errors every where in the code while building , every where bugs ???????? why this ???????????
i am disappointed of using this project because all of this things , i lost my job because this project 
i hate the android development as a result of using this 
____________ .

**Comment by rafaelks** [comment]
@mahmodsallam Thanks for your great points! I'm closing the issue and reporting you, please don't do that again. 👍
