### ISSUE TITLE
Press back to open channel list

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat.Android#152]
Your Rocket.Chat.Android version: latest
This is more of a feature request really.

Currently when you press back the app quits.
I prefer the work flow of: Press back channel list opens, press back again you get a toast message that pressing back again will exit the app, pressing back again will exit.

Feedback appreciated.

**Comment by geekgonecrazy** [comment]
This is kind of tricky to me.  Per Android norm.. I would expect it to take me to the last open activity.  In this case if I was in another channel prior to this, just based on how things normally operate in apps... You'd almost expect the previous channel to come up. Even though technically it might not be another activity.

I for sure agree though that hitting back shouldn't exit the application.  We should aim to fit Android guidelines here if we can.

**Comment by mrplow** [comment]
Unless you think of it as the channel list being open as its own activity, pressing back goes back to the channel list and pressing back again then goes to the last previous channel. But I see your point as the channel list itself isn't really an activity.

Slack's default behaviour works the same as this app right now. But they have an option to open the channel drawer on hitting back, so there was enough of a need to add the option there. Its really a personal preference but I find using back to open the drawer a lot more intuative.

**Comment by laggedHero** [comment]
Going back is quite tricky. But, per guideline, back button may take you out of the app.

https://developer.android.com/design/patterns/navigation.html

This image shows a complex case of navigation within an app.

![navigation_between_siblings_market2](https://cloud.githubusercontent.com/assets/1779545/21982648/84513e76-dbd4-11e6-8d23-e9d04f4b99d9.png)

And here one exiting the app.

![navigation_up_vs_back_gmail](https://cloud.githubusercontent.com/assets/1779545/21982655/961345be-dbd4-11e6-8a9a-799b839cb9d6.png)

Maybe a non-default option could be something.

**Comment by rafaelks** [comment]
Closing it for now.
