### ISSUE TITLE
No nofications in background again

### ISSUE THREAD

**Issue by kkachura** [RocketChat/Rocket.Chat.Android#1521]
## Description

No nofications in background again.

## Devices and Versions
Rocket.Chat.Android version: 2.4 (last)
Rocket.Chat Server version: 0.63.3

Mobile device model and OS version: "LeEco Cool1 - Android 6.0.1"

**Comment by rafaelks** [comment]
@kkachura This is fixed in 2.5.0 (released yesterday to the store).
