### ISSUE TITLE
DE translation

### ISSUE THREAD

**Issue by MasterMNB** [RocketChat/Rocket.Chat.Android#1522]
Hi. I have created a translation into German.
Hope everything is correct.
[de_strings_xml.zip](https://github.com/RocketChat/Rocket.Chat.Android/files/2222438/de_strings_xml.zip)

**Comment by philipbrito** [comment]
Thank you very much @MasterMNB!
Feel free to reach us whenever you can [here](https://open.rocket.chat/channel/androidnativeapp) too.
I'll put it into the project, but feel free to submit PR's here too :)
