### ISSUE TITLE
problem with kotlin protected values

### ISSUE THREAD

**Issue by dubacu** [RocketChat/Rocket.Chat.Android#1523]
## Description
Hello. i hope that feel good. 
i've get the rockeckchat android release 2.3.2 and when i am trying to compile,, i have error about kotlin.collections.

Maybe i don't follow the good step to do it. because i juste get back source code and i put it in android studio project folder and i try to compile. 

let's see the errors:

error:

 **State is not public in kotlin.collections; cannot be accessed from outside package
 private final kotlinx.coroutines.experimental.channels.Channel<kotlin.collections.State> stateChannel = null;**

**error: State is not public in kotlin.collections; cannot be accessed from outside package     private final java.util.concurrent.CopyOnWriteArrayList> statusChannelList = null;**    

**error: State is not public in kotlin.collections; cannot be accessed from outside package     kotlin.collections.State state);**               

**error: State is not public in kotlin.collections; cannot be accessed from outside package     kotlin.collections.State state) {**             

**error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. public final class ChatRoomsFragment extends android.support.v4.app.Fragment implements chat.rocket.android.chatrooms.presentation.ChatRoomsView {**         

**error: State is not public in kotlin.collections; cannot be accessed from outside package     private final kotlinx.coroutines.experimental.channels.Channel stateChannel = null;**   

   

**error: State is not public in kotlin.collections; cannot be accessed from outside package     public static final kotlin.collections.State getState(@org.jetbrains.annotations.NotNull()**              

**error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code. public final class ChatRoomFragment extends android.support.v4.app.Fragment implements chat.rocket.android.chatroom.presentation.ChatRoomView, chat.rocket.android.widget.emoji.EmojiKeyboardListener, chat.rocket.android.widget.emoji.EmojiReactionListener {**            

Thnaks already four your brand attention.

**Comment by philipbrito** [comment]
Hi @dubacu 

Looks like you're trying to build an old version (that isn't a problem), but it always better to build the latest updates from `develop` branch. 

As you could see, this isn't a project error. My advice is that you follow the steps [here](https://github.com/RocketChat/Rocket.Chat.Android#how-to-build) (it'll help you to avoid the `Maybe i don't follow the good step to do it` phrase).

Also, feel free to ask for help on our [channel](https://open.rocket.chat/channel/androidnativeapp).

Thanks.

**Comment by dubacu** [comment]
hello @filipedelimabrito  thanks for your response and helping. i've foffowed your steps link but when yous say to build the latest update from develop branch, i dont' understand. in fact i'm newer in github so i don' understand . i did think that i can get backsource code and customise on my android studio envirorement

**Comment by dubacu** [comment]
in this link it about to run kotlin sdk in by running `git clone https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK.git.`  
> 

and also to run build-sdk.sh by using this command

`./build-sdk.sh`. so i think that this commande is for linux envirooment then i 'm in windows OS

**Comment by philipbrito** [comment]
Don't worry.
[Contact me](https://open.rocket.chat/direct/filipe.brito) and let's try to address your problems (I'll try to reply you ASAP) :)
