### ISSUE TITLE
[NEW] Sharing contacts

### ISSUE THREAD

**Issue by Amirko28** [RocketChat/Rocket.Chat.Android#1525]
## Description
I think that as a chat, Rocket Chat should support sharing contacts that are saved on your phone. However, at its current state, I'm unable to share contacts.

## Devices and Versions

Your Rocket.Chat.Android version: 2.5.0
Your Rocket.Chat Server version: 0.64.2 - develop

Mobile device model and OS version: Samsung S7 Edge - Android 8.0.0

**Comment by rafaelks** [comment]
@Amirko28 You mean, share a contact as an attachment?

**Comment by Amirko28** [comment]
@rafaelks yes

**Comment by rafaelks** [comment]
There's no support for that in Rocket.Chat platform right now, so I'll be closing the issue for now.
