### ISSUE TITLE
File upload on mobile app is not working

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.Android#1526]
@ledainam commented on [Fri Oct 20 2017](https://github.com/RocketChat/Rocket.Chat/issues/8575)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances:  1
* DB Replicaset Oplog: Enable

Mobile app on Android and iOs file upload not working.
when i click on icon computer to upload, and after borrow file nothing happen.
pls help us fix it soon.
Thanks.

---

@ledainam commented on [Fri Oct 20 2017](https://github.com/RocketChat/Rocket.Chat/issues/8575#issuecomment-338221767)

Server version 0.58 worked fine. Only v0.59.1 have issue with file upload on mobile app both android and iOs.

---

@ledainam commented on [Tue Dec 05 2017](https://github.com/RocketChat/Rocket.Chat/issues/8575#issuecomment-349218990)

@MartinSchoeler  : version 0.59.3 have same issues.
I didn't know when this issues will be fixed.

---

@ccfiel commented on [Mon Jul 23 2018](https://github.com/RocketChat/Rocket.Chat/issues/8575#issuecomment-407040898)

same here version 0.66.3 cannot upload andriod

**Comment by rafaelks** [comment]
The issue is probably related to some bad configuration on the server. Refer to this one: https://github.com/RocketChat/Rocket.Chat.iOS/issues/2066
