### ISSUE TITLE
Error on opening some chats

### ISSUE THREAD

**Issue by mrjavum** [RocketChat/Rocket.Chat.Android#1532]
## Description

After updating to 2.5.0 some chats stoped opening.

## Devices and Versions

Your Rocket.Chat.Android version: 2.5.0
Your Rocket.Chat Server version: 0.66.3

Mobile device model and OS version: 
Lenovo Zuk Z1 - Android 7.1.2
Xiaomi Redmi 4 - Android 6.0.1 (MIUI Global 9.5.3.0)

## Steps to reproduce

Open app and try to open chat.

## Logs

[2018-07-25-11-38-54.txt](https://github.com/RocketChat/Rocket.Chat.Android/files/2226510/2018-07-25-11-38-54.txt)

![screenshot_20180725-112652](https://user-images.githubusercontent.com/977334/43179822-10c4c046-8fff-11e8-9ca9-3042216cba48.png)
![screenshot_2018-07-25-11-29-37-929_chat rocket android](https://user-images.githubusercontent.com/977334/43179823-10e8b046-8fff-11e8-96cf-7887bbedd66d.png)

**Comment by tezukzai** [comment]
![image](https://user-images.githubusercontent.com/23151258/43393890-9c9a03de-93f0-11e8-953b-e431fe1c9f7d.png)

I am also getting this issue, for one specific channel. The error message is slightly different as shown.

**Comment by rafaelks** [comment]
This one is fixed in release 2.5.1 (released yesterday in Google Play), please update it and if it still happening we can reopen this one. Thank you!

**Comment by tezukzai** [comment]
Hi @rafaelks ,

Yes, I am still getting this with 2.5.1 and version 66.2. 

Mobile Device Pixel XL
OS: Android Version 9 (Beta)

**Comment by rafaelks** [comment]
@tezukzai OK, we're going to check it, thank you!

**Comment by leonardoaramaki** [comment]
@tezukzai We just rolled out a new beta (versionCode **2036**) with a fix for this. It should hit Google Play Beta program soon, if not already. Can you test if the issue you reported is solved and get back to us here?

**Comment by tezukzai** [comment]
@leonardoaramaki I can confirm that this is fixed. Cheers!
