### ISSUE TITLE
[BUG] When drawing, black color is not selected back

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1533]
Your Rocket.Chat.Android version: 2.5.0 build 2034
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9 (8.4.12) , Developer ROM
Your Rocket.Chat Server version: 0.66.2

When drawing, if the black color has been changed to some other one, it is not selected back

**Comment by divyanshub024** [comment]
Thanks @Pitstopper for the issue, I will fix this soon.

**Comment by rafaelks** [comment]
@divyanshub024 Let's try to fix this for release 2.6.0 please! 👍
