### ISSUE TITLE
Cannot enter channel, error message "cannot cast..."

### ISSUE THREAD

**Issue by ennorehling** [RocketChat/Rocket.Chat.Android#1535]
## Description

When trying to enter one of the channels on our RC instance, I get the message org.commonmark.node.Orderedlist cannot be cast to org.commonmark.node.Paragraph

## Devices and Versions

Your Rocket.Chat.Android version: 2.5.0 2034
Your Rocket.Chat Server version: don't know.

Mobile device model and OS version: Huawei P9 Lite - Android 7.0

## Steps to reproduce

Open app, go into the channel, which has 11 unread messages, error message appears, page stays blank. Other channels are fine.

**Comment by Pitstopper** [comment]
Hi! Duplicate #1532 ?

**Comment by leonardoaramaki** [comment]
Closed by #1558
