### ISSUE TITLE
[BUG] Unablen to login via Google OAuth with 2FA

### ISSUE THREAD

**Issue by pandada8** [RocketChat/Rocket.Chat.Android#1537]
## Description

Login via Google OAuth when 2fa enabled result in net::ERR_UNKOWN_URL_SCHEME

## Devices and Versions

Your Rocket.Chat.Android version: Latest
Your Rocket.Chat Server version: open.rocket.chat
Mobile device model and OS version: Essential Phone PH-1 Android 8.1

## Steps to reproduce
0. Enable 2FA in your google account
1. Open the app
2. Using open.rocket.chat as server
3. Click Google
4. Input your email, password, wait for 2fa login page
5. boom

![screenshot_20180725-183326](https://user-images.githubusercontent.com/3305174/43196299-098fccd6-903a-11e8-8b82-86258b613ea6.png)

**Comment by pandada8** [comment]
The error occurs whether Google Authenticator installed or not

**Comment by philipbrito** [comment]
We're releasing a new beta version today and probably this issue is gone (I tested here and worked well)

**Comment by rafaelks** [comment]
Closing this one for now.

**Comment by pandada8** [comment]
I think this problem still exists in 2.5.1 from google play

**Comment by philipbrito** [comment]
Hi @pandada8, could you [send me](https://open.rocket.chat/direct/filipe.brito) a short video showing the problem which are you facing?

**Comment by apham0001** [comment]
Hi,
I still have the same error message : net::ERR_UNKOWN_URL_SCHEME
I'm using the last RocketChat available in Google Play : 3.4.2
I'm on Android 9 (Huawei p10)

![Screenshot_01](https://user-images.githubusercontent.com/34276938/60599633-19d8ff80-9daf-11e9-8f81-dfdc1c53c69c.jpg)
![Screenshot_02](https://user-images.githubusercontent.com/34276938/60599637-1cd3f000-9daf-11e9-9db4-4c436f121b64.jpg)
![Screenshot_03](https://user-images.githubusercontent.com/34276938/60599657-21000d80-9daf-11e9-8fef-541c65d216f3.jpg)
![Screenshot_04](https://user-images.githubusercontent.com/34276938/60599672-25c4c180-9daf-11e9-9324-33844a077422.jpg)
![Screenshot_05](https://user-images.githubusercontent.com/34276938/60599680-28271b80-9daf-11e9-8cff-5397c05b85c8.jpg)
![Screenshot_06](https://user-images.githubusercontent.com/34276938/60599688-29f0df00-9daf-11e9-8dfc-95d16e56e20e.jpg)


Thank you

**Comment by apham0001** [comment]
Hi,
I still have the same error message : net::ERR_UNKOWN_URL_SCHEME
I'm using the last RocketChat available in Google Play : 3.4.2
I'm on Android 9 (Huawei p10)

![Screenshot_01](https://user-images.githubusercontent.com/34276938/60599842-6cb2b700-9daf-11e9-8972-31a46aa3dafb.jpg)
![Screenshot_02](https://user-images.githubusercontent.com/34276938/60599845-6f151100-9daf-11e9-8627-32b34dc61e43.jpg)
![Screenshot_03](https://user-images.githubusercontent.com/34276938/60599851-72100180-9daf-11e9-9cdf-0aa21474079d.jpg)
![Screenshot_04](https://user-images.githubusercontent.com/34276938/60599858-74725b80-9daf-11e9-9c72-94fe9f3baff8.jpg)
![Screenshot_05](https://user-images.githubusercontent.com/34276938/60599865-76d4b580-9daf-11e9-98fd-582c888fea60.jpg)
![Screenshot_06](https://user-images.githubusercontent.com/34276938/60599872-79370f80-9daf-11e9-9d65-597e76725433.jpg)

Thank you

**Comment by philipbrito** [comment]
@apham0001 As mentioned on your [issue](#2393) check your configuration please.
