### ISSUE TITLE
[BUG] Channel name not updated in android app

### ISSUE THREAD

**Issue by davran-sabiraliev** [RocketChat/Rocket.Chat.Android#1542]
When we update(rename) channel name it is changing in the web version, but it is not changing in android app. The same thing happens with ios app

**Comment by philipbrito** [comment]
Hi @davran-sabiraliev It is happening because we aren't listening to this kind of change (a one less process for the app to do) - we are relying on the REST api instead of the Realtime API. Let me ask a question: When you open the app another time are you able to see the renamed channel name?

**Comment by davran-sabiraliev** [comment]
It doesn't change when we restarted the app. But after 5 days, it changed.
In group chat, it showed a message from a user who made changes that the name was changed after restarting the app. But the name was changed only after 5 days
http://joxi.ru/1A5zzjjSnqDjQr
Please take a look for the picture above: 
  I created channel "country tech", renamed to "country tech1b" then to "country tech13" then "country tech134". I received a message for only "country tech134"
