### ISSUE TITLE
No rooms or chats get listed

### ISSUE THREAD

**Issue by thorus90** [RocketChat/Rocket.Chat.Android#1549]
## Description

I can login into our selfhosted RocketChat Server but I cannot see any rooms are chats. I can create a new Room, which I can see via chromium, but it does not appear in the app.
## Devices and Versions
RocketChat Server: Ubuntu 18.04 rocketchat-server 0.66.3 installed via snap
Android App: 2.8.0 (latest from PlayStore

Mobile device model and OS version: Google Pixel 2 XL

## Steps to reproduce

Login
Try to open a room or chat

**Comment by Pitstopper** [comment]
@thorus90  Latest version is [2.5.0](https://github.com/RocketChat/Rocket.Chat.Android/releases/tag/v2.5.0) You probably installed RocketChat (Legacy). This version has not been developed for a long time. Try this [version](https://play.google.com/store/apps/details?id=chat.rocket.android)

**Comment by thorus90** [comment]
I don't know what changed over the weekend, but now it works, and I can't even reproduce where I got the version 2.8 from :D , perhaps I mistyped.

**Comment by MikasaAkerman** [comment]
i got the same problem now, with version 2.6.0.

**Comment by MikasaAkerman** [comment]
oh, 2.6.1 dose not has this problem
