### ISSUE TITLE
[v1.0-beta] Make app version available

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat.Android#155]
We need to surface the app version in order to make it easier to bug report.

**Comment by graywolf336** [comment]
Yes please. :+1:

**Comment by laggedHero** [comment]
I was thinking about doing an about screen, but that is an overkill.

I'll just add it to the footer here. Later we may move it to somewhere else.

![screenshot_1484596351](https://cloud.githubusercontent.com/assets/1779545/21997096/8fd049c8-dc14-11e6-8077-36b85f8a55c4.png)

(I had posted the image w/o the version... just dumb)

**Comment by Sing-Li** [comment]
Umm... can everyone see the version in the above screenshot.  Or is it just me 🤔

**Comment by laggedHero** [comment]
@Sing-Li The first version didn't had the version there. xD
