### ISSUE TITLE
Security Issues in Android app

### ISSUE THREAD

**Issue by neohitokiri** [RocketChat/Rocket.Chat.Android#1556]
## Description

- The users on my server are created according to an LDAP directory (the registration form is disabled). In the configuration of the server I chose not to allow the change of name, alias or avatar to the users because it is something that is done when synchronizing with the company's Windows domain. In the web version this prohibition is respected, but not in the mobile version, there the prohibition is ignored and the user can edit the details of his profile.

- I also noticed that there is a problem with the SSL handshake in the Android application. I had to change `ssl_ecdh_curve secp384r1` to `ssl_ecdh_curve prime256v1` to work through my Nginx. I think the mobile application should show some message related to SSL problems because I could only solve it by checking the source code of the application on GitHub.

## Devices and Versions

My Rocket.Chat.Android version: **2.5.1**
My Rocket.Chat Server version: **0.66.3**
Mobile device model and OS version: **Moto G5 Plus - Android 7.0**

**Comment by john171** [comment]
Exact same issue here. Restrictions for LDAP users doesn't work on android version.

**Comment by rafaelks** [comment]
@neohitokiri @john171 This restrictions can be applied client-side but the API should block this changes. This is being fixed here and should be on the release 0.68: https://github.com/RocketChat/Rocket.Chat/pull/11474.
