### ISSUE TITLE
[QUESTION] Cannot connect to server from Android app

### ISSUE THREAD

**Issue by BlackHoleFox** [RocketChat/Rocket.Chat.Android#1559]
## Description

Every time I try to connect to a self-hosted RocketChat instance I get the error "An error occurred checking your servers version, please try again". The instance is hosted locally and has an NGINX proxy in front of it for SSL, which works fine in the desktop app and on the web.

## Devices and Versions

Your Rocket.Chat.Android version: 2.5.1
Your Rocket.Chat Server version: 0.66.3 (Ubuntu Snap)

Mobile device model and OS version: Samsung S9, Android 8.0.0

## Steps to reproduce
1. Install RocketChat fresh from the Google Play store
2. Try and connect to a RocketChat instance behind an NGINX proxy.

**Comment by neohitokiri** [comment]
Hi, SSL handshake error?, see my post: https://github.com/RocketChat/Rocket.Chat.Android/issues/1556

**Comment by BlackHoleFox** [comment]
@neohitokiri I don't think so. I just set the NGINX config to use `ssl_ecdh_curve prime256v1` and the error persisted.

**Comment by neohitokiri** [comment]
Check the nginx logs, in my case i did not see any https request record, only with http, that indicates that the connection with the server was not being made, i changed the configuration of SSL and so solved the issue.

**Comment by rafaelks** [comment]
@BlackHoleFox Can you pass us your host URL?

**Comment by BlackHoleFox** [comment]
@rafaelks Id rather not post it here public. Would a Twitter DM or email suffice?

**Comment by rafaelks** [comment]
@BlackHoleFox Yes, please send me over email: `rafael.kellermann @ rocket.chat`.

**Comment by BlackHoleFox** [comment]
@rafaelks Mail sent.

**Comment by rafaelks** [comment]
@BlackHoleFox Your server do not support WebSockets.

```
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: (private)" -H "Origin: (private)" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://(private)/websocket
HTTP/2 400 
date: Tue, 31 Jul 2018 20:00:03 GMT
strict-transport-security: max-age=15552000; includeSubDomains; preload
x-content-type-options: nosniff

Not a valid websocket request
```

**Comment by rafaelks** [comment]
@BlackHoleFox Take a look on this one: https://github.com/RocketChat/Rocket.Chat.Android/issues/1116.

**Comment by BlackHoleFox** [comment]
Is there a difference between the iOS and Android client? The iOS one is working just fine after I added the headers to NGINX, but the Android is still failing. Followed that issues instructions at the bottom to the needle.

**Comment by rafaelks** [comment]
@BlackHoleFox I wasn't able to connect on iOS to your server... what app are you using?

**Comment by BlackHoleFox** [comment]
I am using the official Rocket.Chat app out of the iOS store and doing it inside of my LAN. Haven't tested it through Cloudflare, all my stuff has just been LAN only.

**Comment by rafaelks** [comment]
@BlackHoleFox It's possible that Android didn't recognise your SSL certificate in this case... can you try using `Cloudflare`?

**Comment by BlackHoleFox** [comment]
Hm yeah that fixed it for some reason. I have not a clue why, though I did notice Curl was complaining about my SSL certificate. Its a valid LetsEncrypt one.

**Comment by BlackHoleFox** [comment]
Oh the iOS one stopped working xD

**Comment by asadmukhtar28** [comment]
After adding my host and SSL certificate IOS app is working fine but Android App signin, signup not working?

**Comment by asadmukhtar28** [comment]
After adding my host and SSL certificate IOS app is working fine but Android App signin, signup not working?

**Comment by blackhatethicalhacking** [comment]
same

**Comment by f-the-architect** [comment]
Same issue while using android app

**Comment by asadmukhtar28** [comment]
@fthzkrtn  I solved this issue after adding ssl security certificates on server side and also having implementation of adding certificates while connecting to server.

**Comment by skjnk** [comment]
I have the same issue, i can access rocket.chat server on desktop app, web and ios app with ssl but cannot connect on android app. Android app can connect to server with non-ssl http://mydomain:3000. I config Apache SSL Reverse Proxy for rocketchat server. Can someone help me fix this issue?

**Comment by JoelLisenby** [comment]
Just in case anyone else runs into this issue, make sure the following mods are enabled. Enabling proxy_wstunnel worked for me with the default Apache2 reverse proxy configuration from the rocketchat documentation here:

https://docs.rocket.chat/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-an-apache-ssl-reverse-proxy

```
a2enmod proxy
a2enmod proxy_http
a2enmod proxy_wstunnel
