### ISSUE TITLE
Insert Gif from keyboard

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#156]
Your Rocket.Chat.Android version: latest

![screenshot_20170116-130431](https://cloud.githubusercontent.com/assets/51996/21995822/968c7eee-dbec-11e6-8d99-044b644ef308.png)

Being able to insert from keyboard would be amazing for inserting gifs 😁

**Comment by laggedHero** [comment]
This is not as easy as I was expecting. xD

I can't just query for the content (looks like it's not a local file). I may check for the content link and send the link.

Not the most beautiful solution, but would work.

Maybe later we could parse it better??

**Comment by laggedHero** [comment]
Update: the native mobile app won't even render the gif. But web does.

I'll open a issue for that.

**Comment by geekgonecrazy** [comment]
Awesome!! 😁
