### ISSUE TITLE
I can not run

### ISSUE THREAD

**Issue by Ruhallah93** [RocketChat/Rocket.Chat.Android#1563]
I can not run but I've done all configuration's steps in manual.

![Uploading Screenshot from 2018-07-31 12-06-58.png…]()

**Comment by philipbrito** [comment]
Hi @Ruhallah93, as you can see [here](https://circleci.com/gh/RocketChat/Rocket.Chat.Android/tree/develop) this project is building so take a look on other (closed) issues related to this one (probably you'll get some directions there).

Btw, your attachment isn't opening.

**Comment by Ruhallah93** [comment]
![screenshot from 2018-08-05 13-23-17](https://user-images.githubusercontent.com/7311445/43684303-d3e3b012-98b2-11e8-82c9-a4761d9cbe5c.png)

**Comment by Ruhallah93** [comment]
Actually I build the Project successful but it doen't run
I think that android studio has problem with "dependencies.gradle"

**Comment by Ruhallah93** [comment]
![screenshot from 2018-08-05 13-28-39](https://user-images.githubusercontent.com/7311445/43684327-79f6f158-98b3-11e8-94b8-96fbcafabddd.png)

**Comment by divyanshub024** [comment]
Try "Sync project with gradle files".

**Comment by Ruhallah93** [comment]
I do it but my problem doesn't solve
