### ISSUE TITLE
push notifications stopped working

### ISSUE THREAD

**Issue by robertwessen** [RocketChat/Rocket.Chat.Android#1568]
## Description

Sometime after the latest Android app update, push notifications stopped working.

## Devices and Versions

Your Rocket.Chat.Android version: 2.5.1 (Build 2035)
Your Rocket.Chat Server version: 0.66.2

Mobile device model and OS version: Pixel 2 XL, Android 8.1

## Steps to reproduce

Have someone @mention a user or hit Send Test Notification, no notification is received. 

## Logs
Have verified default user settings and individual user settings are all set to notify within RC. Have tried using the RC gateway for push and without, same results with both.

No logcat anomalies or receipt of push msg in device logs. No RC console logs entries generated server side. RC indicates in the top right "Your push was sent to 1 devices" the first time a test is sent, then subsequent times reports "There are no tokens for this user". No console log is generated for this event regardless of the Administration>Push>Debug radio button setting. Logging out then logging back into the Android app seems to reset something, as a test message will again be attempted ("Your push was sent to 1 devices") but again is not received and all subsequent attempts get the error message: "There are no tokens for this user" again.

**Comment by robertwessen** [comment]
After turning on Push Debug (and restarting the RC server, which seems to be required but not noted anywhere) the following is seen. Curiously iOS push is also broken now as well. No server changes made recently, only mobile apps updated when new version hit respective stores.

```ANDROID: Result of sender: {"multicast_id":xxxxxxxxxxx,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}```

This appears to be an error associated when there is a FCM project_id mismatch between the app and server?

**Comment by rafaelks** [comment]
@robertwessen Thanks for the report! You're not receiving notifications for both iOS and Android now?

**Comment by rafaelks** [comment]
@robertwessen Just check with the back-end guys and they recommended you guys to try restarting your server. There's a bug that happens sometimes and the database gets stuck, and the library that's being used to send the push notification stop sending it at all. Can you try that and let me know please?

**Comment by robertwessen** [comment]
@rafaelks Restarting the server did not make any difference.

Changing to use the public rocketchat gateway, then restarting starts push delivery again.
Without using the gateway, the error is the same as above. (this is how we had it configured initially)

**Comment by rafaelks** [comment]
@robertwessen If you're using our app from Google Play you need to use our gateway.
