### ISSUE TITLE
Mobile notification problem

### ISSUE THREAD

**Issue by himel2017** [RocketChat/Rocket.Chat.Android#1569]
## Description

I m using rocket chat on my own Linux server and i have downloaded android latest version mobile apps in mobile, but when someone messaged me i didn't get notify like other apps. all my users facing same problem.  but we get notify on desktop version only mobile app not get any notification.

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by AmShaegar13** [comment]
Same for us. Not working since about Monday 30th Jul.

**Comment by rafaelks** [comment]
@AmShaegar13 @himel2017 Thanks for opening the issue! Are you guys using our gateway to send the notifications?

**Comment by AmShaegar13** [comment]
Yes we do.

**Comment by AmShaegar13** [comment]
This might be related: https://github.com/RocketChat/Rocket.Chat.Android/issues/1568

**Comment by rafaelks** [comment]
@AmShaegar13 Can you confirm if you're receiving the notifications on the iOS app?

**Comment by himel2017** [comment]
I m using gateway. rocketchat. Com and I have problem with both ios and the android app, both mobile notifications not working

**Comment by rafaelks** [comment]
@himel2017 I see... I just tested here and works for me. Can you confirm if that happens only to your user or to all users?

**Comment by AmShaegar13** [comment]
I had multiple complaints from many users. We just rolled out mobile access to our instance so I cannot say if it's really all users affected but I do not know of any user that got notifications since Monday.

Both Android and iOS affected.

**Comment by rafaelks** [comment]
@AmShaegar13 Thanks! It was working before? Wondering if it's related to some setting on the server that was changed. It doesn't work even for DMs?

**Comment by himel2017** [comment]
It was working before but suddenly stopped work..

**Comment by himel2017** [comment]
I can give you a my admin login info

**Comment by rafaelks** [comment]
@himel2017 Please contact me in private here: `open.rocket.chat`, my username is `rafael.kellermann`.

**Comment by AmShaegar13** [comment]
Yup. Was working before and does not even work for DMs.

**Comment by rafaelks** [comment]
@AmShaegar13 @himel2017 Just check with the back-end guys and they recommended you guys to try restarting your server. There's a bug that happens sometimes and the database gets stuck, and the library that's being used to send the push notification stop sending it at all. Can you try that and let me know please?

**Comment by himel2017** [comment]
OK I will....

**Comment by AmShaegar13** [comment]
@rafaelks Restarting the server fixed the problem for us. Thank you! Is this something we can expect to happen frequently or was that issue related to a configuration change on your end?

**Comment by himel2017** [comment]
Problem Solved..

**Comment by rafaelks** [comment]
@AmShaegar13 It may happen frequently, yes... it's a bug in MongoDB that wasn't fixed yet.
