### ISSUE TITLE
[NEW] Support for multiple servers at the same app installation

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat.Android#158]
The idea is to be able to connect to multiple servers.

We may have only one user logged per server.

**Comment by geekgonecrazy** [comment]
Yes this would be very useful to have back.  I know in my case i'm connected to at least 3 usually. :+1:

**Comment by punkr0ck** [comment]
I would like to support his feature. It's really needed.

**Comment by rafaelks** [comment]
@punkr0ck What you mean by support? You want to develop it?

**Comment by punkr0ck** [comment]
@rafaelks: I should have write "I want to push this feature request", by commenting here. Sorry for the misunderstanding.

**Comment by andreafspeziale** [comment]
We really need this feature!

**Comment by rafaelks** [comment]
Closed by #436
