### ISSUE TITLE
[BUG] File size validation do not take in consideration negative or zero values

### ISSUE THREAD

**Issue by gudge25** [RocketChat/Rocket.Chat.Android#1581]
![](https://user-images.githubusercontent.com/2346208/43573659-ea289db6-964a-11e8-9067-7cd289777036.png)

But it works on PC. -same settings

**Comment by rafaelks** [comment]
@gudge25 Looks like you're trying to upload a file that's bigger than your size limit? What's the size limit in your server? If you're using a negative value, try using `0` for unlimited please.

**Comment by gudge25** [comment]
http://i.imgur.com/QODk50t.png   
:)  r U sure?  :)

**Comment by gudge25** [comment]
please  read my comment "But it works on PC. -same settings"
Problem is on Android

**Comment by rafaelks** [comment]
@gudge25 It's possible that the API is not handling the negative value... can you try a bigger number, like `1000000000`

**Comment by leonardoaramaki** [comment]
@rafaelks I think we should check it client side on our end (Android).

**Comment by ghost** [comment]
@rafaelks It worked in my Android perfectly, and would reject the file upload in another device [Both Android 7.0 {Motorola}, App version 2.5.1]. I changed the value as you suggested and the another device could send some files, but still got the following error with pictures: **"Use JsonReader.setLenient(true) to accept malformed JSON at path $"**

**Comment by gudge25** [comment]
@rafaelks  it works in https://play.google.com/store/apps/details?id=chat.rocket.reactnative  
no  settings  modification

**Comment by rafaelks** [comment]
@gudge25 What's your server version?

**Comment by rafaelks** [comment]
@openseasite What's your server version as well?

**Comment by gudge25** [comment]
Version | 0.68.2

**Comment by rafaelks** [comment]
@gudge25 Web, Desktop and the app you posted are using WebSocket to send the upload, the Android app uses a different API (REST) to upload files. Can you try updating your setting to something bigger and try again please?

Also, I don't see the message you saw on the field 🤔 

![screen shot 2018-08-08 at 09 17 44](https://user-images.githubusercontent.com/551004/43836504-f397a82e-9aeb-11e8-9fcb-2894abd4615e.png)

**Comment by rafaelks** [comment]
@gudge25 OK... I found that the check is actually happening on client-side for this case. Please increase the number to a high integer for now and we're going to submit a fix in the next release.

**Comment by rafaelks** [comment]
The problem is here: https://github.com/RocketChat/Rocket.Chat.Android/blob/e83f51756d34f71db319d8617c0337df6797d035/app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.kt#L344-L346

**Comment by ghost** [comment]
@rafaelks Version 0.68.1
