### ISSUE TITLE
I can not run

### ISSUE THREAD

**Issue by Ruhallah93** [RocketChat/Rocket.Chat.Android#1584]
I can not run but I've done all configuration's steps in manual.
Actually I build the Project successful but it doen't run
I think that android studio has problem with "dependencies.gradle"

**Comment by Ruhallah93** [comment]
![screenshot from 2018-08-05 13-23-17](https://user-images.githubusercontent.com/7311445/43700204-07f2693e-9967-11e8-8681-6e3e624cd0ff.png)

**Comment by Ruhallah93** [comment]
![screenshot from 2018-08-05 13-28-39](https://user-images.githubusercontent.com/7311445/43700229-14f0ce28-9967-11e8-96b1-c89a177c5d5d.png)

**Comment by philipbrito** [comment]
Take care of following [these steps](https://github.com/RocketChat/Rocket.Chat.Android#how-to-build) and also **avoid** opening [duplicated issues](https://github.com/RocketChat/Rocket.Chat.Android/issues/1563).
