### ISSUE TITLE
[PROBLEM] Rocket.Chat.Android-2.5.1 cannot access kotlin.collections.State from outside

### ISSUE THREAD

**Issue by almuwahhid** [RocketChat/Rocket.Chat.Android#1598]
## Description

I have problem when running Rocket Chat Android 2.5.1, it caused by accessing a private class "kotlin.collections.State". I've tried upgrading and downgrading the kotlin version and the problem remains the same.

## Devices and Versions

My Rocket.Chat.Android version: 2.5.1

## Logs

Here the logs of my project : 

app/build/tmp/kapt3/stubs/debug/chat/rocket/android/server/infraestructure/ConnectionManager.java |  
-- | --
error: State is not public in kotlin.collections; cannot be accessed from outside package     private final java.util.concurrent.CopyOnWriteArrayList> statusChannelList = null;                                                                                                                                ^ |  
error: State is not public in kotlin.collections; cannot be accessed from outside package     public final androidx.lifecycle.MutableLiveData getStatusLiveData() {                                                                       ^ |  
error: State is not public in kotlin.collections; cannot be accessed from outside package     public final kotlinx.coroutines.experimental.channels.Channel getStatusChannel() {                                                                                     ^ |  
error: State is not public in kotlin.collections; cannot be accessed from outside package     kotlinx.coroutines.experimental.channels.Channel channel) {                                                                        ^ |  
app/build/tmp/kapt3/stubs/debug/chat/rocket/android/chatroom/presentation/ChatRoomView.java |  
error: State is not public in kotlin.collections; cannot be accessed from outside package     kotlin.collections.State state);                       ^ |  
app/build/tmp/kapt3/stubs/debug/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.java |  
error: State is not public in kotlin.collections; cannot be accessed from outside package     private kotlin.collections.State lastState;                               ^ |

**Comment by almuwahhid** [comment]
My mistake, i forget to attach the SDK

**Comment by asadmukhtar28** [comment]
failed linking references.
