### ISSUE TITLE
Sharing to RocketChat-App not possible

### ISSUE THREAD

**Issue by Hans1Hansen** [RocketChat/Rocket.Chat.Android#1599]
## Description

It is not possible to share items from an app to the RocketChat-app on a Smartphone. Many apps support this important feature, e.g. sharing an URL from a webbrowser to a channel in RocketChat would be great. But the RC-Icon is missing in the list of apps able to do this.

## Devices and Versions

Your Rocket.Chat.Android version: 2.51
Your Rocket.Chat Server version: 0.67.0

Mobile device model and OS version: Samsung Note 8, Samsung S7, both Android 8.0

## Steps to reproduce

Take any app that can share info to another app. RockerChat is missing in the list.

Cheers, Hans

**Comment by philipbrito** [comment]
Thanks for opening this issue. Currently there is another issue related to this one, so let's track its status from there.

https://github.com/RocketChat/Rocket.Chat.Android/issues/98
