### ISSUE TITLE
Ignoring sign in your server

### ISSUE THREAD

**Issue by Ruhallah93** [RocketChat/Rocket.Chat.Android#1601]
How can I ignore "Sign in your server" step with static server address ?
![screenshot_1534341136](https://user-images.githubusercontent.com/7311445/44151640-6d0f7ade-a0b8-11e8-9aa9-57292935d77c.png)

**Comment by philipbrito** [comment]
Hi @Ruhallah93, 

You'll need to hard coded the server url and take away this fragment doing so.
