### ISSUE TITLE
Run Rocket chat on devices with API 17 or higher

### ISSUE THREAD

**Issue by sealiasheq** [RocketChat/Rocket.Chat.Android#1602]
I downloaded Rocket.Chat.Android (Kotlin) but minSdk of this code is on 21 but I need to run it on API 17 or higher.

**Comment by philipbrito** [comment]
Hi @sealiasheq We explained the reason [here](https://github.com/RocketChat/Rocket.Chat.Android/issues/1216#issuecomment-387389821). Thanks.
