### ISSUE TITLE
How can I add member to an existing channel via mobile app?

### ISSUE THREAD

**Issue by anshukpal** [RocketChat/Rocket.Chat.Android#1603]
## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by philipbrito** [comment]
Hi @anshukpal , thanks for opening. There is an issue already opened regarding this feature. You can track [here](https://github.com/RocketChat/Rocket.Chat.Android/issues/1230).
Thanks.
