### ISSUE TITLE
I am facing this issue when i am running #Rocket Chat in Studio Carney 3.3  

### ISSUE THREAD

**Issue by raviLogicalwings** [RocketChat/Rocket.Chat.Android#1610]
## Description

" Cannot access class 'Lkotlinx.coroutines.experimental.android.HandlerContext;'. Check your module classpath for missing or conflicting dependencies"

When i am trying to run the application, i am getting this issue every time. I need the quick solution. Can anybody give me the proper solution.  I have cloned the project from github, do you have any suggestion to setup and working this project without any warning and errors

## Devices and Versions
Kotlin Version 1.2.61
Gradle Version 4.9
Android Studio

## Logs

Thanks in advance

**Comment by leonardoaramaki** [comment]
If you're using Android Studio 3.3 Canary 6, please downgrade it to 5.
It seems to be a bug on this new AS release that could be causing this.

**Comment by philipbrito** [comment]
The issue is gone with a temporary workaround @raviLogicalwings. You can build the app now with any Canary version.

**Comment by luckcoolla** [comment]
can you please provide more logs on the error?
