### ISSUE TITLE
chat room message design 

### ISSUE THREAD

**Issue by Mohamed-Salah-WealthLab** [RocketChat/Rocket.Chat.Android#1616]
I am sending action link from server to chat room message but I can't receive it ...

so the question is 
can I change the Message class to add new attribute (contain action Link)
or chang MessageViewModel ...

simple note (I have added new attribute to MessageViewModel and BaseMessageViewModel )
and i get this error
"
No value passed for parameter 'actionLinks' |  
"

<img width="437" alt="screen shot 2018-08-27 at 5 37 48 pm" src="https://user-images.githubusercontent.com/24864924/44669746-14898680-aa21-11e8-8ab8-df6a165361b3.png">
<img width="596" alt="screen shot 2018-08-27 at 5 37 58 pm" src="https://user-images.githubusercontent.com/24864924/44669755-1ce1c180-aa21-11e8-952f-90d6b6782dfc.png">
<img width="605" alt="screen shot 2018-08-27 at 5 43 36 pm" src="https://user-images.githubusercontent.com/24864924/44669756-1ce1c180-aa21-11e8-9c16-bb811f6dcd1b.png">

**Comment by rafaelks** [comment]
Please refer to our Community Support for this kind of question: https://forums.rocket.chat/c/community-support
