### ISSUE TITLE
Logging out and logging in with another accounts keeps you on the channel you were before

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Android#162]
Your Rocket.Chat.Android version: 1.0-beta5

Steps to reproduce:

- Log in with user A
- Go to a private channel
- Log out
- Log in with user B
- You'll still see the private channel messages, even if you don't have access to it

**Comment by laggedHero** [comment]
This is related to #95 

May we continue the discussion there? :)

**Comment by sampaiodiego** [comment]
sure..
