### ISSUE TITLE
[BUG] Numerous application crashes

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1629]
Your Rocket.Chat.Android version: 2.6.0 beta
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.69.0

The application crashes: 
1. When i trying to create a channel,
2. When i try to view the version of the program in the settings, 
3. When i try to view information about the user in the list of users.

**Comment by philipbrito** [comment]
Thanks for informing us @Pitstopper !
Does your application for the FOSS or did you download it from the Play Store?

**Comment by Pitstopper** [comment]
Hi! I downloaded it in Google Play.

**Comment by Pitstopper** [comment]
Hi! 2.6.0 beta 2 fixed this issue. Thanks!

**Comment by philipbrito** [comment]
@Pitstopper Thanks for informing us too!
