### ISSUE TITLE
Missing current room indicator on rooms list

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Android#163]
Your Rocket.Chat.Android version: 1.0-beta5

On the web UI it highlights the channel you are in (like here on `#dev` channel):

![image](https://cloud.githubusercontent.com/assets/8591547/22106891/29cb236c-de32-11e6-893d-f76be912aaec.png)

This is missing on the app

**Comment by rafaelks** [comment]
Already fixed!
