### ISSUE TITLE
[CHORE] Update AppTheme

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#1634]
We need to update the `AppTheme` to support the [Material Components for Android](https://material.io/develop/android/docs/getting-started/).

Right now we are using the `1.0.0-beta1` version of that dependency and it works well, but if we increase its version we'll get the following exception: 

`java.lang.IllegalArgumentException: This component requires that you specify a valid TextAppearance attribute. Update your app theme to inherit from Theme.MaterialComponents (or a descendant)`

*We need to take care of the UI when updating the `AppTheme`.*

**Comment by divyanshub024** [comment]
I suggest verifying all the components after updating the theme to MaterialComponents. I tried it once, it changed the color of some components like button, dialog etc.

**Comment by philipbrito** [comment]
It changes the button style of our authentication screens for instance.

![screenshot_1535637735](https://user-images.githubusercontent.com/11776825/44859027-a4117e00-ac49-11e8-9aea-4b5050b572fa.png)

![screenshot_1535637617](https://user-images.githubusercontent.com/11776825/44859039-ac69b900-ac49-11e8-9cb6-94df4e605e6b.png)


*We need to take care of the UI when updating the AppTheme*

**Comment by philipbrito** [comment]
@divyanshub024 Taking advantage of this topic, could you change the `AppTheme` and test it with your current work in progress for the new UI?

**Comment by divyanshub024** [comment]
@filipedelimabrito I think it's a great idea. We should leave the theme as it is for the current version and introduce `MaterialComponent` theme in `v3.0.0`. I'll update the new designs with MaterialComponent.

**Comment by philipbrito** [comment]
Great!!! Thank you @divyanshub024!

**Comment by divyanshub024** [comment]
@filipedelimabrito I don't think so it's a right time to include Material components. There are still lots of bugs in it https://issuetracker.google.com/savedsearches/5220252. Like `android:textAllCaps="false"` is not making any changes in text. So I suggest let's wait for some time.

**Comment by philipbrito** [comment]
Thanks for sharing us this information. Let's wait the Material components get matured then.

**Comment by rafaelks** [comment]
@filipedelimabrito Moving this to 3.2.0.

**Comment by rafaelks** [comment]
That's already merged in `develop` and `beta` 💯
