### ISSUE TITLE
[BUG] Emoji skin tone is shown by hieroglyphs

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1637]
Your Rocket.Chat.Android version: 2.6.0 beta
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.69.0

Skin tone is shown by hieroglyphs.
![img_20180830_214117](https://user-images.githubusercontent.com/18574776/44872183-7e15c900-ac9d-11e8-9980-9fe30ceb9eb4.jpg)

**Comment by leonardoaramaki** [comment]
@Pitstopper does this always happens to you when you tap to select a skin tone?

**Comment by Pitstopper** [comment]
@leonardoaramaki yes, always

**Comment by leonardoaramaki** [comment]
OK, thanks for reporting this one. I'll investigate it further since I could not reproduce it just yet. Anyway, it's supposed to show an emoji for each different skin color tone. If I fail to make it fail :) then I'll just replace it with plain circles.

**Comment by Pitstopper** [comment]
@leonardoaramaki upd. In Android 7.1.2 (MIUI Stable 9.6) everything is fine. The problem is present in Android 5.1 (MIUI Stable 9.6).

**Comment by leonardoaramaki** [comment]
@Pitstopper Can you please confirm if it still happens on the latest beta build?

**Comment by Pitstopper** [comment]
@leonardoaramaki Hi! Now I'm using 2.6.1 Build 2043-2b41c7d1-play and bug is still here

**Comment by Pitstopper** [comment]
Fixed in 3.0.0 Build 2045 - 432bef6b - play. Thanks.

**Comment by Pitstopper** [comment]
3.1.0 Build 2049 - 60b39dad - play

It started to happen again :(

**Comment by leonardoaramaki** [comment]
Sorry to hear @Pitstopper. I'll post an update for this soon.
