### ISSUE TITLE
CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by esmondgh** [RocketChat/Rocket.Chat.Android#1645]
I'm trying to import the project into Android Studio v3.2rc2, but getting the following error.
**"CreateProcess error=2, The system cannot find the file specified"** (Open File).

When I click on (Open File), it redirected me to this directory: C:\AndroidProjects\Rocket.Chat.Android\app\build.gradle.

Indicating the following code.

    def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()
        def buildTime = new GregorianCalendar().format("MM-dd-yyyy' 'h:mm:ss a z")
        buildConfigField "String", "GIT_SHA", "\"${gitSha}\""

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

![rocket_chat_android_error](https://user-images.githubusercontent.com/42568091/44954806-7f631380-aea0-11e8-933e-ed4e91ed5cca.jpg)

**Comment by leonardoaramaki** [comment]
Do you have `git` installed and on system path?
