### ISSUE TITLE
[REQUEST] "Delete My Account" not available

### ISSUE THREAD

**Issue by jaytat0** [RocketChat/Rocket.Chat.Android#1657]
## Description

On the web client there is an option for a user to delete their account. It appears on the Profile page. Currently this functionality is not exposed in the android client.

**Comment by jaytat0** [comment]
@rafaelks Is there any chance of putting this on the road map as it compromises GDPR compliance currently?

**Comment by rafaelks** [comment]
We can use it by calling the Meteor method: `deleteUserOwnAccount`.

@jaytat0 Yes, we're going to include it in the mobile apps. 👍

**Comment by jaytat0** [comment]
A bounty has been opened for this issue: https://www.bountysource.com/issues/63091290-request-delete-my-account-not-available
