### ISSUE TITLE
Missing message's "alias" support

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Android#166]
Your Rocket.Chat.Android version: 1.0-beta5

A full list of message's options can be found [here](https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage)

This is how it looks like on the Web UI:
![image](https://cloud.githubusercontent.com/assets/8591547/22114728/a57a5cac-de51-11e6-9240-11e08c843969.png)

This is the message's data:
```json
{
  "_id": "Guqr8bmWZZvCWoua9",
  "alias": "some alias",
  "msg": "message's text",
  "rid": "GENERAL",
}
```

**Comment by laggedHero** [comment]
Gotta Catch 'Em All at #169
