### ISSUE TITLE
Can you produce a set of Java version of SDK?

### ISSUE THREAD

**Issue by Jersey-Guo** [RocketChat/Rocket.Chat.Android#1662]
## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by philipbrito** [comment]
Could you please elaborate your question? If you are referencing our Kotlin SDK please post your question on the proper [repository](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK).

**Comment by Jersey-Guo** [comment]
I'm using the latest version of kotlin sdk, but my project is Java code, and kotlin SDK doesn't fit into my project. I hope you'll provide the Java version of rocket. chat SDK

**Comment by philipbrito** [comment]
There is no plan today to develop a SDK write purely in Java. Kotlin is interoperable with Java, so you probably need to make some tweaks with your project if needed.
