### ISSUE TITLE
Missing message's attachment support

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Android#167]
Your Rocket.Chat.Android version: 1.0-beta5

A full list of message's attachments options can be found [here](https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage#attachments-detail)

This is how it looks like on the Web UI:
![image](https://cloud.githubusercontent.com/assets/8591547/22114860/0e99ca4c-de52-11e6-8534-e6e739fcc8ba.png)

This is the message's data:
```json
{
  "_id": "wSQAFpnQADxjjcHmm",
  "msg": "",
  "attachments": [
    {
      "title": "attachment title",
      "text": "attachment text"
    }
  ],
  "rid": "GENERAL"
}
```

**Comment by laggedHero** [comment]
Gotta Catch 'Em All at #169
