### ISSUE TITLE
[BUG] Channels aren't showing any messages, only user icons

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#1679]
## Description

Channels aren't showing messages at all, the screen is pretty much blank.

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.0
Your Rocket.Chat Server version: 0.69.0

Mobile device model and OS version: Samsung Galaxy S9 - Android 8.0.0.

## Steps to reproduce
Go into any channel.

Here's a screenshot showing the problem (note phone has RTL locale, not sure if relevant):
![bad-screenshot](https://user-images.githubusercontent.com/295571/45491755-2a15e480-b773-11e8-979e-ddefb8463c86.jpg)

Here's the same channel from another phone, where it works fine:
![good-screenshot](https://user-images.githubusercontent.com/295571/45492721-b45f4800-b775-11e8-8cd6-57622b6f32ea.png)

**Comment by leonardoaramaki** [comment]
It looks like RTL is not being properly supported.

**Comment by antgel** [comment]
@rafaelks What happened to this? It's still happening and affecting many users. Cycle 10 seems to have been closed with issues still in the New column.

**Comment by antgel** [comment]
@rafaelks Friendly ping, users still suffering.

**Comment by rafaelks** [comment]
@antgel We're going to investigate the issue! 👍

**Comment by hfeky** [comment]
@filipedelimabrito This does not occur anymore in version 3.4.0 (2065). Everything appears now.

**Comment by philipbrito** [comment]
Thanks for the ping @HusseinElFeky. Yes, this is an old bug (actually the report here refers to an very old app version, 2.6.0.). 

Closing it. Thanks!
