### ISSUE TITLE
Missing message's "avatar" support

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat.Android#168]
Your Rocket.Chat.Android version: 1.0-beta5

A full list of message's options can be found [here](https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage)

This is how it looks like on the Web UI:
![image](https://cloud.githubusercontent.com/assets/8591547/22114948/4ed1eb30-de52-11e6-83df-9339aa75a1d1.png)

This is the message's data:
```json
{
  "_id": "vfcWjFANwv7fPc4B3",
  "msg": "changing avatar",
  "avatar": "http://i2.wp.com/www.fox.ra.it/images/avatar-fox.png",
  "rid": "GENERAL"
}
```

**Comment by laggedHero** [comment]
Gotta Catch 'Em All at #169
