### ISSUE TITLE
Can't load image from smartphone

### ISSUE THREAD

**Issue by madcry** [RocketChat/Rocket.Chat.Android#1683]
## Description

When try to add image from phone to chat, sometime it's work, sometimes dosn't.
From PC it's work properly.

## Devices and Versions

Your Rocket.Chat.IOS version: (e.g. 3.1.0)
Your Rocket.Chat Server version: (0.69.2)

## Steps to reproduce

Choose image to add from library to chat
Choose new one, and it didn't work

**Comment by lorek123** [comment]
Can you check what is the filesize of each image? If it only fails for big images you may have to change client_max_body_size value in nginx config.
