### ISSUE TITLE
"Forgot password?" should not appear when default login form is disabled

### ISSUE THREAD

**Issue by jaytat0** [RocketChat/Rocket.Chat.Android#1688]
## Description

When "Show Default Login Form" is set to False, "Forgot password? Reset" should not appear on the login screen since it then does not apply. Secondarily, "Or continue using social accounts" doesn't make much sense in the custom oauth context since it's not necessarily a social account.

**Comment by philipbrito** [comment]
Thanks for opening! We'll fix that!

P.s: The "Or continue using social accounts" will not be part of the new UI.

**Comment by jaytat0** [comment]
@filipedelimabrito is there somewhere I can go to see what changes/features are going to be in the new UI you mention? Thanks.

**Comment by philipbrito** [comment]
Yes @jaytat0 
Here is: https://github.com/RocketChat/Rocket.Chat.Android/issues/1454

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/1700
