### ISSUE TITLE
[BUG] Android app - only part of message is visible

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat.Android#1689]
I have incoming webhook UptimeRobot integration.

In official android app is only part of message and it is not possible to read the whole text:

![screenshot_2018-09-19-04-36-34-599_chat rocket android](https://user-images.githubusercontent.com/1219067/45752828-0b05cf80-bc17-11e8-8879-edc84110dbcd.png)

In Rocket.Chat.ReactNative is everything ok:

![screenshot_2018-09-19-04-36-41-457_chat rocket reactnative](https://user-images.githubusercontent.com/1219067/45752844-1822be80-bc17-11e8-959d-63eaebfacb0c.png)

It is very annoing.

Please fix it. 

```
Rocket.Chat.Android version: 2.6.0
Rocket.Chat.ReactNative version: 1.2.1
Rocket.Chat Server version: 0.69.2
```

**Comment by rafaelks** [comment]
@tuxmartin Thanks for reporting the issue! We're already working on a fix for this cases. 👍
