### ISSUE TITLE
[NEW] Add analytics when reseting the password

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#1698]

**Comment by localguru** [comment]
Could you please make the error description more detailed. So you can only assume that the analytics will be reactivated when the password is changed. Under which version does the problem occur?

**Comment by philipbrito** [comment]
It isn't an error. It isn't about reactivate the analytics. Do you want to work on it or make a suggestion on that?

It is about adding the analytics when a user resets it's password on the app.
