### ISSUE TITLE
[BUG] customOath opens in webView when it should be a chrome custom tab

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/Rocket.Chat.Android#1699]
## Description
[Best practices according to the IETF](https://tools.ietf.org/html/rfc8252) explicitly state:

" OAuth 2.0 authorization requests from native apps should only be made
   through external user-agents, primarily the user's browser....

4.  Overview
   For authorizing users in native apps, the best current practice is to
   perform the OAuth authorization request in an external user-agent
   (typically the browser) rather than an embedded user-agent (such as
   one implemented with web-views).

   Previously, it was common for native apps to use embedded user-agents
   (commonly implemented with web-views) for OAuth authorization
   requests.  That approach has many drawbacks, including the host app
   being able to copy user credentials and cookies as well as the user
   needing to authenticate from scratch in each app.  See Section 8.12"

Currently Oath is implemented with a webView here:  https://github.com/RocketChat/Rocket.Chat.Android/blob/93d43d3b6584161c57baac397952fd2ebfc8658b/app/src/main/java/chat/rocket/android/webview/oauth/ui/OauthWebViewActivity.kt#L107

Is this something that should be fixed in Rocket.Chat so that it is in compliance with best practices?  

It could be done perhaps with a chrome custom tab using something like this: https://github.com/RocketChat/Rocket.Chat.Android/blob/93d43d3b6584161c57baac397952fd2ebfc8658b/app/src/main/java/chat/rocket/android/util/extensions/View.kt#L10 but I think it would also require adjustments to AndroidManifest.xml to handle deep linking in order to get the response back into the app.

Thoughts?

**Comment by philipbrito** [comment]
Thanks for opening @ear-dev!
It is something that is in the plan as you can see here too: 
https://github.com/RocketChat/Rocket.Chat.Android/issues/968

I'm closing this issue but could you post your content there? We can track the issue from a single place.

Thank you.

**Comment by ear-dev** [comment]
@filipedelimabrito Excellent!  Thanks..... Will do...
