### ISSUE TITLE
Notification icon is a big blank square

### ISSUE THREAD

**Issue by epatpol** [RocketChat/Rocket.Chat.Android#17]
Smartphone model : Oneplus one
Android version : 5.1.1

When receiving a new notification from Rocket.chat (@my_nick or pm), the icon for the notification is a blank square and is barely recognizable.

Thank you!

**Comment by YusukeIwaki** [comment]
Maybe this issue is for [RocketChat/Rocket.Chat.Android](https://github.com/RocketChat/Rocket.Chat.Android) or [Rocket.Chat.Cordova](https://github.com/RocketChat/Rocket.Chat.Cordova).
Lily doesn't have any notification features.
