### ISSUE TITLE
Slow start/restart/coming from background

### ISSUE THREAD

**Issue by darko-poljak** [RocketChat/Rocket.Chat.Android#17]
Hello!

I am using RocketChat android application and it start slowly.
If the app gets to background when I want it again in front then it
acts as it connects and fetches everything again, like when you start it for first time,
the only difference is that it does not ask for login and password.
So, when I use app and I am writing a message, and I want to see something on, for example, web I have to switch to browser and then when I want to get back to RC app it starts again with connecting/fetching, I don't know, but I have to wait for it, and usually I lost message in input field I didn't yet send (I want to paste something from browser, for example).
Can you do something about it?

**Comment by telmich** [comment]
I'm also using the android app and it takes ~20 seconds every time I open it, until I can view a message or can write. I've also checked it on iphone, it's not much different there

**Comment by greendeath** [comment]
Same here. Android app takes long until it's open and useable

**Comment by telmich** [comment]
anyone alive?

**Comment by greendeath** [comment]
Any news here?

**Comment by graywolf336** [comment]
Are you guys talking about the current android application or the native android application this repository is for?

**Comment by telmich** [comment]
@graywolf336 the current android application -- where is the right repo to report bugs to it, if this isn't the right one?

**Comment by graywolf336** [comment]
Over here: https://github.com/RocketChat/Rocket.Chat.Cordova

**Comment by Syirrus** [comment]
I notice the slowness on iOS and Android. If you background the app and then go back it to, it says connecting and the app is laggy for about 8 seconds or so.
