### ISSUE TITLE
[INVESTIGATE] Unread message count is not showing in the channel list

### ISSUE THREAD

**Issue by eco4ndly** [RocketChat/Rocket.Chat.Android#1703]
## Description
Unread message count is not showing in the channel list. After debugging I found that unread is coming as null in RoomViewHolder.kt

## Devices and Versions
RocketChatVersion - 2.6.1
Devices - Accross Many devices(eg. OnePlus 5, Motorola E4 Plus)

## Steps to reproduce
Open the Homescreen and you'll notice unread message count is not being showed though there are some unread messages

## Logs
RoomUiModel(id=pq6WJtaZL6XW7Pi4s, type=c, name=newchannel, avatar=http://myserver/avatar/%23newchannel?format=jpeg, open=true, date=12:36 PM, unread=null, alert=false, lastMessage=991683XXXX: Hi 
Giigg, status=null, username=null)

**Comment by rafaelks** [comment]
@eco4ndly Do you have the number coming from the API? On the web client do you see the number?
