### ISSUE TITLE
[BUG] Message missed in input box when connection lost

### ISSUE THREAD

**Issue by skyfall174** [RocketChat/Rocket.Chat.Android#1706]
## Description

When i write some message in metro, and RocketChat loose connection, the message that was in input box disappear. 

In metro station when connection is establish and i write new message, its works, but in metro tunnel its disappear again 
## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1
Your Rocket.Chat Server version: 0.69.2

## Devices
* Honor 9-Lite Android 8.0
* Samsung Galaxy S9 - Android 8.0

## Steps to reproduce
1. Write some message, but dont send it.
2. Then (i dont how but try simulate it ) lost  connection of server
3. Message in box is disapppear

## Logs
Sorry i dont have any logs

I

**Comment by igorr-stc** [comment]
Some of our users have same problems. Also I could reproduce bug while using evevator with poor mobile network coverage.

**Comment by rafaelks** [comment]
@leonardoaramaki Do this as a hot fix (directly to master).

**Comment by leonardoaramaki** [comment]
Does this behavior always happens or sometimes not?

**Comment by skyfall174** [comment]
Just sometimes . It's start when "connection cutdown " is ends. After it message will disappear.

And some times I can not send photos via mobile network after this issue. (I don't know if this is same issue but I have it )

**Comment by leonardoaramaki** [comment]
Ok. We have some issues with the composer, indeed. I think this one is related to the _draft_ feature of the composer, which is probably broken.

**Comment by leonardoaramaki** [comment]
Guys, any alternative or additional steps to help me reproduce the issue? It doesn't happen here on my tests

**Comment by leonardoaramaki** [comment]
Ok, I was able to reproduce the problem. Looking into this now :+1:
