### ISSUE TITLE
Use JsonReader.setLenient(true) to accept malformed JSON at path$ on sending a VIDEO file

### ISSUE THREAD

**Issue by fromage9747** [RocketChat/Rocket.Chat.Android#1711]
## Description

Reference: https://github.com/RocketChat/Rocket.Chat.Android/issues/1352

When trying to upload a video file using the latest Rocket.Chat mobile app:
https://play.google.com/store/apps/details?id=chat.rocket.android&hl=en

The below error will be displayed:
"Use JsonReader.setLenient(true) to accept malformed JSON at path$" on sending a VIDEO file.
Image files work perfectly fine without issue.

![image](https://user-images.githubusercontent.com/23147783/46268008-48952180-c562-11e8-9b7d-123f2be316f3.png)

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1 Build 2043 - 2b41c7d1
Your Rocket.Chat Server version: 0.70.0

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")
Samsung Note8, Samsung s8

## Steps to reproduce
1. Download the the Android Mobile app from the Google Playstore.
2. Connect to your Rocket.Chat onsite server
3. Navigate to a contact or to the '#general' channel
4. Click on the paperclip icon in the send message text area
5. Click on all files
6. Navigate to and select a video file to upload (regardless of size, 1mb doens't even work)
7. Note that you will receive the error message as per below:

![image](https://user-images.githubusercontent.com/23147783/46268127-fd2f4300-c562-11e8-95dd-c3a67063dacc.png)

## Logs
I will need to setup Android studio in order to obtain these logs to use the logcat and update this request.

**Comment by TannerJuby1** [comment]
I am receiving this same error when trying to favorite a chat room. Have any update on the fix?

**Comment by rafaelks** [comment]
Is this still happening in 3.1.0?

**Comment by fromage9747** [comment]
I gave up with it and moved onto mattermost. Works without issue. Video and pictures upload without any issue. Suits my requirements.

**Comment by fadanner** [comment]
Having the exactly same issue on Android Rocket.Chat 3.1.1 , Server Version 0.71.1 (Ubuntu snap)
Any chance to fix this?

**Comment by fromage9747** [comment]
@fadanner, as this issue has now been closed. You may need to create a new issue and reference this one.
