### ISSUE TITLE
Ability to have video and voice calls on rocket chat mobile apps like whatsapp and telegram

### ISSUE THREAD

**Issue by FaizanZahid** [RocketChat/Rocket.Chat.Android#1714]
cket.Chat.Android version: (e.g. 2.6.1)
Your Rocket.Chat Server version: (e.g. latest as of 1st oct 2018)

It would make rocket chat amazing, if we can have audio and video calls with users on rocket chat android and ios apps like we can do on the web.

Is there any chance of making this feature request? We are happy to do a bounty for this for those who are interested to do this :)

**Comment by rafaelks** [comment]
Duplicates #466
