### ISSUE TITLE
[NEW] Logout Confirmation

### ISSUE THREAD

**Issue by shubhsherl** [RocketChat/Rocket.Chat.Android#1715]
## Description

The app should ask for confirmation before Logout.

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1
Mobile device model and OS version:
Xiaomi Redmi Note 4 - Android 7.0
## Steps to reproduce
Just press LOGOUT

**Comment by localguru** [comment]
Just out of interest: what case might that be good for? I hardly know of a web application that asks if you really want to "exit" when logging out, unless some data has not yet been saved.

**Comment by shubhsherl** [comment]
The option for Logout is the last option in Menu, and it's annoying if you press it by mistake(in case if you were to press Setting).
All the other apps which don't have Logout confirmation have log out option not directly in the menu(like in quora app), or if it's in the menu, then it would be the last option among many options(like in facebook app), unlike in our case with only five choices.

**Comment by rafaelks** [comment]
I agree that the Logout option should have a confirmation dialog, it's much more convenient for the user instead of logout by mistake and loose everything.

**Comment by localguru** [comment]
I am now also convinced (not that that would be decisive :) )
