### ISSUE TITLE
[NEW] User information screen

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Android#1719]
## Description

In the desktop app and in the browser, it's possible to display the information about a user. In the Android App, clicking on the user's name or image opens the dialog to respond to a message.

Ultimately, it is more convenient to get the message dialog by clicking on the message than using the "option" at the line end of the message. But the Android app should also allow you to view the information about a user.

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1
Your Rocket.Chat Server version: 0.69.2

## Steps to reproduce

Click on the user's name or image

**Comment by FaizanZahid** [comment]
i faced the same issue, the react native app atleast has this feature i think.  https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by rafaelks** [comment]
Changed the title to "User information screen" to have more context. 👍

**Comment by FaizanZahid** [comment]
i have also mentioned this thing in one of the other issues. this will be a huge UX improvement and also users love to brag about themselves, so a short bio, photo album, and users followers section will be good to have on user profile page.
