### ISSUE TITLE
"More channels" missing, can't join

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat.Android#172]
Your Rocket.Chat.Android version: 1.0beta5? I dunno I compiled it today

The "more channels" button on desktop left menu has more that just searching for channels. You can also browse all channels including archived. That's really why this is different than issue #96.

Currently I can see no way to join public channels.

**Comment by laggedHero** [comment]
I'll check out with the guys how it works on web. Thx!

**Comment by mcjwsk** [comment]
Any updates?

**Comment by aenonGit** [comment]
Same here, news?

**Comment by mrplow** [comment]
Bump!

Not being able to join a channel seems like a pretty big issue no?

**Comment by geekgonecrazy** [comment]
@mrplow I think this is actually partially resolved.  If you slide open the panel and search for channels you can tap them and join.  We just don't show a list to browse through yet :smile: 

So while yes a nice to have, its not as critical since the functionality to join channels exists.

**Comment by mrplow** [comment]
Very true, I didn't realize it showed channels you hadn't joined.

Thanks @geekgonecrazy
