### ISSUE TITLE
SSL certificate...

### ISSUE THREAD

**Issue by asadmukhtar28** [RocketChat/Rocket.Chat.Android#1721]
When i change the host to my Domain and also add SSL certificate using OkHttpclient signup, and signin not working?

**Comment by rafaelks** [comment]
@asadmukhtar28 Please make sure you've a valid SSL certificate, I'm closing the issue for now. There are many other issues related to SSL that you can check the resolutions. If you find something different, please post here again and we can reopen it. Thank you!
