### ISSUE TITLE
Renaming Package causes Build Errors

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat.Android#1722]
## Description

I forked this repo with the goal to modify the project and launch in the google store. However, I need to change the package name before uploading the APK to the play store or else I get the error saying the package name is already in use. 

I attempted to change the package name using [this solution](https://stackoverflow.com/questions/16804093/android-studio-rename-package) but after doing that, I received a bunch of errors similar to Issue #1598 which I understand is caused by not attaching the Kotlin SDK. So I attempted to rerun the script that installs the Kotlin SDK and even after completing, the same errors were still occurring.

Do you perhaps have a guideline on how to prep this project for loading into the Play Store, or have any recommendations on how to properly change the package name so that I am able to load the project into the Play Store?

Thanks

## Devices and Versions

Device and Version is not really relevant for this question

Version:
Your Rocket.Chat.Android version: Latest (2.6.1)
Your Rocket.Chat Server version: Latest (?)

Device:
Mobile device model and OS version: Pixel 2 Simulator (not relevant)

## Steps to reproduce

Rename package using [this solution](https://stackoverflow.com/questions/16804093/android-studio-rename-package)

## Logs

_Copied from issue #1598_
 
app/build/tmp/kapt3/stubs/debug/chat/rocket/android/server/infraestructure/ConnectionManager.java |  
-- | --
error: State is not public in kotlin.collections; cannot be accessed from outside package private final java.util.concurrent.CopyOnWriteArrayList> statusChannelList = null; ^ |  
error: State is not public in kotlin.collections; cannot be accessed from outside package public final androidx.lifecycle.MutableLiveData getStatusLiveData() { ^ |  
error: State is not public in kotlin.collections; cannot be accessed from outside package public final kotlinx.coroutines.experimental.channels.Channel getStatusChannel() { ^ |  
error: State is not public in kotlin.collections; cannot be accessed from outside package kotlinx.coroutines.experimental.channels.Channel channel) { ^ |  
app/build/tmp/kapt3/stubs/debug/chat/rocket/android/chatroom/presentation/ChatRoomView.java |  
error: State is not public in kotlin.collections; cannot be accessed from outside package kotlin.collections.State state); ^ |  
app/build/tmp/kapt3/stubs/debug/chat/rocket/android/chatroom/presentation/ChatRoomPresenter.java |  
error: State is not public in kotlin.collections; cannot be accessed from outside package private kotlin.collections.State lastState; ^

**Comment by TannerJuby1** [comment]
I attempted this again, and instead of getting those errors, I am getting failed tasks due to `no matching client found for package name 'my.new.package'`.

The specific task that is failing first is `:app:processPlayReleaseGoogleServices`

**Comment by TannerJuby1** [comment]
I was able to find a solution to this problem. You don't need to do the solution I originally attempted listed above. Here is how I was able to modify the project to be able to upload to the Play store:

**Step 1: Refactor `package` in AndroidManifest.xml**

Open the `AndroidManifest.xml file`, and find the package name. Right click on the `chat.rocket.android` string and select `Refactor > Rename` Note: which ever string you right click on, that's the string that will be refactored (i.e. right click on `android` only android will be refactored. right click on `rocket` only rocket will be refactored.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="chat.rocket.android"

    ....
```

There will be some dialogue boxes to work through but it's pretty straight forward.

**Step 2: Update build.grade file `applicationId`**

Open the build.gradle file (app) and find the `applicationId` in the default config

```
android {
    compileSdkVersion versions.compileSdk
    buildToolsVersion versions.buildTools

    defaultConfig {
        applicationId "chat.rocket.ytpconnect"

    ....
```

Change the `applicationId` to whatever you refactored the package name to.

**Step 3: Update the google-services.json file.

Locate the `google-services.json` file in the `app` folder. Find all instances of the previous package name and change it to your new package name. Save the file.

**Step 4: Clean and Rebuild**

Go back to Android Studio and clean and rebuild the project.

**Comment by philipbrito** [comment]
Glad to hear that you found a solution @TannerJuby1 and thank you for posting it here!

**Comment by zolbayars** [comment]
Hi, @TannerJuby1 

I modified the project as you've described. But those `error: State is not public...` errors are still occurring. Any idea on how to bypass this?

**Comment by kirkkhua** [comment]
Only [this way](https://stackoverflow.com/questions/16804093/rename-package-in-android-studio/39701758#39701758) of renaming the package worked properly for me.
