### ISSUE TITLE
[BUG] Unable to chat or send private message: com.squareup.moshi.JsonDataException

### ISSUE THREAD

**Issue by adrienbresson** [RocketChat/Rocket.Chat.Android#1723]
## Description

Unable to chat or send private message:` com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was NULL at path $.messages[0].reactions at $.messages[0].reactions`

## Devices and Versions

Your Rocket.Chat.Android version: 
```
From F-droid : 2.6.0 Build 2042 - 22c57a15 - foss
```
Your Rocket.Chat Server version: 
```
Hash : 40b50f31641c77c5d60a26641fdd840b374140da
Date : Fri Sep 28 00:06:32 2018 -0300
Branch : HEAD
Tag : 0.70.0
Author : Diego Sampaio
Subject : Merge pull request #12198 from RocketChat/release-0.70.0
```
Mobile device model and OS version:
```
Device: Samsung Galaxy s4: GT-I9505 
Android: 7.1.2 (LineageOS 14.1-20180928-NIGHTLY-jltexx - without GApps installed)
```

## Steps to reproduce

* Install rocket.chat FOSS from fdroid
* Connect to rocket.chat server
* Click on one user or one channel
* Get blank conversation window with message:  `com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was NULL at path $.messages[0].reactions at $.messages[0].reactions`

## Logs

```
com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was NULL at path $.messages[0].reactions at $.messages[0].reactions
```

**Comment by rafaelks** [comment]
@adrienbresson This is already fixed for next release, thank you!
