### ISSUE TITLE
Support Basic Authentication

### ISSUE THREAD

**Issue by ahuret** [RocketChat/Rocket.Chat.Android#1727]
## Description

Android application doesn't support basic authentication.
ex: it should authenticate with username:password@rc-domain.com

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1
Your Rocket.Chat Server version: 0.69.2

## Steps to reproduce

- Authenticate with: username:password@rc-domain.com
- see error: "An error has occurred while checking your server version, please try again"
=> authentication doesn't work

**Comment by rafaelks** [comment]
@antony360 Yes it works... are you using 2FA?

**Comment by ahuret** [comment]
not on our side, and no 2FA, only basic auth
![image](https://user-images.githubusercontent.com/25103434/46537540-d601aa00-c8b1-11e8-87a7-c15c362cc600.png)

**Comment by rafaelks** [comment]
@antony360 What's your server URL? As far as I can see, you cannot even connect to it.

**Comment by andypost** [comment]
It is reproducible in local net with dockerized version and some nginx/traefik in front of RC with basic/auth enabled

**Comment by rafaelks** [comment]
@andypost Is the SSL valid? If not you need to choose "http://" instead.

**Comment by Drintios** [comment]
It is valid checked on https://www.ssllabs.com

**Comment by jbguerraz** [comment]
@rafaelks you can check it out on http://64f11a42.ngrok.io or even https://64f11a42.ngrok.io with auth login: foo / password: bar (I'll keep it running for a while)

you can repro that setup the following way : 
```
docker run --name db -d mongo:3.0 --smallfiles  
docker run --name web --link db -d rocket.chat
sudo docker run -d -e FORWARD_PORT=3000 -p 80:80 --link web:web --name basicauth beevelop/nginx-basic-auth
ngrok http 80
```

and this is how it looks like when the server info request comes from android app : 
![image](https://user-images.githubusercontent.com/861556/46550650-f6dbf680-c8d5-11e8-9f0d-ba146a7c4e27.png)
as you can see the Authorization header is missing (despite I've used the url `http://foo:bar@64f11a42.ngrok.io` from the android app)

and locally (docker / ngrok / chromium), from desktop, all is OK :

![image](https://user-images.githubusercontent.com/861556/46550467-74533700-c8d5-11e8-9d27-3e61cbb3e9cf.png)

**Comment by rafaelks** [comment]
Oh, now I'm understanding what you guys are talking about... it really doesn't work for iOS and Android. That's the first time we have this kind of request, hehe... in theory, this should be added as a Header parameter, it works on the browser and other tools because they're doing that under the hood.

Any ideas how to solve this problem in the apps? We could try identifying this information and creating the headers on the request, but honestly, this would need to be saved for future requests as well... 🤔

**Comment by jbguerraz** [comment]
Probably it could be implemented somewhere around here https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/develop/core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt

I've implemented there an okhttp interceptor that adds the Authorization header (hardcoded for now) and that worked well.

IMHO, ideally the app would prompt the user for basic authentication credentials when the server answers with a 401 so there won't be a need to rely on userinfo (OTOH, it would be much faster / easier to implement it relying on the userinfo part of the URI for me now)

**Comment by jbguerraz** [comment]
```
diff --git a/core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt b/core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
index 3484021..6ce913e 100644
--- a/core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
+++ b/core/src/main/kotlin/chat/rocket/core/RocketChatClient.kt
@@ -29,11 +29,13 @@ import kotlinx.coroutines.experimental.channels.Channel
 import okhttp3.HttpUrl
 import okhttp3.MediaType
 import okhttp3.OkHttpClient
+import okhttp3.Credentials
+import java.net.URL
 import java.security.InvalidParameterException
 
 class RocketChatClient private constructor(
-    internal val httpClient: OkHttpClient,
-    baseUrl: String,
+    internal var httpClient: OkHttpClient,
+    var baseUrl: String,
     userAgent: String,
     internal val tokenRepository: TokenRepository,
     internal val logger: Logger
@@ -66,6 +68,20 @@ class RocketChatClient private constructor(
     internal val socket: Socket
 
     init {
+        //if userinfo add basic auth interceptor
+        URL(baseUrl).getUserInfo()?.let{
+            val credentials = it.split(":")
+            httpClient = httpClient.newBuilder().addInterceptor { chain ->
+                val originalRequest = chain.request()
+
+                val builder = originalRequest.newBuilder()
+                        .header("Authorization", Credentials.basic(credentials[0], credentials[1]))
+                val newRequest = builder.build()
+                chain.proceed(newRequest)
+            }.build()
+            baseUrl = baseUrl.replace(it+"@","")
+        }
+
         url = sanitizeUrl(baseUrl)
         agent = userAgent
```

That get it working but not for the avatar images loading (those requests doesn't go thru that http client obviously) + the _userinfo_ is displayed in the left sidebar, as part of the server URL (which is not OK).

I will dig a bit deeper ASAP (maybe later today).

**Comment by Drintios** [comment]
```
diff --git a/app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt b/app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
index 496d907b..a7bb2c74 100644
--- a/app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
+++ b/app/src/main/java/chat/rocket/android/dagger/module/AppModule.kt
@@ -53,6 +53,7 @@ import chat.rocket.android.server.infraestructure.SharedPrefsConnectingServerRep
 import chat.rocket.android.server.infraestructure.SharedPrefsCurrentServerRepository
 import chat.rocket.android.util.AppJsonAdapterFactory
 import chat.rocket.android.util.HttpLoggingInterceptor
+import chat.rocket.android.util.BasicAuthInterceptor
 import chat.rocket.android.util.TimberLogger
 import chat.rocket.common.internal.FallbackSealedClassJsonAdapter
 import chat.rocket.common.internal.ISO8601Date
@@ -109,6 +110,7 @@ class AppModule {
     fun provideOkHttpClient(logger: HttpLoggingInterceptor): OkHttpClient {
         return OkHttpClient.Builder()
             .addInterceptor(logger)
+            .addInterceptor(BasicAuthInterceptor())
             .connectTimeout(15, TimeUnit.SECONDS)
             .readTimeout(20, TimeUnit.SECONDS)
             .writeTimeout(15, TimeUnit.SECONDS)
diff --git a/app/src/main/java/chat/rocket/android/util/BasicAuthInterceptor.kt b/app/src/main/java/chat/rocket/android/util/BasicAuthInterceptor.kt
index e69de29b..b5b8d5dc 100644
--- a/app/src/main/java/chat/rocket/android/util/BasicAuthInterceptor.kt
+++ b/app/src/main/java/chat/rocket/android/util/BasicAuthInterceptor.kt
@@ -0,0 +1,33 @@
+package chat.rocket.android.util
+
+import chat.rocket.android.BuildConfig
+import okhttp3.Credentials
+import okhttp3.Request
+import okhttp3.Headers
+import okhttp3.Interceptor
+import okhttp3.MediaType
+import okhttp3.OkHttpClient
+import okhttp3.Response
+import timber.log.Timber
+import java.net.URL
+import java.io.IOException
+
+class BasicAuthInterceptor : Interceptor {
+
+    init {
+        Timber.d("Basic authentication")
+    }
+
+    @Throws(IOException::class)
+    override fun intercept(chain: Interceptor.Chain) : Response {
+        var authenticatedRequest = chain.request().newBuilder().build()
+
+        URL(chain.request().url().toString()).getUserInfo()?.let {
+            val request = chain.request()
+            val credentials = it.split(":")
+            authenticatedRequest = request.newBuilder()
+            .header("Authorization", Credentials.basic(credentials[0], credentials[1])).build()
+        }
+        return chain.proceed(authenticatedRequest)
+    }
+}
diff --git a/build.gradle b/build.gradle
index 39812fdb..6bf5e3f0 100644
--- a/build.gradle
+++ b/build.gradle
@@ -10,7 +10,7 @@ buildscript {
     }
 
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.2.0-rc03'
+        classpath 'com.android.tools.build:gradle:3.2.0'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${versions.kotlin}"
         classpath "org.jetbrains.dokka:dokka-gradle-plugin:${versions.dokka}"
         classpath 'com.google.gms:google-services:4.0.2'
```

Following @jbguerraz suggestion i added interceptor on app side it authenticate only if authentication data on url, and loads avatar, now need to hide user data from side bar url.

**Comment by jbguerraz** [comment]
https://github.com/jbguerraz/Rocket.Chat.Android/commit/5b395da309ef76ceb9701a7d60f21d5163012597

This works quite well (avatars are OK, userinfo is removed from URLs) but that doesn't survive an application restart : the app tries to connect but fails, only a logout / login will helps

Need to find out what's the proper way to persist those http basic authentication credentials so it survives application restarts

**Comment by Drintios** [comment]
Created PR that addresses this issue using a model to store basic auth data mb need some further improvements plz add any comments and opinions about it,  it is a good start.

**Comment by Drintios** [comment]
Since this was added `fun String.isValidUrl(): Boolean = Patterns.WEB_URL.matcher(this).matches()`
now basic auth url doesn't allow to click on connect button

**Comment by jbguerraz** [comment]
great! @rafaelks would you mind reviewing it ? :)

**Comment by rafaelks** [comment]
Thank you guys! We'll be reviewing this PR shortly! :-)
