### ISSUE TITLE
[NEW] Hide email/password on login screen

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat.Android#173]
Your Rocket.Chat.Android version: built 2017.01.20

The only way to login to my server is by Google auth. It would be nice to have the email/password fields hidden.

**Comment by antgel** [comment]
Any updates on this? It's very confusing for users.

**Comment by antgel** [comment]
@rafaelks Any updates on this? It's really confusing for those of us using GSuite.

**Comment by rafaelks** [comment]
@antgel We're working on that for 2.0.0.

**Comment by rafaelks** [comment]
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).

**Comment by antgel** [comment]
@rafaelks Okay, any forecast for 2.0 delivery date? https://github.com/RocketChat/Rocket.Chat.Android/milestone/6 is pretty long. :)

**Comment by rafaelks** [comment]
@antgel Milestone is set to 31 March. :-)

**Comment by antgel** [comment]
@rafaelks Oops, missed it. Good luck to the team! :)
