### ISSUE TITLE
Animated gifs gets turn into static gifs

### ISSUE THREAD

**Issue by xGigaa** [RocketChat/Rocket.Chat.Android#1744]
## Description
Animated gifs upload from an android phone will be converted to a static gif.
(However animated gifs uploaded from the webclient will stay animated and preview correctly.)

## Devices and Versions

Your Rocket.Chat.Android version: (2.6.1)
Your Rocket.Chat Server version: (0.70.0)

Mobile device model and OS version: (Oneplus 3 - LineageOS 15.1")

## Steps to reproduce
1. Try to upload a animated gif to a conversation.
2. The animated gif gets turned into a static one.

**Comment by localguru** [comment]
I can confirm that. An animated gif uploaded with the Android App will no longer be animated in the browser or electron client. The image size also decreases. Only the first image of the animated gif seems to be uploaded.
