### ISSUE TITLE
[BUG] Numerous application crashes

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1747]
Your Rocket.Chat.Android version: 3.0.0 Build 2044 - 0ddd70d - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.69.2

The application crashes:
1. When i trying to create a channel,
2. When i trying to open admin panel.

**Comment by rafaelks** [comment]
@Pitstopper Thank you! We're working on this ones as well. 👍
