### ISSUE TITLE
[BUG] Strange button artifacts

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1748]
Your Rocket.Chat.Android version: 3.0.0 Build 2044 - 0ddd70d - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.69.2

I found strange button artifacts. Maybe some text did not fit in the button? I checked the translation and did not find anything like that.

![screenshot_2018-10-11-09-41-27-250_chat rocket android](https://user-images.githubusercontent.com/18574776/46785477-85b79b80-cd3a-11e8-9b28-3f87e7a9c89d.png)

**Comment by rafaelks** [comment]
Oh... this is because the button has two lines. Adding @filipedelimabrito here.
