### ISSUE TITLE
[NEW] Emoji support

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat.Android#175]
We'll need to properly deal with emoji (displaying and entering).

This is a prerequisite for #174

**Comment by sscholl** [comment]
It would be nice if this feature would be added soon. Without that, the app lacks a very important aspect of mobile chat. For us, this is mendatory. I'm very surprised that it's still not added. Especially the emoji relations. 
Thanks

**Comment by rafaelks** [comment]
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).
