### ISSUE TITLE
Application / Google Play

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat.Android#176]
I apologize in advance for the question... but is this the official Rocket.Chat application that resides in Google Play?

Thanks in advance.

**Comment by geekgonecrazy** [comment]
The one on the play store is: https://github.com/RocketChat/Rocket.Chat.Cordova

**Comment by dmkjr** [comment]
Thanks.  What is the difference in the two?  Different approach?

**Comment by geekgonecrazy** [comment]
@dmkjr The one in the play store is our initial app.  This one we're working on will have better performance.  But is not yet ready for prime time.  And yes different approach.

**Comment by dmkjr** [comment]
@geekgonecrazy Thank you for the response.  I would like to test what you have so far, if there is a beta channel or do I need to compile through GitHub?  Also, if available, could I keep the Cordova version installed as well?

**Comment by geekgonecrazy** [comment]
A beta version will be out for this before too long.  Both can be installed side by side.
