### ISSUE TITLE
[BUG] Admin cannot delete messages from other users

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Android#1760]
## Description

A user with the role "admin" cannot delete messages from other users in a channel/room. This is possible in browser or in the Electron client.

Editing a message of another user as admin is possible.

Own messages can be deleted.

_It should be tested whether this also applies to the roles "moderator" and "owner" if they have the authorization to delete messages._

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1
Your Rocket.Chat Server version: 0.69.2

Mobile device model and OS version: BQ Aquaris X5 Plus and Android 7.1.1

## Steps to reproduce

1. log in to the Android App as a user with admin role
2. try to delete a message written shortly before by another user.
3. the message is **not** deleted; no error message.
4. repeat steps 1 and 2 in the browser or Electron Client.  The message will be deleted (but will still be displayed in the Android app, bug #1754)

**Comment by leonardoaramaki** [comment]
@localguru Thanks for sharing with us this issue. 
We investigated it internally and we found out that there's an old bug on the `chat.delete` REST endpoint. 
A fix was released for this and it should be available on the next release for the platform. 
You can follow it here: https://github.com/RocketChat/Rocket.Chat/pull/12408
I'm closing this now, until we get to next release. 
As always, feel free to reopen it again if you feel there's something else we missed.
