### ISSUE TITLE
Some of word cannot use 

### ISSUE THREAD

**Issue by sophornsna** [RocketChat/Rocket.Chat.Android#1762]
Dear Rocket Chat Team,

I have updated Rocket Chat to the last version 0.70.4. Now I got the problem. There are a lot of words, that I cannot use as the word hello, the name of someone....... It shows the asterisk (*******). For example:
![selection_028](https://user-images.githubusercontent.com/16955446/46939418-71ec9c00-d090-11e8-93b6-e4f84ef9a030.png). 
could you help to show me how to resolve it?

Thanks,

**Comment by rafaelks** [comment]
This is related to E2E and on the web client. Mobile clients still don't support E2E.

**Comment by sophornsna** [comment]
@rafaelks how can I fix this problem?
