### ISSUE TITLE
[BUG] Crash in Read-only channel with reply option to message.

### ISSUE THREAD

**Issue by DipaliShah** [RocketChat/Rocket.Chat.Android#1763]
## Description

App crashes with Fatal Exception while trying to send reply to read-only channel from Android Device.
## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: 
Emulator Pixel 2- API 27 
[device-2018-10-15-154634.zip](https://github.com/RocketChat/Rocket.Chat.Android/files/2478324/device-2018-10-15-154634.zip)

## Steps to reproduce

1. Create Read only channel. Add 2-3 members.
2. Add message in this channel.
3. Try to send Reply to this message from other user. This should not be possible as this is Read- only channel (for admin only) but reply to the message is available .
4. Hitting send button will produce the bug with following logs. 
## Logs

>  E/MessageService: chat.rocket.common.RocketChatApiException: [You can't send messages because you have been muted](url='http://serverurl/api/v1/chat.sendMessage')
>         at chat.rocket.core.internal.rest.RestClientKt.processCallbackError(RestClient.kt:173)
>         at chat.rocket.core.internal.rest.RestClientKt$handleRequest$$inlined$suspendCancellableCoroutine$lambda$1.onResponse(RestClient.kt:104)
>         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
>         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)
> 

clicking on channel will produce 

> FATAL EXCEPTION: main
>     Process: chat.rocket.android.dev, PID: 9364
>     kotlin.KotlinNullPointerException
>         at chat.rocket.android.chatroom.presentation.ChatRoomPresenter$loadActiveMembers$1.doResume(ChatRoomPresenter.kt:722)
>         at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
>         at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
>         at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 2018-10-15 15:30:15.232 9364-9530/chat.rocket.android.dev E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-0
>     Process: chat.rocket.android.dev, PID: 9364
>     kotlin.KotlinNullPointerException
>         at chat.rocket.android.chatroom.presentation.ChatRoomPresenter$loadActiveMembers$1.doResume(ChatRoomPresenter.kt:722)
>         at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
>         at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
>         at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:19)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by rafaelks** [comment]
This is not reproducible anymore in 3.2.0. 👍
