### ISSUE TITLE
[QUESTION] Large images are being compressed/resized on upload

### ISSUE THREAD

**Issue by thepowerprocess** [RocketChat/Rocket.Chat.Android#1765]
## Description

When uploading high resolution photos (ie 2000x2000) they are compressed/resized before uploading.  Is this a feature, and if so, can this be turned off?  I do not remember this happening several months ago.

## Devices and Versions

Your Rocket.Chat.Android version: 2.6.1
Your Rocket.Chat Server version: 0.69.2

Mobile device model and OS version: Samsung Galaxy S6

## Steps to reproduce

Upload a few high resolution image via the app
2) download the images from the server
3) they are compressed/lower resolution.

**Comment by rafaelks** [comment]
@cloudsandladders Does your server have any limitation on the uploading of the images?

**Comment by thepowerprocess** [comment]
@rafaelks the upload size limit is 8mb.  Uploaded images are not being compressed when uploaded via browser or iphone, only android app.

**Comment by rafaelks** [comment]
This one was fixed by #1810
