### ISSUE TITLE
[BUG] Image compression

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1768]
Your Rocket.Chat.Android version: 3.0.0 Build 2047 - 0a57fbd8 - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.70.4

The first image is loaded and displayed normally, and the next image is loaded very compressed. This was not observed in the previous build. After some time, this is repeated. The first picture is loaded normally, and the next one is compressed.

![img_20181017_092707](https://user-images.githubusercontent.com/18574776/47066453-d6257200-d1ee-11e8-9643-dfa5b45747bf.jpg)

**Comment by rafaelks** [comment]
@Pitstopper They're different images... can you tell us the steps to reproduce this?

**Comment by Pitstopper** [comment]
@rafaelks Images are different, but of the same quality (screenshots). Ок, i'm take two identical images and load them with a difference of 15 seconds. And get this:
![screenshot_2018-10-17-20-13-06-376_chat rocket android](https://user-images.githubusercontent.com/18574776/47104498-43b2bc00-d24a-11e8-9dff-12e1e390968a.png)

If you look closer, the first image looks like this:
![2](https://user-images.githubusercontent.com/18574776/47104589-75c41e00-d24a-11e8-9054-ae961ab9f3a9.png)
And second:
![3](https://user-images.githubusercontent.com/18574776/47104618-82487680-d24a-11e8-9527-24f0965d5523.png)

**Comment by rafaelks** [comment]
This one was fixed by #1810
