### ISSUE TITLE
[IMPROVEMENT] Language switch button

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1769]
Your Rocket.Chat.Android version: 3.0.0 Build 2047 - 0a57fbd - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.70.4

It would be nice to see the language switch button in future versions (as implemented in the React Native version).

**Comment by rafaelks** [comment]
Duplicates #747
