### ISSUE TITLE
Close chatRoomFragment when I am attaching a file ?

### ISSUE THREAD

**Issue by sealiasheq** [RocketChat/Rocket.Chat.Android#1774]
When I use from attach file in `ChatRoomFragment` for upload a video,Image... it redirect me to Recent for select a video,image or ... but for example when I select a video, close `chatRoomFragment` and redirect me to `chatRoomsFragment` and I can't upload for example a video and I should try again for upload.(For upload a video I try this way several times)

What can I do?

**Comment by rafaelks** [comment]
I didn't understand the problem... can you send us more detailed information or a video/GIF?
