### ISSUE TITLE
[BUG] Line breaks "\n" are ignored on mobile device

### ISSUE THREAD

**Issue by Breee** [RocketChat/Rocket.Chat.Android#1781]
## Description

Line breaks "\n" are ignored on my mobile device, when sending a message using the RestAPI.
In the desktop-webapp and the mobile-webapp messages are shown correctly.

## Devices and Versions

Rocket.Chat.Android version: 3.0.0
Rocket.Chat Server version: 0.70.1

Mobile device model and OS version: One plus 6, Oxygen 9 (Android 9)

## Steps to reproduce

Just post a message with linebreaks "\n",
either in the app directly or using a curl calling the api.

**Comment by localguru** [comment]
Possibly a duplicate of #1707

**Comment by leonardoaramaki** [comment]
It's not actually a bug as we all thought at first. The thing is, the library we use to parse markdown follows strictly the specs. 
Please, take a look at [https://github.com/noties/Markwon/issues/54](https://github.com/noties/Markwon/issues/54).
