### ISSUE TITLE
Custom Emojis not displaying in Android at all 

### ISSUE THREAD

**Issue by real19** [RocketChat/Rocket.Chat.Android#1785]
## Description

I have over 800 custom emojis on my server. And Rocket Chat Android app doesn't display any of them. 

Can we please try to figure out why that is the case? 

Thanks
Suleman. 

## Devices and Versions

Google Pixel
Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by real19** [comment]
I am getting the exception: 

chat.rocket.common.RocketChatInvalidResponseException: Expected a string but was BEGIN_OBJECT at path $.emojis[9]._id(url='https://www.thepen.chat/api/v1/emoji-custom')

**Comment by leonardoaramaki** [comment]
It looks like some of your custom emojis are returning with the `_id` property as an object. Checked and got `"_id": {"_str":"5bc429276e3a9221cee9fb03"}` when it should have been `"_id": "5bc429276e3a9221cee9fb03"`. Have you changed something on the backend side of your instance? I'm investigating this issue within our backend.

**Comment by real19** [comment]
I didn't change anything in the backend. But I used the following script to upload custom emojis: 

https://github.com/amtypaldos/rocketchat-emoji-upload

**Comment by leonardoaramaki** [comment]
@real19 I'm closing this since it was disclosed that the bug was on the aforementioned script. 
Feel free to reopen the issue if you feel there's something else we can do on our side.

**Comment by real19** [comment]
Thanks @leonardoaramaki for looking into the issue. I have fixed the emoji id data and it's working for me now :)
