### ISSUE TITLE
[BUG] Custom Oauth initially does not fetch the username on the client

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/Rocket.Chat.Android#1791]
## Description
eric.rosenthal 11:07 AM
I'm testing the Custom Oauth crash fix. I can confirm that it does not crash anymore, but I am seeing a new issue. After logging in with my custom Oauth, I am asked for a RC username (as expected). But when first logged in as that user, the profile page in android client never populates the username. For example "val myselfUsername = userHelper.username()" returns null in this case. Is anybody else seeing this?

rafael.kellermann Rocket.Chat Team 11:09 AM
@eric.rosenthal If you close the app and open again, does it show it to you?

eric.rosenthal 11:16 AM
yes it does

@eric.rosenthal Gotcha, maybe the app needs to force a `/me` request over there. (cc @filipe.brito)

**Comment by ear-dev** [comment]
@rafaelks Do you have any thoughts about how to fix this?  Maybe point me in the right direction?  

I can see where presenter.loadCurrentInfo() get's called in the MainActivity.kt file, and I'm sort of assuming that's where the username gets populated in the local repository.   I just don't understand why after logging in with customOauth that the username info is not available.  

Thanks.

**Comment by rafaelks** [comment]
@ear-dev I think we can force a `/me` request on the profile screen or after user authenticates in the app. 🤔

**Comment by jaytat0** [comment]
A bounty has been opened for this: https://www.bountysource.com/issues/65139855-bug-custom-oauth-initially-does-not-fetch-the-username-on-the-client

**Comment by ear-dev** [comment]
@filipedelimabrito does your latest note here indicate that you are currently working on this?
