### ISSUE TITLE
[NEW] Let user to see who "reacted" each reaction

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Android#1792]
## Description

Authors of "reactions" are not visible.

## Devices and Versions

Your Rocket.Chat.Android version: 3.0.0.
Your Rocket.Chat Server version: 0.69.2 and 0.71.0-rc.0 (open.rocket.chat)

Mobile device model and OS version: BQ Aquaris X5 Plus and Android 7.1.1

## Steps to reproduce

In the Android version there is no way to see the authors of reactions. This could be listed under e.g. _Message-Info_.

**Electron client:**

![reaction_electron](https://user-images.githubusercontent.com/8544984/47370784-c1f9dd00-d6e6-11e8-870c-c8cb7523b0a2.png)

**Comment by hfeky** [comment]
You long click on the reaction to view who reacted. @filipedelimabrito This is already implemented. It can be closed.

**Comment by philipbrito** [comment]
Thanks for keeping us informed @HusseinElFeky 💯 ! Closing this one!
