### ISSUE TITLE
[Bug] Data security - level-aware logging of user data

### ISSUE THREAD

**Issue by mrsimpson** [RocketChat/Rocket.Chat.Android#1797]
## Description

A user of the Rocket.Chat-App recently published a system-log in order to analyze defects in another app. Doing this, he published also the Rocket.Chat.Android-App which contained usernames and presence information.

## Devices and Versions

I can't seriously tell which version he was using back then, it was on June 22, our server version back then was 0.65.

## Steps to reproduce

Start the app, log in, check other user's presence. Now check Logcat.

## Expectation

Unless the log-level is not increased to `debug`, there should not be any data of the app logged.

## Logs
Some (now anonymized) samples (replaced the relevant content with `<..>`)

```
06-22 14:39:24.600 14187 14286 D null    : SDK(https://<our URL>): Received text message: {"msg":"added","collection":"users","id":"<GUID>","fields":{"emails":[{"address":"<here's an email-address>","verified":true}],"username":"<username>"}}, channel: RendezvousChannel@379a391{ReceiveQueued}
```
```
06-22 14:39:24.816 14187 14286 D null    : SDK(https://<our URL>): Received text message: {"msg":"added","collection":"users","id":"<GUID>","fields":{"name":"<name removed>","status":"online","username":"<username removed>","utcOffset":2}}, channel: RendezvousChannel@379a391{SendQueued,queueSize=18}
06-22 14:39:24.817 14187 24449 D null    : Got update of active user stream for the user: User(id=<GUID>, username=<username removed>, name=<name removed>, status=online, utcOffset=2.0, emails=null, roles=null)
06-22 14:39:24.818 14187 24449 D null    : active User: User(id=<GUID>, username=<username removed>, name=<name removed>, status=online, utcOffset=2.0, emails=null, roles=null)
```

**Comment by mrsimpson** [comment]
@RocketChat/android I don't know about the log level on Android or how it was set. If you confirm that userdata is only logged on `debug`, I'm more than fine ;)

**Comment by rafaelks** [comment]
@mrsimpson Thanks for the report! We'll be investigating it ASAP!
