### ISSUE TITLE
 Type mismatch: inferred type is DrawingActivity but LifecycleOwner was expected

### ISSUE THREAD

**Issue by samk17cmutpm** [RocketChat/Rocket.Chat.Android#1800]
<img width="1441" alt="screen shot 2018-10-26 at 1 58 23 pm" src="https://user-images.githubusercontent.com/7029528/47549791-56eb1900-d927-11e8-8db8-6fee44ccbe98.png">
Could some one help me out of this. I tried to build but I does not work

**Comment by rafaelks** [comment]
Please use our Community Support for this kind of error: https://forums.rocket.chat/c/community-support.
