### ISSUE TITLE
CAS login with version 3.0.0

### ISSUE THREAD

**Issue by AmShaegar13** [RocketChat/Rocket.Chat.Android#1802]
## Description

When trying to login using CAS in version 3.0.0 I cannot find a way to do so anymore. Our company instance does not allow login with username/password.

## Devices and Versions

Your Rocket.Chat.Android version: 3.0.0
Your Rocket.Chat Server version: 0.70.4

## Steps to reproduce

1. Click *Connect with a server*
2. Enter server that supports CAS and click *Connect*
3. There is only a button to *Login with e-mail*

**Comment by rafaelks** [comment]
@AmShaegar13 @filipedelimabrito will be investigating the issue. Would you be able to share you server URL in private with us? (rafael.kellermann at rocket.chat)

**Comment by rafaelks** [comment]
@AmShaegar13 Next release will have a fix for CAS, but in order to hide the "email" authentication you will need to set the setting "Show Login Form" to false. 👍

**Comment by AmShaegar13** [comment]
Awesome, thanks! And thanks for the reminder. We used to have a local admin account for changing settings. Thus the hidden login form. But we created a dedicated CAS account for this now. Will make things easier.

**Comment by rafaelks** [comment]
This one was closed by #1817
