### ISSUE TITLE
[INVESTIGATE] "Missing credentials for this server" 

### ISSUE THREAD

**Issue by rocapp** [RocketChat/Rocket.Chat.Android#1804]
I just set my server up with SSL, and it was working fine for everyone. Now, I can't log in via the Android app. I can still log in via the browser on all my devices. 

No one else on the server is experiencing this issue.

When I enter the server address on the app, it says "missing credentials for this server." And it never progresses to the actual login page.

I'm on a Google Pixel 2 using Android 9.

Please let me know if you need any other details.

Thanks!

**Comment by rafaelks** [comment]
@rocapp Can you share you server URL with us? If you want to share in private, send me an email at `rafaelkellermann at rocket dot chat`.

**Comment by rocapp** [comment]
@rafaelks I tried sending you an email but got an address not found error in response

**Comment by rocapp** [comment]
@rafaelks I sent you an email a while ago... any progress?

**Comment by rafaelks** [comment]
@rocapp Can you send it again?

**Comment by rocapp** [comment]
@rafaelks Sent

**Comment by rafaelks** [comment]
@rocapp I was able to connect to his server using both iOS and Android app. Please make sure that you have the latest version of the Android app running. Can you share the version you're using?

**Comment by rocapp** [comment]
V3.1.1
Android version 9

**Comment by rocapp** [comment]
Well I just fixed it... I had tried this before without success, but I just
cleared the cache and can now log in from the app.
Thanks for checking into it!

**Comment by rafaelks** [comment]
Great! Closing the issue! 👍

**Comment by ThierryMallard** [comment]
Greetings there. Possibly having the same issue : installed http://rocket.inga.tech/ (will move to HTTPS soon). Works fine on Web, but the Android app just asks for the URL of our server and said « Missing credentiels », but never asked for the login / password. Somehow it did happen correctly at some point (I remember having used the android app), but something prevents it from working.
