### ISSUE TITLE
[BUG] Can't play MP3

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.Android#1807]
## Description

Uploaded MP3 file.
Icon is large black square with triangle play button.
Clicking play brings up standard menu list but does not play.
First saw this on my own instance 0.70.4 but saw another user post the same on open.rocket.chat.
Tested again myself on open.rocket.chat to confirm.

## Devices and Versions

Your Rocket.Chat.Android version: 3.0.0 Build 2048 65de72ff - play
Your Rocket.Chat Server version: (e.g. 0.70.4 & tested on open.rocket.chat)

Fails on - no other device to test with:
Mobile device model and OS version: Samsung S6 Android 7

![screenshot_20181029-105038](https://user-images.githubusercontent.com/3800384/47642752-bf293d00-db69-11e8-8cdc-5b2f34e86124.png)

![screenshot_20181029-105046](https://user-images.githubusercontent.com/3800384/47642760-c2bcc400-db69-11e8-8063-9af0eb040054.png)

**Comment by luciofm** [comment]
Tested with several mp3 files, and all working fine...
@reetp can you provide a sample file that is not working?

**Comment by rafaelks** [comment]
Closing this because there was no reply here, let's reopen if needed. 👍
