### ISSUE TITLE
Unable to get notifications to work. 

### ISSUE THREAD

**Issue by Think2grow** [RocketChat/Rocket.Chat.Android#1811]
## Description

Unable to get notification badges to show on android devices for @mention and direct notifications

## Devices and Versions

Your Rocket.Chat.Android version: react-native 9f9a9b71a4
Your Rocket.Chat Server version: 0.70.4

Mobile device model and OS version: Samsung Galaxy S9+ 

I'm nearly certain I'm missing settings within rocket chat to make this work correctly. Everything I've tried to get the notification badge to show for direct messages and @mentions is not working thus far.

**Comment by rafaelks** [comment]
@Think2grow You don't receive the notifications? Or you don't see a badge number?

**Comment by samk17cmutpm** [comment]
Hi @rafaelks 
I check the code and see the log 
But I can not find with method sending firebase token to server.
I config firebase, and using firebase console to send to notification. every thing works fine
But when I go to administrator to update api key and project number, then I restart every thing again. Still not working
I check the log 
<img width="1831" alt="screen shot 2018-11-01 at 9 03 39 am" src="https://user-images.githubusercontent.com/7029528/47828363-56360500-ddb5-11e8-9e4f-8981bef98371.png">
I see that there is no method to send to token to sever..
Please help me to find where sending token to server

**Comment by rafaelks** [comment]
Please use our Community Support for this kind of problem: https://forums.rocket.chat/c/community-support.
