### ISSUE TITLE
[INVESTIGATE] App hang during message input

### ISSUE THREAD

**Issue by mschmitzer** [RocketChat/Rocket.Chat.Android#1813]
## Description

App slows down and eventually hangs completely while entering a non-trivial amount of text in the message input box.

## Devices and Versions

Your Rocket.Chat.Android version: 3.0.0 Build 2048 65de72ff - play
Your Rocket.Chat Server version: 0.69.2

Mobile device model and OS version: Nexus 5x - Android 8.1.0

## Steps to reproduce

Write a slightly larger (multiple sentences) message in the input Box in a group chat. Use a small amount of markup (\*bold\*). Text input becomes gradually slower, eventually the app hangs completely. "App is not responding" system dialog appears.

## Logs

N/A

**Comment by rafaelks** [comment]
@MarcSchmitzer Is this always reproducible? We're trying with a very long text here, bold and mentions and the app is not getting slow. 🤔

**Comment by luciofm** [comment]
@MarcSchmitzer could you provide some sample inputs that are causing the problem for you?

**Comment by mschmitzer** [comment]
Sorry for not responding. I can't provide the exact inputs, but there's a pattern that might be relevant:

The occasions where this happened was when I tried to write my "daily" report, which has the pattern (albeit in German):
```
*Yesterday:* ...
*Today:* ...
```
So there's some markup with colons mixed in. As I said, the "..." stands for a non-trivial amount of text, multiple sentences. 

The other thing is that this always happened on the train, so with a potentially flaky internet connection.

Thanks for looking into this.

**Comment by nemhods** [comment]
I am seeing this aswell on RC App 3.1.1, Server 0.70.0, Oneplus 3 running LineageOS.
I did not get the app to crash though. It seems like the markup really compounds the issue. i can type long messages with emojis and pure text without problems.

**Comment by nemhods** [comment]
We are getting more reports of this.
Some users are able to type long messages, others can't even type two paragraphs.
A heavily affected user runs a ZTE-Smartphone with Android 5.0.2. We have meanwhile updated to RC 0.72.0.

**Comment by rafaelks** [comment]
@luciofm We identified the problem here... it's being caused after you type `:` and start typing other things... something is still being processed, probably related to the autocomplete.

We'll be working on a fix for this ASAP. 👍

**Comment by rafaelks** [comment]
Bug is fixed and will be included in our next beta already, please make sure to help us testing it! 👌
