### ISSUE TITLE
error: State is not public in kotlin.collections; cannot be accessed from outside package

### ISSUE THREAD

**Issue by cvxus** [RocketChat/Rocket.Chat.Android#1815]
Hi, people already reported about this issue before. But there no reasonable answers till this time. And the error quit strange during the project compilation 'from the box' - reference to private declaration inside standard Kotlin library. Any ideas?

 /android/rocketchat/App/app/build/tmp/kapt3/stubs/fossDebug/chat/rocket/android/server/infraestructure/ConnectionManager.java:9: error: State is not public in kotlin.collections; cannot be accessed from outside package private final java.util.concurrent.CopyOnWriteArrayList<kotlinx.coroutines.experimental.channels.Channel<kotlin.collections.State>> statusChannelList = null;

**Comment by rafaelks** [comment]
Please use our Community Support for this kind of error: https://forums.rocket.chat/c/community-support.
