### ISSUE TITLE
[Notification] When user login, the application doesn't send fcm token to server

### ISSUE THREAD

**Issue by samk17cmutpm** [RocketChat/Rocket.Chat.Android#1818]
## Description
I clone the latest code on tag V3.0.0
I also config firebase for it and sending pushing notification from firebase console, everything works fine.
But when I config push on administrator. add api key, project number. then restart server
But when I close the app, try to send message by mention but no notification

And I check the log from server, The server cannot find the fcm token for my user. So It can not send the notification
But the ios can

## Devices and Versions
Your Rocket.Chat.Android version: (3.0.0)
Your Rocket.Chat Server version: (0.72)
Mobile device model and OS version: (e.g. "Sam Sung Galaxy s8+  - Android 7.0.1")

**Comment by HardwareToWebWizard** [comment]
Did you get this to work ?
