### ISSUE TITLE
[NEW] Add "License" and "Contact Us" to Settings screen

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1823]
- License: should open this URL: https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/LICENSE
- Support: should open the email form to `support@rocket.chat` with the device and app information (Android version, app version, device name, etc);

**Comment by GOVINDDIXIT** [comment]
@rafaelks I would like to work on this issue

**Comment by localguru** [comment]
@rafaelks How about using the e-mail address of "global_from" for the support e-mail address? So the local support of the own Rocket.Chat could be used first or a mix of both (local and official RC support).

**Comment by GOVINDDIXIT** [comment]
@rafaelks I m facing a little problem while configuring the project in my window machine. I had also read some issues already asked but they are not helpful to me. Is there any way we can generate the required jar files by kotlin sdk in windows
