### ISSUE TITLE
[BUG] Notifications with replies are not rendered properly

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.Android#1826]
## Description
Notifications with replies are showing url to message, which is redundant there.

## Devices and Versions

Your Rocket.Chat.Android version: 3.0.0
Your Rocket.Chat Server version: 0.71.0
Mobile device model and OS version: Xiaomi Mi 5 - Android 8.1

## Steps to reproduce
1. Send a reply message to the user
2. User receives
![image](https://user-images.githubusercontent.com/1567272/47923292-53243d00-deb9-11e8-9d73-0e354d9ab70b.png)

**Comment by rafaelks** [comment]
This was already requested here in our core project: https://github.com/RocketChat/Rocket.Chat/issues/9979.
