### ISSUE TITLE
[NEW] missing logo and layout content on login screen

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Android#1827]
## Description

On the login screen the logo is missing and references to information from `Layout/Content` like `Login Terms`.

The content of the field `Login Terms` should be displayed on the login page in order to comply with legal obligations.

## Devices and Versions

Your Rocket.Chat.Android version: 3.1.0.
Your Rocket.Chat Server version: 0.69.2 and 0.72.0-develop (open.rocket.chat)

Mobile device model and OS version: BQ Aquaris X5 Plus and Android 7.1.1

## Steps to reproduce

Connect to a server and go to login screen.

![screenshot_20181102-090104](https://user-images.githubusercontent.com/8544984/47940298-8501c780-deea-11e8-8239-5ec77fd8c260.png)

**Browser login screen:**

![browser](https://user-images.githubusercontent.com/8544984/47940319-934fe380-deea-11e8-9fbf-c52bed07feb8.png)

**Comment by rafaelks** [comment]
Login terms are present in the "..." button. We don't plan to add the logo to this screen right now (because it takes too much space). Thank you!

**Comment by localguru** [comment]
> Login terms are present in the "..." button. We don't plan to add the logo to this screen right now (because it takes too much space). Thank you!

Ah, didn't get that with the "..." button. Thanks.
