### ISSUE TITLE
[NEW] Add rate the app in playstore feature to setting screen

### ISSUE THREAD

**Issue by GOVINDDIXIT** [RocketChat/Rocket.Chat.Android#1831]
## Description
There must be a feature to rate the app on play store inside the setting screen
This feature will surely improve the app ratings at playstore as many user having good experience with the app are too lazy to rate app manually.

## Devices and Versions
Your Rocket.Chat.Android version: 3.1.0 Build 2049 - 60b39dad-play

**Would you like to work on the issue?**
- Yes

**Comment by FaizanZahid** [comment]
i fully support this feature.

**Comment by rafaelks** [comment]
Sounds good to me! 👍

**Comment by FaizanZahid** [comment]
nice work guys
