### ISSUE TITLE
[NEW] Add share the app feature to share the Google Play link in other apps

### ISSUE THREAD

**Issue by GOVINDDIXIT** [RocketChat/Rocket.Chat.Android#1839]
## Description
Currently there is no way available to share the app. Add  feature to share the app by all possible ways available to phone.

## Devices and Versions
Your Rocket.Chat.Android version: 3.1.0 Build 2049 - 60b39dad-play

**Would you like to work on the issue?**
- Yes

**Comment by rafaelks** [comment]
Duplicates #98.

**Comment by GOVINDDIXIT** [comment]
The feature was intended to  share the chat app to other phones by means of sharing using facebook, whatsapp, gmail and other sharing apps

**Comment by rafaelks** [comment]
@GOVINDDIXIT Share what exactly?

**Comment by GOVINDDIXIT** [comment]
I mean one person can share this app to his friends by sharing the links through whatsapp or facebook or any other sharing app like shareit or xender

**Comment by rafaelks** [comment]
@GOVINDDIXIT Gotcha, you mean like an option in "Settings" to "Share this App with my friends" and then opening an intent with the Google Play URL?

**Comment by GOVINDDIXIT** [comment]
Exactly 😃

**Comment by rafaelks** [comment]
@GOVINDDIXIT Gotcha, reopened it.

**Comment by GOVINDDIXIT** [comment]
Also I will add sharing the app apk through xender and Shareit which will directly share the app to near friends using hotspot
