### ISSUE TITLE
[NEW] Remove `@` from mentions on the text of the message

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#1846]
In order to support Federation, Rocket.Chat internally decided that removing `@` from mentions in the message is a good solution.

In summary, the changes are:

1. In order to mention someone, `@all` or `@here` you keep using `@`;
2. When the clients display the mention, the `@` is removed from the text;

**Comment by akinadude** [comment]
Hey guys!
In release 3.1.1 mentions aren't highlighted. Is such behavior expectable?

**Comment by rafaelks** [comment]
@akinadude Can you send us some screenshot?

**Comment by akinadude** [comment]
Of course! Here is it.
![screenshot_20181211-112034](https://user-images.githubusercontent.com/2254944/49787152-0a249b80-fd37-11e8-88fd-1f4d5fff6ca9.png)

Mentions looks like a plain text.

**Comment by Adizbek** [comment]
I opened PR #2241, and here is demo: https://www.youtube.com/watch?v=L2pbFxk8Eys
Is that works as intended?
