### ISSUE TITLE
App does not recognize client certificates

### ISSUE THREAD

**Issue by pombaer** [RocketChat/Rocket.Chat.Android#1851]
## Description

I have some sort of 2 factor authentication for RocketChat. I am using client certificates in my Webserver which is configured as Reverse proxy to Rocketchat. This works in Chrome and Firefox but breaks the RocketChat app.

## Devices and Versions

Android version: 3.0.0 (latest on f-droid)
Rocket.Chat Server version: 0.71.1 (docker image)

Android 5.0.1

## Steps to reproduce

If using NGINX as reverse proxy add configuration:

1. Create self singed certificates 
2. Change NGINX configuration
`
    ssl_client_certificate /etc/nginx/ssl/private_ca.cert;
    ssl_verify_client on;
`
3. Install client certificate on mobile device
4. Try to access Rocketchat with Webbrowser, if this works try to access Rocketchat with the App.

## Logs

The App reports:

`
400 Bd Request
No required SSL certificate was sent
nginx/1.14.0(Ubuntu)
`

This is a standard error page from NGINX and is directly displayed in the Rocketchat app.

**Comment by localguru** [comment]
I would open a feature request so that there is the possibility to deposit client certificates. This would also affect the Electron and iOS client.

https://forums.rocket.chat/c/feature-requests

**Comment by reetp** [comment]
@pombaer this is not a support forum.

If you have an error with Rocketchat then file a bug but first make sure it really is an error with Rocketchat itself. Read, ask questions in forums, and if they advise you then open an Issue.
Thank you.

**Comment by reetp** [comment]
[Ed I can't close this. Can someone else]

@rocket-cat close
Closing as a support issue and notabug.
