### ISSUE TITLE
Android Mobile App Authenticates, but Doesn't Show Rooms

### ISSUE THREAD

**Issue by jasonsumner-zz** [RocketChat/Rocket.Chat.Android#1856]
## Description

When using the Android Mobile App, I can authenticate, but I cannot see the contents of any rooms. I can search users and rooms, but when selecting I get nothing. Web and desktop clients work.

Latest snap version hosted with Caddy serving it on 3000 on a private IP. Hosted on vcloud where snat and dnat is setup to translate 80 to 3000 on a routable IP. Additional the organization I'm hosting with offers a Web Application Firewall that serves the application on a secured URL with a different IP.

## Devices and Versions

Server version: 0.71.1 (Snap)
Android App: 3.1.1
Device: Google Pixel with Android 9

Merge pull request #12499 from RocketChat/release-0.71.1

## Steps to reproduce

Install Android app, login. 

Clear app cache and storage, open app again, login.

All attempts authenticate user, can hit admin panel, but cannot access rooms. Just shows connecting.

## Logs

Can't appear to bring up on my phone. Can provide later when I go into work.

**Comment by rafaelks** [comment]
@jasonsumner Do you have WebSockets enabled on your server?

**Comment by jasonsumner-zz** [comment]
Sorry for my ignorance, is that a server setting under the admin panel or a config entry for caddy?

**Comment by rafaelks** [comment]
@jasonsumner This is basically if your server supports real-time connection. Can you share the URL of your server? Then I can check for you.

**Comment by jasonsumner-zz** [comment]
For privacy purposes, I'd like to not share. Can you provide a sample request you would do to test it? 

I can browse to https://REDACTED/websocket and I get an error, "Not a valid websocket request".

**Comment by rafaelks** [comment]
@jasonsumner Yes, so your server is not supporting WebSockets. It needs to support in order to use the mobile apps, more info here: https://github.com/RocketChat/Rocket.Chat.Android/issues/1116

**Comment by jasonsumner-zz** [comment]
I can use a websocket client and connect, I immediately get a server id back. Client reports it is open.

**Comment by rafaelks** [comment]
@jasonsumner Do you have any more information? Screenshots, logs?

**Comment by jasonsumner-zz** [comment]
I have additional information, and this may not be the section for this, but hoping you can send me in the right direction. 

Again I have rocket chat listening on 80. My organization offers a reverse proxy that adds ssl from their ca. I have added the certs to Android and the website is trusted, but when connecting from a websocket client I get the following error. 

"""Error: Failed to connect to WEBSITE URL port 80 from Port 4851"""

That leads me to believe that there is something wrong with my caddy config, and the server is responding with the URL at 80 and not 443.

**Comment by rafaelks** [comment]
I believe there's something wrong in your setup as well... not sure how I can help you here. On the web it works fine?

**Comment by jasonsumner-zz** [comment]
Yes, web and desktop app works.

**Comment by rafaelks** [comment]
@jasonsumner Web & Desktop works without WebSocket.

**Comment by jasonsumner-zz** [comment]
It appears to be a certificate issue. Using a websocket client connecting to wss://website/websocket with the connect message documentee I get an error stating ”java.security.cert.CertPathValidationException: Trust anchor for certofication path not found."

I am using a certificate issued to me by our corporate enterprise CA. I have the root CA, intermediate CA, and website certificate installed on my device. Chrome authenticates properly.

**Comment by rafaelks** [comment]
@jasonsumner If the root CA is installed **and** trusted on your device, it should work (I saw other people doing that). Can you double-check?
