### ISSUE TITLE
Error Installing Kotlin SDK

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat.Android#1857]
## Description

I am attempting to install the Kotlin SDK by running the command: `./build-sdk.sh`, but am getting the error: `Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory()`...

## Logs

FAILURE: Build failed with an exception.

What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

**Comment by GOVINDDIXIT** [comment]
@TannerJuby1  Are you properly following the installation guide given  in readme. I think it is enough to setup the project.

**Comment by TannerJuby1** [comment]
@GOVINDDIXIT Yes I did.. I have forked versions and it builds find on my older machine, but not on the new one. After further inspection, it's a permissions occurring on lines 97 and 98:

    cd "${SDK_DIR}" && ./gradlew common:assemble && cd "${CURRENT_DIR}"
    cd "${SDK_DIR}" && ./gradlew core:assemble && cd "${CURRENT_DIR}"

This is a Gradle issue, not script issue.

**Comment by ear-dev** [comment]
How was this resolved?
