### ISSUE TITLE
Use JsonReader.setLenient(true) to accept malformed JSON at path$ on sending a picture

### ISSUE THREAD

**Issue by fadanner** [RocketChat/Rocket.Chat.Android#1862]
## Description

When i try to send a picture the error message appears and the image isn't uploaded.

## Devices and Versions
Your Rocket.Chat.Android version: 3.1.1
Your Rocket.Chat Server version: 0.71.1 (snap)

Mobile device model and OS version: Xiaomi Mi5s (Android 7.0)

## Steps to reproduce
1. Login to RocketChat
2. Open a channel to write (or direct message)
3. Click plus sign right of message
4. Click "Files"
5. Select a file 
6. Click "Send"

**Comment by fadanner** [comment]
Tested with another android smartphone. Picture upload is NOT working there, too.
Your Rocket.Chat.Android version: 3.1.1
Your Rocket.Chat Server version: 0.71.1 (snap)

Mobile device model and OS version: Samsung S5 (SM-G900F) Android 6.0.1

The bug is very annoying for us because user acceptance is decreasing so much. we are currently in a chat rollout.
If needed i can create a user for debugging, or send logfiles.

**Comment by rafaelks** [comment]
@fadanner I think you're hitting a limitation on the Nginx `client_max_body_size`. Take a look here: https://github.com/RocketChat/Rocket.Chat.iOS/issues/2184#issuecomment-423517754.

Can you try this and let us know please?

**Comment by fadanner** [comment]
@rafaelks Thanks for the suggestion.  Problem is solved.
Now it works very well.
+1 to adjust the documentation https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/ to mention `client_max_body_size`

**Comment by rafaelks** [comment]
Amazing @fadanner!
