### ISSUE TITLE
Type mismatch: inferred type is DrawingActivity but LifecycleOwner was expected

### ISSUE THREAD

**Issue by Prachidighe** [RocketChat/Rocket.Chat.Android#1868]
Please help in resolving this issue.

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

<img width="1322" alt="screen shot 2018-11-24 at 8 13 13 pm" src="https://user-images.githubusercontent.com/7402561/48969498-6f814880-f025-11e8-9a88-de77b072c97c.png">

**Comment by Inouju** [comment]
Try removing the dollar sign ($) in front of `activity` on line 21

**Comment by Prachidighe** [comment]
@Inouju Thanks for the reply. 
But still getting the same error.
<img width="1131" alt="screen shot 2018-11-25 at 8 31 51 am" src="https://user-images.githubusercontent.com/7402561/48974980-b48c9580-f08c-11e8-911b-6a5f75b9dc9c.png">

**Comment by Inouju** [comment]
I would suggest re-cloning the repo, or resetting and then pulling.

For more support, and for questions like this in the future, please use the forums:
> Please use our Community Support for this kind of problem: https://forums.rocket.chat/c/community-support
