### ISSUE TITLE
incoming and outgoing message should be distinct

### ISSUE THREAD

**Issue by 4nku5h** [RocketChat/Rocket.Chat.Android#1883]
![img_20181129_224525](https://user-images.githubusercontent.com/33266550/49239561-10f30a80-f429-11e8-9865-1013a8072f49.jpg)
incomming message should be at left side and out going message should be at right side.

**Comment by rafaelks** [comment]
This is not expected and it's not how Rocket.Chat works, thanks for the suggestion but we don't plan to make the change right now! 👍
