### ISSUE TITLE
Change password Should need old password

### ISSUE THREAD

**Issue by 4nku5h** [RocketChat/Rocket.Chat.Android#1884]
Current behaviour:
user can change password even if he didn't know the old password.

Expected Behaviour:
to change password old password is needed.
and app should have 1 more edittext on change password activity for old password verification.
![screenshot_2018-11-29-23-00-25-802_chat rocket android](https://user-images.githubusercontent.com/33266550/49240161-95925880-f42a-11e8-8118-50b0fa27b8b2.png)

**Comment by rafaelks** [comment]
This is not how the API works right now, but thanks for the suggestion! 👍

**Comment by 4nku5h** [comment]
> This is not how the API works right now, but thanks for the suggestion! 👍

oh!, but for now (for security purpose). this feature also can be implemented using Shared Preferences..On first Login we can store password in shared preferences and verify password when user wants to change. and update it after user changed it.
