### ISSUE TITLE
Message sending button disappears

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1892]
Your Rocket.Chat.Android version: 3.2.0 Build 2051 - e51c8da7 - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.71.1

When you type a message and someone sends a message to the channel, message sending button disappears.

![img_20181201_183046](https://user-images.githubusercontent.com/18574776/49329902-6fd69200-f597-11e8-9f05-e3269b8bb12e.jpg)

**Comment by ankush-01** [comment]
is this your private channel??

**Comment by Pitstopper** [comment]
@ankush-01 It's not a private channel. This is main channel.

**Comment by 4nku5h** [comment]
> @ankush-01 It's not a private channel. This is main channel.

okay. i want to work on this issue

**Comment by 4nku5h** [comment]
> @ankush-01 It's not a private channel. This is main channel.

but it dosn't happen

**Comment by tezukzai** [comment]
I am getting the same issue on private messages,

**Comment by gyverchang** [comment]
Getting this issue as well, it's a huge breaker as we have to retype the whole message for the send button to appear. Had to temporarily use the web version as the Experimental version is also unusable.
