### ISSUE TITLE
Logon required after restart

### ISSUE THREAD

**Issue by michaelknigge** [RocketChat/Rocket.Chat.Android#1893]
## Description

When using other chat clients, they usually store the server information and signon information, so on a restart of the application, the user don't has to enter this information again. The Rocket-Chat clients asks me every time I restart it for my server address and my user credetials. This is quite annoying and it would be great if Rocket.Chat would "auto-login" on restart.

## Devices and Versions

Your Rocket.Chat.Android version: 3.1.1
Your Rocket.Chat Server version: 0.71.1

Moto G4, Android 7.0

**Comment by Marwe** [comment]
Usually credentials are saved. But I also often have to login, too. Right now I saw an error message, then server and login credentials habe to be given again.

**Comment by diegolmello** [comment]
3.1.1 is a really old version and this repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

New repo is https://github.com/RocketChat/Rocket.Chat.ReactNative/
