### ISSUE TITLE
No "Share" (i. e. in gallery) on Android

### ISSUE THREAD

**Issue by michaelknigge** [RocketChat/Rocket.Chat.Android#1895]
## Description

On the Galery I can "share" the shown image with some applications (like HipChat, Slack, Threema etc.). It would be great if images (or whatever) can also be "shared" with Rocket.Chat.

## Devices and Versions

Your Rocket.Chat.Android version: 3.1.1
Your Rocket.Chat Server version: 0.71.1

Moto G4, Android 7.0

**Comment by Akronix** [comment]
Also links or text from other apps like Firefox should have Rocketchat in their sharing options.

**Comment by lorek123** [comment]
duplicate of #98

**Comment by philipbrito** [comment]
As @lorek123 have pointed out this is a duplicate of #98.
