### ISSUE TITLE
Gradle Sync and Build Failing

### ISSUE THREAD

**Issue by ubarsaiyan** [RocketChat/Rocket.Chat.Android#1897]
## Description
I am unable to build the latest `develop` commit 9972928. 
I am using Android Studio 3.3 RC1. 

## Steps to reproduce
Clone the Rocket.Chat.Android repo and Kotlin SDK in the same directory.
Open AS. 
AS starts syncing the gradle files. After some time, it "strongly recommends" updating the gradle plugins.
```
To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you update the Android Gradle plugin to version 3.3.0-rc01 and Gradle to version 4.10.1.
```
Update the above.
After this the gradle sync fails with the following error.
```
ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
root project 'Rocket.Chat.Android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
Affected Modules: app

WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: app
```
Updating the `kotlin: 1.2.71` in `dependencies.gradle` solves the Gradle sync issue but then the build fails due to some incompatible coroutine version, I think. I am not much experienced with Android so maybe I am doing something wrong.

**Comment by srchit** [comment]
Any update on this?

**Comment by ubarsaiyan** [comment]
@srchit Go to File>Project Structure>Project and change the Android gradle version to 3.2.1 from 3.3 RC alpha.

**Comment by philipbrito** [comment]
Please remember to close an issue when finding the solution.

**Comment by ubarsaiyan** [comment]
@filipedelimabrito it was not a complete solution, hence, I didn't close the issue. It would be great if first time developers won't have to manually change the Android Gradle Version. :)
