### ISSUE TITLE
Add Detailed Readme file for the project

### ISSUE THREAD

**Issue by sujaysudheenda** [RocketChat/Rocket.Chat.Android#19]
As a new developer who is willing to contribute to the project, it would of great help if we have a readme which would guide them on how to bootstrap the project on their local machine and all the information that would help them with the app development (like dependencies, libraries need to be pulled in, compatibility, setting up the development environment etc).

**Comment by YusukeIwaki** [comment]
Sorry for inconvenience.
I added some commands instructions to README.md.

@sujaysudheenda Could you try with the new README.md? If you have some trouble with building Lily project, let me know :)  I will modify it.
Thank you!

**Comment by sujaysudheenda** [comment]
Hi @YusukeIwaki thank you for taking it up! I appreciate the effort! one thing that I had to do after all the steps mentioned in readme is to comment [this line](https://github.com/RocketChat/Rocket.Chat.Android.Lily/blob/develop/app/build.gradle#L37) from app/build.gradle. can you add this to the readme file too!

**Comment by YusukeIwaki** [comment]
@sujaysudheenda Thank you for your report. I will add some description about app/build.gradle.
