### ISSUE TITLE
Markdown is not rendered in attachment texts

### ISSUE THREAD

**Issue by fleaz** [RocketChat/Rocket.Chat.Android#1900]
## Description
Hi everyone,

we use quite a few self build integrations to post messages from e.g. CI/CD or Monitoring into our customer channels via API or Webhooks. To have the ability to set the message color to quickly distinguish info/warning/error we wan't the messages to have a color which is afaik only possible when putting the message into the `attachment` field. All of this is working great.

But when we use markdown in the attachment text, it just show the raw markdown in the Android App.
This behaviour can only be observed under Android. Both iOS and the Desktop App render markdown in the attachment test as expected.

Apparently #732 only applies to the message text itself and not to message inside the attachment.

Best regards,
Felix

## Devices and Versions
Your Rocket.Chat.Android version: 3.1.1
Your Rocket.Chat Server version:  0.96.2

Mobile device model and OS version:  Andorid 8.1 on One+ 5T

## Steps to reproduce

1. Use the API or a webhook to post a message into the channel which uses the following body: ```attachments: [{"text": "**Hello World**}]```

**Comment by rafaelks** [comment]
@fleaz Thank you! I think that duplicates #1899?

**Comment by fleaz** [comment]
Yes, according to the screenshots it seems to be the same issue . I will close this issue here.

**Comment by rafaelks** [comment]
@fleaz Thank you for this detailed description of the issue! 👍
