### ISSUE TITLE
Update all strings.xml

### ISSUE THREAD

**Issue by GOVINDDIXIT** [RocketChat/Rocket.Chat.Android#1909]
## Description

Some strings.xml files are not updated and missing some new translations

**Would you like to work on the issue?**
- Yes

**Comment by Pitstopper** [comment]
Today I will complement the translation into russian

**Comment by GOVINDDIXIT** [comment]
@Pitstopper Thanks, please go for it 😃

**Comment by philipbrito** [comment]
Closes by #1910
