### ISSUE TITLE
[BUG] `Body param "roomid" or "username" is required [error-room-param-not-provided]`

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1912]
Your Rocket.Chat.Android version: 3.2.0 Build 2052 - a830e92 - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.72.1

Attempting to start a conversation with any person ends with an error message - `Body param "roomid" or "username" is required [error-room-param-not-provided]`

![video2gif_20181208_190737](https://user-images.githubusercontent.com/18574776/49688046-8774c400-fb1d-11e8-9514-b6c5b266ab88.gif)

**Comment by owengombas** [comment]
Same issue here....
