### ISSUE TITLE
[BUG] Images of avatars disappear in the user information section

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1913]
Your Rocket.Chat.Android version: 3.2.0 Build 2052 - a830e92 - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.72.1

Images of avatars disappear in the user information section. The conditions for this are not clear.

![img_20181208_192004](https://user-images.githubusercontent.com/18574776/49688129-652f7600-fb1e-11e8-85f7-df4565e8373c.jpg)

![screenshot_2018-12-08-19-19-19-900_chat rocket android](https://user-images.githubusercontent.com/18574776/49688131-6f517480-fb1e-11e8-8532-fcde0205f093.png)

**Comment by leonardoaramaki** [comment]
@Pitstopper Is your avatar an svg?

**Comment by Pitstopper** [comment]
@leonardoaramaki my avatar sync by Gravatar, but other guys in my chat have same problem and i don't know what image format they use.

**Comment by leonardoaramaki** [comment]
@Pitstopper Is this user *Alcatraz* can be found on `open` server?

**Comment by Pitstopper** [comment]
@leonardoaramaki no, i'm Pitstopper on open.rocket.chat

**Comment by leonardoaramaki** [comment]
@Pitstopper Do you also have a channel/group in your server called `Alcatraz`?

**Comment by Pitstopper** [comment]
@leonardoaramaki no, only #Main, #test and #bugs

**Comment by Pitstopper** [comment]
@leonardoaramaki I just went to open.rocket.chat, found your profile and your avatar picture has also disappeared. I used last beta.

![screenshot_20181217-202326](https://user-images.githubusercontent.com/18574776/50104035-15e1f780-023a-11e9-853c-259f1473af91.png)

**Comment by rafaelks** [comment]
@Pitstopper This one should be fixed in our next beta, let us know if not please.

**Comment by Pitstopper** [comment]
@rafaelks 3.2.0 Build 2055 - ac4ffd5 - play same problem.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18574776/50352187-839d6480-0555-11e9-8511-b2e3327d30ce.gif)
