### ISSUE TITLE
Message isn't sort in proper manner

### ISSUE THREAD

**Issue by 4nku5h** [RocketChat/Rocket.Chat.Android#1926]
Current Behaviour: Message isn't sort in proper manner.
Expected Behaviour: Message should be sort according to their time.

![gif-181213_213302](https://user-images.githubusercontent.com/33266550/49951184-5cc0ac00-ff1f-11e8-88ce-88a4a9e5b991.gif)

**Comment by antgel** [comment]
Duplicate of #1677 , suggest checking existing issues before opening new ones. (And using realistic data when reporting bugs so they're easier to understand.)

**Comment by philipbrito** [comment]
Closed by #2337
