### ISSUE TITLE
[BUG] "Cancel" and "Ok" buttons are too close to each other in some dialogs.

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1935]
Your Rocket.Chat.Android version: 3.2.0 Build 2054 - 8d932145 - play
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.72.3

In some dialogs (for example, the confirmation dialog for deleting a message), the "Cancel" and "Ok" buttons are too close to each other.

![screenshot_20181215-093059](https://user-images.githubusercontent.com/18574776/50040762-be396580-005a-11e9-96c0-b6921bb187e3.png)

**Comment by gopikaharikumar** [comment]
May I please work on this issue?

**Comment by GOVINDDIXIT** [comment]
@gopikaharikumar  This issue can be closed, solved by #1994.

**Comment by philipbrito** [comment]
It is solved already.
