### ISSUE TITLE
[NEW] Add erase feature in Drawing 

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1938]
## Description

Right now in draw the erase will clear the whole canvas. This feature will erase only the respective area where you touch.

**Comment by GOVINDDIXIT** [comment]
@divyanshub024  @filipedelimabrito  Can I work on this issue?

**Comment by divyanshub024** [comment]
@GOVINDDIXIT We are going to remove the 'draw' package and use library instead. So, there won't be any further changes in the 'draw' package.

**Comment by philipbrito** [comment]
@divyanshub024 I think that you mean that we are going to remove some classes on the `draw` package in the favour of the library using. That said, the `draw` package will continue to be live on our project - no need to remove them.

**Comment by divyanshub024** [comment]
@filipedelimabrito Is it a good idea to include `AndroidDraw` library just for few classes. Because then our project will have 2 classes for same thing( one class will be in draw package and other will be in AndroidDraw lib). I've also DM you regarding this concern.

**Comment by divyanshub024** [comment]
I think we should just include ColorSeekBar Library( #1691 ). What do you say?
