### ISSUE TITLE
[Bug] Search User

### ISSUE THREAD

**Issue by Hkarimi561** [RocketChat/Rocket.Chat.Android#1939]
## Description

When I search for user that i didnt send any message to him i can not send message while i close the app and open it again to send message 

## Devices and Versions

Your Rocket.Chat.Android version: 3.2.0
Your Rocket.Chat Server version: 0.72.1

Mobile device model and OS version: Android 9.0 google pixel 2 & Sumsung galaxy s7 7.0

## Steps to reproduce

Search A User and find it click on it and send message to it and send icon didnt apear

**Comment by abicur** [comment]
May be your issue is the duplicate of mine?
#1875

**Comment by Hkarimi561** [comment]
@abicur Tanks For Commenting yes my issue is same az you

**Comment by Hkarimi561** [comment]
close #1939
