### ISSUE TITLE
Legacy Android app refuses to connect to any server

### ISSUE THREAD

**Issue by hacklab01** [RocketChat/Rocket.Chat.Android#1940]
## Description

After a fresh install of the server and the legacy Android app, the app refuses to connect with "The server *** is not enabled for mobile apps".

The non-legacy version works perfectly with the server on different devices.   

I do realize that the phone is old and unsupported. I have also searched issues and found that it could be an issue with how my SSL certs are set up. However, the server gets A rating on ssllabs meaning the SSL chain is setup properly. 

## Devices and Versions

Rocket.Chat.Android version: 2.8.0 build 3221 (legacy)
Rocket.Chat Server version: Version 0.72.3
-- | --

Mobile device model Sony Xperia D2005, Android 4.4.2
 
## Steps to reproduce

Trying to log in to any RocketChat server, including the official open.rocket.chat produces a "The server *** is not enabled for mobile apps".

Thanks! :)

**Comment by rafaelks** [comment]
@hacklab01 This repository is only related to the native app, the Legacy one is already deprecated. You can download the new one on this link: https://play.google.com/store/apps/details?id=chat.rocket.android

**Comment by hacklab01** [comment]
Thanks!

Just an idea... The old app should then be removed from the Play store if it's deprecated and not compatible with new servers. 
Would have saved me some time.

**Comment by rafaelks** [comment]
@hacklab01 Yes, the app will be removed from the store as soon as version 3.2 hits Google Play. 👍
