### ISSUE TITLE
Click uploaded Image on room -> Access Denied

### ISSUE THREAD

**Issue by cheonjoosung** [RocketChat/Rocket.Chat.Android#195]
Your Rocket.Chat.Android version: (make sure you are running the latest)
![capture _2017-02-07-12-59-12](https://cloud.githubusercontent.com/assets/13310269/22677406/93b6a85c-ed35-11e6-9c77-418c1dab4918.png)
![Uploading Capture+_2017-02-07-12-59-34.png…]()

**Comment by geekgonecrazy** [comment]
So when it opens in the browser access is denied because you aren't signed in on the browser.  You can goto your server settings and change that under file uploads.

But I'm guessing only reason you clicked it is because you want to see it bigger.

**Comment by cheonjoosung** [comment]
Oh Thanks. I got it.

**Comment by cheonjoosung** [comment]
Also I tested uploaded Image download.
**Currnent img link** : hostname/fileupload/somevalue/filename.jpg or png
**Test img link** : hostname/fileupload/somevalue/filename.jpg or png+?rc_uid="id_value"&rc_token="login_token"
it works good.
