### ISSUE TITLE
Chats trying to connect repeatedly

### ISSUE THREAD

**Issue by wsams** [RocketChat/Rocket.Chat.Android#1950]
## Description

I used the [docker compose file](https://rocket.chat/docs/installation/docker-containers/docker-compose/) to start the mongodb, init, and chat containers. I created an admin account and I can add other users and modify settings but when I open Chats it says, "Connecting in x seconds". After each time it adds more seconds to the timer. None of the containers are outputting any errors or logs at that time. I looked through the issues but didn't find anything related. Is this a known issue or something like a bug? I'm happy to provide any other information that might be useful. 

## Devices and Versions

Using Sprint LG V20 with Oreo 8.0.0.

Rocket.Chat.Android version 3.1.1
Rocket.Chat Server version: 0.71

**Comment by wsams** [comment]
I just went through most of the closed issue more carefully and I think I found a couple similar issues. For example #1116. I'll check my reverse proxy configuration again and report back.

**Comment by wsams** [comment]
As far as I can tell the reverse proxy looks okay. I'm also able to use the web client. I see all of the channels I created on my phone.

**Comment by rafaelks** [comment]
@wsams Your server probably don't support or don't have WebSockets enabled... can you confirm?

**Comment by wsams** [comment]
@rafaelks definitely looks like an issue with websockets. I'll see if I can figure it out and report back.

**Comment by wsams** [comment]
I found this doc and looks like the reverse proxy wasn't right for websockets. https://rocket.chat/docs/installation/manual-installation/running-in-a-sub-folder/

It's now working! Thanks for the help.
