### ISSUE TITLE
FCM Token not registered on server

### ISSUE THREAD

**Issue by HardwareToWebWizard** [RocketChat/Rocket.Chat.Android#1952]
## Description
I built my own android app with this repository. I added firebase to my project via the google-services.json. Then I added firebase cloud messaging to the app (subfolder 'app:'). Then the api keys where added to the server and the server got restarted. Kotlin is configured in the project. The gradlew build was successful but no fcm token is sent to the server to get push notifications working.
The gateway on the server is disabled as I use my own firebase project. As I want to send a test notification it says there are no tokens for this user.

## Devices and Versions
Your Rocket.Chat.Android version: Build 3.2.0 (foss)
Your Rocket.Chat Server version: 0.72.3

## Steps to reproduce
Build app as in documentation explained.
Add Api Keys to server and restart it.
Start android app.

## Logs
I cannot provide any logs since no fcm logs are visible. Neither at the server or the client.
Server only says GCM configured.

Did I missed anything regarding the push notification setup ?
Thanks in advance.

**Comment by rafaelks** [comment]
@Snom Is the request to register token being made? What's the response like?

**Comment by HardwareToWebWizard** [comment]
@rafaelks Thank you for your response.
Actually i am not seeing any kind of request to the chat server to register a token. How should the request on the client should look like if it is working ? Is the request to the server like `/api/v1/token` or something like this ? I cannot find any request like that. The only tokens i can find in the logs are the x-auth token for the authentication. If I filter only for firebase messages in android studio I also cannot find anything helpful for the token request.

Does this log help you ? `com.google.android.gms.persistent W/GLSUser: [DeviceKeyStore] Cannot load key: Device key file not found.`

So what I assume is that the client is already not sending a request with the fcm token to the server.
Do you have any idea why this is the case ? The compiled app is working fine besides that it is not requesting the token to be registered at the server.

**Comment by rafaelks** [comment]
@Snom Maybe your FCM file is wrongly configured? 🤔

**Comment by HardwareToWebWizard** [comment]
So you mean my google-services.json ? I just pressed the download button at the firebase project. How can i recognize if the push settings are configured in the file ?

**Comment by HardwareToWebWizard** [comment]
The problem was is built the foss version of the app. I changed it to the play build version (`./gradlew assemblePlay`) and it is now working as expected. Thank you for answers. I will close the issue right now.

**Comment by Dnl118** [comment]
I am having the same issue, can you explain me what is the "foss" version? I am trying to run it from Android Studio and push notifications is not working as expected. I also added the google-services.json, and I saw that we only enable google services when not building "foss" version.

Some haw, the manifest on app -> src -> play have FirebaseMessagingService registered but still not working.

Thanks!

**Comment by HardwareToWebWizard** [comment]
Hi,

You cannot built it with android studio. You have to open your Terminal and go to the Root project folder of your App. Then type in my mentioned command in the issue (./gradlew assemblePlay) this will produce the play version of the app. This apk you generated can be installed on your device as usual. The push worked then for me.

Kind regards

**Comment by pcsantana** [comment]
Actually, you can build with Android Studio, but needs to build a release version (signed apk). At least it worked for me.

Thank you @Snom !

**Comment by anveshfactorly** [comment]
Hello @Snom 

I am also having same issue which you identify 

But the problem here is my notification method **RocketChatMessagingService -> onNewToken method** not called and my token didn't send to the server

Can you please help me in this

It's bit urgent. if i can get your help instance , it would be really appriciated

Thanks

**Comment by HardwareToWebWizard** [comment]
Hi @anveshfactorly

First make sure that you followed the instructions on how to configure the firebase push notifications and then build your app either with Android Studio or with the command, you can find above, as a signed apk. If it is still not working it is another error.
I would recommend you to open a new issue and post your case there. Maybe also with more detail so it is a bit clearer what and where the error happens.
Cheers
