### ISSUE TITLE
[BUG] Error message: "Use JsonReader.setLenient(true) to accept mailformed JSON at path $".

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1957]
Your Rocket.Chat.Android version: 3.2.0 Build 2055 - ac4ffd53 - play
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.72.3

If you create a private message to another user and enter the information about this chat using the "i" button, you can see the message: "Use JsonReader.setLenient(true) to accept mailformed JSON at path $".

![videosnapshot_20181221_182531](https://user-images.githubusercontent.com/18574776/50350162-3e763400-054f-11e9-9ab1-6d877ab52d92.jpg)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18574776/50350491-6914bc80-0550-11e9-844c-75cf57184566.gif)

**Comment by shellster** [comment]
I have GridFs file storage.  This problem also occurs every time a user attempts to upload a file via the Android app.  The upload fails with the above mentioned JSON error.  This issue is long standing and multiple versions.

**Comment by jgerle** [comment]
This is most probably related to max file upload size in your reverse proxy (e.g. nginx). Try to incease it to 10M and restart the proxy.

**Comment by shellster** [comment]
Can confirm that @jgerle's suggestion fixed the problem in my case.
In particular, you want to add a line something like this:
`client_max_body_size 200M;`
