### ISSUE TITLE
[IMPROVEMENT] Use draw library instead of draw package in app.

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1971]
## Describe the bug

To use [AndroidDrawLibrary](https://github.com/divyanshub024/AndroidDraw) instead of [draw](https://github.com/RocketChat/Rocket.Chat.Android/tree/develop/draw) package in app.

cc: @filipedelimabrito @rafaelks 

related: #1691

**Comment by philipbrito** [comment]
@divyanshub024 We'll keep the draw package in the app - the plan is only to remove all the code referent to the draw feature there.

**Comment by philipbrito** [comment]
@divyanshub024 No more plans to use the draw library inside the Rocket.Chat app?

**Comment by divyanshub024** [comment]
@filipedelimabrito I have given my answer here https://github.com/RocketChat/Rocket.Chat.Android/pull/1691#issuecomment-473164096.
