### ISSUE TITLE
Rocket chat android  not show chat window

### ISSUE THREAD

**Issue by sflyer** [RocketChat/Rocket.Chat.Android#1987]
## Describe the bug
 After login in server chat window is empty. I see only connect timer. 
Status user account online and i can enter in server admin console.

## Devices and Versions

My Rocket.Chat.Android version: 3.1.1
My Rocket.Chat Server version: 0.72.3
My device: Xiaomi redme 4A with Android 7.1.2 N2G47H.

**Comment by lorek123** [comment]
There was an update recently, check if your issue persists.

**Comment by RcrdBrt** [comment]
I'm still facing this issue, the message string in the toast says "null cannot be cast to non-null type kotlin.String". I guess there is some casting issues when retrieving the message list.

The issue persists also in the beta release from the Play Store.

**Comment by RcrdBrt** [comment]
This is the toast message I'm referring to. As of today, the issue is still there. It looks kinda trivial to fix though. Sounds like a bad type casting.

![screenshot_20190128-234045](https://user-images.githubusercontent.com/1354394/51871435-a130cb80-2356-11e9-8045-39e53d1b7b4d.jpg)

**Comment by hfeky** [comment]
@filipedelimabrito I do not think this issue occurs in any server anymore.

**Comment by philipbrito** [comment]
Thanks for the ping @HusseinElFeky! 

Yes, this specific bug isn't happening anymore. I'm going to close this issue. Thanks!
