### ISSUE TITLE
[BUG] Alert button not showing title.

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#1990]
![screenshot_20190111-113734](https://user-images.githubusercontent.com/11776825/51041152-10a56d80-1598-11e9-8a52-c7bf08338b6c.png)

**Comment by divyanshub024** [comment]
@filipedelimabrito would you like me to work on it?

**Comment by philipbrito** [comment]
@divyanshub024 It would be appreciated! Are you planning to work on it today?

**Comment by divyanshub024** [comment]
@filipedelimabrito It's done, pls check.
