### ISSUE TITLE
Android studio updated to 3.3 but the rocket chat(kotlin) not work now

### ISSUE THREAD

**Issue by sealiasheq** [RocketChat/Rocket.Chat.Android#1999]
My android studio updated to 3.3 but the rocket chat(kotlin) not work now.

What can I do?

**Comment by philipbrito** [comment]
Please, open the issue on the respective [repository](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK). You can also use our [channel](https://open.rocket.chat/channel/androidnativeapp) for this kind of question.

Thank you.

**Comment by abhishekdeshkar** [comment]
@filipedelimabrito Link is dead mate.
