### ISSUE TITLE
Replace SQLite to Realm

### ISSUE THREAD

**Issue by YusukeIwaki** [RocketChat/Rocket.Chat.Android#20]
Currently Lily uses SQLite, ContentProvider, CursorAdapter, ... 
It would be smarter to use Realm, RealmBasedRecyclerViewAdapter for dealing with relational models (such as `User <- N..N -> Room` relation)

**Comment by YusukeIwaki** [comment]
Realm seems not to be mature. The lack of backlink feature is fatal...
Consider other DAO library such as "Android-Orma"

**Comment by YusukeIwaki** [comment]
## model design.

```
Room
  |- type(public/private/direct)

Message
  |- syncstate(0:NOT_SYNCED, 1:SYNCING, 2:SYNCED)
  |- room_id
  |= User

RoomUserRelationship
  |= Room
  |= User
  |- status(online/offline)
```

## use-case design

### list messages for a room

```
`Room.where(id=xxx).messages`: NG
`Message.where(room_id=xxx)`: OK
```

the reason is below...

### send new message

```
insert Message(id=zzzz, room_id=xxx, syncstate=0)
```

```
-> shown by `Message.where(room_id=xxx)`
-> not shown by `Room.where(id=xxx).messages`

-> handled by Observer with condition `Message.where(syncstate=0)`
 -> DDP method called
  -> after success, message.syncstate=2
```

### list rooms for a user

```
RoomUserRelationship.where(user.id=xxx) .map(.Room)
```

### list users in a room

```
RoomUserRelationship.where(room.id=xxx) .map(.User)
```

**Comment by engelgabriel** [comment]
@YusukeIwaki maybe we should arrange some time to talk, as we are thinking about doing the same in Electron and iOS, so we could collaborate in that effort.

**Comment by YusukeIwaki** [comment]
This issue will be separated into each functions. close now.
