### ISSUE TITLE
"setUserPresence:online" didn't be called sometimes.

### ISSUE THREAD

**Issue by cheonjoosung** [RocketChat/Rocket.Chat.Android#200]
Your Rocket.Chat.Android version: latest-develop

onStart() in MainActivity call setUserOnlineIfServerAvailable().

But, this function do not work well when app start(after termination with back-key)

This problem is relative with push. Because server send push gcm if that method is not called.

It seems more appropriate to put  setUserOnlineIfServerAvailable()  func() in onHostnameUpdated().

Please feedback. thanks.

**Comment by laggedHero** [comment]
That makes sense. I have to change a couple of things in `MainActivity`. Let me add this to it.
