### ISSUE TITLE
[NEW] Slash Commands

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#202]
Your Rocket.Chat.Android version: latest

Need support for /commands

**Comment by laggedHero** [comment]
@geekgonecrazy Do you have a link for the docs on that?

**Comment by geekgonecrazy** [comment]
This one might be kind of hard to dynamically do... The slashcommands are generally intercepters on client side, though not always.

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-slashcommand-asciiarts/shrug.js Most in this package would all be client side
