### ISSUE TITLE
[BUG] Not able to select the black color in color palette in drawing 

### ISSUE THREAD

**Issue by Cool-fire** [RocketChat/Rocket.Chat.Android#2021]
## Describe the bug
Unable to select the black color in color palette.
## To Reproduce
1. Go to drawing
2. Select color palette and change color
3. Now select black color
4. see that we cannot draw with black color

## Expected behavior
Able to select black color and draw with it.

## Devices and Versions

Your Rocket.Chat.Android version: (2.1.0)
Your Rocket.Chat Server version: (0.63.1-develop)

Mobile device model and OS version: (Redmi note 5- Android 8.0.1)

**Comment by GOVINDDIXIT** [comment]
thanks for mentioning this issue this is a known bug and will be fixed in #1961

**Comment by philipbrito** [comment]
Closed by #1961
