### ISSUE TITLE
[BUG]  Drawing is cleared on Orientation change.

### ISSUE THREAD

**Issue by Cool-fire** [RocketChat/Rocket.Chat.Android#2027]
## Describe the bug
Drawing is cleared on rotating the phone.

## To Reproduce
1. Go to Drawing
2. Draw something on canvas
3. rotate the phone
4. See that drawing is cleared and fresh white canvas appears

## Expected behavior
The drawing should persist on rotation and should not be cleared.

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: ( "Redmi note 5 - Android 8.1.0")

**Comment by divyanshub024** [comment]
@Cool-fire Good catch.

**Comment by divyanshub024** [comment]
@rafaelks Regarding this issue, what do you think we should do? What happens in ios on rotate?

**Comment by rafaelks** [comment]
@divyanshub024 Can we keep the draw on rotation? We just keep it I on iOS.

**Comment by divyanshub024** [comment]
@rafaelks Ok, I'll do that.
