### ISSUE TITLE
Android 7 unable to login to RocketChat

### ISSUE THREAD

**Issue by elcolie** [RocketChat/Rocket.Chat.Android#2029]
## Describe the bug
Android 7 is unable to login to RocketChat server

## To Reproduce

1. Download Android FOSS version from github
2. Install the application
3. Login to `https://chat.elcolie.com`

## Expected behavior
Be able to login to the chatserver

## Logs
Not provided

## Screenshots
![screenshot_1550128695](https://user-images.githubusercontent.com/18206728/52772042-1811d800-306a-11e9-8fa3-bfec36b71ab7.png)

## Devices and Versions
Your Rocket.Chat.Android version: 3.2.0
Your Rocket.Chat Server version: 0.74.2

Not be able to connect
I have tested on real device and emulator. Android 7 is unable to login
Lenovo K6 Android 7.0
Emulator with Android 7.0

Be able to connect
My Android 9.0 emulator be able to pass first pass and show me username: password form for enter

## Additional context
I did not test Android 9 login because it just an emulator

**Comment by rafaelks** [comment]
It looks like this is not the correct URL:

```
➜  ~  curl "http://chat.elcolie.com/api/info"
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
```

**Comment by elcolie** [comment]
It is `https` not `http`!
```
curl https://chat.elcolie.com/api/info
{"version":"0.74.2","success":true}
```

**Comment by rafaelks** [comment]
@elcolie My bad! Checking what's happening...

**Comment by elcolie** [comment]
Phew. Thank you very much.

**Comment by rafaelks** [comment]
It works for me... don't you have any blocker on your network, proxy or something?

![screenshot_20190214-135701](https://user-images.githubusercontent.com/551004/52799194-82257f80-3060-11e9-9a15-b835d5fd100b.png)

**Comment by elcolie** [comment]
Thank you for your reply.
My server is located in Singapore. And Android 7 from Thailand is unable to connect
For some reason Android 7 from Brazil Internet can do that!

I can conclude that Thailand internet has proxy or firewall to prevent Android 7 doing that. 
Shame on it
