### ISSUE TITLE
[Bug] Batteryload on Samsung Galaxy S7 and S8

### ISSUE THREAD

**Issue by Ultimativschmidt** [RocketChat/Rocket.Chat.Android#2031]
## Describe the bug
Some of my colleagues told me a higher batteryload, when they had start the RocketChat-APP.

## Expected behavior
I couldn't reproduce it on my Android Device (BQ Aquaris M 5.5 - Android 7.1.2). My colleagues wish to have a normal Batteryload back.

## Devices and Versions

Rocket.Chat.Android version: 3.2.0
Rocket.Chat Server version: v0.70
Mobile device model and OS version: - Samsung Galaxy S7 and S8 - Android 8

**Comment by lorek123** [comment]
Could you ask them to verify if this is really RocketChat app? They can check system battery information, or use some kind of Wakelock monitor. This battery drain may be related to app not letting go to sleep their phones.

**Comment by GOVINDDIXIT** [comment]
@Ultimativschmidt  Working fine for me. I also checked with background running processes and there is nothing unexpected there.

**Comment by Ultimativschmidt** [comment]
@lorek123 The Question at my colleagues is in progress.

**Comment by Ultimativschmidt** [comment]
@lorek123 I've told my colleagues to reinstall the RocketChat-App. There's no problem since there.
