### ISSUE TITLE
[IMPROVEMENT] Setting -> "Contact us" should show only email apps

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#2038]
## Describe the bug
In  `Setting -> Contact` us is meant to send an email at `support@rocket.chat` and it should show only email apps but right now it's showing other apps like WhatsApp etc. which is not the correct behaviour.

**Comment by GOVINDDIXIT** [comment]
@divyanshub024 I Will send a PR to fix this. 👍
