### ISSUE TITLE
[BUG] Profile avatar is not changing

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#2040]
## Describe the bug

After chaning the avatar in profile the avatar is set back to previous profile pic. The change is reflected on web but not on android app.
## To Reproduce
1. Go to profile
2. Click on the profile picture and select `Reset avatar` or any other option.
3. Go to chats or some other fragments and come back. 
4. Your previous avatar will there.

## Expected behavior

Same as the web.

## GIF

![ezgif-1-dd40f7d3fef8](https://user-images.githubusercontent.com/16731434/53417114-dcc4c100-39fa-11e9-93ae-cd5a6f043345.gif)

**Comment by dev-ritik** [comment]
I would be making a PR to fix this @divyanshub024

**Comment by divyanshub024** [comment]
@dev-ritik Great 👍

**Comment by divyanshub024** [comment]
@dev-ritik Make sure that it works for all the three conditions.
1. Select photo from gallery.
2. Take Photo.
3. Reset Avatar.
