### ISSUE TITLE
[NEW] Option to view user profile avatar in fullscreen.

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#2042]
## Description

There should be an option to view user profile avatar in full screen when you click it in profileFragment and userDetailFragment.

**Comment by GOVINDDIXIT** [comment]
@divyanshub024 Can I work on this issue?

**Comment by divyanshub024** [comment]
@GOVINDDIXIT Sure, go ahead 👍
