### ISSUE TITLE
[IMPROVEMENT] Correct delete account dialog UI Alignment 

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#2043]
## Describe the bug

In profile-> Delete Account, the dialog edit text left alignment should be the same as its title left alignment.

<img src ="https://user-images.githubusercontent.com/16731434/53420460-ddad2100-3a01-11e9-83b7-ab6cbd7bcff2.png" width=320/>

**Comment by AuraOfDivinity** [comment]
I'll start working on this!

**Comment by divyanshub024** [comment]
@AuraOfDivinity Thank you 😄

**Comment by arthurbdiniz** [comment]
Hi @divyanshub024, i looked this part of code and i think it's better to create a custom dialog UI to solve this problem.

**Comment by arthurbdiniz** [comment]
Hi @divyanshub024, just send a PR with this fix.  Waiting for review! 

![screenshot_20190228-150458_rocketchat](https://user-images.githubusercontent.com/18387694/53588783-89728000-3b6c-11e9-8ddf-cf593fa4722e.jpg)
