### ISSUE TITLE
[IMPROVEMENT] Search field width should be the max width

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#2045]
## Describe the bug

Right now search field is showing with other icons. Whci reduces content space. Search field width should be max.

![device-2019-02-26-202946](https://user-images.githubusercontent.com/16731434/53422337-4a75ea80-3a05-11e9-940c-5729e644964e.png)

**Comment by VANKINEENITAWRUN** [comment]
@divyanshub024 should we remove those icons while searching?

**Comment by divyanshub024** [comment]
@VANKINEENITAWRUN Yes, the search field should only be there. But lets see what @filipedelimabrito has to say.

**Comment by AuraOfDivinity** [comment]
I would like to start working on this issue @divyanshub024

**Comment by divyanshub024** [comment]
@AuraOfDivinity If @VANKINEENITAWRUN is not working on it then you can work on it.

**Comment by VANKINEENITAWRUN** [comment]
@AuraOfDivinity you can work on it.

**Comment by philipbrito** [comment]
Good finding @divyanshub024, thanks for creating this issue!
