### ISSUE TITLE
No channels visible after login

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#205]
Your Rocket.Chat.Android version: 1.0.0

Hi Devs.

After installing version 1.0.0 and login to my Rocketchat Server 0.52.0 no channels are visible so i have no possibility to enter channels. When i log in with the browser there are 10 channels visible. Is there a way to find out what causes this problem?

Update: Have 7.1.1 running too.

thanks and cheers

**Comment by TheReal1604** [comment]
Got this also at 1 User. He is using a Nexus 6P Android 7 (7.1.1 Patchlevel from 5 february 2017)

some screenshots:

![image](https://cloud.githubusercontent.com/assets/5877910/22989448/3b187054-f3b6-11e6-9413-540c5c46465d.jpg)
![image](https://cloud.githubusercontent.com/assets/5877910/22989467/47c551f0-f3b6-11e6-8656-74b5e754683f.jpg)

But he can search for other users, unfortunately there is no way to get this working.

Anyone got an idea? At other users it works flawless.

**Comment by CodazziS** [comment]
Hello,
Same issue here, Nexus 5X (android 7.1.2-preview).
Tried to uninstall/reinstall application, but don't work :/ 

(Application was working for the first launch).

**Comment by laggedHero** [comment]
Version 1.0.3 (in beta release) may have this issue fixed.

@himbeere @TheReal1604 @stephane- Could you try it?

**Comment by CodazziS** [comment]
Nice!
Fixed for me. 
Thanks 👍

**Comment by RichardFoxworthy** [comment]
Same problem: 
nexus 6P 
Android 7.1.2
rocket. Chat+ 1.05

Originally tried to login via - google oauth. This failed so I set up password manually via Web app, the logged I  successfully via + client to see empty channels list

Update: I reinstalled Rocket.Chat+ app and logged in with my new username/password and  it works! Can see channelnlist

**Comment by rafaelks** [comment]
Closing this one, seems fixed.
