### ISSUE TITLE
[IMPROVEMENT] Remove notification when message is read directly on app.

### ISSUE THREAD

**Issue by eliezer-of** [RocketChat/Rocket.Chat.Android#2052]
## Describe the bug

when a message from a favorite chat is received and it’s open directly in Rocket.Chat
 app, it would be interesting to removed in notification.

## Devices and Versions

Your Rocket.Chat.Android version: (3.20)

## Additional context

https://www.dropbox.com/s/zp7ldgxn7rsiwb7/improvement_remove_notification.mp4?dl=0

**Comment by VANKINEENITAWRUN** [comment]
I would like to take it.

**Comment by eliezer-of** [comment]
@VANKINEENITAWRUN Actually, I'm already working in this issue. :)
