### ISSUE TITLE
[IMPROVEMENT] Keep the scroll position in chatrooms after rotating screen.

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#2060]
## Description

Right now after rotating screen the scroll position is changed to default. We should save the scroll position on screen rotation.

**Comment by AuraOfDivinity** [comment]
I'd like to work on this issue! @divyanshub024  :)

**Comment by divyanshub024** [comment]
@AuraOfDivinity I'm working on it.
