### ISSUE TITLE
[BUG] WHITE BLANK IMAGE VIEW FOR USER PROFILE

### ISSUE THREAD

**Issue by anhanh11001** [RocketChat/Rocket.Chat.Android#2074]
## Describe the bug
When a user profile image is reset, the image view is white and blank 

## Expected behavior
Container to indicate that's there is a place for new image 

## Screenshots
<img src="https://i.ibb.co/TRL3kxZ/52991274-289836591692164-734322249498099712-n.png" width="200">

**Comment by dev-ritik** [comment]
Well @anhanh11001 , this issue gets resolved in the PR #2048 . Actually, the avatar is locally cached and when you reset the image, it is the bug which renders an empty image. Once merged, it shall be replaced by the `Initials avatar`.
I guess a simple placeholder will do the job.

**Comment by anhanh11001** [comment]
I am not sure we are on the same page here. What I meant is that there should be a default image avatar that's displayed when the user reset his/her avatar. Something like this below, which I did in PR #2075 
<img src="https://i.ibb.co/31QmwQy/52861806-787461298313384-5927574112846217216-n.png" width="200">
<img src="https://i.ibb.co/bQYtk8p/52995463-1762059793900236-8914854142162239488-n.png" width="200">

Please take a look, this is what you meant and you have solved it then I will close this issue @dev-ritik

**Comment by dev-ritik** [comment]
okay, a background image will always help! Thanks for the clarification.:thumbsup:
