### ISSUE TITLE
[IMPROVEMENT] Swipe down to reload in chat 

### ISSUE THREAD

**Issue by anhanh11001** [RocketChat/Rocket.Chat.Android#2076]
## Describe the feature you'd like
Swipe down to reload the ChatRoomFragment

## Screenshots
<img src="https://i.ibb.co/1Mcr3FZ/53139439-1006876596186638-1778532703004524544-n.png" width="200">
Swipde down to reload in this Fragment

## Notes
I'm working on this

**Comment by philipbrito** [comment]
It isn't on our plans. You could check that here: https://github.com/RocketChat/Rocket.Chat.Android/pull/809#issuecomment-386459544

Thank you.
