### ISSUE TITLE
Unable to build the Project

### ISSUE THREAD

**Issue by Vipinsoni38** [RocketChat/Rocket.Chat.Android#2081]
Could not get unknown property 'androidGradlePluginVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by AllanWang** [comment]
Did you build the sdk? For some reason we are required to build it ourselves vs using something like jitpack

**Comment by philipbrito** [comment]
You don't need to build the SDK yourself. Building the app as it should be done will build the jars from the SDK as pointed out on the README.md.

Also it is not an error from the project (`org.gradle.api ...`)
