### ISSUE TITLE
Fix avatar loading

### ISSUE THREAD

**Issue by AllanWang** [RocketChat/Rocket.Chat.Android#2085]
## Describe the bug

I don't know why this has not been fixed, given that it has already been noticed over a year ago.
https://github.com/RocketChat/Rocket.Chat/pull/9749#issuecomment-366390259

There are tokens scattered everywhere when you already have a decent solutions using interceptors.
Move auth to the interceptor, and everything will work.

You can fix this using something like this:

https://github.com/AllanWang/Rocket.Chat.Android/blob/26a2616a1c86561aa6516977f000e422e2e6e3d2/app/src/main/java/chat/rocket/android/util/BasicAuthenticatorInterceptor.kt#L76-L84

Though you'd probably want to add a way to refetch the token or fetch it every time to support logging out.

## To Reproduce
1. Open the app with a new server build
2. Notice that no avatars load

## Expected behavior
Avatars should load

Your Rocket.Chat.Android version: 3.2.0
Your Rocket.Chat Server version: 0.74.3

**Comment by AllanWang** [comment]
@filipedelimabrito friendly ping.

This error is really obvious to all your new users (given server defaults and images taking up 1/5 of the screen), and a simple fix is provided.

If you are okay with query based authentication, which is used in other parts of the app, I recommend you patch the problem soon.

Even if you don't support token refetching/invalidation, having a bad token upon logout won't do more harm than no token at all.

**Comment by philipbrito** [comment]
Issue is gone from the latest app version (3.4.0).
