### ISSUE TITLE
Project status / maintenance

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#2086]
Has something happened? No commits since mid-January, kind of strange considering the pace that things had been going at before.

**Comment by rafaelks** [comment]
@antgel Our team just came back from vacation last Friday and today is holidays in Brazil. Things will come back to normality this Wednesday! :-)

**Comment by antgel** [comment]
Welcome back, hope it was a good one, and thanks for responding! :)
