### ISSUE TITLE
not possible to join a room

### ISSUE THREAD

**Issue by Borda** [RocketChat/Rocket.Chat.Android#2100]
## Description

There is a public room in our workspace, but the Andriod app does not offer to join a room I am not a member yet nor posting anything to the chat. On the other hand, the Linux desktop chat allows it.

![screenshot_20190304-141152](https://user-images.githubusercontent.com/6035284/53888373-a3a4d600-4024-11e9-8686-7ebc909153fe.png)

## Devices and Versions
Your Rocket.Chat.Android version: 3.2.0 (Build 2057 - 373602fe - play)
Your Rocket.Chat Server version: private
Mobile device model and OS version: Mi A2 Lite - Android 9

**Comment by GOVINDDIXIT** [comment]
@Borda Currently a user can automatically join a public room after sending a message to it.

**Comment by Borda** [comment]
I tried too, but it did not pass either... I taped message but it was not sent...

**Comment by aenonGit** [comment]
same as #2298 and #2367
