### ISSUE TITLE
[Bug] Missing Padding to Delete Buttons

### ISSUE THREAD

**Issue by codekhal** [RocketChat/Rocket.Chat.Android#2108]
## Describe the bug
The buttons padding and width needs to be fixed.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to any of the public/private chat rooms.
2. Click on message.
3. Scroll down to Delete
You will see the bug.

## Expected behaviour
The two buttons should be properly spaced.

## Current Behaviour:

![newissue](https://user-images.githubusercontent.com/32578541/53988302-2e7ef100-4149-11e9-867e-f4a552f7d43a.png)

## Devices and Versions

Mobile device model: Asus Zenfone Max Pro M2
OS version: Android 8.1.0

## Additional context
I would like to take this issue.

**Comment by codekhal** [comment]
Hope Kautilya won't mind about his name in this image ;)

**Comment by knrt10** [comment]
Not a problem @codekhal

**Comment by AuraOfDivinity** [comment]
@codekhal  This bug is actually fixed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2097

**Comment by codekhal** [comment]
It's different from deleting the account itself, it's about deleting the messages. Kindly read the description properly.

**Comment by AuraOfDivinity** [comment]
My bad @codekhal  It definitely looked like what I was working on. Apologies for raising an misguided concern!

**Comment by codekhal** [comment]
No issues at all @AuraOfDivinity Thanks for your concern BTW. Will ask for your help if I find any trouble setting up things. :)

**Comment by Cool-fire** [comment]
@codekhal I think this issue has been resolved. The screenshot is for the rocket chat android app from playstore, this issue has been resolved in the current build. You should check if the bug exists in the current build.

**Comment by GOVINDDIXIT** [comment]
@codekhal this is an old bug #1935 which is already fixed by #1994. You can close this issue.

**Comment by codekhal** [comment]
@GOVINDDIXIT Thanks for mentioning. Referencing #1994 
Now Closing!
