### ISSUE TITLE
User is not automatically scrolled to last message after sending a message

### ISSUE THREAD

**Issue by GOVINDDIXIT** [RocketChat/Rocket.Chat.Android#2113]
## Describe the bug

User is not automatically scrolled to his last send message on sending a message

## To Reproduce
1. Go to any chatroom
2. Scroll up a little
3. now send a message 
4. Nothing happen

## Expected behavior

After sending a message user should be automatically scrolled to his last send message 

## Additional context

I would like to work on this issue

**Comment by philipbrito** [comment]
@GOVINDDIXIT Like we discussed on the past (June last year to be more precise) on our community channel this is a not desired thing to do.

You can find more information about the reason here: https://open.rocket.chat/channel/androidnativeapp?msg=ceGsrnJFtoFz3E6Lt

Thank you.
