### ISSUE TITLE
[IMPROVEMENT] Client should use thread topic name instead of guid

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#2116]
## Describe the feature you'd like
The new threads feature works great with the web client but with the Android client it has a usability problem -- the thread topic name is not displayed so its hard to tell which thread you are in. See screenshot below. The first two chatrooms listed in the view correspond to these two threads (as seen using web client):
![image](https://user-images.githubusercontent.com/4001792/54124391-ab73ca00-43d8-11e9-9576-fa0150b079fb.png)

## Devices and Versions
Your Rocket.Chat.Android version: 3.2.0

## Screenshots

![image](https://user-images.githubusercontent.com/4001792/54124423-c21a2100-43d8-11e9-9340-c7e7cc48dec1.png)

**Comment by AuraOfDivinity** [comment]
I'd like to work on this issue :)

**Comment by Adizbek** [comment]
https://github.com/RocketChat/Rocket.Chat.Android/blob/acb0f6f3c89d228a36a74dfaeb6e25c56ba12d14/app/src/main/java/chat/rocket/android/chatrooms/adapter/RoomUiModelMapper.kt#L199-L205

as you can see, displaying names depend on server configurations. If I am not wrong.

I think it's not bug, server-side problem.
