### ISSUE TITLE
Replied Message Is not properly formatted

### ISSUE THREAD

**Issue by RotBolt** [RocketChat/Rocket.Chat.Android#2118]
## Describe the bug
In reply to message , along with the message URL also come with it . This makes the chat unclear

## To Reproduce

1. Go to 'Any Room or Group'
2. Reply to any message
3. URL also come with message

## Expected behavior
URL shouldn't come with replied message

## Screenshots
<img src="https://user-images.githubusercontent.com/24780524/54135923-c37f3400-4440-11e9-8f18-842eff9656df.jpg" width=360>

## Devices and Versions
Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: Nokia 6.1 (Android Pie)

**Comment by RotBolt** [comment]
I am working on this issue

**Comment by dev-ritik** [comment]
@theLimitBreaker, I guess this is same as #1899. If so, please close this one and continue over there.
