### ISSUE TITLE
Native View of Showing Licence Screen. For Native UX

### ISSUE THREAD

**Issue by RotBolt** [RocketChat/Rocket.Chat.Android#2130]
## Describe the feature you'd like
Instead of opening WebView of github's Licence Screen , native screen should be there for Licence screen

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

## Screenshots

<img src="https://user-images.githubusercontent.com/24780524/54250744-02a9a400-456b-11e9-82d1-4de746513325.jpg" width=360>

**Comment by RotBolt** [comment]
I am working on this

**Comment by philipbrito** [comment]
@theLimitBreaker We really don't want to have it into the code. This is the reason: We'll need to update our Readme.md all the time the license here is updated and we also would need to update the application all the time to reflect that changes.

Opening a webview to show the license here in the Github (where the code is) is enough.
Thank you.
