### ISSUE TITLE
[BUG] Unable to open drawing activity after giving permissions to write.

### ISSUE THREAD

**Issue by Cool-fire** [RocketChat/Rocket.Chat.Android#2143]
## Describe the bug
Unable to open drawing activity after giving permissions to write for the first time.

## To Reproduce
1. Go to 'chatroom'
2. Click on 'drawing'
3. Allow permission to write 
4. See that drawing activity is not opening after giving permission to write.

## Expected behavior
Drawing activity should be opened as soon as permission to write is given.

## Screenshots

![videotogif_2019 03 16_16 52 33](https://user-images.githubusercontent.com/25877454/54474921-15450700-4811-11e9-8db0-382268e35705.gif)

## Devices and Versions

Your Rocket.Chat.Android version: (3.2.0)

Mobile device model and OS version: ( "Mi Note 5 - Android 8.0.1")

**Comment by philipbrito** [comment]
Issue is gone already.
Thanks.
