### ISSUE TITLE
[BUG]Users are able to send messages to themselves.

### ISSUE THREAD

**Issue by AuraOfDivinity** [RocketChat/Rocket.Chat.Android#2147]
## Describe the bug
A logged in user is able to send direct messages to himself.

## Expected behavior
Users shouldn't be able to message themselves.

## Screenshots
![1](https://user-images.githubusercontent.com/31003923/54503739-99ed6d80-4956-11e9-99df-64b16457b6ee.png)
![3](https://user-images.githubusercontent.com/31003923/54503745-9ce85e00-4956-11e9-9882-8ecc06ab2379.png)

## Devices and Versions

Your Rocket.Chat.Android version: 3.2.0

**Comment by lorek123** [comment]
Actually I often use this to send myself stuff between devices.

**Comment by GOVINDDIXIT** [comment]
I agree with @lorek123 This was like a private space for the user within the app and may not be considered as a bug.

**Comment by wreiske** [comment]
I talk to myself all the time to leave notes, run slash commands like [search](https://apis.reiske.tech/search), [math](https://apis.reiske.tech/math), amazon, etc...!!! There is no reason why you shouldn't be able to talk to yourself.

**Comment by AuraOfDivinity** [comment]
Honestly thought it would be a waste of resources. Thanks for pointing the reasons out!
