### ISSUE TITLE
[v3.3.0 Beta] Cannot use multiple accounts

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.Android#2154]
Samsung S6 / Android 7.0

Rocket.Chat App upgraded to v 3.3.0 beta

Go to swap accounts and find that some accounts have disappeared.

Cleared all cache etc.

Add account. Logs in OK
Add second account. Logs in OK
Go to change account and first account is missing
Try with a 3rd account. Same problem.

**Comment by reetp** [comment]
Oddly enough if you set up the accounts, even though they 'disappear' they are still kind of 'there' because you seem to get notifications for them.

They seem to appear and disappear randomly. If you click a notification it will take you to the server, but then you look in the list for another server and one or more have disappeared.

**Comment by andypost** [comment]
Confirm, it's confusing to relogin each time

**Comment by philipbrito** [comment]
Closed by #2159
