### ISSUE TITLE
[NEW] When room name is too big to fit screen, allow dragging the name to view the rest

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.Android#2157]
Check the title area of this reddit app:

![2019_03_20_15_29_45](https://user-images.githubusercontent.com/1986378/54710452-75e08680-4b26-11e9-81ae-1d52f0aa3fc6.gif)

**Comment by divyanshub024** [comment]
@filipedelimabrito I would like to work on this issue.

**Comment by weijia-yu** [comment]
@filipedelimabrito @divyanshub024 has this issue been worked on? I would like to take this if not

**Comment by philipbrito** [comment]
I think nobody is working on it @weijia-yu. Feel free to submit a PR! Thank you!
