### ISSUE TITLE
OAuth options not showing first time

### ISSUE THREAD

**Issue by aenonGit** [RocketChat/Rocket.Chat.Android#2158]
As the title says, when you enter the `server` (eg: `open.rocket.chat`) the app shows the `email/password` fragment instead of the `oauth providers list`.

If you go back and forth then the oauth list shows up.

This only happens the first time (fresh installs)

**Comment by philipbrito** [comment]
What version are you using? 

From the most recent one I'm not able to see it happening:

![demo](https://user-images.githubusercontent.com/11776825/54766026-75152680-4bf2-11e9-9a17-d737a1451d5d.gif)

**Comment by aenonGit** [comment]
@filipedelimabrito my bad, it looks like from the `3.2.0` the issue disappeared. Closing
