### ISSUE TITLE
[BUG] Some items of the action menu are not translated.

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#2163]
Your Rocket.Chat.Android version: 3.3.0 Build 2059 - 11154770 - play
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.74.3

Some items of the action menu are not translated into Russian, although the full translation of this menu is available in strings.xml.

![Screenshot_20190323-092430](https://user-images.githubusercontent.com/18574776/54867378-9e6bb900-4d90-11e9-9914-8793e4cd5136.png)

**Comment by philipbrito** [comment]
Not a bug. All these strings need to be translated as pointed out on the current strings.xml Russian file (`<!-- TODO Add translation -->`).
