### ISSUE TITLE
[QUESTION] Is there any way to translate this?

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#2166]
Your Rocket.Chat.Android version: 3.3.0 Build 2059 - 1115477 - play
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.74.3

Is there any way to translate this? Everything is translated in the chat room, but there is no translation in the general chat window.

![Screenshot_20190323-133856](https://user-images.githubusercontent.com/18574776/54867660-ca3c6e00-4d93-11e9-8fb1-27ae12639263.png)

![Screenshot_20190323-133952](https://user-images.githubusercontent.com/18574776/54867662-d0324f00-4d93-11e9-9c66-c36a83b39e0c.png)

**Comment by ghost** [comment]
i think maybe you can translate this on the server?? path:Rocket.Chat/packages/rocketchat-i18n/i18n  
     "Started_a_video_call"  .

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13976492/54972757-f6d8cb80-4fc7-11e9-902a-a660054d93b6.png)
![image](https://user-images.githubusercontent.com/13976492/54972891-8e3e1e80-4fc8-11e9-92f2-e05d8bb86bf0.png)

ps:catpture image from android app.
hi, i have test success. you can edit  "Started_a_video_call": "开始视频通话",  translate  to your language in rocketchat-i18n/i18n/en.i18n.json file.

**Comment by Pitstopper** [comment]
@xfunforx thanks, i'll try this!
