### ISSUE TITLE
Clearing the EditText

### ISSUE THREAD

**Issue by lokesh-kedia** [RocketChat/Rocket.Chat.Android#2174]
#BUG 
When we sends any message , the editText doesn't get cleared by itself, we need to cut the whole text ourselves

## To Reproduce
Send message in #general and see yourself

## Expected behavior
The EdiText Should be cleared

## Devices and Versions
Xiaomi Redmi 4A, android 7.1.2 , Rocket.Chat version 3.2.0

**Comment by noor-binte-amir** [comment]
I'll look into the issue.

**Comment by philipbrito** [comment]
@lokesh1agarwal From the latest release it isn't happening as you can see here:

![message-compose-cleared](https://user-images.githubusercontent.com/11776825/57156762-2b088e80-6db5-11e9-9167-1c3c97c70fa5.gif)
