### ISSUE TITLE
[IMPROVEMENT] Add support for hardcoded server URL

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#2177]
The IOS client supports RC_SERVER_URL in info.plist file, which allows the user to skip the initial screens that are about selecting a server. It would be great if the Android client supported a similar mechanism and, if set, would take the user directly to the login screen.

**Comment by nauzub** [comment]
I am also looking for something similar, even login user with credentials coming from API and creating a direct session for chatting without showing any onboarding, server or user login screens. Kindly respond If you managed to achieve above.
