### ISSUE TITLE
3.3.0 released days ago, not in Google Play Store

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#2189]
Have I missed something or was there a problem with the upload to the Play Store? Still not updating for me...

**Comment by rafaelks** [comment]
@antgel It's not 100% released yet, @filipedelimabrito can correct me if I'm wrong

**Comment by philipbrito** [comment]
@antgel You should be able to download it in a few. As @rafaelks wrote, it wasn't 100% released. It is now.

**Comment by antgel** [comment]
Thanks both! Out of interest, was this a one-off or will all future releases be staggered?
