### ISSUE TITLE
Support username sugestion

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat.Android#219]
It's possible that a user will not have an username.

We should detect that and show a screen for username setting. It will have suggestions.

**Comment by RichardFoxworthy** [comment]
Not sure if this issue means what I think it might mean... 

I want the android app to launch a pop-up and auto-suggest user names when I begin to @mention a user in a message - same as with Web client.

**Comment by geekgonecrazy** [comment]
@RichardFoxworthy Yes exactly :+1:

**Comment by laggedHero** [comment]
We had an issue for that. I'll close this in favor of #136
