### ISSUE TITLE
[BUG] Methods removed from Jitsi Meet SDK

### ISSUE THREAD

**Issue by hfeky** [RocketChat/Rocket.Chat.Android#2192]
It looks like there are issues with Jitsi Meet integration in `VideoConferenceActivity.kt`, in which the following methods are removed from `JitsiMeetViewListener`:

1. `onConferenceWillLeave`
2. `onConferenceLeft`
3. `onLoadConfigError`
4. `onConferenceFailed`

and `loadURLObject` is removed from `JitsiMeetView`.

I believe that the library got updated, and the implementation in Rocket.Chat needs to be updated as well.

This causes the project to fail in compiling and always causes 3 CircleCI tests to fail when submitting pull requests due to this error.

**Comment by philipbrito** [comment]
Thanks for opening @HusseinElFeky. It will be closed from https://github.com/RocketChat/Rocket.Chat.Android/pull/2187.

**Comment by Jamal81** [comment]
for now how can I compile the project, Im facing the same issue as state on top?

**Comment by hfeky** [comment]
@Jamal81 You can just comment it for now as if it was not written.

**Comment by Jamal81** [comment]
yup I have comment it as and able to compile, thanks @HusseinElFeky 

Below will make it compile-able.. 


<img width="964" alt="Screenshot 2019-04-08 at 9 14 14 AM" src="https://user-images.githubusercontent.com/15603781/55692924-b5401b80-59de-11e9-8e49-8c1afd7e9dc4.png">

**Comment by hfeky** [comment]
Yup exactly. You're welcome.
