### ISSUE TITLE
Audio Recording and Playback doesn't work on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat.Android#2203]
## Describe the bug

After a fresh installation, recording MP3 audio message doesn't work. Tested on All major browsers. The video recording works instead.

## To Reproduce
1. Go to the audio message icon.
2. Click on the micro sign
3. the recording starts
4. You get an empty audio file

## Expected behavior
Your voice message recorded. 

## Server Versions

Ubuntu 18.04  LTS
Nginx Reverse Proxy with Letsencrypt

**Comment by lorek123** [comment]
Is this issue related to Android App? Becuase if not, you posted this issue to the wrong repository.

**Comment by franckadil** [comment]
Hi @lorek123  yes indeed that was a mistake.  I appologize.
