### ISSUE TITLE
Images not uploaded correctly

### ISSUE THREAD

**Issue by Artraxon** [RocketChat/Rocket.Chat.Android#222]
Your Rocket.Chat.Android version: 1.0.4
Rocket.Chat version: 0.52.0

Everything is working fine when using the demo.rocket.chat!

Following (for me) reproducible Problem:
When Deleted all App Data and signing in to a server, first try to upload an image fails (Error Code 500), getting the following exception  in my exception channel:

Exception while invoking method 'ufsComplete'

Error: ENOENT: no such file or directory, open '/tmp/ufs/oj3TRceRQNqhJFyCz'
  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
  at [object Object].ufsComplete (/app/bundle/programs/server/packages/jalik_ufs.js:821:28)
  at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1064:26)
  at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:2108:12)
  at /app/bundle/programs/server/packages/ddp-server.js:1042:22
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /app/bundle/programs/server/packages/ddp-server.js:1041:43
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /app/bundle/programs/server/packages/ddp-server.js:1040:48
  at Session.method (/app/bundle/programs/server/packages/ddp-server.js:1018:23)
  at /app/bundle/programs/server/packages/ddp-server.js:880:89

    - - - - -
  at Error (native)

After the first time, no error message is displayed or some exception shows up in the log,
but the image is empty:
(Uploaded with App)
![](http://puu.sh/uj8Is/136a329876.png)

**Comment by laggedHero** [comment]
Thank you for the report.

I'll talk with the server guys and check out what could cause this.

**Comment by laggedHero** [comment]
@Artraxon 

So: I'm dumb.

We have a lot of options for file uploads. The Android app does not support all of them and the ufs implementation on Android may be broken.

So yeah: it may take more time. I may try your upload option first.

What are you using exactly?

**Comment by Artraxon** [comment]
Im using above mentioned Version on the OnePlus 3T with OxygenOS 4.0.3 (Android 7.0)
Does not have a SD Card, uploading via Wi-Fi.
Do you need the server specs? 
But as i said, it's working fine on the demo server.

**Comment by laggedHero** [comment]
@Artraxon yep: the server.

We have a lot of different ways to store the files. Depending on what you're using, messages change.

The demo uses s3 and it works fine. I think you may be using ufs. I just need to be sure about it.

**Comment by Artraxon** [comment]
I am using GridFS

**Comment by laggedHero** [comment]
@Artraxon Since this affects the web client too it's not an Android issue. I'll close this issue.
