### ISSUE TITLE
[BUG] Layout issues when device font is set to larger than default

### ISSUE THREAD

**Issue by hfeky** [RocketChat/Rocket.Chat.Android#2220]
## Describe the bug

When one sets the device font to be larger than default from the device settings, there are some layout issues that are produced in many parts of the app.

## Expected behavior

The app should optimize its user interface according to the device font set. This can easily be fixed by setting the views' dimensions to be in `sp` (Scale-independent Pixels) instead of any other unit, for any view that can change size when text size is changed.

## Screenshots

Some examples:

![Screenshot](https://user-images.githubusercontent.com/20887574/55820066-8323dc00-5afa-11e9-9e7b-f781eb8279cf.png)

## Version

Rocket.Chat.Android version: 3.3.0

**Comment by noor-binte-amir** [comment]
Thank you for submitting the issue. I'll check it out.
