### ISSUE TITLE
android kotlin bug

### ISSUE THREAD

**Issue by RyanSummer** [RocketChat/Rocket.Chat.Android#2222]
## Describe the bug

android kotlin bug
![4963BE13-F393-4f00-B1DF-4CE1D956C9F8](https://user-images.githubusercontent.com/19684255/55848895-28819300-5b81-11e9-95dd-099fa195b136.png)

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by Adizbek** [comment]
https://github.com/RocketChat/Rocket.Chat.Android/blob/acb0f6f3c89d228a36a74dfaeb6e25c56ba12d14/dependencies.gradle#L59

Just change this line to 1.16.0

**Comment by RyanSummer** [comment]
Thank you. This problem has been solved by your method. Would it be convenient to give me your email address? We can discuss other issues in the follow-up of this project.

**Comment by RyanSummer** [comment]
> [Rocket.Chat.Android/dependencies.gradle](https://github.com/RocketChat/Rocket.Chat.Android/blob/acb0f6f3c89d228a36a74dfaeb6e25c56ba12d14/dependencies.gradle#L59)
> 
> Line 59 in [acb0f6f](/RocketChat/Rocket.Chat.Android/commit/acb0f6f3c89d228a36a74dfaeb6e25c56ba12d14)
> 
>  jitsi                 : '+', // TODO Avoid using + (https://github.com/jitsi/jitsi-meet/issues/3987) 
> Just change this line to 1.16.0

Thank you. This problem has been solved by your method. Would it be convenient to give me your email address? We can discuss other issues in the follow-up of this project.

**Comment by Adizbek** [comment]
My account in rocket chat: https://open.rocket.chat/direct/Adizbek.Ergashev

If will be faster to communicate with chat.

**Comment by hfeky** [comment]
This is a duplicate of the issue #2192.
