### ISSUE TITLE
[Apache configuration issue] Android app cannot read or send messages (Browser works)

### ISSUE THREAD

**Issue by thawn** [RocketChat/Rocket.Chat.Android#2225]
## Describe the bug

* After logging in to my server, the Android app shows an empty channel list and in the `Chats` window it shows either `connecting` or `disconnected`.
* Searching for a channel works and I can enter the channel, but inside the channel I don't see any messages (it shows "No chat messages") and I cannot send messages.
* However, I can successfully create new channels. I also receive push notifications, but I cannot read the respective messages.

To me it appears like the android app fails to connect to the websocket.

I run a self-hosted rocket.chat docker instance behind an apache ssl reverse proxy in a subdirectory. For example, the server url would be `https://example.com/chat/`

The browser interface and mac desktop client work perfectly.

## To Reproduce
1. Install and open the android app
2. log in to a self hosted server (in a subdirectory via apache reverse ssl proxy)
3. The `Chats` screen appears and is empty - it shows `disconnected` or `connecting`
4. Searching for a channel provides results and it is possible to enter a channel. However, inside the channel it shows no messages and no messages can be sent

## Expected behavior

* The App should show channels that the user subscribed to in the `Chats` window. 
* Inside a channel it should be possible to read and send messages.

## Screenshots

![Screenshot_20190413-114002_RocketChat](https://user-images.githubusercontent.com/1308449/56078109-70542480-5de4-11e9-9e3e-1b5029398783.jpg)
![Screenshot_20190413-114025_RocketChat](https://user-images.githubusercontent.com/1308449/56078110-70ecbb00-5de4-11e9-8149-0971c3a60e9e.jpg)
![Screenshot_20190413-114036_RocketChat](https://user-images.githubusercontent.com/1308449/56078111-70ecbb00-5de4-11e9-9946-5baa39a3fe1d.jpg)

## Devices and Versions

Your Rocket.Chat.Android version: 3.3.0 Build 2060 - aa6be17e - play
**Edit**: also tested the app Version 3.3.1, 3.1.1 and 3.2.0 to no avail.
Your Rocket.Chat Server version: 0.74.3

Mobile device model and OS version: 
* Galaxy S8, Android 9, Patch level March 1, 2019
* Galaxy Tab S3, Android 8, Patch level Dec 1, 2018

**Comment by thawn** [comment]
Question to the developers: Do the browser and desktop apps also use the websocket or is the websocket only used by the mobile apps.

To rephrase: could it be that the fact that the mobile app does not work is a misconfiguration of my server?

Here is the relevant section of my apache ssl configuration:
```
<Location /rc>
    Require all granted

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /var/www/localhost/htdocs/(.*)           ws://localhost:3000/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /var/www/localhost/htdocs/(.*)           http://localhost:3000/$1 [P,L]

    ProxyPassReverse http://localhost:3000
</Location>
```

**Comment by hypery2k** [comment]
Maybe you also hit this error: #2290

**Comment by thawn** [comment]
@hypery2k I don't thik so. The channels are newly created and contain max. 5 messages.

**Comment by lehrhardt** [comment]
We are experiencing this as well with some of our android users (different android versions [6.x,7.x,9.x]. Problem seems to be related to android app version 3.3.0 or 3.3.1. Manually downgrading the app to 3.2.x fixes the problem.

**Comment by thawn** [comment]
I suspect that this may have something to do with the fact that I am running the app on the server behind an apache reverse proxy in a subdirectory (I unfortunately don't have a choice there).
@lehrhardt do you have a similar server setup?

**Comment by reetp** [comment]
99.9% of the time this will be proxy related. Your web server logs will probably tell the tale.

Web browsers try to connect with a websocket. If that fails they fall back to a XHR connection. You can tell that from your web browser developer console. It will work, but like it is in treacle. Very slow.

In Chromium/e go to Inspect, Network, refresh the page and look for WS and you should see a websocket connection. Test on https://open.rocket.chat so you can compare.

However, the apps will seriously mess about. iOS is the worst - no websockets, no connection. Simple.

In your browser you should see some stuff like this from the websocket connection:

Request URL: wss://open.rocket.chat/sockjs/081/uw2xhujd/websocket
Request Method: GET
Status Code: 101 Switching Protocols
.....
Host: open.rocket.chat
Origin: https://open.rocket.chat
.....
Sec-WebSocket-Version: 13
Upgrade: websocket

So, no matter if you are in a subdirectory or whatever **go back and check your proxy** 

 (subdirs do have their own issues but work perfectly well - have a read of other issues and the documentation)

Note this Issue is almost certainly not a bug but a support Issue and should be closed and a question asked in the forums or open.rocket.chat

**Comment by tars21** [comment]
We are running RocketChat behind a reverse proxy (haproxy) but not in subdirectory (@thawn).

I'll take a deeper look into our haproxy, but at first sight I don't see something conspicuous. I see the GET websocket 101 similar to open.rocket.chat at our instance.
Why does this problem affects the Android app 3.3.x but nothing else (older version, desktop app, GUI)?

**Comment by thawn** [comment]
I just tried Versions 3.1.1, 3.2.0, 3.3.0 and 3.3.1 none of them work.
The strange thing is, that there definitely is a working connection to the server. I can even change my password and create a channel from within the app. The only thing that does not work is sending or receiving messages.

**Comment by thawn** [comment]
Small correction:
With versions 3.1.1 and 3.2.0 I was able to **send** messages but **could not read** any messages.

**Comment by hypery2k** [comment]
for me websocket is working in nginx and I can see also 101 requests

**Comment by thawn** [comment]
@reetp thank you very much for the extensive reply! Your hunch was entirely correct (I guess I was among the 99.9%). The problem was that I had a rewrite rule in my apache configuration, that caused all websocket connections to be redirected to a mattermost instance. After moving the mattermost configuration into the respective <Location> section, it all works fine (both mattermost and rocket.chat)
In case anyone else encounters a similar problem with two websocket applications behind an apache reverse proxy:
The configuration that **works**:
```
<Location /mm>
        RewriteEngine On
        RewriteCond %{REQUEST_URI} /mm/api/v[0-9]+/(users/)?websocket [NC,OR]
        RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
        RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
        RewriteRule .* ws://127.0.0.1:8065%{REQUEST_URI} [P,QSA,L]
        Require all granted
        ProxyPass http://127.0.0.1:8065/mm
        ProxyPassReverse http://127.0.0.1:8065/mm
        ProxyPassReverseCookieDomain 127.0.0.1 thawn.noip.me
</Location>

<Location /rc>
    Require all granted

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /var/www/localhost/htdocs/(.*)           ws://localhost:3000/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /var/www/localhost/htdocs/(.*)           http://localhost:3000/$1 [P,L]

    ProxyPassReverse http://localhost:3000
</Location>
```
The configuration that **did not work**:
```
RewriteEngine On
RewriteCond %{REQUEST_URI} /mm/api/v[0-9]+/(users/)?websocket [NC,OR]
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
RewriteRule .* ws://127.0.0.1:8065%{REQUEST_URI} [P,QSA,L]
<Location /mm>
        Require all granted
        ProxyPass http://127.0.0.1:8065/mm
        ProxyPassReverse http://127.0.0.1:8065/mm
        ProxyPassReverseCookieDomain 127.0.0.1 thawn.noip.me
</Location>

<Location /rc>
    Require all granted

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /var/www/localhost/htdocs/(.*)           ws://localhost:3000/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /var/www/localhost/htdocs/(.*)           http://localhost:3000/$1 [P,L]

    ProxyPassReverse http://localhost:3000
</Location>
```
Note how in the not-working case, the rewrite rule for mattermost was outside the location tag.

**Comment by tars21** [comment]
In our haproxy config I've added some lines from [here](https://www.haproxy.com/de/blog/websockets-load-balancing-with-haproxy/), i. a.
`timeout tunnel 3600s`
was missing.
From now on reading and sending messages out of the Android App is working for newer versions.

**Comment by hypery2k** [comment]
any ideas why we still experience issues with nginx?
```
upstream backend {
    server 127.0.0.1:3000;
}

server {
  listen 80 default_server;
  listen [::]:80 default_server ipv6only=on;

  return 301 https://$host$request_uri;
}

server {

  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name myhost.com;


  location / {
    # don't send the nginx version number in error pages and Server header
    server_tokens off;

    # config to don't allow the browser to render the page inside an frame or iframe
    # and avoid clickjacking http://en.wikipedia.org/wiki/Clickjacking
    # if you need to allow [i]frames, you can use SAMEORIGIN or even set an uri with ALLOW-FROM uri
    # https://developer.mozilla.org/en-US/docs/HTTP/X-Frame-Options
    add_header X-Frame-Options SAMEORIGIN;

    # when serving user-supplied content, include a X-Content-Type-Options: nosniff header along with the Content-Type: header,
    # to disable content-type sniffing on some browsers.
    # https://www.owasp.org/index.php/List_of_useful_HTTP_headers
    # currently suppoorted in IE > 8 http://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx
    # http://msdn.microsoft.com/en-us/library/ie/gg622941(v=vs.85).aspx
    # 'soon' on Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=471020
    add_header X-Content-Type-Options nosniff;

    # This header enables the Cross-site scripting (XSS) filter built into most recent web browsers.
    # It's usually enabled by default anyway, so the role of this header is to re-enable the filter for
    # this particular website if it was disabled by the user.
    # https://www.owasp.org/index.php/List_of_useful_HTTP_headers
    add_header X-XSS-Protection "1; mode=block";

    # with Content Security Policy (CSP) enabled(and a browser that supports it(http://caniuse.com/#feat=contentsecuritypolicy),
    # you can tell the browser that it can only download content from the domains you explicitly allow
    # http://www.html5rocks.com/en/tutorials/security/content-security-policy/
    # https://www.owasp.org/index.php/Content_Security_Policy
    # I need to change our application code so we can increase security by disabling 'unsafe-inline' 'unsafe-eval'
    # directives for css and js(if you have inline css or js, you will need to keep it too).
    # more: http://www.html5rocks.com/en/tutorials/security/content-security-policy/#inline-code-considered-harmful
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ssl.google-analytics.com https://assets.zendesk.com https://connect.facebook.net; img-src 'self' data: 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://assets.zendesk.com; font-src 'self' https://themes.googleusercontent.com; frame-src https://*.rocket.chat; connect-src 'self' wss://myhost.com; object-src 'none'";

    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto http;
    proxy_set_header X-Nginx-Proxy true;
    proxy_http_version 1.1;
    proxy_set_header Connection "upgrade";

    add_header Referrer-Policy same-origin always;

    proxy_redirect off;
    proxy_pass http://backend/;
    proxy_send_timeout 300;

    tcp_nodelay on; 

    client_max_body_size       10m;
    client_body_buffer_size    128k;

    proxy_connect_timeout      300;
    proxy_send_timeout         300;
    proxy_read_timeout         300;

    proxy_buffer_size          4k;
    proxy_buffers              4 32k;
    proxy_busy_buffers_size    64k;
    proxy_temp_file_write_size 64k;
  }

  # deny access to .htaccess files
  location ~ /\.ht {
         deny all;
  }
  # deny access to the .jar file
  location ~ /\*.jar {
           deny all;
  }
}

```

**Comment by fabius** [comment]
@hypery2k - using this nginx vhost config, our mobile apps are up and running:

```
server {
  listen 443;
  server_name sub.domain.com;
  client_max_body_size 200M;
  location / {
    proxy_pass http://backend/;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forward-Proto http;
    proxy_set_header X-Nginx-Proxy true;

    proxy_redirect off;
}
```

**Comment by hypery2k** [comment]
thanks, with the increased client_max-body_size it seems to work
