### ISSUE TITLE
[BUG] Channel Details view is not showing that a channel is favorite 

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#2234]
When opening the Channel Details view the favorite icon isn't working as expected. It should show the favorite icon when a channel is starred from the user.

**Comment by Adizbek** [comment]
I'll work on it.

**Comment by Adizbek** [comment]
@filipedelimabrito  But there is no bug? I tried many times, every works nice. maybe I got you wrong?

**Comment by Adizbek** [comment]
I got it.
