### ISSUE TITLE
[BUG] The last item is not visible in settings menu

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#2238]
Your Rocket.Chat.Android version: 3.4.0 (2061)
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.74.3

Possibly due to the fact that for administrators there is a menu item "Admininistration".
![IMG_20190419_103943](https://user-images.githubusercontent.com/18574776/56413251-86a02b80-628f-11e9-9529-566e4c7bb9de.jpg)

**Comment by Adizbek** [comment]
Thanks for submitting issue. I'll work on it.
