### ISSUE TITLE
Detecting audio/video call in rocket chat iOS app

### ISSUE THREAD

**Issue by hesham91fci** [RocketChat/Rocket.Chat.Android#2240]
Currently in my **iOS** app I'm using rocketchat integrated with Jitsi so as to enable audio and video calls.
currently when I send a call through the functionality `openAudioOrVideoCall` the other end user when **receives** this call, there is no way to detect whether this is an audio or video call so it mutes/unmutes the camera. Is there a way to get this working in my app ?.
Any help would be appreciated, best regards :)

**Comment by Adizbek** [comment]
It's android repository, IOS related issue should be submitted to https://github.com/RocketChat/Rocket.Chat.iOS
