### ISSUE TITLE
[BUG] Chat sorting options not visible in pop-up when phone orientation is landscape.

### ISSUE THREAD

**Issue by noor-binte-amir** [RocketChat/Rocket.Chat.Android#2253]
## Describe the bug

Chat sorting options not visible in pop-up when phone orientation is landscape.

## To Reproduce

1. Hold phone in horizontal orientation.
2. Tap the sorting button at the top right.
3. Sorting options are inaccessible.

## Expected behavior

Sorting options should be accessible in horizontal orientation.

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.0

## GIF

![issue horizontal-2253](https://user-images.githubusercontent.com/30703644/56494037-6cbe4d00-650a-11e9-88e6-38955173dd92.gif)

**Comment by noor-binte-amir** [comment]
@filipedelimabrito I'd like to work on the issue.

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2328
