### ISSUE TITLE
Messages notifications feature

### ISSUE THREAD

**Issue by CodazziS** [RocketChat/Rocket.Chat.Android#226]
Hello,
I see in #215 , you support push. No idea if it's used for notifications, but on V1.0.5 I don't have any notifications on my phone when i'm mentioned (@name) in a message.

Any plan to support messages notifications ?

**Comment by laggedHero** [comment]
Hello @stephane- ,

We already support message notifications. We add up support for the push notiication in order to easy up the test of your own server.

If that's the case: are you an Admin on your server? Would you mind trying `send a push test` to yourself (in Administration -> Push)?

That may help troubleshot the problem. If you receives the test push, the problem may lie somewhere else and not in the app.

**Comment by CodazziS** [comment]
Hello,
Thank you for answer.

I tried to send a push notification (In administration -> Push), and don't receive any notification. 
If I install the "old" application ( rocket chat: https://play.google.com/store/apps/details?id=com.konecty.rocket.chat&hl=fr ) the notification working. But not working with RocketChat+.

In admin panel, when I send a push test, (Only when legacy Rocket chat is uninstalled) I have an error  (no token for the current user) :
![rc](https://cloud.githubusercontent.com/assets/8134250/23513136/4c1df3b6-ff63-11e6-8316-0bd2bb9c2d6f.PNG)

In my account settings, the preserving brandwidth option is disable.

Server logs are emptly.

**Comment by CodazziS** [comment]
Test push with RocketChat+ (don't work) :
```
[34mI20170302-16:26:01.937(1) [34mMeteor ➔ method push_test -> userId: WkLcWrRyDcZaoxvzZ , arguments:  {} 
[34mI20170302-16:26:10.740(1) [34mMeteor ➔ method push_test -> userId: WkLcWrRyDcZaoxvzZ , arguments:  {} 
```

Test push With legacy RocketChat application (work) : 
```
[34mI20170302-16:30:07.778(1) [34mMeteor ➔ method push_test -> userId: WkLcWrRyDcZaoxvzZ , arguments:  {} 
[34mI20170302-16:30:08.329(1) Push: send message "@Azzod" via query { userId: 'WkLcWrRyDcZaoxvzZ' } 
[34mI20170302-16:30:08.331(1) Push: send to token { gcm: 'fHo2xBhe8W0:APA91bEqTGdTz4ynizXq2CjFFjA5aZLi8KXpx-DaTBWd95N7WaKCqju0xLZ2Hp1ndtmDu2TJTdrvbaAPPsLN7122i70SoVhYPTKTNKLTyCS0wWAb08VXQ94wBB26ISVbhugWK4GvwDZi' } 
```

**Comment by laggedHero** [comment]
It looks like the same problem as #206 . You can follow that issue, please.
