### ISSUE TITLE
[BUG] Unable to check Other Users Profile details.

### ISSUE THREAD

**Issue by Cool-fire** [RocketChat/Rocket.Chat.Android#2272]
## Describe the bug
Unable to see the other user profile details on clicking the profile picture. An error pops up saying "Error Occurred Please try again"

## To Reproduce

![Screenshot_2019-04-29-16-19-51-820_chat rocket android dev](https://user-images.githubusercontent.com/25877454/56891711-ffc32e00-6a9a-11e9-9e18-9bc04a2ab2e1.png)
## Devices

Mobile device model and OS version: ("Redmi note 5 - Android 8.0.1")

**Comment by Adizbek** [comment]
I will work on it :+1:

**Comment by Cool-fire** [comment]
@Adizbek Thanks but I am working on it.

**Comment by Adizbek** [comment]
Which app version do you use.

**Comment by Adizbek** [comment]
Okay.

**Comment by hfeky** [comment]
This can also be a duplicate of #2195.

**Comment by filipedelimabrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2273

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2273
