### ISSUE TITLE
1.0.1 - Rocket.Chat Mobile app will not load

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat.Android#2275]
### Description:

The app will not load since 1.0.1 -  I see only this message on Android: 
Sorry an error has occurred, please try again 
There is nothing in the logs.

Version - 1.0.1
Apps Engine Version - 1.4.2
Database Migration - 143

Android App version - 3.3.0, build 2060

**Comment by pstambrecht** [comment]
@rafaelks Thanks for reaction. I'm looking for new RC version.

**Comment by himpierre** [comment]
The foss app does not seem to be affected or am i just lucky?

**Comment by hypery2k** [comment]
duplicate of #2223 or?

**Comment by hypery2k** [comment]
the version 3.3.1 was published in playstore but in this version the login is not possible. Always getting:
`length=0;index=0`

Update: Seems related to our OAuth Redirect. The service color was missing in the client settings: https://github.com/RocketChat/Rocket.Chat.Android/blob/6065ebdebc3038d90801a0b8b3fed591468402bd/app/src/main/java/chat/rocket/android/server/presentation/CheckServerPresenter.kt#L547

I think it should be having a default value

**Comment by hypery2k** [comment]
BTW: you can make a quick and dirty fix by setting "button label text color" in your custom oAuth Service on the server side

**Comment by philipbrito** [comment]
Guys, this bug was [fixed](https://github.com/RocketChat/Rocket.Chat.Android/pull/2280).
Thanks for posting the logs/JSON here (c/c @pstambrecht).
 I'm closing this issue.
