### ISSUE TITLE
[BUG] Error while changing language

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#2276]
Your Rocket.Chat.Android version: 3.4.0 (2062)
Mobile device model: Xiaomi Redmi 3
OS version: Lineage OS, Android 7.1.2
Your Rocket.Chat Server version: 0.74.3

When changing the language, an error occurs:

![1](https://user-images.githubusercontent.com/18574776/56981240-0af38800-6b87-11e9-9697-98c1754625a9.png)

**Comment by hfeky** [comment]
I do not think it is an error due to changing language, but certainly it is an error due to something else.

**Comment by Pitstopper** [comment]
Maybe. But I have it appears when changing language

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2334
