### ISSUE TITLE
Upload app on Appetize.io 

### ISSUE THREAD

**Issue by GOVINDDIXIT** [RocketChat/Rocket.Chat.Android#2278]
## Describe the chore

Upload app on Appetize.io for better App previews, automation and testing.

### Would you like to work on this
Yes

@filipedelimabrito Your views?

**Comment by philipbrito** [comment]
@GOVINDDIXIT As we discussed it's not completely free. I'd also suggest opening a post on our forum, so everyone from RC team can discuss it. By opening you can tell us why using that service is good. Thank you!
