### ISSUE TITLE
[BUG] Emoji reactions not shown on Android app

### ISSUE THREAD

**Issue by hfeky** [RocketChat/Rocket.Chat.Android#2288]
## Describe the bug

When I click on an emoji when reacting to a message, it reacts, but it is not shown as reacted on the Android app; however, if you go to the desktop version, you will find that the message got reacted, and the emoji is visible.

## To Reproduce

1. Go to any chat.
2. Click on any message.
3. From the bottom sheet, click on Add reaction.
4. Choose any emoji.
5. Message will not be shown as reacted on the Android app but will be shown as reacted on the desktop version.

## Expected behavior

When clicking on an emoji, it should react to the selected message, showing it.

## Screenshots

Note that this does not demonstrate that the message is reacted on the desktop version; however, it shows that the message is shown as not reacted on the Android app.

![Emoji Reaction Issue](https://user-images.githubusercontent.com/20887574/57172724-1ca58b80-6e24-11e9-82b5-4585c5a18c19.gif)

## Versions

Rocket.Chat.Android version: 3.4.0 (2065)
Rocket.Chat Server version: 1.1.0-develop

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2352
