### ISSUE TITLE
Warning "File exceedes allowed size" does not go away

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat.Android#229]
Your Rocket.Chat.Android version: 2.5.0

If uploading a file > 2 MB I get the warning "File exceedes allowed size", which is okay, because this is my actual limit. But the warning does not go away and is shown forever.

Ciao
Marcus

**Comment by localguru** [comment]
Ah, sorry. I didn't see "close". I had to rotate the screen to landscape ;)

**Comment by laggedHero** [comment]
Hmm. The native app (this project) latest app version is `1.0.5`. Per you version number I'd say that you're talking about the Cordova app (https://github.com/RocketChat/Rocket.Chat.Cordova).

So I did open an issue there (https://github.com/RocketChat/Rocket.Chat.Cordova/issues/178) and I'm closing this one.
