### ISSUE TITLE
Reaction not working since recent Android app update. 

### ISSUE THREAD

**Issue by Ytheleus** [RocketChat/Rocket.Chat.Android#2297]
After updating to Android RocketChat app version 3.3.1, chat reactions are no longer working properly in Android app. 

No reactions appear in the Android client but the reaction appears in the Web client. 

Reactions update in the Android app after clearing cache and data on the app but then does not show any further reactions. 

Devices and Versions

Samsung Galaxy S8
Huawei P20lite

Both on Android 8.0.0

Rocket.Chat.Android version: 3.3.1
Rocket.Chat Server version: 0.74.3

**Comment by hfeky** [comment]
This issue is already mentioned in #2288.

**Comment by philipbrito** [comment]
Let's track the state of this bug from #2288 since it was mentioned there before this issue.
I'm closing this duplicate issue.
Thanks.
