### ISSUE TITLE
[BUG] Weird behaviors in Directory search

### ISSUE THREAD

**Issue by hfeky** [RocketChat/Rocket.Chat.Android#2298]
## Describe the bug

When I open the Directory to search for a channel/user, weird behaviors happen.

If I choose a channel that I am already in, _Join Chat_ button appears although it should not. And if I click on it, it says that I am muted although I am not.

And if I choose a new channel and try sending any message, the app does not respond.

## To Reproduce

1. From `ChatRoomsFragment`, click on search in the toolbar.
2. Go to Directory.
3. Choose any channel/user.
4. Issue will occur.

## Expected behavior

I assume the opposite thing should happen.

1. The app should open the channel normally if I am already in it, not showing that _Join Chat_ button, and check for user mute correctly.

2. The app should show _Join Chat_ button for channels that I am not in.

## GIF

![Directory search](https://user-images.githubusercontent.com/20887574/57186751-55f20000-6ee5-11e9-8f5f-6c9a1bac7a63.gif)

## Versions

Rocket.Chat.Android version: 3.4.0 (2065)
Rocket.Chat Server version: 1.1.0-develop

**Comment by noor-binte-amir** [comment]
Thankyou for posting the issue @HusseinElFeky. Is it taken or may I work on it?

**Comment by hfeky** [comment]
@NBAMIR You can surely work on it.

**Comment by philipbrito** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat.Android/issues/2100. Closing.
