### ISSUE TITLE
[NEW] Missing support for SSO login

### ISSUE THREAD

**Issue by guss77** [RocketChat/Rocket.Chat.Android#230]
Your Rocket.Chat.Android version: 1.0.5

While the Cordoba application allows login using SSO methods configured on a deployed Rocket.Chat server,  the new Android application only supports password login

**Comment by mmarif4u** [comment]
So far i see only Github, Google, Facebook, Twitter and Password based logins are implemented. By any chance, is there any work going on Gitlab SSO implementation?

**Comment by rafaelks** [comment]
We're going to handle all authentication methods soon.

**Comment by thef1sh** [comment]
The 'Cordova' apps had a troubling update to the README file saying that their apps will be deprecated at the end of March. For those of us using these auth methods, if deprecated means delisted, we're without a mobile app for our instance unless this is resolved.

**Comment by rafaelks** [comment]
@thef1sh We'll support all the authentication methods supported from Cordova by March, that's for sure.

**Comment by philipbrito** [comment]
Currently (Android 2+), we are supporting the authentication with:

- username + password
- email + password
- CAS
- LDAP
- Gitlab

Refs: #833 #871 #855 #965

We are working hard to put others (Github, Twitter, etc).

**Comment by brtptrs** [comment]
I can confirm version 2.0.0-alpha1 is working with CAS Authentication. Thanks!!

**Comment by philipbrito** [comment]
Update: Github, Google and Linkedin OAuth become supported.

Refs: #966 #969 #973

**Comment by rafaelks** [comment]
Let's close this issue, every method now has it's own issue, many of them are already present in 2.0.0.
