### ISSUE TITLE
Exception while invoking method 'jitsi:updateTimeout' (Black screen in Jitsi Meet View.)

### ISSUE THREAD

**Issue by franckadil** [RocketChat/Rocket.Chat.Android#2312]
## Describe the bug

Black screen in Jitsi Meet View.

## To Reproduce

1. Go to Video Chat
2. Start a video chat with a user or in a channel or try to join a video call

## Server Log

Checking: executePostMessageSent 
I20190512-14:38:52.009(0) Exception while invoking method 'jitsi:updateTimeout' TypeError: Cannot set property 'msg' of undefined     at MethodInvocation.jitsi:updateTimeout (app/videobridge/server/methods/jitsiSetTimeout.js:36:4)     at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:73:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

## Devices and Versions

Android 6.0 / 7.0 / 9.0

Version 1.0.2 behind Nginx Proxy.
--
App Engine 1.4.2
Database Migration143
PID 1
Runnung Instance1
OPlog Enabled

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by philipbrito** [comment]
The bug with the black screen is already fixed on app version 3.5.0
