### ISSUE TITLE
[BUG] App stoped when click back after changed language

### ISSUE THREAD

**Issue by lushohammy** [RocketChat/Rocket.Chat.Android#2323]
## To Reproduce

1. Go to language
2. Change any language
3. and try to close the app 
4. See error -->

## Expected behavior
user should be able to smoothly exit app without showing stoped .

## Devices and Versions

* Rocket.Chat.Android version: 3.4.1(2069)
* Rocket.Chat Server version: 1.1.0-develop

* Android version: 8.1.0 OPMI

## Additional context
https://youtu.be/xlsmoDp07tI

**Comment by philipbrito** [comment]
Closed by #2334
