### ISSUE TITLE
[BUG] Can't delete account

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.Android#2329]
## Describe the bug
Trying to delete my account, keeps telling me incorrect password, although I can log in with password

## To Reproduce
1. Login
2. Click on settings menu
3. Click on Delete account
4. Type your password
5. Check message that says password is incorrect

## Expected behavior
Account should be deleted

## Devices and Versions
 v3.4.1 - (2069) 
samsung  - SM-G960U 
Android 8.0.0

Also on
OnePlus - ONEPLUS A5000
Android 9

Your Rocket.Chat Server version: 1.1.0-develop

**Comment by HartwigFlamm** [comment]
After setting up my development server several times, I managed to lock my Android phone out.
It won't log out from the server (You have to be logged in to do this) and I can not remove the server from the app.
Android Client 3.4.2 (2070); Server 1.1.1
