### ISSUE TITLE
[Urgent] After upgrade to 3.3.0 -> 3.4.1, nothing works, empty channel list

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#2341]
## Describe the bug
After upgrading to 3.4.1, the channel list is blank and it's impossible to chat. This is causing obvious problems in production, and we would appreciate it if the core team could take a look. We may be in a position to fund priority support depending on the situation, please advise.

I wrongly guessed it was a server issue and upgraded to 1.0.3 from 0.7x, but it didn't help.

I believe that anything after 3.3.0 is broken for us, which is weird as the release notes for 3.3.1 state "We have fixed an annoying bug that makes the chat list not showing for some servers.". Perhaps the fix broke stuff for other servers?

## To Reproduce
Open app.

## Expected behavior
Expect to see channel list. See nothing except for the header.

## Logs
I don't see anything useful in the logs. Server logs look fine, Android logs don't have anything of interest. Happy to dig deeper if you guide me.

## Screenshots
![image](https://user-images.githubusercontent.com/295571/58332781-a3a6bc00-7e44-11e9-8d12-7ec0b8b0bf19.png)

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.1
Your Rocket.Chat Server version: 1.0.3

Mobile device model and OS version: OnePlus 3T / Android 7.1.2, but happening to colleagues as well.

## Additional context

Clicking on search button (magnifying glass) and clicking on Directory shows a list of channels. But clicking on a given channel results in an error message as below:

![image](https://user-images.githubusercontent.com/295571/58333156-7eff1400-7e45-11e9-9fcd-b2db1039d801.png)

**Comment by all3kcis** [comment]
Same as #2308

**Comment by antgel** [comment]
Yes, it looks the same. Closing this to focus discussion there.
