### ISSUE TITLE
Unread message indicator

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat.Android#235]
Your Rocket.Chat.Android version: 1.06

I am using unread rooms mode = true. 

Im seeing rooms stay in the 'unread rooms' menu and remain bolded in the native android app when I've already opened and read the new messages

**Comment by RichardFoxworthy** [comment]
Actually the real problem is that there is no unread messages indicator visible - so can't jump to first unread etc, and the room remains in unread mode and its impossible to know how far to scroll up the message history to the first unread message. 

In smaller channels with little message traffic the unread room indicator updates immediately. Changing name for this issue to 'unread messages indicator'

**Comment by rafaelks** [comment]
Fixed already!
