### ISSUE TITLE
Video conference for android < M

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat.Android#2356]
https://github.com/RocketChat/Rocket.Chat.Android/blob/6f2f5c88754d520e91f8087166117cabe51acfbf/app/src/main/java/chat/rocket/android/chatroom/presentation/ChatRoomNavigator.kt#L29

could someone check of we sill need that condition the pull got merged

**Comment by philipbrito** [comment]
Jitsi has solved this issue and it is working now with Android M- versions. We have removed that condition already.
