### ISSUE TITLE
[IMPROVEMENT] Long data loading on Settings view/ Settings view not ready when opening it

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#2357]
We can see that the Settings view is not ready (some data is missing) when opening it. After some time the data is being show to the user.

There is a delay when getting the:

- User avatar;
- User username;
- App version;
- Server version;
- Switch for send analytics option (when it is enabled);
- Delete account text.

We should make this screen/view ready when opening it or at least show a progress until we get all needed information/data.

**Comment by weijia-yu** [comment]
@filipedelimabrito can I take this issue?

**Comment by philipbrito** [comment]
Hi @weijia-yu! Sure! Feel free to work on it! Thank you!

**Comment by weijia-yu** [comment]
@filipedelimabrito Can you specify what do you mean by  "We should make this screen/view ready when opening it".

Should we wait for the network request and then show the page?
