### ISSUE TITLE
Android APK (3.4.1, 3.4.2) does not display channels or private conversations

### ISSUE THREAD

**Issue by RoseKitsune** [RocketChat/Rocket.Chat.Android#2360]
## Description
We are running a Docker version of Rocket.chat via docker-compose for a private group.  The Docker version was running 0.74.3 of Rocket.Chat and MongoDB 3.6.

Within the last week, we had reports of users unable to view channels or private chats through their mobile apps.  This issue appeared on a variety of devices with versions 3.4.1 and 3.4.2 of the Android APK.  Some users had no issue until they logged out and re-authenticated.

Use of Rocket.Chat Experimental seems to bypass this issue.

Given stability issues, we pulled the trigger on upgrading to the latest Rocket.Chat app in the Docker repository (1.1.1 as of June 6, 2019).

This did not resolve the issue.

This seems related to Rocket.Chat.Android #2308.

A fresh installation of the Rocket.Chat server with a clean database doesn’t recreate the issue.  This suggests an issue with the older database not being compatible with the current client, which was not resolved with the upgrade.

Attempts to force-stop the Android client, clear cache, clear storage, un-install, and re-install the app also do not resolve the issue.

## To Reproduce

1. Log out of Android client
2. Re-authenticate to Android client

Result: An empty activity screen with the error "Sorry, an error has occurred, please try again."  An inability to open any channel or private communication.

## Devices and Versions
Rocket.Chat Android APK (version 3.4.1, 3.4.2)
Rocket.Chat Docker Image (versions 0.74.3, 1.1.1)
MongoDB (version 3.6.9, 4.0)

## Additional context
Users are still able to view a partial list of channels by navigating to the channel search (Magnifying glass) and clicking on Directory. 

The following error message is generated on the server side logs upon navigating to the directory and attempting to view a channel that the user is not already a member of.  This does not occur for channels that the user is already a member of.

`Exception in defer callback: TypeError: Cannot read property 'ls' of undefined     at Meteor.defer (server/methods/readMessages.js:26:81)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at packages/meteor.js:620:25     at runWithEnvironment (packages/meteor.js:1356:24) `

Users are also able to receive notifications of messages sent to them, or for channels they have configured to receive notifications from.

**Comment by pinzolits** [comment]
Same here.

**Comment by wpater** [comment]
Not sure that is related but sounds similar - on Android 8 and 9 with the newest version of app I cannot add my server and connect with it. On Android 5 works properly. I have checked Experimental version and it shows only "invalid url".
SSL is ok (A+ on www.ssllabs.com).

Website and desktop app work good.

**Comment by reetp** [comment]
I think this is a duplicate of 2308

You will need to test with v3.4.2 which was the fix for the original issue.

**Comment by RoseKitsune** [comment]
> I think this is a duplicate of 2308
> 
> You will need to test with v3.4.2 which was the fix for the original issue.

We have tested on v3.4.2.  The newest APK and the version from the Play Store does not resolve the issue.

**Comment by klesher** [comment]
This is still an issue even after running a `Force Stop`, navigating to `Storage`, hitting `Clear Cache`, & `Clear storage`, uninstalling, and re-installing the app.  

After re-installing, I am not prompted for my server/login info even though my cache/storage was cleared and I still receive the "Sorry, an error has occurred, please try again." toast. Is there somewhere else not covered by these methods that I can remove files from to get an even "cleaner" re-install?

If attempting to log out of the app, I receive results similar to https://github.com/RocketChat/Rocket.Chat.Android/issues/2375

Rocket.Chat Experimental seems to work with no issues, but I'd rather not rely on that if I can avoid it if it's considered to be an _experimental_ version.

**Comment by reetp** [comment]
> Rocket.Chat Experimental seems to work with no issues, but I'd rather not rely on that if I can avoid it if it's considered to be an _experimental_ version.

[OT but anyways]

I don't think there is much to choose ;-)

It WAS very experimental but has come on leaps and bounds, and has proper thread support. No it may not have all the main apps features, but is pretty good and I have used it daily for months including testing out some SERIOUSLY Alpha versions direct with the dev....

One phone I have runs both versions just for good measure too.. :-)

I believe also that the 'direction of travel' is for the React app to become the defacto app. So come help debug & fix!

**Comment by nbara** [comment]
> This is still an issue even after running a Force Stop, navigating to Storage, hitting Clear Cache, & Clear storage, uninstalling, and re-installing the app.
> After re-installing, I am not prompted for my server/login info even though my cache/storage was cleared and I still receive the "Sorry, an error has occurred, please try again." toast. Is there somewhere else not covered by these methods that I can remove files from to get an even "cleaner" re-install?

Same problem confirmed with 3.4.2 on two handhelds : 
- Honor 9 lite
- Samsung Galaxy S8

**Comment by philipbrito** [comment]
@nbara Make sure to test our latest release. In this case, `3.5.0 (2074)`.

**Comment by klesher** [comment]
Confirmed this is now working for me on 3.5.0.  Thanks all!
