### ISSUE TITLE
Token not removed after logout - user still receiving notifications

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.Android#2361]
## Describe the bug
Hi, we are using official Rocket Chat Android app. When user logout form app, user token is not removed form '_raix_push_app_tokens' collection. User still receiving push notifications.
Another case when I logout and next login another user I am receiving notfications from first user, bacuse his token is still in database.
I have tested also on iOS app, and there issue not exists. Token is removed from '_raix_push_app_tokens' collection after logout.

## To Reproduce

1. Logout from  Rocket Chat Android app
2. Check '_raix_push_app_tokens' collection, token still exists
3.  User still receiving push notifications

## Expected behavior
After logout token removed from '_raix_push_app_tokens' collection, user not receiving push notifications

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.2
Your Rocket.Chat Server version: 1.1.1

Mobile device model and OS version: LG G6 Android 8.0.0

**Comment by philipbrito** [comment]
Duplicate of https://github.com/RocketChat/Rocket.Chat.Android/issues/2322
