### ISSUE TITLE
Cannot Join a new Channel

### ISSUE THREAD

**Issue by TannerJuby1** [RocketChat/Rocket.Chat.Android#2367]
## Describe the bug
When I go to search for a channel and join a new one I have not already joined, I am prompted with a chatroom with no messages and not options to join the channel.

## To Reproduce
1. Download the app
2. Search for a channel

## Expected behavior
You should see a `Join Channel` button when 

## Screenshots
![Screenshot_1556133445](https://user-images.githubusercontent.com/10744929/59297584-ca872f80-8c45-11e9-8df4-e416824b0820.png)

![Screenshot_1556133462](https://user-images.githubusercontent.com/10744929/59297579-c78c3f00-8c45-11e9-987b-276695b27815.png)

![Screenshot_1556133468](https://user-images.githubusercontent.com/10744929/59297576-c4914e80-8c45-11e9-8c2e-e32de6fe48e9.png)

## Devices and Versions
Pixel 2 XL, API 28

Your Rocket.Chat.Android version: Whatever the latest store release is in
Your Rocket.Chat Server version: Whatever `open.rocket.chat` is on

## Additional context
Emailed @rafaelks about this issue back in April and was directed to email @filipedelimabrito, so I did and received zero response. Checked back in a week later and was ignored again. Hopefully this will get something going.

**Comment by hfeky** [comment]
This is a duplicate of #2298.

**Comment by TannerJuby1** [comment]
Thanks, the title of that issue didn't appear when searching for this issue.
