### ISSUE TITLE
[BUG] Cannot send messages in new private conversation

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat.Android#2368]
## Describe the bug
It is not possible to send a message to user that has never been written in private conversation. When conversation was started from web or desktop client everything is fine.

## To Reproduce

1. Start private conversation with user that has never been written
2. Try send message
3. Message is not sent

## Expected behavior
Message is sent to user that has never been written

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.2
Your Rocket.Chat Server version: 1.1.1

Mobile device model and OS version: LG G6 Android 8.0.0

**Comment by softwareDeployerSean** [comment]
When can you solve it?   thanks

**Comment by Ky-ren** [comment]
same problem here..
Rocket.Chat.Android version: 3.4.2
Rocket.Chat Server version: 1.1.3

**Comment by antgel** [comment]
@softwareXiaotao I'd suggest reading about the open source ecosystem. Feel free to submit a PR, or perhaps offer a bounty to expedite the fix.

**Comment by Ky-ren** [comment]
Just a workaround, but the Rocket.Chat experimental app works fine (at least in my case).

https://play.google.com/store/apps/details?id=chat.rocket.reactnative&hl=de

**Comment by franckadil** [comment]
Hi guys, I have successfully reproduced this behavior each time I have done a 
`git clone URL`

This actually downloads the Master branch and not the Develop branch we are supposed to all use.

I advise doing `git clone --branch develop URL`.

Best regards,
