### ISSUE TITLE
Android to Rocket.Chat

### ISSUE THREAD

**Issue by Hutsalod** [RocketChat/Rocket.Chat.Android#2373]
Good afternoon, I have an error connecting the android to Rocket.Chat
Sites
chat.weltwelle.com
weltwelle.com

**Comment by philipbrito** [comment]
Hi @Hutsalod, something is wrong with your server that make it not working even from a web browser. I'm going to close this issue since it is not a bug from our Android side. 
If you need some help then check out our community/support channels on our open server please.
