### ISSUE TITLE
[Feature Request] Compiling the app to only allow a single server

### ISSUE THREAD

**Issue by DonaldTsang** [RocketChat/Rocket.Chat.Android#2376]
## Describe the feature you'd like
Assume that I start my own server, I would like to make the Mobile client to only access my server, or at least treat my server as "first class" such that I can distribute the compiled app binaries to my fans/users.
Is there a config file variable that allows for this to be done easily?

**Comment by philipbrito** [comment]
You are free to change the code to allow only your server to be accessed (from a fork for instance). If you need help doing it than I advise you to check for the white label

**Comment by DonaldTsang** [comment]
@filipedelimabrito better to have the link to the related settings here

**Comment by philipbrito** [comment]
@DonaldTsang It is not a simple setting to be changed in order to do what you want. That said, do it by yourself (you are free to do that) or check for our white label service - we will be glad to help you.
