### ISSUE TITLE
Blank screen with video chat

### ISSUE THREAD

**Issue by gerroon** [RocketChat/Rocket.Chat.Android#2386]
Hi

I am using RChat Docker(proxied over Apache) on Debian Testing and I also have Jitsi Meet in the same server. Both of them works perfectly as far as I can tell. 

I added my own Jitsi-Meet in the Jisti tab in admin panel. I can use this jitsi conference in Chromium on Linux in Rocket.Chat rooms , I can start a video call and the videocall on my Jitsi server shows up however the android app shows only a blank screen when I join a video chat.

The app has all the permissions.

Android 14.1, ROcket.Chat 3.4.2

Rocket.Chat
Version 	1.1.1
Apps Engine Version 	1.4.2
Database Migration 	147

**Comment by dwmunster** [comment]
I'm also experiencing this issue with the default `meet.jit.si` domain. I am able to start and join the calls on desktop Chrome, but only have a blank black screen in the android app. 

Phone Software | Version
-- | --
Android | 9 (Pie)
Rocket.Chat App | 3.4.2 (2070)

Software | Version
-- | --
Server | 1.2.1
Apps Engine| 1.4.2
Database Migration | 147

**Comment by franckadil** [comment]
+1 Many users can reproduce: https://github.com/RocketChat/Rocket.Chat.Android/issues/2326

**Comment by philipbrito** [comment]
Issue was fixed guys! You can download the 3.5.0 beta version on Google Play bringing that fix already.

**Comment by gerroon** [comment]
Is it possible to add the release to the github releases? I d onot see an update on Gplay.
