### ISSUE TITLE
Only logo/white screen is showing from Android app of Rocket chat project

### ISSUE THREAD

**Issue by rajitgarg2** [RocketChat/Rocket.Chat.Android#239]
Hello,

I am using Rocket Chat project and created android apk, but now when i am opening this app, it stucks at default meteor logo and nothing else show, if i go to back then only complete white screen is showing .I am using mac mini of version 10.11.5 (15F34) to generate apk.

please help me to come out of this, Thanks a lot in advance...

Rocket.Chat Version: 0.53.0
Running Instances: 1
Node Version: v4.2.3

**Comment by geekgonecrazy** [comment]
What are you using as your reverse proxy in front of Rocket.Chat?

**Comment by rajitgarg2** [comment]
Actually I am using Rocket chat project from this github repo
https://github.com/RocketChat/Rocket.Chat.git
but i am not sure, whether this is only for WebChat Platform or for both WebChat and mobile chat platform, or I should use different repo for mobile platform, I have search and found https://github.com/RocketChat/Rocket.Chat.Android , this github repo is mainy for Native Android Application, I have follow all its steps, and finally I got the message of Build Successful, But I don't know What happens with this , is any apk created with this or what i should do next, Can someone help...

**Comment by laggedHero** [comment]
@rajitgarg2 If you issue is about the Rocket.Chat server, please open an issue on the https://github.com/RocketChat/Rocket.Chat repo.

About the apk, I've answered you on the other issue.

I'll be closing this one too.
