### ISSUE TITLE
Unable to login via Google OAuth with 2FA activated on Google

### ISSUE THREAD

**Issue by apham0001** [RocketChat/Rocket.Chat.Android#2393]
## Describe the bug
unable to login via Google OAuth with 2FA activated on Google.
after put the password the redirection failed
we have this error message : net::ERR_UNKNOWN_URL_SCHEME

## To Reproduce
1. Go to RocketChat Apps
2. Connect to a server
3. https://url_private_server and connect
3. Continue with Google
4. enter your adress mail
5. enter your password
6. you will see an en error message : net::ERR_UNKNOWN_URL_SCHEME

## Expected behavior
to be able to login to the private server with RocketChat App

## Screenshots
![Screenshot_01](https://user-images.githubusercontent.com/34276938/60649197-df6c7280-9e41-11e9-88ee-a7ac5a30d41d.jpg)
![Screenshot_02](https://user-images.githubusercontent.com/34276938/60649198-e0050900-9e41-11e9-889e-7937e70109f6.jpg)
![Screenshot_03](https://user-images.githubusercontent.com/34276938/60649199-e0050900-9e41-11e9-91f0-b07195109616.jpg)
![Screenshot_04](https://user-images.githubusercontent.com/34276938/60649201-e0050900-9e41-11e9-8665-6fe27cd95be6.jpg)
![Screenshot_05](https://user-images.githubusercontent.com/34276938/60649203-e0050900-9e41-11e9-9733-bd61259dc760.jpg)
![Screenshot_06](https://user-images.githubusercontent.com/34276938/60649210-e4312680-9e41-11e9-9e7f-18421d30e399.jpg)

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.2
Your Rocket.Chat Server version:  1.3.0

Mobile device model and OS version: Huawei p10 Android 9

**Comment by franckadil** [comment]
Hi @apham0001 ,

Your Google Authentification is not properly setup and your redirect URL endpoint seems to be wrong.
https://rocket.chat/docs/administrator-guides/authentication/oauth/

In your Google Cloud Console head over: 1 **Api & Services** > _Select your project_ > 2. **Credentials**

![image](https://user-images.githubusercontent.com/42721509/61423854-a4724080-a911-11e9-8ab7-0a71e8ad1000.png)

3. Choose one of the following solutions:
A) Choose HTTP referrers (websites) and whitelist your rocketchat.domain.com
B)  IP addresses (not recommended if you are going to use Proxies or if you plan changing hosts)
C) None if you want some flexibility (👍 This what have proven to work the best so far)

As you can see the problem have nothing to do with Rocket.Chat Mobile App.

Note: as soon as you log in, try to access a channel and or post something, otherwise The app About page may have some trouble syncing with your server.

Cheers!

**Comment by franckadil** [comment]
Ps: If this solves your issue, please remember to close this issue.

**Comment by apham0001** [comment]
Hi @franckadil this is not the procedure to activate google oauth.
you send me how to create api key.
I have followed the documentation : https://rocket.chat/docs/administrator-guides/authentication/oauth/

![rocketchat](https://user-images.githubusercontent.com/34276938/62050142-0899dc00-b211-11e9-89de-a63a2cf4fcb3.PNG)


Google Auth is working well on Desktop version we have this bug only on Android app

**Comment by apham0001** [comment]
I Think it's the same problem as in this closed issue :
https://github.com/RocketChat/Rocket.Chat.Android/issues/1537

**Comment by philipbrito** [comment]
@apham0001 Check the related configuration on your server as told by @franckadil please. It is working fine as you can see [here](https://drive.google.com/file/d/1IWvl05Y8CJKZrjIqvmYlDzdDTjxEgrL7/view?usp=sharing)

**Comment by apham0001** [comment]
Hi @filipedelimabrito 

@franckadil  has written a procedure how to create an api key.

It's not the first time I use google auth, it's working on others products in my company (vault / gitlab...)

My setup is working well on rocketchat when I use a browser (desktop or mobile)



I have only this issue on your app.

On Google Cloud Platform I have created a project
Go to Apis & Services => Credentials => Create Credentials => Oauth Client ID
Application type : Web application
Name : Rocketchat
Authorized JavaScript origins : https://chat.domain.com
Authorized redirect URIs :  https://chat.domain.com/_oauth/google?close

On RocketChat Server : 
Go to https://chat.domain.com/admin/OAuth => Google
Google Login : yes
Google ID : [id created on GCP]
Google Secret : [secret created on GCP]
Google Callback URL : https://chat.domain.com/_oauth/google (I can"t edit it automatically filled)

**Comment by apham0001** [comment]
complete error on app : 

Impossible de charger la page Web intent:#Intent;action=com.google.android.apps.authenticator.AUTHENTICATE;S.request=%7B%22type%22%3A%22u2f_sign_request%22%2C%22appId%22%3A%22https%3A%2F%2Fwww.gstatic.com%2Fsecuritykey%2Forigins.json%22%2C%22challenge%22%3A%22AP3BxwOyeX6LVESzUg63OdcTLoJR-kblbAtPp1XiTRk8Z2sxuCRsstCbQAGHqG7sodMoXLB4t4qMFy0DeF7LMGkfW9_BaYzOBBrkbPE79Hq5n6UKXJyGxHdvcecOSNch7kUrm5BXI6M5_AKOwdcl87R5d3erk0Shsfim561v3rX17t4SF_zf4CIfKKUU94EkfzETefrCQTKSIZ_M1PFR8R0qaOjGEmGi1wsxLgedfgkQOAeTQJ_TGQG6lOA1y0FKk7FslnsSKobQWGNgq3y7Cx8hehdUnAkL8dnhHyhS-uS5EAuwFr9bBfIR0iyffWSDxnK-jlI6Gm8gqMv46Xs29MFCgRUtthUutmypgekM_TAoGaoVn1-hoLGsdHFd_9pXAEI387wXn_ZGIxNirbTeqVvr8rSesLob1o8mZuARW4Y1cGgs86tAtYfssSYVYEamqDccxBNtfE4kJ5BpDXBtoy0pENhFjXdkFSlZ_YzMwVWq_RtnfOgApu3F_Zydg_s5F0MQi_4GJI3oBQHh2PBKet6dfBKxN1KNsR2uuYzGmCyNSGPbOYOurYj5HaL4n4xzmE2rmnNm728tcMzoBZKKeyCmZDmjYwl3Omk7JDNEwN9aM1OYGFMF1pISGB-XWylNoRijVOaWmKSJTBd5tRTNVGPiH0_oQ57U4HL16hUwKY-SeDGZdawMN623bCgEzmqgtDBw-guoY2GKWZ8GW9UB26QJNWsT64v6DJNlKhf9e3eGbPIqTRKiPUBlWX3aHJ8NTW6D8J4gnYaKBX3zGFGuYLVstrUdMExr0VmxoobhCZjtuRxaHoTK2Y8LNoi7HEoSili3hqGtPyz7Jq_vd_WN7mZ68pMgOUInT-CDPmIawWVJQ6x6qmM9Sfet77x_ZOSjpkywPgUhsf8k0aGnvgFAwJvJAHEeRv-NG09Tuy-dGZzmuSZR_VYhB6Vv4pgHMguQbWQPPKzbF2JihyIluDvo68F6dCAuvWsyQRO_wUEbXdHoLwwxxU_EFoYfC88X0fwifqnqoVlPhDJfdN-gux1f-L69vc4TscMgMs4Sw_0LK7ysVmSnLBj0DNA8TL3WR04atPTTRd1KNMbXJ2P6pBnejLhyf61qS9HIuY1PoPPRcGapBxHVJTxAEicQojxgVdtQ9FCxOppeuL6s_BCABsKBQ9eDfgtYm7wTC6MeNqJX7YOh4fmj3PmLSG9x12KDBqf5yH2J6DIRRe6l5DNa4IvgV73wOM_jcv9cbA4eSnpvgqLF2UOTJsJuuhwRy7zus9VRJbw6csn1PD-r4CVvqpbVWRw2vwE6MGVFS55nFNXNQGoRj5HDBg3Sl4a4Y6JKo9kDLJPqntULrnRQ1UN6QbWB-QJeyZ_szQDlyFrjEvWF1d6vSt0y4HRyI-UwqVQaXYhJK8YvxTbh6kmqyiUA_Z26-amH2IsIq2V7PzToP5ed4DNzze_pg5U7g12PDQf01prsAry8ryRpqg%22%2C%22registeredKeys%22%3A%5B%7B%22version%22%3A%22U2F_V2%22%2C%22keyHandle%22%3A%22PS5vwluVDVf3uKmJDm75WqTVYfiTiboFd61zAK9w5kzmdaVSCNAX5QINDC1uCFKUPxfoTB7BPBNvjGDst0zQGw%22%7D%5D%2C%22timeoutSeconds%22%3A180%2C%22requestId%22%3A816384840%7D;end pour la raison suivante :

net::ERR_UNKNOWN_URL_SCHEME

**Comment by apham0001** [comment]
I know now where is the problem. 
I have disabled use of my yubikey and it's working.
You have a problem with yubikey 2FA
