### ISSUE TITLE
[BUG] App crashes at start

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#2400]
## Describe the bug
App crashes on initial open after install.

## To Reproduce
Install 3.4.2 on Samsung S10e.

## Expected behavior
App opens.

## Logs
Please advise how to get logs.

## Screenshots
No screenshots - app didn't open.

## Devices and Versions

Your Rocket.Chat.Android version: 1.4.2
Your Rocket.Chat Server version: N/A, we didn't succeed in connecting to the server.

Mobile device model and OS version: Samsung S10e - Android 9

## Additional context
Please let me know if we can assist debugging this, it's urgent.

**Comment by philipbrito** [comment]
@antgel Could you try our new 3.5.0 version? It is on Play Store as a Beta.

**Comment by antgel** [comment]
@filipedelimabrito Thanks, it worked in 3.5.0!
