### ISSUE TITLE
Malformed JSON error on attachment upload

### ISSUE THREAD

**Issue by odc311** [RocketChat/Rocket.Chat.Android#2406]
## Describe the bug
When trying to attach an image or take a photo and send it to the chat window, it returns the error shown in the screenshot. The image is never added to the chat on either the Android device or the browser version.

## Screenshots
![61085984-83c45b00-a3e6-11e9-8857-36412fe5b8f3](https://user-images.githubusercontent.com/52514071/61087516-b6705280-a3ea-11e9-9cdc-cc01ded1e8eb.png)

## Devices and Versions
Device - Motorola Moto X Pure 
![Screenshot_20190711-141904](https://user-images.githubusercontent.com/52514071/61086112-e3bb0180-a3e6-11e9-86d3-23fc027349d0.png)

![61086049-ba9a7100-a3e6-11e9-93d1-745050bb842d](https://user-images.githubusercontent.com/52514071/61087585-e4ee2d80-a3ea-11e9-9709-9de9db1527e8.png)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by emikolajczak** [comment]
Hi, look this ticket
https://github.com/RocketChat/Rocket.Chat.Android/issues/1050
