### ISSUE TITLE
[BUG] Can't start or join video chats using the Android App

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat.Android#2408]
## Description

I don't see any way to start a video chat using the Android app.  And when another user creates one, the button does not appear in that chat for a mobile app user to join.

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0): 3.2.2   (I think -- I can't get into "Admin panel" on the app but this is under "Settings-> About"
Your Rocket.Chat Server version: (e.g. 0.63.1-develop):   1.1.1

Maybe the video chat simply isn't a feature for the mobile app?  I might have assumed it was when its not.

**Comment by philipbrito** [comment]
The video chat is working fine at this moment @flantascience. Have you configured it on your server?

**Comment by philipbrito** [comment]
Some users related an issue with a black screen when trying to do a video call. It was fixed and is live on Play Store already as a beta app (version 3.5.0).

**Comment by flantascience** [comment]
@filipedelimabrito    when I'm on the Android app, I don't see:
1) any way to create a video call
2) the button is absent from the chat allowing me to click to join a video call created by someone else

Everything is working fine on my desktop and on the iOS app.   is there a separate setting to enable video conference on the Android?

**Comment by philipbrito** [comment]
@flantascience Let's reopen this issue until we discovered what is causing it to you.

1st let me know if you are using our new latest release: `3.5.0 (2074)`.

2nd I'd like to say that  we are checking if the settings `Jitsi_Enabled` and `Jisti_Enable_Channels` are enabled. Do you make sure you have them enabled on your server?

3rd That feature wasn't working on Android M- versions before due to a Jitsi issue . They have resolved it and now it is working from the Android Lollipop (our minimum supported version).

**Comment by flantascience** [comment]
#1 - where do I find what version the Android App is?   I know the server is running v1.1.1

#2-  On the server admin, I have both enabled.  And everything works fine on my desktop.  Is there a separate admin for the app?

![image](https://user-images.githubusercontent.com/12577122/61974907-b315c300-afb5-11e9-9f2a-1c4517d0f438.png)


Also have screens of the mobile app to review if his is helpful.    You can see there is no button to initiate a video chat and also the button to join one is hidden from the chat.

![Screenshot_2019-07-25-12-41-25 1](https://user-images.githubusercontent.com/12577122/61974986-de98ad80-afb5-11e9-95de-f1c75a5cf4d5.png)

![Screenshot_2019-07-25-12-41-31 1](https://user-images.githubusercontent.com/12577122/61974976-da6c9000-afb5-11e9-9919-ecec9cb1f9a8.png)

**Comment by philipbrito** [comment]
@flantascience That video icon will be only displayed to you if you have Jitsi enabled on your server (and from your screenshot it is enabled even for channels). 

You can see the app version on the settings screen:

<img width="390" alt="Screen Shot 2019-07-26 at 16 45 10" src="https://user-images.githubusercontent.com/11776825/61977420-cf6d2c00-afc4-11e9-83c8-1601e84379a3.png">

**Comment by philipbrito** [comment]
@flantascience wait, from your screenshot we can see that you are using an old app version. Could you please make sure to use the latest version we have?

**Comment by philipbrito** [comment]
It is really clear that the user is using an old app version. That said, please make sure to download our latest version (3.5.0 - 2074). 

Since https://github.com/flantascience has not answered here anymore, I’m going to close this issue.
