### ISSUE TITLE
Can't send messages in a new or empty channel

### ISSUE THREAD

**Issue by Fermman** [RocketChat/Rocket.Chat.Android#2409]
## Describe the bug
Can't send messages in a new or empty  (of messages) channel (direct message included)

## To Reproduce
1.- Install the app and connect to your server
2.- Join to an empty (of messages) channel
3.- Send any message, nothing happens
4.- For the app works sending messages, is necessary send a picture (or attached file)
5.- After this, app works.

## Expected behavior
At join in any channel, empty or not, the messages must be send.

## Devices and Versions
Rocket.Chat.Android version: 3.4.2 (2070)
Rocket.Chat Server version: 1.3.0-develop
Android 8.1.0
Galaxy J7 Prime

**Comment by Ky-ren** [comment]
Duplicate of #2368

**Comment by philipbrito** [comment]
Duplicated of a closed issue already. Please try using the 3.5.0 Beta version (it is on Play Store already) - we are planning to release it to everyone in few days.
