### ISSUE TITLE
KotlinFrontEndException on getSettingsInteractor

### ISSUE THREAD

**Issue by meto85** [RocketChat/Rocket.Chat.Android#2417]
Hi, i'm trying to compile and run the 3.4.2 version of Android Rocket Chat. I'have this error when i try to run it on device:

e: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (43,44) in /Users/myuser/Downloads/Rocket.Chat.Android-3.4.2/app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt

Can you help me? Thank you

**Comment by philipbrito** [comment]
@meto85 Try updating your branch now, please.

**Comment by hreza779** [comment]
> 
> 
> @meto85 Try updating your branch now, please.

I have the same problem
I don't understand your solution
You can explain more?

**Comment by philipbrito** [comment]
Have you updated your branch?

**Comment by hreza779** [comment]
> Have you updated your branch?

Yes

**Comment by philipbrito** [comment]
Try updating both the branches for the Android app and Kotlin SDK because as you can see our ci is passing, so no problem from our side.

**Comment by xuguochen** [comment]
Now I have the same problem, how to deal with it, the code is the latest download.

**Comment by awaik** [comment]
I think your should clone Kotlin SDK (I also didn't do it and had the same error)
Inside projects folder clone this repository https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK

![image](https://user-images.githubusercontent.com/5330807/68928782-eb355180-07b0-11ea-8849-6e8780dfacda.png)

**Comment by GuardYang** [comment]
是不是傻逼搞个项目都跑步起来
