### ISSUE TITLE
App freezes on Resume from Background

### ISSUE THREAD

**Issue by shellster** [RocketChat/Rocket.Chat.Android#242]
Your Rocket.Chat.Android version: 2.5.0 (I'm on the Beta channel)
Your Rocket.Chat.Server version: 0.53.0

Since the 2.5.0 update, I am unable to resume Rocket Chat by clicking on a notification when someone PM's me.  The app opens, but it just freezes on a white screen, even if I wait multiple minutes.  I have to kill the application, then re-open Rocket Chat, which is of course very slow as all the server files have to be re-downloaded.  At this point, I am uncertain if this always happens, or only after the application has been background for a significant period of time.  If I background the application, then go back to it immediately, it works just fine.

**Comment by laggedHero** [comment]
Your issue is about the Cordova (https://github.com/RocketChat/Rocket.Chat.Cordova) app.

Please, open the issue there.

Thank you.
