### ISSUE TITLE
[BUG] Error when change the password

### ISSUE THREAD

**Issue by edmargomes** [RocketChat/Rocket.Chat.Android#2423]
## To Reproduce
1- Install and open the app
2- Allow in-app log in without entering password
3- Access the server itself
4- Close the app
5- Chat online and change password
6- Open the app again
7- Shows the error in the image below, I can't log out, I can't go to another chat.
![image](https://user-images.githubusercontent.com/6574942/61708859-3ddf8f00-ad24-11e9-8718-6b9f0980c300.png)

If you uninstall the app and install it again, you will be returned to this same screen.

## Expected behavior
I would like to change the password and in the app back to the login screen, or know where I should delete the app registration on my android so it does not load a cache of it

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.2 -> lastest in the google play
Your Rocket.Chat Server version: 1.1.3

Mobile device model and OS version: "Samsung Galaxy J6 - Android 9

**Comment by ghost** [comment]
sounds familiar, but with different circumstances ([#2375](https://github.com/RocketChat/Rocket.Chat.Android/issues/2375))

**Comment by philipbrito** [comment]
@edmargomes Could you please test with the latest release (3.5.0)?

**Comment by edmargomes** [comment]
@filipedelimabrito It's working now!! Thanks!!
