### ISSUE TITLE
[BUG] First message to someone

### ISSUE THREAD

**Issue by juliensl** [RocketChat/Rocket.Chat.Android#2424]
Hi everyone
## Describe the bug
Currently I cannot send a private message to someone with who I never spoken.
It's written: [Invalid channel] I a cannot send the message.
I have to begin the discussion on my PC and after we can discuss on our mobile phone.

## To Reproduce

1. Go to rocketchat
2. Search someone with who you never spoken
3. Open the private discussion
4. See error --> [Invalid channel]
5. Try to send a message, that doesn't work.

## Expected behavior
This should send the message a begin the discussion.

## Devices and Versions

Your Rocket.Chat.Android version: 3.4.2 (2070)
Your Rocket.Chat Server version: 1.1.3

Mobile device model and OS version: 
 1) Samsung A3 2016 - SM-A310F - Android 7.0
 2) BQ Aquaris U2 - Android 7.1.2

Thank you for your work!

**Comment by TheReal1604** [comment]
@juliensl Some user reported to me that this is also the case for newly created channels. Can you confirm that also? @rafaelks Should we create a new issue for channels?

**Comment by juliensl** [comment]
Yes, that's true, it doesn't work too.
________________________________

**Comment by philipbrito** [comment]
@juliensl Could you please test again with our latest release (3.5.0)?

**Comment by juliensl** [comment]
It works!
Thank you very much for the fix ! :)

**Comment by philipbrito** [comment]
Glad it is working! Thanks for letting us know. Closing this issue now.
