### ISSUE TITLE
Unread notification is not removed after reading sideways.

### ISSUE THREAD

**Issue by exec228** [RocketChat/Rocket.Chat.Android#2434]
## Describe the bug

Push notification on incoming message is not removed after this message is read outside.

## To Reproduce
1.Login into Android app
2.Login into Windows Desktop app (example), same server, same credentials
3.Wait for incoming messages
4.See the push notification on smartphone about unread messages.
5.Go to Windows app and read incoming messages.
6.See the push notification is not removed.

## Expected behavior
6.See the push notification is removed

## Devices and Versions
Android 9, this rocket-chat {kotlin 3.5.0-2074}
Windows 10, this rocket-chat {electron 2.15.3}
Rocket server 1.1.3 engine 1.4.2

**Comment by sadstone** [comment]
HI, it's quite unconvinient behavior better to be fixed. Is someone goint to look at it ?

**Comment by reetp** [comment]
This repo is now deprecated and issue will not get fixed here.

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

Please close and move to the React Native Client

https://github.com/RocketChat/Rocket.Chat.ReactNative
