### ISSUE TITLE
Missing images on integrations

### ISSUE THREAD

**Issue by adam-kulagowski** [RocketChat/Rocket.Chat.Android#244]
Rocket.Chat.Android version: 1.0.7
Server version: 0.53
Server location: codilime.rocket.chat

We are using JIRA integration w/ webhooks as advised on: https://rocket.chat/docs/administrator-guides/integrations/jira

On web pare everything is ok. However on native android app there are icons missing. Please see the attached images to get better view. On the "adb logcat" the following line is logged while entering the channel (I've replaced private parts with [DELETED]):

`
03-22 21:47:48.382 23998 24075 D DDPClientWrapper: rpc:[f9b30981-393e-4b9e-9c48-ebc03a1c006b]< result = {"messages":[{"_id":"T9CuBTiQ7xmnKhrot","alias":null,"msg":"","attachments":[{"author_name":"[DELETED]","author_icon":"https:\/\/codilime.atlassian.net\/secure\/useravatar?size=small&ownerId=[DELETED]&avatarId=[DELETED]","thumb_url":"https:\/\/codilime.atlassian.net\/secure\/viewavatar?size=xsmall&avatarId=[DELETED]&avatarType=issuetype","text":"[DELETED]"}],"parseUrls":false,"bot":{"i":"bDWr9qgJn4u3TcDNf"},"groupable":false,"avatar":"https:\/\/codilime.atlassian.net\/secure\/projectavatar?pid=[DELETED]&avatarId=[DELETED]","ts":{"$date":1490204968807},"u":{"_id":"rocket.cat","username":"rocket.cat"},"rid":"hExvr2dARhyW2yYan","_updatedAt":{"$date":1490204968810}},.....`

![android](https://cloud.githubusercontent.com/assets/15870825/24220413/7467def8-0f4a-11e7-9976-d1300d96d46c.png)
![web_gui](https://cloud.githubusercontent.com/assets/15870825/24220412/7466d7b0-0f4a-11e7-8493-aa36677d4fc2.png)

**Comment by rafaelks** [comment]
@adam-kulagowski Is this still happening on latest version of the app?

**Comment by adam-kulagowski** [comment]
Still happening on 1.0.11 
Might be a duplicate of https://github.com/RocketChat/Rocket.Chat.Android/issues/237

**Comment by geekgonecrazy** [comment]
@adam-kulagowski the images in the integrations look like might be markdown images?  Something like `![](url)` ?

**Comment by adam-kulagowski** [comment]
not really - However it is hard to tell from app itself (see screenshot above). 
It looks like the miniature of unloaded image (when someone post image on channel, and the app has not downloaded it yet)

**Comment by adam-kulagowski** [comment]
Please hold investigation on this issue. It might be caused by the fact that those images are behind Atlassian authentication mechanism. In browser we are always logged in RC and in Atlassian Cloud so thats why it might be working. It is something I need to verify and I'll post my results here.

**Comment by rafaelks** [comment]
@adam-kulagowski Sounds good, thanks for letting us know about it. Will wait for your tests.

**Comment by rafaelks** [comment]
Closing it due to inactivity.
