### ISSUE TITLE
Cannot run ./build-sdk-sh

### ISSUE THREAD

**Issue by pbenedetti** [RocketChat/Rocket.Chat.Android#2445]
Reposting the issue because I can't find any solution among the ones given in the other posts:
I cannot build the .jar files needed to get Rocket.Chat.Android to run. Please help or link me someone who can. 
I already updated gradle, invalidate cache and build after cleaning the path, try to compile it using intelliJ, clone the directory multiple times and start from scratch again. I really don't know waht is missing.

(base) MacBook-Pro-di-FB:app paola$ ./build-sdk.sh 
CURRENT DIR: /Users/paola/Desktop/Workspace/Rocket.Chat.Android/app
SDK DIR: /Users/paola/Desktop/Workspace/Rocket.Chat.Kotlin.SDK
CURRENT SHA: 570f3dd
not dirty
same hash as before 570f3dd = 570f3dd

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
rm: /Users/paola/Desktop/Workspace/Rocket.Chat.Android/app/libs/common*: No such file or directory
rm: /Users/paola/Desktop/Workspace/Rocket.Chat.Android/app/libs/core*: No such file or directory
/Users/paola/Desktop/Workspace/Rocket.Chat.Kotlin.SDK/common/build/libs/common-0.1-SNAPSHOT.jar -> /Users/paola/Desktop/Workspace/Rocket.Chat.Android/app/libs/common-570f3dd.jar
/Users/paola/Desktop/Workspace/Rocket.Chat.Kotlin.SDK/core/build/libs/core-0.1-SNAPSHOT.jar -> /Users/paola/Desktop/Workspace/Rocket.Chat.Android/app/libs/core-570f3dd.jar

**Comment by philipbrito** [comment]
We have lots of closed issues regarding the same inability you've posted here and also the build is working as expected from our side. That said, try following those issues by finding a closest one which fits your case, following the [instructions](https://github.com/RocketChat/Rocket.Chat.Android#how-to-build) or by using our [community channel](https://open.rocket.chat/channel/androidnativeapp).
