### ISSUE TITLE
User status always stays offline in Settings ignoring status changes made in the app or in other clients

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat.Android#2448]
## Describe the bug

User status under Settings always stays offline, even though it has been changed in the app or in any other client and the actual status is reflected when you find the user by searching or see the user's details in any room. 

## To Reproduce

1. Login to Android native app. 
2. Go to Settings - the user status is offline.
3. Go to Settings->Profile->Status
4. Change it to busy, tap Change status.
5. Tap on the back arrow. 
6. The user status under username still shows offline

## Expected behavior 

A user's actual status should be reflected in Settings

## Screenshots 

![image](https://user-images.githubusercontent.com/47217833/62707613-575a2980-b9fa-11e9-98cd-94822ea9028f.png) ![image](https://user-images.githubusercontent.com/47217833/62707619-5b864700-b9fa-11e9-91c9-12d78df20d7d.png)

## Devices and Versions

Your Rocket.Chat.Android version: 3.5.0
Your Rocket.Chat Server version: 1.4.0-develop
Mobile device model and OS version: Samsung SM-J530F Android 8.1.0

**Comment by aenonGit** [comment]
That info is retrieved from LocalStorage (a SharedPref) which does not seem to observe tre actual value of the status. I've mitigated by using the value retrived from the RCClient

`rocketChatClientFactory.get(currentServer).me().status`

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2481
