### ISSUE TITLE
Logout request

### ISSUE THREAD

**Issue by sagaydach** [RocketChat/Rocket.Chat.Android#2463]
## Describe the bug
When user clicks on logout button from settings, logout and unregister tocken request's does calling.
## To Reproduce
1. Go to settings
2. Click 'Logout from Rocket.Chat'
3. Approve dialog click
4. User loget out on device, but no request to server

## Expected behavior
Clear user data on server.
Unregister FCM tocken

## Logs
No logs.

## Screenshots
Nothing here
## Devices and Versions

Your Rocket.Chat.Android version:  3.5.1
Your Rocket.Chat Server version: 0.62.0

All android devices

**Comment by philipbrito** [comment]
Closed by #2471
