### ISSUE TITLE
New language translation - HOW TO?

### ISSUE THREAD

**Issue by Skygge666** [RocketChat/Rocket.Chat.Android#2468]
Hi!

I made a new translation file (strings.xml) for Polish language,
but I'm not very familiar with Github features and I don't know how to upload my work here.
I only know the Transifex... Any tips? Thanks! The language file is attached to this post.
I put Polish (Język polski) as the last position in the "languages" array.
Best regards! Skygge

[strings.xml.txt](https://github.com/RocketChat/Rocket.Chat.Android/files/3545844/strings.xml.txt)

**Comment by philipbrito** [comment]
Thanks a lot for doing the translation! We will add that on the next app version and I'll mention you on the PR.
