### ISSUE TITLE
Sends empty message when repling or quoting

### ISSUE THREAD

**Issue by iprok** [RocketChat/Rocket.Chat.Android#2469]
## Describe the bug

If I send message by choosing "Answer" or "Quote", then empty message is sent. Please see screenshots/

## To Reproduce
Just try to quote or answer any message in any channel. You will see empty message and the quote.

## Expected behavior
Both quote and message should be sent.

## Screenshots
![Capture+_2019-08-27-15-20-26](https://user-images.githubusercontent.com/9906715/63777823-773f8780-c8ec-11e9-8424-d0af4190d85c.png)
![Capture+_2019-08-27-15-20-45](https://user-images.githubusercontent.com/9906715/63777784-642cb780-c8ec-11e9-9f55-a8e59df7e859.png)
## Devices and Versions

Your Rocket.Chat.Android version: 3.5.1
Your Rocket.Chat Server version: 1.3.2

Mobile device model and OS version: LG G6 - Android 8.0.0

**Comment by 3ronco** [comment]
Same here!
![image](https://user-images.githubusercontent.com/6967078/64007078-cb788080-cb13-11e9-97dd-09e6c17dc734.png)
