### ISSUE TITLE
ability to change font size

### ISSUE THREAD

**Issue by daira** [RocketChat/Rocket.Chat.Android#249]
Your Rocket.Chat.Android version: 1.0.8

The default font size for chat messages is too small for my eyesight. This is an accessibility issue.

The feature to change font size was [added to the desktop app](https://github.com/RocketChat/Rocket.Chat.Electron/issues/120), but I cannot find it in the Android app.

**Comment by laggedHero** [comment]
The Android app does not have support for it, yet.

We do need to add some basic settings/preferences in the app. Let's add it to the #186 list.

**Comment by rafaelks** [comment]
Since this issue was added to another issue, let's close it.
