### ISSUE TITLE
Unable to reach the server

### ISSUE THREAD

**Issue by asarubbo** [RocketChat/Rocket.Chat.Android#2498]
## Description

Few days ago I got a rocket.chat update. Apart the fact that it losed all saved logins, atm I'm unable to reach anymore the server.

Our server is in https on a different port than 443 and on a different path that "/", so:
https://$HOSTNAME:$PORT/$LOCATION
I'm attaching a screenshot
![photo_2019-10-14_08-47-58](https://user-images.githubusercontent.com/4741819/66733522-236b0c80-ee60-11e9-8d33-e40384c4273c.jpg)

## Devices and Versions

Your Rocket.Chat.Android version: 4.0.0
Your Rocket.Chat Server version: 2.1.0

Mobile device model and OS version: Lenovo K6 - Android 7.0

## Steps to reproduce

Open the app and try to login to the server.

**Comment by asarubbo** [comment]
Obviously it works from the desktop app and from the browser.

**Comment by reetp** [comment]
App update - please see this:
https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

Your version is now React Native so you should be in this repo:
https://github.com/RocketChat/Rocket.Chat.ReactNative

Before you close this and open it there please gather some information on your server setup that will be required - you are not using a standard installation so you need to explain exactly how you set it up.

Read this first:
https://rocket.chat/docs/contributing/reporting-issues

Then use this template to see the information required:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by asarubbo** [comment]
Closed. Opened it in https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by reetp** [comment]
This is the reference
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1307
