### ISSUE TITLE
User still seeing v3.5.1 in Play Store

### ISSUE THREAD

**Issue by antgel** [RocketChat/Rocket.Chat.Android#2503]
## Describe the bug
User still seeing v3.5.1 in Play Store, even though 4.0.0 has been out for a while.

## To Reproduce
Have that user's device and open RC in the Play Store.

## Expected behavior
v4.0.0 would be available for download.

## Screenshots
![image](https://user-images.githubusercontent.com/295571/67297061-0edae400-f4f2-11e9-8c76-67742df1e13f.png)

![image](https://user-images.githubusercontent.com/295571/67296849-b7d50f00-f4f1-11e9-8b58-be68b653b4cb.png)

## Devices and Versions

As per screenshot.

**Comment by seasick** [comment]
I believe this is connected to https://rocket.chat/2019/08/26/android-app-3.5.1-update-issue

**Comment by reetp** [comment]
This should be closed and opened in the React Native repo.

https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by antgel** [comment]
@seasick I don't think so, the user uninstalled and reinstalled the app, the Play Store version didn't update. I have v4.0.0. in my Play Store, she has v3.5.1.

@reetp Thanks, I opened the issue, I'll leave this here as a placeholder until the issue is resolved.

**Comment by antgel** [comment]
Closing as React Native issue gaining traction, thanks.
