### ISSUE TITLE
Need tag for version 4.0.0

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat.Android#2504]
## Describe the chore
There is no tag for 4.0.0 -- can someone tag the appropriate commit so we can test against this version specifically to diagnose issues? This is the current version available for download in the Play Store.

## Devices and Versions

N/A

**Comment by reetp** [comment]
It's all a bit messy right now.

Please read this:
https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

v4 is React Native and you need to go here:
https://github.com/RocketChat/Rocket.Chat.ReactNative

Not sure how they are going to deal with the release numbers  as they intend to keep 'Experimental' as the development and Beta version.

Probably needs the React.Native tag bringing up to v 4.x

**Comment by JoshMcCullough** [comment]
Thanks, closing.
