### ISSUE TITLE
Flutter Package

### ISSUE THREAD

**Issue by kamrancr7** [RocketChat/Rocket.Chat.Android#2506]
Any Flutter Package in future?

**Comment by reetp** [comment]
Not in this repo. The Android app has moved to React Native.

Please see: #2499

And: https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

**Comment by kamrancr7** [comment]
oh but i just implement Rocket chat in my flutter app through Platform Channel, so could there be any issue?

**Comment by reetp** [comment]
> oh but i just implement Rocket chat in my flutter app through Platform Channel, so could there be any issue?

What has this got to do with Rocket.Chat native Android???

This repo is no longer active and mobile applications are now developed in React Native.

There isn't any Flutter development at this minute, and none on the roadmap. You can of course develop whatever you want.

Please close - you may be better asking further questions in #support at https://open.rocket.chat
