### ISSUE TITLE
Latest avatars and images no show, wrong avatar & handle during "sending"

### ISSUE THREAD

**Issue by terencezl** [RocketChat/Rocket.Chat.Android#251]
Hello, this might not be the right place but I'm not sure where else. Where is the repo for Rocket.Chat+ on Android?

**Comment by mrplow** [comment]
Ummmm...
You just posted this issue in the Rocket.Chat+ Android repo.

It's unclear what your asking.

**Comment by terencezl** [comment]
Oh nice. I thought there were two RC Android clients, one is RC, another is RC+.

Anyway, below are the two problems I met. The first one: quite often the avatars of the newest messages are shown as the stock name initials, and images are not shown either. No matter how long I wait, they are still not converted to actual avatar pics. This only disappears when I scroll up then back a few times, and then everything is good.

![screenshot_20170331-200518](https://cloud.githubusercontent.com/assets/3190888/24580471/8084698e-16d6-11e7-900b-28d0fa142233.png)

The next one is sometimes when I write a message and send, while it's being sent with the indicator "sending", my handle and avatar would actually become someone else, but when the message is out, it shows I'm the actual sender. The problem only occurs in that sending moment.

![screenshot_20170331-200959](https://cloud.githubusercontent.com/assets/3190888/24580503/1db6dd72-16d7-11e7-9b5a-3fc5bdf94a3f.png)

It's the Google Play version of RC+ I downloaded yesterday.

**Comment by laggedHero** [comment]
That looks like a view recycling problem.

Thank you for your report!

**Comment by matheusjardimb** [comment]
This issue reports two problems: 
- the first one perhaps to be related to a non-treated error happening in the background. Once this error happens, the app starts looking to wrong avatar urls, not being able to downloading it
- the second issue is related to view recycling (as @laggedHero stated) and I've just created a PR for that (https://github.com/RocketChat/Rocket.Chat.Android/pull/296)
