### ISSUE TITLE
Missing some references : common, core

### ISSUE THREAD

**Issue by gabriel-TheCode** [RocketChat/Rocket.Chat.Android#2514]
## Desciption of the bug 

When I compile the app I got this error on some objects :
Unresolved reference:  RocketChatException, 
Unresolved reference:  RocketChatClient,
Unresolved reference:  Token.

## Logs

e: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (43,44) in C:/Users/Gabriel/Downloads/Rocket.Chat.Android-develop/Rocket.Chat.Android-develop/app/src/main/java/chat/rocket/android/authentication/registerusername/presentation/RegisterUsernamePresenter.kt

## Screenshots
![CaptureRocketChatMissing](https://user-images.githubusercontent.com/26333609/68405910-3502b400-0181-11ea-841a-0178131291e7.PNG)

**Comment by reetp** [comment]
Please read this:
https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

No more development. Please use the react Native client, and then ask for support via the normal channels:

ttps://rocket.chat/docs/getting-support

**Comment by gabriel-TheCode** [comment]
Ah Okay! Thank you guy ! This repo must be archived
