### ISSUE TITLE
Can't connect to server using android app

### ISSUE THREAD

**Issue by Conrado916645** [RocketChat/Rocket.Chat.Android#2516]
i have secured ssl on my deployed website but android app says 'The URL you entered is invalid check it and try again please!' site work at IOS and Desktop but not android

**Comment by Conrado916645** [comment]
I solved it just need to merge the issued cert to intermediate cert to access by android

**Comment by reetp** [comment]
Please note this:
https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

This repo and code is now deprecated and no longer supported, and all mobile apps are moving to React Native.

You should be migrating now.

https://github.com/RocketChat/Rocket.Chat.ReactNative
