### ISSUE TITLE
Version 4.x regression : wrong Username displayed in all Direct Message rooms

### ISSUE THREAD

**Issue by didierm** [RocketChat/Rocket.Chat.Android#2518]
## Describe the bug
In the Android **v4.x.x** app, an identical, wrong username is displayed for all users.

Both **Android v3.5.0** and **iOS v3.5.1** display corrrect usernames.

## To Reproduce
1. Go to 'Direct Message' room
2. Click on '...' (3 dots)
3. [Name] and [Avatar] fields are correct
4. [Username] field displays an incorrect value, which is identical for all users.
5. When clicking on the Avatar, the Room Info screen displays the correct Username value

## Expected behavior
Show the correct [Username]  for all users

## Screenshots

* Actions : 

![image](https://user-images.githubusercontent.com/989004/68844283-d5009600-06c9-11ea-834d-3c69888517a3.png)

* Room Info : 

![image](https://user-images.githubusercontent.com/989004/68844514-39bbf080-06ca-11ea-8959-5db5b3f9ac86.png)

## Devices and Versions
Your Rocket.Chat.Android version: 4.0.5
Your Rocket.Chat Server version: 2.2.0

## Additional context
The issue occurs for **all** users (both LDAP & email-registered).

**Comment by didierm** [comment]
Label -> [Regression]  ?

**Comment by reetp** [comment]
This repo is now deprecated and issue will not get fixed here.

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

This is a React Native issue. Please close and move there.

https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by didierm** [comment]
@reetp Issue moved to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1427, as per request.
