### ISSUE TITLE
Image saving Problems

### ISSUE THREAD

**Issue by smooth-baking-powder** [RocketChat/Rocket.Chat.Android#2520]
Hi,

If i Show in a Image and hold my Finger on it, a menu comes up to save the Image. After k click on save to Album, the Image didnt save on Smartphone.

Android Version: 4.0.6.2092
(Rocketchat and Rocketchat Experimental tested) 
Server Version: Univention 2.2.0

**Comment by reetp** [comment]
https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

Android 4.0.x + Experimental are both React Native apps.

Please close this and open in the correct repo:
https://github.com/RocketChat/Rocket.Chat.ReactNative
