### ISSUE TITLE
Default Login Button shown even if 'Show Default Login Form' is diabled

### ISSUE THREAD

**Issue by pkolmann** [RocketChat/Rocket.Chat.Android#2521]
## Describe the bug
We only use SAML to login to rocket.chat. Therefore I have disabled 'Show Default Login Form' in the rocket.chat. This setting works fine on web and desktop, but on Android clients the default login button is shown.

## To Reproduce
1. Go to Administration --> Accounts
2. Disable 'Show Default Login Form'
3. open Android app and connect to rocket.chat instance
4. Default Login button still exists

## Expected behavior
The default Login Button should not be shown if it's disabled in the settings.

## Screenshots
![Screenshot_20191128-155209](https://user-images.githubusercontent.com/2240760/69815730-3a3ea600-11f7-11ea-944c-e52c47171ed4.png)

## Devices and Versions

Your Rocket.Chat.Android version: 4.1.0 (beta) happens on regular one too
Your Rocket.Chat Server version: 2.2.0 and 2.3.0

**Comment by reetp** [comment]
Android 4.x is React Native. Please open in the correct repo

This repo is now deprecated and issue will not get fixed here.

https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/

https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

Please move to the React Native Client

https://github.com/RocketChat/Rocket.Chat.ReactNative

**Comment by sschueller** [comment]
> Android 4.x is React Native. Please open in the correct repo
> 
> This repo is now deprecated and issue will not get fixed here.
> 
> https://rocket.chat/2019/10/11/moving-mobile-apps-to-react/
> 
> https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first
> 
> Please move to the React Native Client
> 
> https://github.com/RocketChat/Rocket.Chat.ReactNative

I am very disappointed in this decision. I understand the complexity of running two code bases but the react native version of Rocket Chat is garbage on android just like many other react native apps. UI lags and appears to get blocked by background processes (single threaded?) etc.. 

I strongly hope someone will decide to continue this repository for the good of the entire Rocket Chat project.

**Comment by reetp** [comment]
> I am very disappointed in this decision. I understand the complexity of running two code bases but the react native version of Rocket Chat is garbage on android just like many other react native apps. UI lags and appears to get blocked by background processes (single threaded?) etc..

The decision has been made. The best thing to do is try it and help locate and fix bugs.

> I strongly hope someone will decide to continue this repository for the good of the entire Rocket Chat project.

It has been tried and no one was forthcoming. If you want to do it yourself then please say so, or find someone who will.

**Comment by pkolmann** [comment]
Bug already open
https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1377

closing here.
