### ISSUE TITLE
Notification but no message

### ISSUE THREAD

**Issue by rvlta** [RocketChat/Rocket.Chat.Android#2524]
## Describe the bug

When the app is off, the notification popup with the message and when i run the app the message don't appear.
If the discussion continue messages appears but not the first one.
But If the app is running in background and a notification come, the last message appear with all lost messages of the discussion
## To Reproduce

step 1 : close the app
step 2 : wait a notification
step 3 : run the app (the message don't appear, sometime but few time the message can appear)
step 4 : talk to see messages appear but not the first one
step 5 : wait for put the application running in background or open another app without close Rocket.Chat
step 6 : wait a notification
step 7 : open the app => you can see all messages appearing

## Expected behavior

I don't know
## Devices and Versions

Your Rocket.Chat.Android version: 4.1.0.2095
Your Rocket.Chat Server version: 2.1.1

Mobile device model and OS version: Android 9

**Comment by mobin1623** [comment]
Im not getting notification, as my token is also register to rocket chat server, when i click "send test push", it successfully send the push but not able to receive on device.

Compiled version - 3.5.1

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

Here's the new one: https://github.com/RocketChat/Rocket.Chat.ReactNative

Can you uninstall and install it again?
Versions 4+ are using our new app.
Thanks.
