### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by cdisabatino** [RocketChat/Rocket.Chat.Android#2532]
## Describe the bug
I cannot upload files (documents, photos, sound) from the android mobile application. From the windows client and from the web interface, it works. I tested with mobile data and wifi. The rocketchat server is under docker. It is configured to accept all types of files. It is not a file size issue. The error displayed is "Error uploading, Invalid file type", while all types are authorized and work from windows or web. I have the same problem with iOS, I opened another ticket for iOS.

Thanks

## Screenshots
![rocketchat_error_upload](https://user-images.githubusercontent.com/46713357/73756602-1f912c00-4768-11ea-9f13-4638f58ed9db.jpg)

## Devices and Versions
Version server (docker) : 2.4.7
Version android application : 4.3.1.2102
Phone : Samsung Galaxy J5 2016, android 7.1.1. **And other**

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

This repo is deprecated.
Correct repo is https://github.com/RocketChat/Rocket.Chat.ReactNative/
