### ISSUE TITLE
Search in Android client does not provide the Jump to Message option

### ISSUE THREAD

**Issue by alleait** [RocketChat/Rocket.Chat.Android#2534]
## Describe the bug
While in Desktop app you can search and jump to message to see more in Android there is no such option , so you cannot see messages send previously or after that message.

## Expected behavior
Have a jump to message button just like the desktop client.

## Devices and Versions

Your Rocket.Chat.Android version: 4.3.1.2102
Your Rocket.Chat Server version: 1.3.1

Mobile device model and OS version: Xiaomi Red Mi A2 - Android 10

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

There's an issue on the new repo already: RocketChat/Rocket.Chat.ReactNative#1315
