### ISSUE TITLE
how to know logined user's user id and password

### ISSUE THREAD

**Issue by devsksong** [RocketChat/Rocket.Chat.Android#2535]
## Description
Hi, I changed little function at Rocket chat android.
that function is add webview for rest api.
I developed rest api at my web server.
but, if i want to use rest api, I should send app login user and password.
I don't know that where can I get

http://myserver:3000/api/v1/login
api working when user, password wrote.

please let me know 

## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by diegolmello** [comment]
Hi, @devsksong.
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

Make sure you're using [the new repo](https://github.com/RocketChat/Rocket.Chat.ReactNative/) to get help.
Thanks.
