### ISSUE TITLE
BBB integration

### ISSUE THREAD

**Issue by terra-assistance** [RocketChat/Rocket.Chat.Android#2540]
I'd really like to use BBB for video conferencing. At the moment it's possible to use BBB only with Rocket Chat desktop client (tested on Windows client) but not possible to use it on mobile devices.

When trying to lauch video conference on Android it just opens Jitsi interface regardless of server-side settings (tried to disable Jitsi and leave only BBB enabled).

------
Rocket.Chat.Android version: 4.6.4.2118
Rocket.Chat Server version: 2.3.0

**Comment by diegolmello** [comment]
Duplicated of https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1959
