### ISSUE TITLE
Not showing NextCloud auth button

### ISSUE THREAD

**Issue by loxK** [RocketChat/Rocket.Chat.Android#2544]
## Describe the bug
In web client (mobile and desktop) I have the button but not in the android app

## Screenshots
Web login:
![image](https://user-images.githubusercontent.com/136687/81644457-7e56f780-9473-11ea-8b22-25aa66002990.png)

Android:
![signal-attachment-2020-05-12-170829](https://user-images.githubusercontent.com/136687/81644497-929af480-9473-11ea-8bfa-a24fb1a4856c.jpeg)

## Devices and Versions

Your Rocket.Chat.Android version: 4.6.4
Your Rocket.Chat Server version: 3.1.1 (stable 3.x snap channel)

Mobile device model and OS version: OnePlus 6T Android 10

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first
Transferring to new one.
