### ISSUE TITLE
Auth nextcloud is show in web but not in android version

### ISSUE THREAD

**Issue by yodatak** [RocketChat/Rocket.Chat.Android#2545]
## Describe the bug
We're using standalone Rocket.Chat server with nextcloud OAuth, mobile application don't show the nextcloud bouton.
Maybe its some permission issues

There are no problems with web version, desktop version

## Devices and Versions

Your Rocket.Chat.Android version: 4.6.4.2118
Your Rocket.Chat Server version: 3.2.2

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

There's an open issue on the new repo: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2109
