### ISSUE TITLE
Analytics can't be turned off (GDPR violation)

### ISSUE THREAD

**Issue by thatgim** [RocketChat/Rocket.Chat.Android#2546]
## Describe the bug
Analytics can't be turned off

## To Reproduce
1. Go to 'Settings'
2. Click on 'Send Analytics'
3. See error --> No change of 'Send Analytics'

## Expected behavior
I expect to be able to turn off tracking.
This is required by the GDPR.

## Screenshots
![Screenshot_20200530-180657](https://user-images.githubusercontent.com/862483/83333442-b0a08b80-a2a0-11ea-83d3-3878d8dfae4b.png)

## Devices and Versions 
Your Rocket.Chat.Android version: 3.5.1 (2077) F-Droid
Your Rocket.Chat Server version: 2.4.9

Mobile device model and OS version:
Nokia 7.2 Android 10

**Comment by diegolmello** [comment]
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

New repo (version +4.0.0): https://github.com/RocketChat/Rocket.Chat.ReactNative/

We're currently working on a F-Droid version.

**Comment by thatgim** [comment]
In F-Droid is no notice recarding the discontinuation of this app.
This bugtracker is mentioned and donations are requested which lead me to assume this app/project was active.

I think it's reasonable for other users to make a similar misjudgment. 
In combination with this GDPR violation this could be rather problematic.
