### ISSUE TITLE
App not listed in task managers

### ISSUE THREAD

**Issue by adam-kulagowski** [RocketChat/Rocket.Chat.Android#255]
Your Rocket.Chat.Android version: 1.0.8

We received a notification from one of our users, that rocket.chat+ is not listed in task manager. Further investigation showed that indeed, when one launch such appllication (i.e. Advanced Task Manager), the rocket.chat+ is not there.

**Comment by geekgonecrazy** [comment]
Is this a 3rd party application you're using to try and view running applications?  When Rocket.Chat is in the background it shouldn't be doing anything.  So might not show up as a background application by a 3rd party application.

What version of Android are you running these on?

**Comment by adam-kulagowski** [comment]
Weired: currently it seems that my task app. sees Rocket Chat+ corectly - so it might false alarm. Please give me 24hours to confirm this behavior (that everything is fine) with our employee. 
After that I'll give more feedback (or just the info to close the issue).

**Comment by adam-kulagowski** [comment]
After consulting the user: false alarm. Issue can be safely closed.
