### ISSUE TITLE
[BUG] Text in input lost when screen sleeps

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#256]
Your Rocket.Chat.Android version: latest

I've had several times where I have a big message typed and someone starts talking to me in person.  So I stop typing.  Screen goes to sleep.  Then I wake it and message is gone. 

So right now if its important I have to keep tapping the phone to keep it awake until I can hit send :grin:

**Comment by geekgonecrazy** [comment]
Not sure when this broke... But really annoying that it's not there

**Comment by rafaelks** [comment]
@geekgonecrazy Thanks for the report!

**Comment by philipbrito** [comment]
Closed by #696
