### ISSUE TITLE
How to merge Rocket chat to my android app

### ISSUE THREAD

**Issue by guptamonu4** [RocketChat/Rocket.Chat.Android#259]
Your Rocket.Chat.Android version: (make sure you are running the latest)

**Comment by geekgonecrazy** [comment]
Currently we have no guide for this.  In the future we will have an sdk you will be able to use.  So right now if you wish to do this, you'll have to do it on your own.

**Comment by laggedHero** [comment]
Since @geekgonecrazy is right in the spot, I'll close this one.
