### ISSUE TITLE
[REQUEST] Upload the app to F-DROID

### ISSUE THREAD

**Issue by tpeg5stan** [RocketChat/Rocket.Chat.Android#26]
Hello,

As the licence (MIT) is compatible with the FOSS catalog "F-DROID", is it possible to get the app there ?
I am a Rocket.Chat user on my desktop browser, but on my mobile browser it is not easy to use. Moreover, I have uninstalled Google Play Store, and thus won't get the app on it.

Thanks in advance

**Comment by geekgonecrazy** [comment]
@tpeg5stan I don't believe this app is feature complete enough to be listed in any store.  But... please see this issue https://github.com/RocketChat/Rocket.Chat.Cordova/issues/104 for our main app

**Comment by tpeg5stan** [comment]
Oh, I did not understand that, you have 3 different apps for Android ? Which one should I use (at the moment, I prefer using my browser) ? Is one of the 3 projects abandoned ?
Don't worry about the fact that the app is not finished, there are beta and even alpha apps on F-DROID, I am a volunteer to test it if needed :)

**Comment by geekgonecrazy** [comment]
The Rocket.Chat.Cordova is most actively maintained, and currently the only one we as the core team are maintaining.  As soon as we have the bandwidth we'll be venturing into the Native apps, and at that time we will probably combine the two projects if need be.

**Comment by herbsmn** [comment]
fyi @tpeg5stan: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/104#issuecomment-248840584
I think it still uses Google for push notifications though, so it can't be added to the regular f-droid FOSS repo yet.

**Comment by tpeg5stan** [comment]
Oh, yes, I see that this thread has parallel issues.
I perfectly understand the problem, it is difficult ot take away all the google specific requirements, but once it is done, app is 100%open-source.
Is it possible to have an application without notification yet ? Like an alpha-version or so...

**Comment by geekgonecrazy** [comment]
Lets continue conversation over here: RocketChat/Rocket.Chat.Cordova#104.  Closing this one.

**Comment by schaengel** [comment]
Since Cordova app looks like its unmaintained. The conversation of creating FDroid app belongs here.

**Comment by geekgonecrazy** [comment]
Situation has definitely changed since I closed this.  The other is still maintained, but this one is much more active

**Comment by rafaelks** [comment]
👍

**Comment by Bubu** [comment]
We have a request for packaging issue now in the f-droid tracker: https://gitlab.com/fdroid/rfp/issues/436

The two main problems I can see right now is the custom maven repositories used by this app and the firebase/gcm dependencies.

F-Droid only allows a certain set of whitelisted maven repositories which guarantue they contain free software and also require source arhcive upload. You can find the list here: https://f-droid.org/en/docs/Build_Metadata_Reference/ search for `mavenCentral`

For the gcm dependencies there would need to be another build flavour which works without these dependencies. I guess this should be doable when losing push notifications is an acceptable tradeoff? (These won't work anyway for anyone not having the google play services installed on their phone.)
Having an alternative push implementation would of course be preferable but is *much* more work.

For the custom maven repos it would be goof to know if those dependencies could alternatively pulled from jcenter/jitpack.io? Or we'd need to manually build them as a preobuild step inside the fdroid repository. This is more effort and prone to breaking.

Would you accept a separate build flavour which doesn't depend on non-free software components?
And could someone maybe make a list of dependencies which cannot be pulled from one of the main maven repositories?
