### ISSUE TITLE
UI is almost empty and can't able to take any action further 

### ISSUE THREAD

**Issue by JigneshWorld** [RocketChat/Rocket.Chat.Android#261]
Your Rocket.Chat.Android version: 1.0.10

Attached images for reference 

![device-2017-04-24-152003](https://cloud.githubusercontent.com/assets/7347854/25331832/0a52ed38-2902-11e7-8f6e-3553c87cc254.png)
![device-2017-04-24-152019](https://cloud.githubusercontent.com/assets/7347854/25331833/0a56ce8a-2902-11e7-938a-5e13620da488.png)
![device-2017-04-24-152034](https://cloud.githubusercontent.com/assets/7347854/25331834/0a56f5d6-2902-11e7-9f19-4e177b6dbd55.png)

**Comment by manwe-pl** [comment]
Same thing on Huawei P9 with Android 7 and Rocket.Chat+ 1.0.10. Also I had connection error ("please try again later") on this phone, had to disable https redirection in nginx. Five other phones are working fine.

**Comment by geekgonecrazy** [comment]
@manwe-pl even if you specified https in your connection url you had to disable redirection?

@JigneshPatel23 first step here would be to try and clear the application data and give it another shot and see if that fixes it.

**Comment by manwe-pl** [comment]
@geekgonecrazy I didn't put https:// or http:// on any of those phones. Just the hostname.

**Comment by JigneshWorld** [comment]
Thanks, yes it got fixed after clear the application data and setup again. 
Can anyone please me help to get on possible reason for this?

**Comment by matheusjardimb** [comment]
Hello there! 

@JigneshPatel23 and @manwe-pl, does this issue still happens to you? The last message gave me the impression the problem got solved.

If that's the case, can we close it?  Thanks!

**Comment by JigneshWorld** [comment]
Hello @matheusjardimb 

Yes, I am not getting this issue anymore. Let's close it. If required we will create a new issue. 

Thanks.
