### ISSUE TITLE
Upgrade destroyed the UX 

### ISSUE THREAD

**Issue by kyyberi** [RocketChat/Rocket.Chat.Android#263]
Your Rocket.Chat.Android version: 2.5.0

During the morning I was notified on my phone that upgrade is available. I upgraded and after that the UX became unusable. It looks odd and not able to chat. 

![app](https://cloud.githubusercontent.com/assets/1927158/25370680/08df83ec-2995-11e7-99a3-b99924314561.png)

**Comment by kyyberi** [comment]
If it makes any difference, I'm using Honor8

**Comment by geekgonecrazy** [comment]
This is for the other Android application. But try clearing data and re-adding the server.  If this doesn't resolve please open an issue on the correct repo: https://gitHub.com/rocketchat/rocket.chat.cordova/issues

**Comment by kyyberi** [comment]
Reinstall of the app fixed everything. Working now.
