### ISSUE TITLE
Strange behaviour with fleksy keyboard

### ISSUE THREAD

**Issue by valerionew** [RocketChat/Rocket.Chat.Android#266]
Your Rocket.Chat.Android version:  latest on play store. 

I'm having some issues with fleksy keyboard from playstore. The keyboard has a "swipe left to delete" and a "swipe up or down to change the corrected word" features. 

Using those features on the rocket chat input field sometimes exhibits some strange behaviour. I don't know how to explain the issue in technical terms, but in general it messes up the input filed. 

If more details are required, please ask :)

**Comment by rafaelks** [comment]
@5N44P Do you mind posting a video with this issues happening?

**Comment by valerionew** [comment]
I believe that this behaviour it's a keyboard problem, as it showed in other apps. For now I'm using rocketchat+. I'll close this issue for now
