### ISSUE TITLE
Application crash on Android 7.1.1

### ISSUE THREAD

**Issue by PPPBerlin** [RocketChat/Rocket.Chat.Android#267]
Your Rocket.Chat.Android version: 1.0.10

The application crash on my OnePlus One with LineageOS 14.1 (Android 7.1.1) after I type in the hostname and fire it up. If i try to restart the application, it crash instantly. 
[logcat-chat.rocketchat.android.txt](https://github.com/RocketChat/Rocket.Chat.Android/files/960732/logcat-chat.rocketchat.android.txt)

**Comment by rafaelks** [comment]
@PPPBerlin Did you try clearing all the app data?

**Comment by PPPBerlin** [comment]
Hi, yes. I try it also on 2 other mobiles with 7.0 and 7.1 with the same behavior.

**Comment by rafaelks** [comment]
@PPPBerlin Can you try using the beta version, here? https://play.google.com/store/apps/details?id=chat.rocket.android

**Comment by PPPBerlin** [comment]
Is the + Version your Beta? I have installed both.

**Comment by rafaelks** [comment]
@PPPBerlin Yes, make sure you've it updated.

**Comment by PPPBerlin** [comment]
I've reinstalled it minutes ago. Now i try it with demo.rocket.chat and this works. But with our subfolder url it doesn't. url like chat.url.com/instance seems to make the trouble

**Comment by rafaelks** [comment]
@PPPBerlin Sounds good, then crash is gone. I'll close the issue, this connection bug is known already. Can you use a subdomain instead of folder?
