### ISSUE TITLE
Rocket.Chat+ on Android: Sending message stuck in "Sending" state, displaying wrong message owner

### ISSUE THREAD

**Issue by somsak** [RocketChat/Rocket.Chat.Android#268]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: 0
Node Version: 4.8.1 (We use Official Docker image)
Android app version: 1.0.10

When sending message from Android app. Most of the time it will stuck in the "Sending" state and showing wrong owner of the message (It should be the owner of the phone, but it randomly pick someone around and show the message state as Sending).

This seems to happen when we exit the app for a while and comeback (Usually from push notification). The App works fine the first time we login to the server.

When the message was in Sending state, the message was actually already delivered (by checking on Web-site or Cordova app).

Sometime the message was stuck in "!" state and need resend, although the message was actually delivered.

The current workaround is to push "Back" button to exit the app, or kill the app and re-open it.

This didn't happen with Cordova app.

NOTE: We use Rocket.chat Gateway in push notification setting.

**Comment by somsak** [comment]
Today I can confirmed that this problem also occurred with https://demo.rocket.chat

Here's an example screenshot of what happened. It stuck in "Sending" state for a long time.

![smartselectimage_2017-05-03-16-19-05](https://cloud.githubusercontent.com/assets/353565/25671146/27067018-3059-11e7-9b51-57b552a73f0f.png)

**Comment by adam-kulagowski** [comment]
This issue also affect our team/company at codilime.rocket.chat - it kinda blocking point for native app.

**Comment by djschilling** [comment]
We also have this problem with our instance https://chat.ct-srv.de.

**Comment by guptamonu4** [comment]
I am also facing same problem in Rocket chat+.

**Comment by rafaelks** [comment]
This is very important, will add the urgent label to it.

**Comment by TheReal1604** [comment]
@rafaelks Can also confirm this.

**Comment by rafaelks** [comment]
This is in progress already.

**Comment by joneswe** [comment]
the wrong message owner getting displayed, because the recyclerView doesn't overwrite the views of messages which are not synced. Caused by missing attributes.

The interesting Question is: Why do we get Problems by sending and receiving messages after an instance of time or after we turn off and on the internet connection

**Comment by matheusjardimb** [comment]
Hello there! Let me help on this one!

I see clearly two different problems listed in this issue: 
- the first one is related to the recyclerView, as @joneswe said. This part is duplicated of #251 and should not be happening anymore.
- the second issue is related to the app getting stuck in "sending" state. I'm not sure if that part got fixed too and I'll investigate it now. 

Thanks for reporting this issues!

**Comment by djschilling** [comment]
Is there an update on this?

**Comment by rafaelks** [comment]
@djschilling We're working hard to solve this issue. Sorry about the delay! :-(
