### ISSUE TITLE
[NEW] Support deep links

### ISSUE THREAD

**Issue by laggedHero** [RocketChat/Rocket.Chat.Android#269]
Idea coming from RocketChat/Rocket.Chat#6820

## Initial URLs to be supported

- [x] Authentication;
- [x] Server + Chat;

**Comment by narlei** [comment]
@laggedHero when this feature will works?

**Comment by rafaelks** [comment]
@narlei Authentication is already working, just missing the chat now.

**Comment by rafaelks** [comment]
That's already implemented in 3.2.0. 👍
