### ISSUE TITLE
[DOCS] Improve Documentation

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat.Android#272]
Hi,
Thanks for this repo and your works but I think it's need more documentation. Do you have any plan about it?

**Comment by rafaelks** [comment]
@cyclops24 Can you explain more what you need? What kind of documentation?

**Comment by matheusjardimb** [comment]
I was about to open an issue this very same subject. These are some topics that must be better documented:

- Getting started (how to setup environment and run the app - #324)
- Technologies this app depends on and links to easy getting started
- What each module is intended for?
- How to build release apk files? 
- A simple overview of how the app interacts with RC server

@cyclops24 I'm not really concerned about code documentation at this point. If that's what you were looking for when opened this issue, I might open a new one to address my request.

Thanks!

**Comment by aenonGit** [comment]
@matheusjardimb that would be an awesome starting point

**Comment by aenonGit** [comment]
then it would be amazing if someone would documents every single package of the app in detail, and by detail I mean something like:

**MODULE APP**
1. **service** contains all the bla bla bla
- inside service, the directory **internal** contains all te bla bla bla which uses this library and bla bla bla connected to bla bla bla

2. **shared** contains all the bla bla bla

... bla bla bla 

**MODULE PERSISTENCE REALM**

1. bla bla bla

**Comment by cyclops24** [comment]
@matheusjardimb I agree with you 👍  . Some tutorial and topics (like titles that you mention above) would be a good starting point.

**Comment by rafaelks** [comment]
This is already in progress/done for version 2.0.0.
