### ISSUE TITLE
Search does not show channels a member of

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat.Android#274]
Your Rocket.Chat.Android version: 1.0.11

The new 'Search Rooms' function does not actually work. 

It sometimes displays non-matching rooms and sometimes does not display any results at all.

**Comment by laggedHero** [comment]
I'm quite expecting the search to have some bugs since it was done in a rush.

No results could be that the server has no matches (it will only try to show channels you are not into). A message saying "nothing found" could help.

Non-matching rooms worry me.

Could you please provide some extra info, @RichardFoxworthy ?

The server you're using is demo? Do you have a screenshot?

**Comment by RichardFoxworthy** [comment]
HI @laggedHero I'm using a private server - running RC v 0.55.1. I can access and use this server from Rocket.chat+ native Android app without any problem.

Search does not work for me at all on this server - for example in attached screenshot I searched for a channel called #general, and android app returns no results - regardless if i am in the #general channe or in some other channel instead. 

NB I also think that the current RC behaviour to not return a search result for channel you are already in is a mistake - https://github.com/RocketChat/Rocket.Chat/issues/6436

I have not seen search work correctly in the Android native app for any search for any channel or username. Search does work in the web interface for this same instance that I'm using Android native app to connect to.

![screenshot_20170509-122644](https://cloud.githubusercontent.com/assets/1432373/25878812/e48be07a-3570-11e7-8d6a-77839050d35a.png)

**Comment by geekgonecrazy** [comment]
@RichardFoxworthy are you a member of the general channel?  If so the currently implementation only searches channels you aren't in.  So this is for sure something we want to improve on.  :+1:

**Comment by RichardFoxworthy** [comment]
Right. Yes I am a member of the channel.

**Comment by rafaelks** [comment]
This is fixed already!
