### ISSUE TITLE
Member List shows JSON

### ISSUE THREAD

**Issue by gardenerik** [RocketChat/Rocket.Chat.Android#275]
Your Rocket.Chat.Android version: (make sure you are running the latest) 1.0.11

When you open member list, this shows up:
![screenshot_2017-05-04-22-00-31](https://cloud.githubusercontent.com/assets/11409143/25722701/5d0fe5b0-3115-11e7-86ca-bcbeb3841929.png)

**Comment by geekgonecrazy** [comment]
Same :grin:

**Comment by cyclops24** [comment]
I have same problem too.

**Comment by laggedHero** [comment]
Server changes. We need to update the client.
