### ISSUE TITLE
package org.nibor.autolink does not exist

### ISSUE THREAD

**Issue by tridib** [RocketChat/Rocket.Chat.Android#28]
If I do 'gradlew assembleDebug', I get compilation error.
Rocket.Chat.Android.Lily\app\src\main\java\chat\rocket\android\view\Linkify.java:16: error: package org.nibor.autolink does not exist
import org.nibor.autolink.LinkSpan;

Adding dependencies in app/build.gradle fix the problem.
compile 'org.nibor.autolink:autolink:0.5.0'

But I think I am doing something wrong. autolink submudule did not build during 'gradlew assembleDebug'. Is there any build step I am missing? I followed all steps mentioned in README,md.

**Comment by YusukeIwaki** [comment]
@tridib Thank you for your error report!

> Rocket.Chat.Android.Lily\app\src\main\java\chat\rocket\android\view\Linkify.java:16: error: package org.nibor.autolink does not exist

It seems that you're using Windows.
Symbolic link is not properly working and it may causes the error...

Actually symbolic linking is not a good way...

> Adding dependencies in app/build.gradle fix the problem.
> compile 'org.nibor.autolink:autolink:0.5.0'

I think this method is better!
If you provide a Pull Request, I will check and accept it...! 👍

**Comment by tridib** [comment]
@YusukeIwaki Created a pull request https://github.com/RocketChat/Rocket.Chat.Android.Lily/pull/29
Not sure why cicle CI fails.

**Comment by YusukeIwaki** [comment]
Fixed! Thank you.
