### ISSUE TITLE
Cant start the app on Android 7.0

### ISSUE THREAD

**Issue by danpospisil** [RocketChat/Rocket.Chat.Android#281]
Your Rocket.Chat.Android version: 1.0.11 
I can't start the App on Galaxy S7 Edge - it crashes immediately.

**Comment by PPPBerlin** [comment]
Maybe the same problem like this? https://github.com/RocketChat/Rocket.Chat.Android/issues/267

**Comment by danpospisil** [comment]
@PPPBerlin - this one crashes after entering the hostname. I can't even do that.

**Comment by rafaelks** [comment]
@danpospisil Can you try clearing all the app data?

**Comment by matheusjardimb** [comment]
@danpospisil Unfortunatelly I don't have an S7 to test on but I've tried. Does this issue still happens?
Have you tried uninstalling and installing the app again? This is the link you should use: https://play.google.com/store/apps/details?id=chat.rocket.android

I'm able to run the app on devices using Android 7.0 and emulators too.

**Comment by Sing-Li** [comment]
Yes. I am on an Android 7.0 device, ZenFone 3 laser, and it runs.

**Comment by matheusjardimb** [comment]
Thanks @Sing-Li! 

Yep, I checked GooglePlay's data and couldn't find any specific issue regarding 7.0 devices. 

@danpospisil are you sure this error is still happening?

**Comment by danpospisil** [comment]
@matheusjardimb - I had to delete all data manually as @rafaelks has suggested - just clearing cache and reinstalling the whole thing didn't help. But now I am stuck at login screen - when I enter my credentials and push login i just see 3 dots running on the screen forever.. So i guess I will open another issue.
