### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat.Android#285]
Just installed this but cannot login.

I didn't have any login issues with cordova app.

The server url is https://rocket.xxxxxxxx.com:PORT and authentication is done using ldap. 
So can the issue be caused by port in the url or ldap?

**Comment by rafaelks** [comment]
@rockneverdies55 LDAP is currently supported by the app. Can you try not using the PORT (using the default HTTPS one)?

**Comment by rockneverdies55** [comment]
I cannot because that's what our server's address is. 
Do you mean if I can test against rc demo server?

**Comment by rafaelks** [comment]
What happens when you try to login?

**Comment by rockneverdies55** [comment]
Nothing. It just hangs in there... Loading animation gets into an infinite loop i guess.

**Comment by rafaelks** [comment]
You don't have access to the server to change the default to the default one?

**Comment by rockneverdies55** [comment]
Actually I have but other services too running on the same machine (gitlab is running on the default port). Unfortunately can't play with that.

**Comment by rafaelks** [comment]
As an alternative, can't you create a subdomain just for the chat?

**Comment by rockneverdies55** [comment]
In our server apache webserver listens on `PORT` and proxies the requests coming to that `PORT` to rocket chat instance on port 3000. If I create a subdomain pointing to same ip address of the machine, can apache be configured to listen the requests coming to that subdomain specifically (instead of a port) and proxy only those to rocket chat without messing up other services running on the machine? Sorry I'm not an expert on these stuff...

**Comment by rafaelks** [comment]
@geekgonecrazy Hey, can you help is here on the Apache settings ^^?

**Comment by geekgonecrazy** [comment]
https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-an-apache-ssl-reverse-proxy Here is our docs on the matter. 

The important part is the Rewrite rules:
```
<VirtualHost *:443>

ServerAdmin it@domain.com
ServerName chat.domain.com
ErrorLog /var/log/chat.domain.com_error.log
TransferLog /var/log/chat.domain.com_access.log
LogLevel info
SSLEngine On
SSLCertificateFile /etc/ssl/certs/chat.domain.com.crt
SSLCertificateKeyFile /etc/ssl/private/chat.domain.com.key
SSLCertificateChainFile /etc/ssl/certs/intermediate.ca.pem

<Location />
        Order allow,deny
        Allow from all
</Location>

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:3000/$1 [P,L]

ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

If you don't need the ssl stuff you can omit everything down to something like:
```
<VirtualHost *:80>

ServerAdmin it@domain.com
ServerName chat.domain.com
ErrorLog /var/log/chat.domain.com_error.log
TransferLog /var/log/chat.domain.com_access.log
LogLevel info

<Location />
        Order allow,deny
        Allow from all
</Location>

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://localhost:3000/$1 [P,L]

ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

**Comment by rockneverdies55** [comment]
@geekgonecrazy thank you. However your virtual host config is set up to listen default http ports. However as I said earlier, the default port is already taken by another service on the machine. 

The default port(s) are used by gitlab served by nginx so https://gitlab.my_domain.com (port 80 and/or 443) is used for gitlab.

In the same machine we also have apache webserver and it proxies the requests that come to port 3443 to rocketchat instance running on port 3000 (to access rocket-chat from outside we use https://gitlab.my_domain.com:3443). Therefor the question is can we configure apache to proxy the requests that come only to rocketchat.my_domain.com so we can reach rocketchat without any :port in the access url.

@rafaelks - Shouldn't the app take care of this somehow? Instead of we're trying to get around the problem like this...

**Comment by geekgonecrazy** [comment]
Just swap 80 for 3443 to switch this.  Or just copy the rewrite rules into your existing config.

Just to be clear though is the existing setup running through Apache to rocket.chat or are you access rocket.chat directly at port 3000?

**Comment by robokaso** [comment]
Just installed Rocket.Chat+ 1.0.11 and logging in simply hangs. Server version is 0.55.1 running behind https proxy.

**Comment by geekgonecrazy** [comment]
@robokaso what are you using as your proxy?

**Comment by robokaso** [comment]
@geekgonecrazy after I configured nginx exactly per https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy I no longer have the login problem

**Comment by geekgonecrazy** [comment]
@robokaso perfect!  Glad to hear :)

**Comment by rafaelks** [comment]
Excellent, closing the issue! @robokaso @geekgonecrazy

**Comment by rockneverdies55** [comment]
This still doesn't work for me. Current `apache2/conf-enabled/rocketchat.conf` file is exactly as @geekgonecrazy put it as with port 3443. But still no luck. I think it has something to do with the port in the access url.

**Comment by rafaelks** [comment]
@matheusjardimb Can you help us debugging this connection, please?

**Comment by geekgonecrazy** [comment]
@rockneverdies55 if you get some time, maybe hit me up on the [demo server](https://demo.rocket.chat): `@aaron.ogle` and maybe we can walk through things in a bit more detail and get things solved for you.

**Comment by dicer** [comment]
We had the same problem. I can also confirm that it was the proxy settings in nginx. iOS app and web did work fine, android app did not. This commit fixed it for us:
https://github.com/selamanse/rocketchat_ynh/commit/e0251e9ce7f06c37edc262fec6b7123604b25124

**Comment by jarakkal** [comment]
We are experiencing the same issue even after following the above suggestion. It works for 'sign up' workflow, but when you log out and try to log back in, it just hangs. Everything works as expected with the cordova app. We are experiencing this issue with Rocketchat plus.

In our case nginx is running within a container by itself. Another container houses the rocketchat. Both containers are running on the same machine with a mlab mongo db.


##nginx.conf

worker_processes 4;

events {
   worker_connections 2048;
}

http {
   upstream ourserver.com{
      ip_hash; #makes it sticky, users request allways returns to the same server
      server 127.0.0.1:3000; # remember setting ip address for these guys in the /etc/hosts
   }

   server {
      listen 443; # lets protect our data transactions
      server_name outserver.com;
      access_log /var/log/nginx/ourserver.com.access.log;
      ssl on; # check letsencrypt's certbot for these =)
      ssl_certificate /etc/nginx/certs/ourserver.com/fullchain.pem; # you need to create these, use self-signed our a free CA
      ssl_certificate_key /etc/nginx/certs/ourserver.com/privkey.pem;
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

      location / { # our reverse proxy
         proxy_pass http://127.0.0.1:3000;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
         proxy_set_header Host $http_host;
         #proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forward-Proto http;
         proxy_set_header X-Nginx-Proxy true;
         proxy_redirect off;
      }
   }
}

**Comment by jarakkal** [comment]
@geekgonecrazy can you please help us with the above config
