### ISSUE TITLE
[Rocket.Chat+] [Feature Request] Add additional accounts to the app + edit message

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat.Android#286]
I am currently using v1.0.11 of [Rocket.Chat+](https://play.google.com/store/apps/details?id=chat.rocket.android&hl=de) on Android 0.6.1.
There are two important things missing:

1. The option to edit your message.
2. To possibility to add additional acounts to the app, so you can switch between different chats easy and fast, without logging out, change the URL and log into another chat.

P.S.: The new app (with +) is performing awesome. The old one (without +) should be trashed, imho. :)

**Comment by rafaelks** [comment]
@punkr0ck Hey, thanks for opening the issue.

1. The app already supports editing a message on the Beta version (1.0.12, you can find it in the Google Play).
2. The additional accounts is an old issue: https://github.com/RocketChat/Rocket.Chat.Android/issues/158

Thank you!
