### ISSUE TITLE
[NEW] Show other user status

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#287]
Several places through out the app the status icon is shown.  But its always grey.  It would be great to have this reflect their actual status.

The one of biggest use would be the @ sign in the direct message.  It'd be nice to know if the person you are about to send a message is available... or if they are offline.

**Comment by rafaelks** [comment]
@geekgonecrazy Definitely, adding it as a feature! 👍

**Comment by cemore2048** [comment]
@geekgonecrazy can you post an example of this? I haven't found where to see anybody's status, outside of the dm

**Comment by geekgonecrazy** [comment]
In the Android app it only shows in the all users list.  Swiping from right side.  In the web app it shows several places

**Comment by aenonGit** [comment]
it would be great to have the user status both in the DM sidebar roster and on the DM room tab bar

**Comment by aenonGit** [comment]
it requires a slightly different management of the RealmUser repository as well as te roster rendering

**Comment by mmarif4u** [comment]
Seems to be implemented for the top bar in 1.0.17, but it always show gray icon for all users(green in the member list and web).

**Comment by rafaelks** [comment]
@mmarif4u The status is showing wrong on the top bar for you in 1.0.17? That's new bug. Do you know how to reproduce it?

**Comment by philipbrito** [comment]
Those PR features that issue: 

https://github.com/RocketChat/Rocket.Chat.Android/pull/416
https://github.com/RocketChat/Rocket.Chat.Android/pull/434
https://github.com/RocketChat/Rocket.Chat.Android/pull/408

Please, feel free to reopen it if you are facing a trouble...

**Comment by mmarif4u** [comment]
@rafaelks i have to clear cache and data, then login again. Which then worked.

**Comment by rafaelks** [comment]
@mmarif4u Thank you, we're going to investigate the issue! 👍
