### ISSUE TITLE
Cannot authenticate with google (OAuth)

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat.Android#290]
Your Rocket.Chat.Android version: 2.5.0

yesterday, rocket chat android download 7 files. (Certainly due to the update of the server)
But, I can't use Google to authenticate.

I thought that the updated files would fix the problem.

Currently, when I try to login with Google, I just have an alert notification that does not contain any text.

I had seen that there was talk of cordova in an issue but I do not find her anymore.

**Comment by geekgonecrazy** [comment]
You're looking for the cordova repo.  They are different apps.  This is a new Native one that's in development currently.

See: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/159
