### ISSUE TITLE
Can not login via Gitlab OAuth

### ISSUE THREAD

**Issue by dasjoe** [RocketChat/Rocket.Chat.Android#291]
Your Rocket.Chat.Android version: 1.0.11

I'm running a rocket.chat without local users, making use of Gitlab's OAuth integration.

After entering the server details I'm shown a login form, asking for username and password. The button for logging in via Gitlab is missing, so I can not log in at all.

This seems to be isolated to Gitlab, enabling Github in the server's configuration enables the Github button for me.

**Comment by geekgonecrazy** [comment]
I think the app doesn't support gitlab yet.

**Comment by rafaelks** [comment]
Yes, the app does not support GitLab yet. The issue was already created. 👍
