### ISSUE TITLE
Missing OAUTH authenticatiors

### ISSUE THREAD

**Issue by adam-kulagowski** [RocketChat/Rocket.Chat.Android#292]
Rocket.Chat.Android version: 1.0.11

According to the github:
https://github.com/RocketChat/Rocket.Chat.Android/tree/master/app/src/main/java/chat/rocket/android/fragment/oauth
the current version of app is supporting only some of RC supported providers. Please add the following ones:
Gitlab
CustomOAUTH
(other are less important for us)

If possible it would be nice to have SAML,CAS as well :)

**Comment by rafaelks** [comment]
This is duplicated from #230.
