### ISSUE TITLE
Mobile app stuck at "Error downloading files, Please try again Later"

### ISSUE THREAD

**Issue by cruisemaniac** [RocketChat/Rocket.Chat.Android#295]
Your Rocket.Chat.Android version: Latest from Android Play Store running on Motorola G5 Plus (Android 7).

I have a rocket.chat server running on https://chat.refermate.co. When I give the url as mentioned above, I am stuck with the "Error downloading files, Please try again later".

I have nginx reverse-proxying to docker on 127.0.0.1:3000 running rocket chat.

These are my nginx logs:
```
103.5.132.71 - - [22/May/2017:13:46:30 +0000] "GET /api/info HTTP/1.1" 200 76 "http://localhost.local/index.html?addServer" "Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Plus Build/NPN25.137-15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Crosswalk/18.48.477.13 Mobile Safari/537.36"
103.5.132.71 - - [22/May/2017:13:46:31 +0000] "GET /__cordova/manifest.json HTTP/1.1" 200 6428 "http://localhost.local/index.html?addServer" "Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Plus Build/NPN25.137-15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Crosswalk/18.48.477.13 Mobile Safari/537.36"
```

**Comment by geekgonecrazy** [comment]
This message sounds like it's coming from the other app: https://github.com/rocketchat/rocket.chat.cordova

This app is listed as: Rocket.Chat+ in the app store

**Comment by rafaelks** [comment]
@geekgonecrazy Yes, it is, thanks!

@cruisemaniac The app you're using isn't the native one, is the Cordova one (https://github.com/RocketChat/Rocket.Chat.Cordova). If you want to try the native app, download it with the name `Rocket.Chat+`.
