### ISSUE TITLE
Opening the app causes audio ducking

### ISSUE THREAD

**Issue by MariusVolkhart** [RocketChat/Rocket.Chat.Android#30]
When rocket chat is running, the volume of media playback is reduced. Once the app is killed, the media volume returns to normal.

Version 2.4.0

**Comment by YusukeIwaki** [comment]
Is this issue for RocketChat/Rocket.Chat.Cordova ?

**Comment by MariusVolkhart** [comment]
Whoops, probably. It's for the version out on the play store.

**Comment by geekgonecrazy** [comment]
Please see: https://github.com/RocketChat/Rocket.Chat.Cordova/issues/73

**Comment by MariusVolkhart** [comment]
👍
