### ISSUE TITLE
Entering rocket.chat server hostname

### ISSUE THREAD

**Issue by adam-kulagowski** [RocketChat/Rocket.Chat.Android#304]
Version 1.0.13

This a minor issue: 
When user is entering hostname of rocket.chat server two things happens on rocket.chat+ app:
1) the text field is treated as normal text field and keyboard autocomplete is giving a hard time (i.e space and capital letter after each dot)
2) when autocomplete finishes the word "chat" (codilime.rocket.chat) it usually add space at the end. This space make application unable to connect ("Connection error")

Expected behavior:
- any space from the end and the beginning of hostname is removed before connecting
- text field, where user enters host name has autocomplete disabled

**Comment by matheusjardimb** [comment]
@adam-kulagowski that seems good improvements and easy to be done. Thanks!

**Comment by rafaelks** [comment]
Fixed already! :-)
