### ISSUE TITLE
Pixel XL - Google account login causes error

### ISSUE THREAD

**Issue by mscfadmin** [RocketChat/Rocket.Chat.Android#305]
Your Rocket.Chat.Android version: 2.5

After opening the app and using the Google button I can select my account I want to use (which I use on the desktop version as well). Then there appears to be some error in the top portion of the screen. You can see a red box with what appears to be an exclamation point, but no further info.

Screenshot of the error after selecting the account:
![screenshot_20170603-171114](https://cloud.githubusercontent.com/assets/29168172/26757421/2606e2b2-4880-11e7-8295-9e8f4d1095cd.png)

**Comment by geekgonecrazy** [comment]
You'll want to open an issue on the other Android app repo :) https://github.com/RocketChat/Rocket.Chat.Cordova
