### ISSUE TITLE
Upcoming changes in how avatars are handled

### ISSUE THREAD

**Issue by matheusjardimb** [RocketChat/Rocket.Chat.Android#306]
App must handle the upcoming changes in the server side (v0.57.0), regarding how avatars are handled.

More details at https://github.com/RocketChat/Rocket.Chat/pull/6788

The easiest approach should be as easy as following a redirect when getting the images.

**Comment by matheusjardimb** [comment]
@rafaelks any comments on how iOS is dealing with this changes?

**Comment by geekgonecrazy** [comment]
@matheusjardimb this https://github.com/RocketChat/Rocket.Chat/pull/7177 seems to fix it actually. :grin:

**Comment by matheusjardimb** [comment]
@geekgonecrazy that's awesome! So it seems this issue isn't necessary anymore. 
I'm closing it and let's just reopen if any scenario isn't covered :+1:
