### ISSUE TITLE
Prepare to upcoming Android O

### ISSUE THREAD

**Issue by matheusjardimb** [RocketChat/Rocket.Chat.Android#311]
Android O is about to come (https://developer.android.com/preview/migration.html) and we must make sure there is no breaking change. 

This issue is about testing the app, identify and possibly fix any issue related to this OS version.

**Comment by geekgonecrazy** [comment]
Heh, funny you should open this as it's downloading in the background on my phone right now :) I'll let you know if I see anything 😎

**Comment by philipbrito** [comment]
Hey @geekgonecrazy  
We would appreciate hearing your thoughts. Are you facing any issues? How is the app icon? Some weird behavior?

**Comment by geekgonecrazy** [comment]
On home screen
![screenshot_20170824-005004](https://user-images.githubusercontent.com/51996/29651471-8e937df6-8866-11e7-86d0-e187b6acbea5.png)

In app drawer
![screenshot_20170824-005131](https://user-images.githubusercontent.com/51996/29651492-a2383b94-8866-11e7-93fe-03af935f9bb6.png)

I don't think any issues I have currently are related specifically to Android O

**Comment by rafaelks** [comment]
Closing it, looking good in Android O already.
