### ISSUE TITLE
Enable "Squash and merge" feature in this repo

### ISSUE THREAD

**Issue by matheusjardimb** [RocketChat/Rocket.Chat.Android#312]
I feel this feature that Github offers should be enabled in this repo, and probably becomes the default choice we should take when accepting pull requests. 

Just opened this issue to start a discussion and to identify if anyone opposes to.

**Comment by matheusjardimb** [comment]
@geekgonecrazy I believe you are the one that has proper perms to change that setting. So you might get involved in this one :D

**Comment by geekgonecrazy** [comment]
I think a few of us do.  But is be more then happy to make default.

I vote for squash and merge.  :)

**Comment by matheusjardimb** [comment]
Just checking that this issue is still pending. 
@geekgonecrazy @rafaelks @filipedelimabrito @leonardoaramaki 
What you guys think? :+1: or :-1:  this comment and let's close this one :)

**Comment by rafaelks** [comment]
Closing guys, due to inactivity.
