### ISSUE TITLE
[IMPROVEMENT] Android Studio reports "cannot resolve symbol Autovalue_XXX" 

### ISSUE THREAD

**Issue by matheusjardimb** [RocketChat/Rocket.Chat.Android#314]
Android Studio reports the following error when editing any class annotated with `@AutoValue`:
`cannot resolve symbol Autovalue_XXX`

It's quite annoying and the solution must be as easy as adding proper plugins to gradle files. 
If any IDE configuration is required, it must be documented somewhere and highlighted to new developers.

**Comment by ghost** [comment]
I have the same problem. I spent almost a day looking for a solution but I couldn't find anything useful.

**Comment by mridah** [comment]
@TeraformareBG  @matheusjardimb did you find anything ? i'm facing the same problem.

**Comment by rafaelks** [comment]
@filipedelimabrito How's the progress of this one?

**Comment by philipbrito** [comment]
I think that it is happening with our SDK too. Let's see how we can solve it...
