### ISSUE TITLE
Rotating display looses text in input

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#318]
Your Rocket.Chat.Android version: latest

I rarely leave rotation lock off.  But happened to and rotated phone and all my text was lost.  :(

**Comment by matheusjardimb** [comment]
@geekgonecrazy actually, this problem is happening in every single text input.
Well, now we can say it "was happening" :D

**Comment by geekgonecrazy** [comment]
:grin:  awesome!

**Comment by cyclops24** [comment]
I found another related issue on rotating. When I rotate my tablet to landscape, channel menu (for example for see member list) not open until rotate to portrait again.

**Comment by matheusjardimb** [comment]
Hello @cyclops24 ! Would you test it again with the latest version? 
https://740-48179404-gh.circle-artifacts.com/0/tmp/circle-artifacts.dMy4HqB/app-release.apk

This apk contains the changes made on #320 and the issue may got solved already.
