### ISSUE TITLE
channel and group list not showing

### ISSUE THREAD

**Issue by farenhite** [RocketChat/Rocket.Chat.Android#32]
everything working i mean i can login but in channel list i cant see anything

**Comment by YusukeIwaki** [comment]
Yes, sorry for inconvenience...

Now working in #33

**Comment by wanharaderta** [comment]
channel has not appeared even though I already pull branch Replace sqlite to realm

**Comment by deepakag12345** [comment]
Hi @YusukeIwaki 
Sorry to bother with this query. I am unable to view the channel list and get it working for any of the branches. 
Would you know when this is fix is planned for release? Is there a chance that I could help with a bounty towards this fix , so that its fixed quicker? 
Once again sorry to bother. 
Thanks.

**Comment by wanharaderta** [comment]
Hi @deepakag12345 
I am trying to replace the existing file here it worked
https://github.com/RocketChat/Rocket.Chat.Android.Lily/pull/33/commits/0c9353ecf6b7f1750f53d32d8aa0dfde4843741f

**Comment by deepakag12345** [comment]
@wanharaderta Thanks for the comment. 
Finally managed to get the rooms showing. However, i am unable to see any messages which are already present in the channels - no existing messages show up in the channels. Only messages that I type fresh/new show up in the channel. Also, messages that are typed in by other users do not appear in the channel.  Any known issues here? Thanks in advance.

**Comment by wanharaderta** [comment]
@deepakag12345 you just need to logout login again, because the incoming message seemed to be kept in Database SQLite

**Comment by deepakag12345** [comment]
@wanharaderta Thanks for helping out again. 
The only thing that know does not work now is : messages that are typed by other users in the same channel do not appear immediately, i have to kill the app and open it again for the messages to appear - i guess its again a DB migration issue.

**Comment by YusukeIwaki** [comment]
fixed by #37
