### ISSUE TITLE
Search should find Direct Message channels

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat.Android#321]
Your Rocket.Chat.Android version: 1.0.14

Unlike the web app (and Cordova), the search does not return DM channels.

Because of this, there is no easy way on the Android app to start a DM with someone - if he/she did not message you first.

**Comment by rafaelks** [comment]
@matheusjardimb You can use our `spotlight` call to get this values, or even use the local results (I think the Android app isn't getting the local results right now).

Here's how we do on iOS: we search locally first, show the results if have more than 0. In this case we show a button on the bottom of the list saying `Load more results` to load the results from `spotlight` call. If the local results are 0, then we go directly to the `spotlight` results.
