### ISSUE TITLE
[NEW] Add support for other languages

### ISSUE THREAD

**Issue by matheusjardimb** [RocketChat/Rocket.Chat.Android#323]
Your Rocket.Chat.Android version: 1.0.14

- In order to support other languages rather than only English, we must first get rid of hard-coded strings in the project. 
- Later we should prioritize languages based on install base
- And then, look for the best translating alternatives (probably Lingohub)

**Comment by cyclops24** [comment]
👍 
@matheusjardimb yes I also try to localize Rocket.Chat.Android but unfortunately many of strings not exist in `strings.xml`

I also suggest RTL support like main RocketChat.

**Comment by aenonGit** [comment]
Besides the hardcoded strings I have already translated the whole string file in Italian, hence eventually this will come in handy

**Comment by rafaelks** [comment]
This is going to be addressed in v2. Thank you guys!
