### ISSUE TITLE
Doesn't record Sender value of a message after sending.

### ISSUE THREAD

**Issue by toyangel0710** [RocketChat/Rocket.Chat.Android#325]
Android app version: 1.0.12

I found a problem that is after sending a message, the realm db doesn't save sender value with the message. And I looked into **"RealmMessageRepository"** this file, the "save" function do codes blow

```
realmMessage.setId(message.getId());
realmMessage.setSyncState(message.getSyncState());
realmMessage.setTimestamp(message.getTimestamp());
realmMessage.setRoomId(message.getRoomId());
realmMessage.setMessage(message.getMessage());
realmMessage.setEditedAt(message.getEditedAt());

RealmUser realmUser = realmMessage.getUser();
      if (realmUser == null) {
        realmUser = new RealmUser();
}

realmUser.setId(message.getUser().getId());

realm.beginTransaction();
```

And it works to me if I add two lines before realm.beginTransaction()

```
realmUser.setUsername(message.getUser().getUsername());
realmMessage.setUser(realmUser);
```

this problem will lead to a unknown user when message stuck after sending.
Maybe the original code has its reason, but I think it'd be better if adding these two lines.

**Comment by matheusjardimb** [comment]
Hello @toyangel0710, thanks for contributing!
You might be seeing an old version of our code base. This exact change is already in place:
https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/persistence-realm/src/main/java/chat/rocket/persistence/realm/repositories/RealmMessageRepository.java#L85

Please git checkout to develop branch and pull the latest code (v1.0.14)
