### ISSUE TITLE
App must avoid unnecessary calls to 'spotlight method'

### ISSUE THREAD

**Issue by matheusjardimb** [RocketChat/Rocket.Chat.Android#327]
Your Rocket.Chat.Android version: 1.0.14

The app triggers an 'spotlight' method call against RC server unconditionally when the user types something. That call has a huge impact in RC performance and should be cached when possible in order to avoid server lockup.

**Comment by matheusjardimb** [comment]
The behavior here may have some changes too, in order to get more similar with the iOS app

**Comment by rafaelks** [comment]
@matheusjardimb I think this one is top priority right now.
