### ISSUE TITLE
Crash loop

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#329]
**Rocket.Chat.Android version: 1.0.14**

Native app is in some sort of crash loop. 

When sending a message it was in sending state so, when switched the rooms to read more messages, the app just crashes.

The possible cause is: data getting corrupted and the app is not being able to continue because of it. Something in the realm data can be corrupt.

**Comment by geekgonecrazy** [comment]
https://paste.ubuntu.com/24956726/ here are my logs related to this

**Comment by rafaelks** [comment]
@luciofm Can you help us on this crash?

**Comment by rafaelks** [comment]
Closing this one, seems that it doesn't happen anymore.
