### ISSUE TITLE
[IMPROVEMENT] Enable ProGuard

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#330]
**Rocket.Chat.Android version: 1.0.14**

This will help the code shrinking, making, for example, the APK file as small as possible.

**Comment by rafaelks** [comment]
How's the progress of this feature @filipedelimabrito?

**Comment by philipbrito** [comment]
This is not done yet. We could enable the ProGuard on the next app versions.

Note: We have a lot of dependencies, so we need pay attention with the ProGuard usage whenever we generate a new (release) .apk.
Note 2: The ProGuard should be enabled on the release `buildType` because it disables the instant run and takes time on the build ([more information](https://developer.android.com/studio/build/shrink-code.html?hl=pt-br)).

**Comment by luciofm** [comment]
I think we should left as is now, and enable on the rewrite from beginning..

**Comment by rafaelks** [comment]
Let's remove it in this case.
