### ISSUE TITLE
Real time messages not displaying

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#337]
Your Rocket.Chat.Android version: 1.0.15

This seems to be new as of this release.

I load the app I get all of my unread channels and I can browse them and send messages no problem.  Even sending messages seems better.

But... If I'm in a channel chatting... I don't get the new messages until I I'll the app and reload it.

Oddly if I'm mentioned in that channel it shows the little red dot and expanding channel list I see I have a mention in that channel.

Used to if messages weren't showing.. just the act of taking app out of focus and bringing it back into focus would cause the messages to load.  But now even constantly in focus messages aren't showing up :(

**Comment by rafaelks** [comment]
@leonardoaramaki What could have been caused this?

**Comment by xenithorb** [comment]
I can definitely attest to this being true at the moment on my oneplus one. Makes it kind of pointless to use this because I always need realtime messages :/ 

I look forward to when this is looked at / fixed, because this is significantly faster to use than the Cordova wrapper

**Comment by rafaelks** [comment]
This is suppose to be fixed, closing it.
