### ISSUE TITLE
Test Tool Support

### ISSUE THREAD

**Issue by JigneshWorld** [RocketChat/Rocket.Chat.Android#343]
Is there any testing tool like Postman which have a support of below stuff for the socket communication?

- Template based support (Add/Edit Template)
- DDP protocol support (Auto-verification of heartbeat, Method, Subscription)
- Better view support of history like 2-way / full duplex communication.

If anyone has such kind of tool will help us to save a lot of time rather that tradition socket testing Chrome extensions/websites.

Thanks.

**Comment by rafaelks** [comment]
We currently don't have any... we're using Chrome Developer Tools to watch the websocket communication.

**Comment by JigneshWorld** [comment]
Just for reference, we are trying to achieve some of them here.
http://web-socket-ddp.herokuapp.com/
https://github.com/JigneshPatel23/websocket-client
