### ISSUE TITLE
[NEW] Delete message

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#347]
Your Rocket.Chat.Android version: 1.0.15

The app should allow the message deletion. Currently only message edition is allowed to the user (holding down its message).

**Comment by dimsedane** [comment]
I have created a pull request for this and would love some comments on it. 

I have had to introduce a new syncstate (3 actually) do handle messages that are marked for deletion, and it is especially this concept i would like your comments on. Is there a better way of doing it? It does add the overhead of not showing the messages that are marked for deletion when querying the list of messages.
