### ISSUE TITLE
Update codebase to use RxJava 2

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#355]
Your Rocket.Chat.Android version: 1.0.16

Update all parts on the codebase that still uses legacy RxJava types.
Even though the project is using RxJava 2.1.0 dependency, there're many parts on the codebase that uses legacy RxJava types (from package rx.* instead of io.reactivex.*).

**Comment by rafaelks** [comment]
Closing this, since we're moving to 2.0.0
