### ISSUE TITLE
[BUG] Opening member list from channels with very large amounts of members crashes

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#356]
Your Rocket.Chat.Android version: 1.0.16

To reproduce this just open the member list from channel **general** which has more than 100k members.

This crash is caused by an OutOfMemoryError since during the loading the app tries to build a json object putting every member info inside it. 

A solution to this would be lazy loading this list.

**Comment by philipbrito** [comment]
Let's see if it happens after implementing #421 👍
