### ISSUE TITLE
[NEW] Honor setting to show first name / last name

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#363]
Reference to issue created on main repo: https://github.com/RocketChat/Rocket.Chat/issues/7573

There is a setting to display first name and last name instead of username.  The Rocket.Chat+ doesn't yet have that feature

**Comment by danieljhochman** [comment]
+1

**Comment by rafaelks** [comment]
Information to accomplish this task:

# Description

> When `UI_Use_Real_Name == true`

- Every part of the app that uses Subscription model will display fname property;
- Every part of the app that uses User model will display name property;

> When `UI_Use_Real_Name == false`

- Every part of the app that uses Subscription model will display name property;
- Every part of the app that uses User model will display username property;

Implementation of the setting in iOS: https://github.com/RocketChat/Rocket.Chat.iOS/pull/565.

**Comment by rafaelks** [comment]
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).
