### ISSUE TITLE
The list of messages show "User not found" before loading the user's username and avatar

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#368]
Your Rocket.Chat.Android version: 1.0.16 (28)
Mobile device model and OS version: Sony Xperia E5 (F3311) - Android 6.0

**Steps to reproduce 01:**
- The app is closed
- User opens the app, waits for authentication
- On the same channel, the list of users will refresh to "User not found" and then a few seconds later change again to the correct username and avatar

**Steps to reproduce 02:**
- The app is opened
- User is authenticated
- User is looking a channel
- User changes to another channel
- The list of users will refresh to "User not found" and then a few seconds later change again to the correct username and avatar

**Screenshot**
![screenshot_20170728-090208](https://user-images.githubusercontent.com/551004/28716488-f1a31b16-7373-11e7-830e-96e20c8e404a.png)

**Comment by leonardoaramaki** [comment]
@rafaelks I think this behavior was already there. I don't think it's a new bug, the only difference is that before there was no placeholder avatar showing and no **user not found** text, just blank there and there.

**Comment by luciofm** [comment]
That's true, the names disappeared on older versions..

**Comment by rafaelks** [comment]
Yes, the behavior was already there, you're right. @luciofm found that in Realm query the User reference is coming `null`.
