### ISSUE TITLE
Hi, what is lifetime of session at Android mobile client?

### ISSUE THREAD

**Issue by oksid** [RocketChat/Rocket.Chat.Android#370]
Your Rocket.Chat.Android version: (make sure you are running the latest)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by rafaelks** [comment]
What do you mean by your question? What session? It depends on lots of things.

**Comment by rafaelks** [comment]
Closing it due to inactivity.
