### ISSUE TITLE
[NEW] Disable the ability to send messages to read only channels

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#371]
Your Rocket.Chat.Android version:  1.0.16

Mobile device model and OS version: Moto X2 - 6.1.0

Steps to reproduce:

1. Select a read only channel.
2. Send anything.

The message is sent and displayed and can be seen by any web client.

This solution should cover two fronts, disabling the Android app ability to send messages and show a warning. The backend should probably block any message if it is read only.

**Comment by mnlbox** [comment]
I have same issue on web version.

**Comment by geekgonecrazy** [comment]
if you are admin, you are allowed to send messages on web btw.  This is as designed. 

So you'll want to check permissions and see if they are muted in the channel along with the read only status.

Pretty much look at it like +m on IRC.  You can use to make moderated channels.  Or Announcement Channels

**Comment by rafaelks** [comment]
This one is already implemented in 2.1.0. 👍

**Comment by fleaz** [comment]
Hi everyone,
not sure if it's still or again broken but there is a bug regarding read-only channels in 3.2.0

The app tells me that it's a read only channel and hides the text input field but apparently doesn't has checked my user permissions because I have the admin role and am allowed to post to read-only channels.

Let me know if you need more information :)

Best regards,
Felix

**Comment by lbblitz54** [comment]
> Hi everyone,
> not sure if it's still or again broken but there is a bug regarding read-only channels in 3.2.0
> 
> The app tells me that it's a read only channel and hides the text input field but apparently doesn't has checked my user permissions because I have the admin role and am allowed to post to read-only channels.
> 
> Let me know if you need more information :)
> 
> Best regards,
> Felix

I can confirm this as well. 
It appears to be Android specific though. 
No matter what role you have: Admin, Moderator, Owner
you see "read only" and cannot post from the Android app
