### ISSUE TITLE
Why Not RxLifecycle? - By Dan Lew(author of RxLifecycle)

### ISSUE THREAD

**Issue by JigneshWorld** [RocketChat/Rocket.Chat.Android#374]
Why Not RxLifecycle?
By Dan Lew(author of RxLifecycle) 
http://blog.danlew.net/2017/08/02/why-not-rxlifecycle/

I find this library in dependencies but I am not sure at how much extends code utilize it. 
It may or may not be useful now but it's good to have a look at this article once.

**Comment by luciofm** [comment]
Dan Lew answer this question http://blog.danlew.net/2017/08/02/why-not-rxlifecycle/

**Comment by rafaelks** [comment]
@JigneshPatel23 Thanks for your suggestion! We're going to take that in consideration for 2.0.0 release. 👍
