### ISSUE TITLE
cannot login to self hosted instance

### ISSUE THREAD

**Issue by turbomettwurst** [RocketChat/Rocket.Chat.Android#375]
Issue:
When trying to login to my self hosted instance Rocket.Chat+ hangs after entering The Username and Password and never logs in.
There are no visible errors on either the Client or the Server side in terms of Logs or Error Messages.
I'd be happy to provide any additional Information, for now i am somewhat lost.

Client:
Rocket.Chat.Android version: 1.0.15
Device: Nexus 6 (Shamu) running LineageOS nightlies (7.1.2), problem has however been confirmed on multiple Devices, including Android Studio Emulator from which the following LogCat has been taken. Seems to be useless as far as i can tell, but maybe someone more knowledgable can extract some useful information.
[logcat-android-emulator-rocketchat.txt](https://github.com/RocketChat/Rocket.Chat.Android/files/1200286/logcat-android-emulator-rocketchat.txt)
It might be useful to know that the iOS Version of RocketChat+ suffers from the same issue.
 

Server:
Rocketchat Version: 0.57.2 (been running 0.52 bevor that)
User Accounts are pulled from Active Directory (LDAP)
Reverse Proxy is Apache/2.4.6 (CentOS 7)
SSL Certificate is provided by LetsEncrypt
Apache config snippet (Server employs SNI)
> <VirtualHost 3.3.3.3:443>
>    ServerName chat.xxxxx.de
>    ProxyPreserveHost On    
>    ProxyPass / http://127.0.0.1:3000/
>    ProxyPassReverse / http://127.0.0.1:3000/
>    SSLEngine on
>    SSLCertificateFile /etc/ssl/chat_domain_tld.crt
>    SSLCACertificateFile /etc/ssl/le_ca.pem
>    SSLCertificateKeyFile /etc/ssl/chat_domain_tld.key
> </VirtualHost>

**Comment by rafaelks** [comment]
@turbomettwurst You're trying to connect over username/password through LDAP?

**Comment by turbomettwurst** [comment]
yes, using samaccountname (digits only) for the username

**Comment by V3XATI0N** [comment]
I have the same symptom. I may be able to add some insight as to what might be the problem (haven't inspected code so maybe I'm super wrong) -- my setup is running at home, and my ISP blocks port 80 but not 443. So it's SSL with a valid cert, but if the app tries to hit port 80 first (despite putting https in the URL), it will hang. Also, it's reverse-proxied behind NGINX along with 300 other things, so the app needs to support SNI (I can't imagine any modern client not supporting that but who knows).

**Comment by TomaszDom** [comment]
My server is 0.58.0 behind nginx with a valid cert, with LDAP enabled.

It won't even go past the first screen, "There's a connection error, please try again later".

The "Rocket.Chat" Android app works fine, the "Rocket.Chat+" iOS app works fine, desktop app works fine, web app works fine, but the "Rocket.Chat+" Android app is useless at this time.

**Comment by austinfelipe** [comment]
I'm facing the same problem. I'm using nginx wth Let's encrypt. I'm trying to connect with an email and a password.

**Comment by austinfelipe** [comment]
Well, I figured out. Just include on your nginx config.

```
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;
                proxy_set_header        Host            $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Nginx-Proxy true;
                proxy_redirect off;
```

It seems that Rocket Chat on Android is expecting these configs.

**Comment by rafaelks** [comment]
Excellent, thanks for sharing, will close the issue.

**Comment by TomaszDom** [comment]
Wait, how is this closed? Why does my config not work then?

```
# Upstreams
upstream backend {
    server 127.0.0.1:3001;
    server 127.0.0.1:3002;
}

server {
    server_name REDACTED;
    listen 80;
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl http2 default_server;
    server_name REDACTED;

    error_log REDACTED;

    ssl on;
    ssl_certificate REDACTED;
    ssl_certificate_key REDACTED;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    resolver REDACTED REDACTED valid=300s;
    resolver_timeout 5s;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    location / {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}
```
@AustinFelipe your configuration doesn't make sense, you set the "Host" header twice with different variables, and for me it makes no difference whether it's $host or $http_host, the Android application still doesn't work.

**Comment by rafaelks** [comment]
@TomaszDom I'm sorry! What's the Nginx version you're using?

**Comment by TomaszDom** [comment]
@rafaelks I'm running nginx/1.10.3, the standard version that comes with Ubuntu 16.04.

Things I've tried:
- removing http2 in the listen directive
- commenting out "proxy_set_header X-Forwarded-Proto..."
- changing `proxy_set_header X-Forwarded-Proto http;` to `proxy_set_header X-Forwarded-Proto $scheme;`
- changing `proxy_set_header Host $http_host;` to `proxy_set_header Host $host;`

Note that I'm using a config almost 1:1 from https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy

But that doesn't inspire confidence, as "X-Forwarded-For" and "X-Forwarded-Proto" are mistyped there, probably copy and pasted from somewhere else without testing.

**Comment by rafaelks** [comment]
@TomaszDom OK, sounds good. Can you give us your server URL to make some tests?

**Comment by TomaszDom** [comment]
The URL is chat dot lab dot opeg1eka dot pl

replace "1" with "i".

**Comment by rafaelks** [comment]
@TomaszDom We're able to connect to the server from Android, but we cannot create users... can you create a test user and send it to me privately? rafael.kellermann at rocket dot chat.

**Comment by TomaszDom** [comment]
@rafaelks Before I do anything, are you really able to get past the Hostname screen?

When I input the URL and tap "Connect", all I get is "There's a connection error. Please try again."

I'm using 1.0.20.

Again, all other apps work fine (Windows Desktop, Android Cordova, iOS, Web browser).

**Comment by rafaelks** [comment]
@TomaszDom Yes, we did. We tried in two different devices. (Look at the GIF).

![2017-09-14 10 36 37](https://user-images.githubusercontent.com/551004/30432630-9e8e09f0-9938-11e7-9de9-1d1f167f3e49.gif)

**Comment by TomaszDom** [comment]
OK that's crazy, I'm using a Galaxy S6 Edge+ with Android 7.0 and it doesn't work.

I will have to sample more phones at work tomorrow and see if it's my phone or what...

**Comment by rafaelks** [comment]
@TomaszDom Are you able to access the same URL on the browser? Are you using Wi-Fi or LTE?

**Comment by TomaszDom** [comment]
I'm running the Cordova-based Rocket.Chat app on the same phone with no issues. 

I've tried the Rocket.Chat+ app on corporate Wi-Fi, on my home Wi-Fi, on LTE - doesn't make a difference.

**Comment by rafaelks** [comment]
@TomaszDom Have you tried removing the app and installing it again?

**Comment by TomaszDom** [comment]
@rafaelks Yes, many times. 

I will ask people tomorrow if they can connect using different Android phones, because this is crazy, there has to be an explanation. It just happens too quick, almost as if it doesn't try to connect at all.

**Comment by TomaszDom** [comment]
OK, nobody I know can connect to the server via the native Android app and I figured out why after MITM myself and checking what is the app trying to do based on your demo server.

When you request the demo.rocket.chat hostname, what you do is an http unencrypted call to /api/info and expect an http**s** 302 response from the server. This will never happen with my server, look the nginx configuration above, the app gets a 301 (which is the correct response - the resource is moved permanently to a secure http**s** connection).

I've no idea how were you able to bypass the 301 response from my server, you're not receiving the JSON version information you expect. 

I also have no clue how to fix this situation on my side at the moment, maybe you could make a http**s** request for /api/info and we could end this.

**Comment by TomaszDom** [comment]
After a bit of tinkering I worked around this issue and now I can connect, but I hope you fix the app.


```
# Upstreams
upstream backend {
    server 127.0.0.1:3001;
    server 127.0.0.1:3002;
}

server {
    server_name REDACTED;
    listen 80;

    location / {
        return 301 https://$host$request_uri;
    }

    location /api/info {
        proxy_pass http://backend/api/info;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }

    location /websocket {
        proxy_pass http://backend/websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}
# HTTPS
server {
    listen 443 ssl http2 default_server;
    server_name REDACTED;

    error_log REDACTED;

    ssl on;
    ssl_certificate REDACTED;
    ssl_certificate_key REDACTED;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    resolver REDACTED REDACTED valid=300s;
    resolver_timeout 5s;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    location / {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}
```

**Comment by TomaszDom** [comment]
Spoke too soon, you also make an unencrypted http call to /websocket , so I need another location directive, I added to the configuration in my previous comment.

Now the app works, but I don't think it should work this way.

**Comment by V3XATI0N** [comment]
wouldn't it make better sense to assume HTTPS to begin with and only fall back to HTTP if it doesn't work?

**Comment by TomaszDom** [comment]
Of course it would, I was just making a point.

**Comment by rafaelks** [comment]
Hey guys, we actually are doing it for `/api/info`, as you can see here:

https://github.com/RocketChat/Rocket.Chat.Android/blob/3de8d825c1caeff60d3dfb4332066f68c375b07e/app/src/main/java/chat/rocket/android/helper/ServerPolicyApiValidationHelper.java#L17-L24

We also try to use SSL when hitting the `/websocket`:

https://github.com/RocketChat/Rocket.Chat.Android/blob/c22c8f0ad312d69f735979b3b601c63191933134/app/src/main/java/chat/rocket/android/api/DDPClientWrapper.java#L42-L45

Are you talking about some other request?

**Comment by TomaszDom** [comment]
No, I'm talking about a /websocket GET at port 80 and receiving an https 302 response on port 443, you can MITM the connection and check, it behaved the same way as the /api/info request AFAIR.

I added the /api/info directive and was able to get to the login screen, but unable to log in.
Then I added the /websocket directive and was able to successfully log in.

If I find the time this week I will provide mitmproxy screenshots/logs if needed.

**Comment by astax-t** [comment]
Just wanted to say that we had the same problem with our instance of rocket chat. But it was set up with Apache in front of it, instead of nginx. After ditching Apache and installing nginx as described at https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy , mobile app started working fine.

Earlier I also noticed that websockets were sometimes failing when opening the chat in browser.

I didn't set this up, so can't provide too much details, but just wanted to share in hope that this will give a clue to find the root of the problem.

**Comment by leonardoaramaki** [comment]
@TomaszDom Does your problem got solved? If not can you try to connect to your instance using this build:
[https://985-48179404-gh.circle-artifacts.com/0/tmp/circle-artifacts.adrriIs/app-release.apk](url)
Using this build we should be able to get more logs regarding the error.

**Comment by jribal** [comment]
Found the same issue here using docker rocket chat + nginx 1.10.3 + let's encrypt ssl + sslh.
Fixed by @AustinFelipe solution which is almost the official recommended config.
```
server {
    listen 80;
    server_name chat.myserver.com;
    return 301 https://$host$request_uri;
}
```
```
server {
listen 1443 ssl http2;
server_name chat.myserver.com;

ssl_certificate           /etc/letsencrypt/live/myserver.com/fullchain.pem;
ssl_certificate_key       /etc/letsencrypt/live/myserver.com/privkey.pem;
ssl_trusted_certificate   /etc/letsencrypt/live/myserver.com/fullchain.pem;
ssl_dhparam               /etc/ssl/dhparam.pem;
ssl_session_cache  shared:SSL:2000m;
ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
ssl_session_timeout 360m;
ssl_stapling on;
ssl_stapling_verify on;
ssl on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES2...
server_tokens off;
add_header X-XSS-Protection "1; mode=block";
add_header X-Content-Type-Options nosniff;
add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; ";

location / {
    proxy_pass http://localhost:8087;
    proxy_read_timeout  90;
    proxy_redirect      off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;


    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Nginx-Proxy true;
  }
}
```
The four last lines were enough for me.

**Comment by TomaszDom** [comment]
@leonardoaramaki I will not be installing an APK from an unknown source, sorry. The config I posted solves my issue, but we will not be rolling out the native client anyway, connectivity is very unreliable, it doesn't display full names from LDAP and it doesn't display slack-style URLs at all (just blank space), but that's offtopic.

@jribal a minor difference I can see in the proxy_* parameters is you have an additional "proxy_read_timeout" statement, which shouldn't affect anything.

The real difference here is that I'm running a two-instance load balanced setup, maybe that has to do with something.

Whatever setup I'm running, it shouldn't affect initial incoming requests from the app itself though.

**Comment by leonardoaramaki** [comment]
@TomaszDom This apk is from our circle-ci build, but I do understand your concern. Upcoming fixes are to be expected soon on next release on Google Play. Regarding the connection reliability we're aware of them and we're working hard on fixing them on the upcoming Java SDK.

**Comment by atlanteg** [comment]
Hi, all.
Do you know why am I still hitting the same issue with android app version 1.1.0?
(" connection error, try later")
My rocket chat server is fresh installed with snap and caddy with ssl (letsencrypt) on non standard port (like https://myserver.xxx.xxx:22444)

**Comment by jaylenw** [comment]
Solution of using the nginx config @astax-t suggested works.
