### ISSUE TITLE
[NEW] RocketChat FCM Push notification

### ISSUE THREAD

**Issue by AppGrade-D** [RocketChat/Rocket.Chat.Android#376]
Rocket.Chat.Android version:  1.0.16

Hello.
I have a problem integrating RocketChat push notification with FCM.
Push payload looks like this: [rocket_push_payload.txt](https://github.com/RocketChat/Rocket.Chat.Android/files/1200363/rocket_push_payload.txt)

When my application is in foreground I can parse this payload and react correctly, but when application is in background, Android System parse payload automatically and do not show notification on tray. This is caused by missing obligatory fields like title and body in payload.

Is there any way to configure push payload on server side?
For example to this:  [rocket_push_final_payload.txt](https://github.com/RocketChat/Rocket.Chat.Android/files/1200378/rocket_push_final_payload.txt)

**Comment by rafaelks** [comment]
@AndDev123321 We don't have a way to customize the payload yet... why don't you use GCM? Our currently supports it.

**Comment by philipbrito** [comment]
@rafaelks Could we close this issue?

FWIW: The Android app is using FCM instead of GCM - that is deprecated since April 10, 2018.

**Comment by rafaelks** [comment]
Yes, let's close it, thanks @filipedelimabrito!
