### ISSUE TITLE
Crash loop if server has subfolder

### ISSUE THREAD

**Issue by retornaz** [RocketChat/Rocket.Chat.Android#379]
Mobile device model and OS version: Nexus 5x
App version: 1.0.15

If the server URL is : https://host.example.com/chat the application enter into a crash loop.

**Comment by philipbrito** [comment]
Could you provide the real server URL? In my test (version 1.0.16) I can not able to get these crash. I've testing for example w/ https://demo.rocket.chat/home

**Comment by retornaz** [comment]
I sent you the URL by email
