### ISSUE TITLE
Only the Test Push Notification works, no other push notifications received

### ISSUE THREAD

**Issue by apiontek** [RocketChat/Rocket.Chat.Android#382]
App version according to GPlay store: 2.5.0
Server is version 0.57.3, running in a snap on Ubuntu on Linode VPS, behind nginx ssl proxy.
Mobile device model and OS version: Nexus 6, Android 7.0

I'm not sure whether my issue is server or client (app) related, but I don't get notifications from new messages.

I do get the test notification, from "Push" in administration, when I click "Send a test notification to my user," but that's the only notification I get. At the moment my "other users" are still on our slack instance, so new messages come through the slack bridge, and I have a couple webhooks that feed messages in @my_user. I don't get notifications for any of it.

I'm interested to have my "team" (family) switch to using Rocket.Chat, but we are heavy mobile users. Even if the app is a little less polished than Slack's, reliable notifications are absolutely required.

Is this behavior not as expected? Am I missing something? Not sure where to start troubleshooting.

**Comment by philipbrito** [comment]
Are you using Rocket.Chat.Android+ app or the Cordova app?

**Comment by apiontek** [comment]
I'm not sure how to tell.

I was using [Rocket.Chat](https://play.google.com/store/apps/details?id=com.konecty.rocket.chat&hl=en)

I tried [Rocket.Chat+](https://play.google.com/store/apps/details?id=chat.rocket.android&hl=en) but it kept giving connection error on initial setup like it couldn't reach my server.

**Comment by apiontek** [comment]
Hm. I also don't get Desktop Notifications, though "Test Desktop Notifications" works. If I have the tab open in chrome, or the Rocket.Chat+ linux client open, that button generates a notification, but new messages in channels do not, whether the app/tab is behind other stuff or not. Maybe it's a server-side issue after all?

**Comment by apiontek** [comment]
Oh, I see the problem. I'm expecting to get notifications for any message of a channel I'm in, but notifications only come for mentions.

This seems to not be possible, but as it's a server issue and not an android client issue, I'll close this.

**Comment by apiontek** [comment]
Adding that I found the per-channel notification settings which aren't set to all messages by default, hence why I wasn't getting notifications. So, no issue, though I think a server setting to set a global default for new channels/users would be nice, but not a priority.

**Comment by philipbrito** [comment]
>  I tried Rocket.Chat+ but it kept giving connection error on initial setup like it couldn't reach my server.

Could you provide more info about that? If not a problem to post here, what is your server URL?

**Comment by apiontek** [comment]
I was about to make a new issue about it, actually. Should I? Server is brap.73k.us

For additional info, Android Rocket.Chat+ 1.0.15 app does connect to demo.rocket.chat but when I try instead brap.73k.us I get "There's a connection error. Please try later."

I can connect via Chrome, the Rocket.Chat+ Linux client (on ubuntu), the regular Android "Rocket.Chat" app, and from mobile browser.

Also:

With "Rocket.Chat+" after I connected to demo.rocket.chat, I couldn't figure out how to get back to the server URL entry screen, I had to uninstall and reinstall to try my server again after testing with demo.rocket.chat. Is there a way to do multi-server or "unhook/unregister" the app from a server?

**Comment by philipbrito** [comment]
I'm able to connect to your server using the Rocket.Chat.Android+ 1.0.16 version (it is under development yet but we'll release on Play Store as soon as possible).

To get back to the server setup screen, after login, you can do the logout. It is easy, simple touch the right button beside your username on sidebar. Take a look:

![photo_2017-08-11_10-52-39](https://user-images.githubusercontent.com/11776825/29216371-d486e87a-7e84-11e7-9cc8-7b6a7f2015b3.jpg)

Tip: you do not need to uninstall and reinstall the app when facing some issue. Clear the app cache on Android app settings.

**Comment by apiontek** [comment]
OK, I'll look for the .16 release.

I did tap "Logout" and it closed the app. When I re-opened the app, it logged me right back in. Thanks, I forgot about clearing the app cache... 

THANK YOU!

**Comment by apiontek** [comment]
Confirming I'm able to connect & login with .16 release.

**Comment by philipbrito** [comment]
Cool! Thanks for the info!
