### ISSUE TITLE
[BUG] App jumps the login screen after setting the hostname

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#384]
Your Rocket.Chat.Android version: 1.0.16

After setting the hostname w/ a subdirectory URL (like https://host.example.com/chat) the app jumps the login screen and shows a "empty" home screen. The solution for that is to close the app and reopen it again to show the login screen. This  behavior doesn't happen w/ a "normal" server URL (e.g https://chat.example.com).

![photo_2017-08-14_13-30-20](https://user-images.githubusercontent.com/11776825/29281285-c9253834-80f4-11e7-837e-cac3bb10cf76.jpg)

![photo_2017-08-14_13-30-13](https://user-images.githubusercontent.com/11776825/29281286-caaf5e0a-80f4-11e7-952f-c7b6fc838f0c.jpg)

**Comment by rafaelks** [comment]
@filipedelimabrito Is this still happening?

**Comment by philipbrito** [comment]
It still happens @rafaelks.

**Comment by rafaelks** [comment]
Closing this issue in favor of our milestone 2.0.0 that is almost completed. More information here: https://github.com/RocketChat/Rocket.Chat.Android/milestone/6
