### ISSUE TITLE
[NEW] App shows a register button on servers with "new user registration" option disabled

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#385]
Your Rocket.Chat.Android version: 1.0.16

Some RC servers doesn't allow the new user registration on their systems (on the login screen), but the RC Android app always shows a register button. 

The app should display the register button only accordingly with the server configuration.

**Comment by antgel** [comment]
Any updates on this? Really confusing for users.

**Comment by philipbrito** [comment]
@antgel We are working in a new Android app version (v2). In that version we'll honor that settings. I'd just ask you for a little more patience.

**Comment by philipbrito** [comment]
Starting from `v2`  this issue is already solved.
