### ISSUE TITLE
How to get compiled apk?

### ISSUE THREAD

**Issue by kkachura** [RocketChat/Rocket.Chat.Android#386]
Your Rocket.Chat.Android version: (make sure you are running the latest)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by kkachura** [comment]
Hi! I not a java developer and get errors via making application. How to get apk?

**Comment by ghost** [comment]
It's on google play. https://play.google.com/store/apps/details?id=chat.rocket.android&hl=de

**Comment by philipbrito** [comment]
To get the most recent apk in production you should go to the Play Store and download the `Rocket.Chat+` app (link already posted above).

To get the most recent apk in development you should generate the app from the AS. How? https://developer.android.com/studio/run/index.html
