### ISSUE TITLE
[NEW] Friendly way to interact with a post

### ISSUE THREAD

**Issue by SkinkaCru** [RocketChat/Rocket.Chat.Android#396]
This is a request for a new feature : I'd like to get a more friendly way of interacting in a channel on the app.

When someone post something, you have to do a "long push" on the screen in order to get the "interaction" menu. Then you can touch "reply" or "reactions" or anything else. Sometimes it's working, sometimes you cannot interact depending on the context (image, text, etc.).

Is is possible to add a simple way to interact on a post. For instance, add a popup above the post when you tap it. Or add a context menu when you double tap it ?

**Comment by rafaelks** [comment]
@SkinkaCru That's a good feature request, thank you! I'll leave this issue opened so we can add to our schedule of development.

**Comment by rafaelks** [comment]
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).
