### ISSUE TITLE
Search and mentions on the right side

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#401]
Your Rocket.Chat.Android version: 1.0.16

I just noticed that swiping from right side show a menu with three icons. search, members and mentions(i guess). But only members is working, the rest of them are disabled. Is this intentional or being worked on?

**Comment by philipbrito** [comment]
Hi @mmarif4u  

It will be implemented. Any news, I update you.

**Comment by rafaelks** [comment]
Closing this issue, the features are going to be implemented in separated issues. Thank you @mmarif4u!
