### ISSUE TITLE
No Obvious Scaling or Font Size Options

### ISSUE THREAD

**Issue by jdkang** [RocketChat/Rocket.Chat.Android#402]
Your Rocket.Chat.Android version: (make sure you are running the latest)
`2.5.0`

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")
`Moto X Pure / Android 6.0`

# Issue
The app is nearly unusable as a low vision user -- even compared to the Slack mobile app. The default scaling is very tiny compared to all other apps and I see no obvious way to re mediate this. 

![screenshot_20170821-190308](https://user-images.githubusercontent.com/1807929/29541938-7e7724c6-86a5-11e7-9577-bdfd2aed7fbc.png)
![screenshot_20170821-190409](https://user-images.githubusercontent.com/1807929/29541937-7e75e4da-86a5-11e7-9ee7-c67349586c08.png)

**Comment by rafaelks** [comment]
@jdkang Please, use the correct repository to open this issue, this issue is related to the Cordova application: http://github.com/RocketChat/Rocket.Chat.Cordova/.
