### ISSUE TITLE
[BUG] Push notifications broken with latest update

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#405]
Your Rocket.Chat.Android version: 1.0.16 (18 Aug update)

Mobile device model and OS version: OnePlus 3T - Android 7.1.1

After updating to the latest version(above), i don't receive notifications anymore. Cleared cache, reinstalled, all the same.

**Comment by rafaelks** [comment]
@mmarif4u Thank you for opening the issue, we're working on it!

**Comment by DoM1niC** [comment]
Since the last Commits the Notification via Firebase works, but could someone explain why the Cloud Messaging not working on Rocket Chat Server? 

The Project ID is the Sender ID I think and the API KEy is the Server Key .... ????

**Comment by mmarif4u** [comment]
Updated to 1.0.17, the issue still exists.

**Comment by leonardoaramaki** [comment]
@mmarif4u Are you logged in at the web client and/or the desktop app at the same time as the Android app?

**Comment by izhdan** [comment]
Push notification do not work for me either, on Meizu M5 (Flyme 5.2.10/Android 6.0). Doesn't matter if I'm logged in in any other instance, tried with/without login to either web/desktop/legacy android versions.

**Comment by mmarif4u** [comment]
@leonardoaramaki I have tried it in different scenarios, its mute(does not work).

**Comment by leonardoaramaki** [comment]
@mmarif4u Are you testing on the demo server (https://demo.rocket.chat)?

**Comment by mmarif4u** [comment]
@leonardoaramaki nope, we have our own hosted server.

**Comment by leonardoaramaki** [comment]
@mmarif4u Just a few checks to make sure we're on the same page. :)

1. At the Admin panel, Push section, on your RC server, have you set the Android key or the server key for your project on the **GCM API Key** field?
2. On that same panel and section, have you set your **Sender Id** at the **GCM Project Number** field?
3. Assuming both items above are set, have you disabled RC gateway?

**Comment by mmarif4u** [comment]
@leonardoaramaki by own server i mean RC server not push notification server for self build RC Android app. We are using app from the Play Store, the default app which i assume do not need GCM keys.
Which means we are using RC gateway.

**Comment by mmarif4u** [comment]
Just for the record, we have iOS users and they have no problems with push notifications, only Android users have problem with it.

Also `needs info` label can be removed as it is misleading this issue now. 
It was addressed by @rafaelks in another issue that they know what the issue is with Android notifications. Hope fix will hit the Play Store soon, as at this time we have to open the app to see if we have any messages(important some time).

**Comment by rafaelks** [comment]
@mmarif4u Can you help us testing our latests fixes? Here's the build: https://941-48179404-gh.circle-artifacts.com/0/tmp/circle-artifacts.C7OzWp8/app-release.apk.

You can also download it from Google Play (Beta).

**Comment by mmarif4u** [comment]
@rafaelks updated to the latest version on Google Play, and i can confirm it is working now. Thanks a lot for heads up on this.

**Comment by rafaelks** [comment]
That's great! I'll close the issue in this case.

**Comment by danieljhochman** [comment]
@rafaelks - is this fix in master? Can you link to the PR which fixes this please?

**Comment by rafaelks** [comment]
@danieljhochman Not yet, this will be shipped on 1.0.20 release (coming this week 🙏).

PR: https://github.com/RocketChat/Rocket.Chat.Android/pull/462.
