### ISSUE TITLE
Permission Denial - While uploading File

### ISSUE THREAD

**Issue by JigneshWorld** [RocketChat/Rocket.Chat.Android#406]
**Your Rocket.Chat.Android version: 1.0.16**

**Mobile device model and OS version: Android 7.1.1 (OnePlus3)**

**Error log writtern in realm FileUploading model:**
`Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A189155 from pid=664, uid=10484 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()`

**Steps to Reproduce(Try on real device):**
1. Open any room
2. Try to post images which is captured by camera
3. It will not get progressed
4. You can find error log on realm db or need to put debug logs for more details.

**Comment by rafaelks** [comment]
@leonardoaramaki Can you take a look on this bug? Maybe is related to the PR we changed the permissions regarding background process.

**Comment by JigneshWorld** [comment]
@rafaelks @leonardoaramaki 
After updating to the latest code, I can't able to generate this issue.
I am closing this right now. If required will open this again and try to fix.
