### ISSUE TITLE
RocketChat call webService on android client

### ISSUE THREAD

**Issue by pishguy** [RocketChat/Rocket.Chat.Android#413]
since 3 days ago i'm trying to find which file or implementation on android client is for RocketChat REST web services, for example:

`/api/v1/login`

unfortunately i cant find implementation classes for them to learn that for developing client application, Thanks in advance

**Comment by luciofm** [comment]
@MahdiPishguy the Android app currently doesn't use the REST API, it is entirely based on the WebSocket and DDP protocol, you can take a look on the android-ddp module.

This will change in the future, as we will start using the REST API for certain operations.

**Comment by pishguy** [comment]
@luciofm so how can i find document of `DDP protocol` which used in Rocket.Chat?

**Comment by philipbrito** [comment]
https://rocket.chat/docs/
