### ISSUE TITLE
[FIX] Keyboard should not close after sending a message

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#417]
After typing and posting one message, the keyboard closes and for the next continuation message have to tap again to bring it up. For user experience i would advise to let the keyboard stay and continue with the rest of the messages.

**Comment by rafaelks** [comment]
@mmarif4u Good one, thanks @mmarif4u!

**Comment by danieljhochman** [comment]
However, the keyboard should close when you click the hamburger menu and currently it does not. Should I file a separate issue about that @rafaelks ?

**Comment by rafaelks** [comment]
@danieljhochman I agree with you, can you open another issue please?

**Comment by danieljhochman** [comment]
@rafaelks - done. Filed as #420

**Comment by mmarif4u** [comment]
Forgot to mention, after hitting the send button, focus should be on the input box to start typing immediately.

**Comment by philipbrito** [comment]
Very very important opened issue to a chat based application! Although it doesn't break the app, it was making unhappy users (very annoying to have to open the keyboard after sending a message to send another message).

That PR solves this issue: https://github.com/RocketChat/Rocket.Chat.Android/pull/435

Thanks for your contribution! :heart:
