### ISSUE TITLE
Show loader instead of "Start of Conversation" when loading room

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.Android#419]
RC Android Version 1.0.16

When accessing a room or DM which was not yet loaded, you see "Start of Conversation" and then a few seconds later the chat history loads. Instead, a loader should be shown until the chat history has loaded. 

Otherwise, the user is misled and thinks there is no history in the room.

**Comment by rafaelks** [comment]
This is already fixed in 1.0.17, you can try our Beta version in Google Play.
