### ISSUE TITLE
User status in the member list are wrong

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#426]
App version : Android, 1.0.17

The member list(swiping from right opens the menu to choose from) pop-up shows the users for the channel, but at times it shows the wrong status. Like the user on the web version is offline(gray), the app shows either orange or green(depends). 

Also sometime it does not show the list and only showing total members count.

**Comment by mmarif4u** [comment]
It some time update the status but after a while. Like opening that list for 5 times.

**Comment by rafaelks** [comment]
@mmarif4u Thanks for opening the issue, we're going to rewrite all the members list using a different API request, so I'm closing this issue but you can follow the progress here: #421.
