### ISSUE TITLE
Build Error - bad return type in lambda expression Completable cannot be converted to ? extends Completable

### ISSUE THREAD

**Issue by chris-shaw-2011** [RocketChat/Rocket.Chat.Android#433]
I followed the directions for building the app. I have Java 8 (JRE and JDK installed) but when I try to build the project using android studio 2.3.3 I get the following error:

Error:(377, 43) error: incompatible types: bad return type in lambda expression
Completable cannot be converted to ? extends Completable

This is on a mac with OSX 10.12.6.

On a Windows 10 computer I don't have this issue

**Comment by philipbrito** [comment]
Hi @crisco96 ! :)
If you are fine w/ Windows OS and you aren't fine with macOS, then this issue is not related to this project.

FWIW: I'm able to build the app w/ Sierra and Yosemite.

**Comment by philipbrito** [comment]
Anyway, feel free to post your the log here, so, some of the community (including me) can help you.
