### ISSUE TITLE
[NEW] Let user recover the 2FA code with backup code (needs to support letters)

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#437]
Your Rocket.Chat.Android version: 1.0.18

Mobile device model and OS version: Pixel XL Android 8.0

Shows numeric only keyboard.  If for some reason you need to enter a backup code they are letters.  

It being numbers is pretty useful when you're entering a regular 2FA code.  So maybe an option to enter backup code that will switch to full keyboard?

**Comment by rafaelks** [comment]
@geekgonecrazy Good catch! I believe an option to recover is the better way to go... let me change the title of your issue a little bit so we can start working on it! 👍

**Comment by rafaelks** [comment]
@filipedelimabrito Can you confirm if this one is already present in version 2, please?

**Comment by philipbrito** [comment]
Version 2 allows to enter regular 2FA codes as well as backup codes.
