### ISSUE TITLE
Upload of image gets stuck at 100% and can only be cancelled

### ISSUE THREAD

**Issue by ericzolf** [RocketChat/Rocket.Chat.Android#44]
Your Rocket.Chat.Android version: 0.45.0 (make sure you are running the latest => I'm pretty sure it's the case but I don't know if the version is from the app, or from the server, or both - it's definitely the latest from the app store and I haven't refused any proposed upgrade OTA).

As the subject says: try to upload an image, either taken from camera or just from an already existing file, and the image will upload up to 100% and stay stuck there. There is a green bar with the name of the file + 100% + a cancel button, and the only thing I can do is to cancel. Same file, same server, same WLAN, but with the desktop app, and it works flawlessly.

**Comment by YusukeIwaki** [comment]
Is this for [Cordova](https://github.com/RocketChat/Rocket.Chat.Cordova) version?

**Comment by ericzolf** [comment]
On 25/11/16 14:55, Yusuke Iwaki wrote:
> Is this for Cordova <https://github.com/RocketChat/Rocket.Chat.Cordova>
> version?

No clue, it's the Android app available from the Market as
https://play.google.com/store/apps/details?id=com.konecty.rocket.chat
