### ISSUE TITLE
[BUG] Username field pass even if request responds with error

### ISSUE THREAD

**Issue by KanthWasTaken** [RocketChat/Rocket.Chat.Android#444]
Rocket.Chat.Android version: 1.0.16 (also seen on live version 1.0.17 didn't check on 1.0.18)

When registering an account, if you set a username already in use you get an error message but you still get "logging" and the account is created anyway. And on that kind of accoutn you can't see anything or send a message to anyone.

**Comment by rafaelks** [comment]
Good finding, thanks @cheval-2!

**Comment by rafaelks** [comment]
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).
