### ISSUE TITLE
Share a file via Rocket.Chat app doesn't work

### ISSUE THREAD

**Issue by ericzolf** [RocketChat/Rocket.Chat.Android#45]
Your Rocket.Chat.Android version: 0.45.0 (make sure you are running the latest => latest from market + all upgrades OTA accepted)

If I share a file in Android, I can select Rocket.Chat as app for sharing, and the app's window appears but then nothing happens. I would expect that I can select a channel and the shared file is then uploaded.

**Comment by YusukeIwaki** [comment]
Is this for [Rocket.Chat.Cordova](https://github.com/RocketChat/Rocket.Chat.Cordova)?

**Comment by ericzolf** [comment]
On 25/11/16 14:55, Yusuke Iwaki wrote:
> Is this for Rocket.Chat.Cordova
> <https://github.com/RocketChat/Rocket.Chat.Cordova>?

No clue, it's the Android app available from the Market as
https://play.google.com/store/apps/details?id=com.konecty.rocket.chat

**Comment by YusukeIwaki** [comment]
> https://play.google.com/store/apps/details?id=com.konecty.rocket.chat

This is [Rocket.Chat.Cordova](https://github.com/RocketChat/Rocket.Chat.Cordova).
Actually Rocket.Chat.Android is now under heavy development and not available in Google Play.
