### ISSUE TITLE
Need info about publications & stream with DDP

### ISSUE THREAD

**Issue by JigneshWorld** [RocketChat/Rocket.Chat.Android#460]
**Understanding**
As per my understanding on Rocket Chat platform(correct me if I am going in wrong directions),
we[(Android native - DDP)](https://github.com/RocketChat/Rocket.Chat.Android/tree/develop/app/src/main/java/chat/rocket/android/service/ddp) have 2 abstract class for subscription from [AbstractDDPDocEventSubscriber](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/app/src/main/java/chat/rocket/android/service/ddp/AbstractDDPDocEventSubscriber.java) with their own purpose to communicate with the server 

> [AbstractStreamNotifyEventSubscriber](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/app/src/main/java/chat/rocket/android/service/ddp/stream/AbstractStreamNotifyEventSubscriber.java) - Communicate with server about [streams](https://github.com/RocketChat/Rocket.Chat/tree/develop/server/stream)

> [AbstractBaseSubscriber](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop/app/src/main/java/chat/rocket/android/service/ddp/base/AbstractBaseSubscriber.java) - Communicate with server about [publications](https://github.com/RocketChat/Rocket.Chat/tree/develop/server/publications)

As we can see that publication may have parameter as per the need of request but as of now the android app is not using in subscription which has param so we have `protected final JSONArray getSubscriptionParams()` on  `AbstractBaseSubscriber` and then we can't override that method in their subclass. 

**Questions**
1. To call param based other subscription which is publications, does it better to make a change in the existing method to remove final or create a new base class for this for other methods? 
2. [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) - Which one is the better for client-server two-way message sync [publications](https://github.com/RocketChat/Rocket.Chat/tree/develop/server/publications) vs [streams](https://github.com/RocketChat/Rocket.Chat/tree/develop/server/stream) to implement new stuff?

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by JigneshWorld** [comment]
Yes @MartinSchoeler it's not in that criteria will post it on mentioned support channels.
Thanks for pointing to the support options.
