### ISSUE TITLE
[BUG] Notification icon is not visible clearly on S8

### ISSUE THREAD

**Issue by karolymarton** [RocketChat/Rocket.Chat.Android#464]
Your Rocket.Chat.Android version: Rocket.Chat+ 1.0.18
Mobile device model and OS version: Samsung Galaxy S8 (Android 7)

Notification icons should be white on transparent background:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html

But this icon is red on transparent background:
https://github.com/RocketChat/Rocket.Chat.Android/blob/9c34af88ca9227aeb182cad95d57439a96db28bc/app/src/main/res/drawable/rocket_chat_notification_24dp.xml

I'm not an android developer but I think this could be easily fixed with updating the icon shapes to #FFFFFF.

Best regards,
Karoly

**Comment by karolymarton** [comment]
![rocket_chat_notification_icon_error](https://user-images.githubusercontent.com/181026/30480763-bac636cc-9a1b-11e7-82af-eeb372642108.png)

**Comment by rafaelks** [comment]
@mdesign83 Thank you for opening the issue! I've seen this happening in other devices as well... let's try to add all icons we need for that.

cc @RocketChat/android
