### ISSUE TITLE
disable showing channel on first time

### ISSUE THREAD

**Issue by pishguy** [RocketChat/Rocket.Chat.Android#465]
I'm trying to disable show channel content on first time, i like to click on channel on sidebar to show that on main fragment, which part of code should be changed? i can't find

thanks in advance

**Comment by rafaelks** [comment]
@MahdiPishguy Sorry but I didn't understand your issue... can you explain with more details?

**Comment by MrSagarShah** [comment]
@MahdiPishguy 
What I understand from your comment is :
Rocket chat is showing the last opened room when you come back to the application and you want to change it to default screen everytime.

if that's what you need then please read below lines.

you just need to comment the following lines from the class AbstractAuthedActivity under onCreate method.

```
updateHostnameIfNeeded(rocketChatCache.getSelectedServerHostname());
updateRoomIdIfNeeded(rocketChatCache.getSelectedRoomId());
```

and you also need to remove/comment "`openRoom();`" inside MainPresenter under on bindView method.

Just in case if you want to show the default screen initially then add a call to "`showHome();`" in MainActivity at the end of the onCreate method.

I am not sure I have answered your question. I tried to help with best of my knowledge.
Hope it helps.

If this is not what you are looking for, please provide more details.

**Comment by pishguy** [comment]
@arrowoliver Thanks you very much sir, thats my answer of question

**Comment by rafaelks** [comment]
@arrowoliver @MahdiPishguy Great, thank you!!!

**Comment by MrSagarShah** [comment]
@MahdiPishguy @rafaelks 
Happy to help...!! :)

**Comment by pishguy** [comment]
@rafaelks @arrowoliver hi could you help me on this issue? 

 #499 

Thanks in advance
