### ISSUE TITLE
[NEW] Integrate with Jitsi

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#466]
**Settings involved:**

- _uniqueID_: currently not being returned, but good to leave it mapped as a string.
- _Jitsi_Enabled_: `true` or `false` in case Jitsi is enabled.
- _Jisti_Enable_Channels_: If Jitsi is enabled for channels/groups or only DMs.
- _Jitsi_SSL_: If the protocol for the Jitsi URL is `https://` or `http://`.
- _Jitsi_Domain_: The Jitsi domain that will be used to create the URL.
- _Jitsi_URL_Room_Prefix_: The Jitsi prefix after the URL domain to generate the URL.

**How to generate the Jitsi URL:**

> protocol + domain + "/" + prefix + uniqueID (or "undefined") + rid

Here's how iOS is doing:

https://github.com/RocketChat/Rocket.Chat.iOS/blob/6ee5a3f9b291be67c26fa3a96911ba5b1f9200b8/Rocket.Chat/Controllers/Video%20Conferencing/JitsiViewModel.swift#L35-L51

**Jitsi Timeout Update (every 10 seconds):**

There's a WebSocket call that needs to be called every 10 seconds when a Jitsi call is happening. This is required in order to work on the web client.

https://github.com/RocketChat/Rocket.Chat.iOS/blob/6ee5a3f9b291be67c26fa3a96911ba5b1f9200b8/Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift#L136-L144

**Jitsi System Message**

There's a new type of system message that needs to be handled: **jitsi_call_started**. When there's a message with this type, the interface needs to show a message and a button to join a video call (using the current room Jitsi URL).

Icon and button style are all in our Zeplin Android project.

**Other things that need to be done**

- Needs to add an option in the channel details to start a video call if settings allow the user to do it;
- Needs to add an option in the user details screen to start a video call with the user if settings allow the user to do it;

**Comment by FaizanZahid** [comment]
video and voice calls on rocket chat will make this a superb app.

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2139
