### ISSUE TITLE
Search by "#channel" returns no results

### ISSUE THREAD

**Issue by anthonylavado** [RocketChat/Rocket.Chat.Android#467]
_Your Rocket.Chat.Android version:_
1.0.18

_Mobile device model and OS version:_
Samsung Galaxy S7 (SM-G930W8) - Android 7.0

Hi there!
Just had this confirmed by one of our users and myself.

If we search for a channel by name alone, we get a result. If we search for a channel with a "#" infront of the name, there are no results returned.

In the Cordova version of the app (which is the same as the Web UI), the search works with either format for channel name.

Examples:
<img src="https://user-images.githubusercontent.com/596194/30557483-7355f558-9c7c-11e7-8432-ee1abd27c4ee.png" width="250" height="250">
<img src="https://user-images.githubusercontent.com/596194/30557482-735509ae-9c7c-11e7-9a10-f43ac905b5d6.png" width="250" height="250">

**Comment by filipedelimabrito** [comment]
Thanks! We'll fix it soon!

**Comment by rafaelks** [comment]
@macabeus I believe this is all handled by web-client, but should be in our back-end, the method that we use to search. Let me talk to the back-end team and see what we can do.

**Comment by rafaelks** [comment]
This is going to be handled by back-end: https://github.com/RocketChat/Rocket.Chat/issues/8205.
