### ISSUE TITLE
[BUG] No stable connection when changing networks (LTE -> Wi-Fi -> LTE...)

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.Android#469]
Your Rocket.Chat.Android version: Rocket.Chat+ 1.0.18
Server: 0.58.2

We cant provide a stable connection between Rocket.Chat+ on different Android Devices and the Rocket.Chat-Sever. We switch a lot between different WLAN-Hotspots and LTE and have a huge problem with the Android-App. The App often says "Authenticating" and nothing happens after a while in the background. You have to restart the App to get a connection to the server. Sometimes when you are connected a message cant get send and you get a "Failed to sync" error. The same behavior is reproducable on different Android devices (in our case: OnePlus 3T with Android 7.1.1, Moto G5 with Android 7.0) 

The Server runs via SNAP Installation on a virtual Ubuntu Server. From the Internet an Apache Reverse Proxy handles the connection.

The iOS Rocket.Chat+ App doesn´t have this issues.

Is there a know problem or can i provide further informations to get a fix for this problem?

**Comment by rafaelks** [comment]
@ArchimedesFM Thanks for opening the issue! We're working hard to fix those issues with our brand new SDK (http://github.com/RocketChat/Rocket.Chat.Java.SDK) in Android. I'll ask you a bit o patience and wait for new updates in the next months.

**Comment by ArchimedesFM** [comment]
@rafaelks Thank you for your answer, but i want to go a bit further. Is this a widely known Problem or a new one? Are you already working on this or is a fix far far away in 2018? We want to roll out Rocket.Chat in our Company on PCs, iPhones and Android devices, but we can not do this with an unstable Android App. Is there any alternative or Workaround in your opinion?

**Comment by rafaelks** [comment]
@ArchimedesFM This is a known issue (and old) in our Android app. I'm really sorry for that, I can assure you we're working really hard to get this fixed.

**Comment by ArchimedesFM** [comment]
The problems are still present in Android App 1.0.21.

**Comment by rafaelks** [comment]
@ArchimedesFM Yes, we're doing a rewrite in our network layer that is going to fix this problems.

**Comment by ccfiel** [comment]
any updates on this? :)

**Comment by leonardoaramaki** [comment]
@ccfiel We have a new version available at Google Play on Beta channel. It has many improvements on network issues. It's still not bulletproof but it's a checkpoint for us. Any help on testing it will be appreciated.

**Comment by ccfiel** [comment]
@leonardoaramaki  how can I apply for beta test? :) I love to help

**Comment by leonardoaramaki** [comment]
@ccfiel It's open to everyone.
Just go to the Rocket.Chat+ app on Google Play and scroll to the bottom to apply :)

**Comment by ccfiel** [comment]
Ok got it! 😀

**Comment by ccfiel** [comment]
Using beta version now. So far so good :) I test some more. Hopefully, its now solved. @ArchimedesFM  Try the beta

**Comment by ArchimedesFM** [comment]
The connection in beta 1.0.33 is much more stable then in the old release 1.0.18.
I dont know how much of the refactoring is done, but you are on a good way.

**Comment by rafaelks** [comment]
@ArchimedesFM Thanks for the feedback! @leonardoaramaki is working hard to fix it! 🎉

**Comment by rafaelks** [comment]
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).
