### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat.Android#47]
Your Rocket.Chat.Android version: (make sure you are running the latest)

I get the following error message when I try to build.

I'm coming from cordova, and I'm a bit new to this:

Rocket.Chat.Android/realm-helpers/src/main/java/chat/rocket/android/realm_adapter/RealmModelViewholder.java:7: error: class RealmModelViewHolder is public, should be declared in a file named RealmModelViewHolder.java
public abstract class RealmModelViewHolder<T extends RealmObject> extends RecyclerView.ViewHolder {
                ^
1 error
:realm-helpers:compileReleaseJavaWithJavac FAILED

**Comment by laggedHero** [comment]
A typo on the file name. I'll fix it

**Comment by laggedHero** [comment]
@Syirrus it's done. Have fun!

**Comment by Syirrus** [comment]
@laggedHero Thanks very much. I actually just noticed it before you sent your reply. It compiles and runs, I enter my rocket.chat server and all is well. However, when I try to login, it does nothing :(
