### ISSUE TITLE
[NEW] Add support to Reactions

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#473]
# Description

Let user see and react to a message (including with custom emojis).

## Custom emojis

There's a web socket call that returns all custom emojis from the server, you can read more about it here: https://rocket.chat/docs/developer-guides/realtime-api/method-calls/list-custom-emoji/#list-custom-emoji.

Blocked from #474 

## Fetching the reactions of some message

On the message object, there's a property called `reactions` that contains all the reactions for that message. This field is returned by default in all web socket calls. Example:

```json
{
    "reactions" : {
        ":heart_eyes:" : {
            "usernames" : [
                "matheus.cardoso",
                "rafael.kellermann"
            ]
        },
        ":rocket:" : {
            "usernames" : [
                "matheus.cardoso",
                "rafael.kellermann"
            ]
        }
    }
}
```

## Adding a reaction to a message

Documentation: https://rocket.chat/docs/developer-guides/realtime-api/method-calls/set-reaction/#set-reaction

**Comment by simonv3** [comment]
We just stumbled onto this while trying to use rocketchat to run a meeting and were disappointed that mobile members couldn't vote using the emoji.

**Comment by rafaelks** [comment]
@simonv3 This is in progress already.

**Comment by arthurgiustina** [comment]
![reactions](https://user-images.githubusercontent.com/30700871/34530490-76aaf30c-f096-11e7-8abd-8fec92d47de5.png)


@rafaelks Link to Abstract updated: https://share.goabstract.com/7e110105-4bd6-48cc-b496-9beb6c99a1b2

**Comment by antgel** [comment]
Do we have to wait for #474 before implementing this? Seems like this could go live first without custom emojis.

**Comment by rafaelks** [comment]
@antgel No, we don't have to wait. We can start simply using the existent emojis.

**Comment by antgel** [comment]
@rafaelks Cool. Is anyone working on it? It would make a lot of people very happy. :laughing: (i.e. Can you remove the blocked label?)

**Comment by rafaelks** [comment]
@antgel No there isn't right now (we're very focused in our 2.0.0 release, check out `develop-2x` branch please). It would be amazing if you could write down the code to support reactions in our 2.0 release :-)

**Comment by antgel** [comment]
I'd love to, but I have no Android experience and a heavy personal backlog. Will definitely check out the branch anyway. Is there a spec for the emoji feature, so that I can wave it by any Android devs that I know?

**Comment by rafaelks** [comment]
@antgel I see, sounds good. Maybe that's a way for you to get some experience with Android? :-)

The emoji feature is very simple: we want to add an emoji icon (I can provide that for you) on top of the text field, when user press it, we'll open a view (with the size of the keyboard) so the user will be able to include emojis on the text. The emojis are provided from `Emojione` library right now.

**Comment by antgel** [comment]
@rafaelks You've encouraged me to dip my toe in. ;)

What do you mean "on top of the text field"? Do you mean that:

1. When user clicks on the message, in addition to the existing Reply / Quote / Edit etc, there will be a React option?
2. Every message will have a react icon, say in the top right corner?

The second option seems messier. Anyway, please guide me to the emoji icon.

Next, what do you mean the view will open "with the size of the keyboard"? In the screenshot above from @arthurgiustina , it's full-screen, no?

Also, what do you mean by "Emojione right now"? I don't see any use of Emojione in the codebase.

Lastly, how should the reactions to a given message be displayed? Below the message?

**Comment by antgel** [comment]
@rafaelks Ping? I was hoping to have a crack at this today.

**Comment by rafaelks** [comment]
@antgel Sorry for the delay... @leonardoaramaki is working into the Emoji keyboard integration, I believe it'll be easier for you to work with emojis after his PR gets merged.

Regarding your questions:

1. Yes. This is how we do on iOS already.
2. No.

Regarding the size: Yes, for Reacting to a message, let's use a fullscreen view.

Emojione is being integrated on @leonardoaramaki PR.

The reactions should be displayed the same way we have on iOS today, like this:

![2018-02-19 13 42 41](https://user-images.githubusercontent.com/551004/36388508-d0b06ed2-157a-11e8-8f23-5458ee826bef.gif)

**Comment by antgel** [comment]
@rafaelks Awesome, thanks for the response! Is there an issue or open PR that I can follow in order to know when @leonardoaramaki 's PR is merged?

**Comment by rafaelks** [comment]
@antgel Yes, you can subscribe to this PR: https://github.com/RocketChat/Rocket.Chat.Android/pull/759
