### ISSUE TITLE
[NEW] Pre-select last selected room (or first room in list)

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.Android#476]
When a user opens the app, pre-select the last selected room. Also, for the first time a user opens the app- select the first room in the list.

**Comment by cemore2048** [comment]
@filipedelimabrito can I take this?

**Comment by philipbrito** [comment]
Of course! Feel free @ralphie9224 to do that! You are welcome :)

**Comment by cemore2048** [comment]
@danieljhochman what does the app currently do now? If I select a room, and close the app, it comes back to that selected room. What do you mean by "pre-select"?

**Comment by danieljhochman** [comment]
@ralphie9224  - last time I checked it opens a blank screen telling you to select a channel from the drawer. It should open the last room the user had loaded. New users should open to the first room in the list of available rooms.

**Comment by cemore2048** [comment]
@danieljhochman hmmm I'm not sure it does that anymore. I can't recreate the issue. any time I leave the app and come back to it, it'll just open up the last opened room

**Comment by rafaelks** [comment]
This one isn't valid anymore for version 2.0.0.
