### ISSUE TITLE
[NEW] Implement notification settings

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.Android#481]
Your Rocket.Chat.Android version: 1.0.20

On the web I have the option of disabling notifications and unread status.

![image](https://user-images.githubusercontent.com/1986378/30975560-f1a8eacc-a448-11e7-94d5-b4e075dffd77.png)

I would like the mobile app to respect that option. I chose not to see any `#general` notifications, even the unread status, but on the mobile it shows up on my channels list as unread.

**Comment by leonardoaramaki** [comment]
I'm closing this in favor of the same issue https://github.com/RocketChat/Rocket.Chat.Android/issues/1203
referencing the new app.
