### ISSUE TITLE
Details page does not show all content, if too long

### ISSUE THREAD

**Issue by ctel** [RocketChat/Rocket.Chat.Android#482]
My Rocket.Chat.Android version: 2.5.0
Mobile device model and OS version: Huawei Honor 8 - Android 7.0, EMUI 5.0
Resolution (might be related to this bug, so I spare you the lookup ;)): 1080 x 1920

It is a visual bug: Just open the details page of a group or user, as seen on the screenshot.
Not all buttons should be visible (partial visibility) and the scrollbar is at its lowest possible position.

Left: screenshot from mobile device; visible area ends abruptly on the bottom
Right: desktop screenshot as it should be; just for reference
![screenshots](https://user-images.githubusercontent.com/9321348/30976345-da8bc298-a474-11e7-9ae3-48351b51d78f.png)

**Comment by philipbrito** [comment]
Hi @ctel! This issue belongs to https://github.com/RocketChat/Rocket.Chat.Cordova

Could you post that issue there?
Thanks.
