### ISSUE TITLE
Cannot use app if server cannot be contacted

### ISSUE THREAD

**Issue by callumthomson** [RocketChat/Rocket.Chat.Android#483]
Hello,

My old RocketChat server is no longer running. I want to connect to my new one, but when I open the app it attempts to connect to the old one forever and it is impossible to stop it and add a new server. Currently I have to reinstall the app to fix.

Rocket.Chat.Android version: Cannot find according to instructions.

Mobile device model and OS version: Samsung S6 - Android 7.0

**Comment by MrSagarShah** [comment]
Hi @callumthomson 
I think this issue will be fixed with https://github.com/RocketChat/Rocket.Chat.Android/issues/469 issue.
Please check it once. It might help you move forward.

**Comment by callumthomson** [comment]
@arrowoliver 
This is not quite the same issue. My issue is that my old server is no longer running, but the app does not give me the option to remove that server when it cannot connect. Instead it tries to connect forever.

**Comment by rafaelks** [comment]
@callumthomson I’m sorry for this issue, the issue is fixed em 1.0.20. We are releasing to the store today, you should be able to download it in the next 24h or by joining our Beta program in Google Play.
