### ISSUE TITLE
Few issues resurfaces with new update

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#485]
Your Rocket.Chat.Android version: 1.0.20 beta  
Mobile device model and OS version: Samsung S8

Updated to the latest update few hours ago and few of the issues which are/were fixed or suppose to be fixed resurfaces again.
- Keyboard close on single message sent. #417 
- Users list still shows wrong status indicators. (what black status represent bdw?). #439 

**The newly added pinned messages, fav etc(all) crash the app completely.**

Are these known issues so far with this release. I thought this new release suppose to fix all these.

Cleared cache, cleared data and even reinstalled the app.
I can create new issues if needed.

Thanks much.

@rafaelks

**Comment by rafaelks** [comment]
@mmarif4u Thank you for opening this issues! The crash is already resolved here: #484. We'll look into the other ones.

**Comment by luciofm** [comment]
thanks @mmarif4u all fixed now...
