### ISSUE TITLE
New pinned and fav features required RC version

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#495]
Your Rocket.Chat.Android version: 1.0.20 beta
Mobile device model and OS version: Samsung S8
RC Server version : 0.58.3 (snap on Ubuntu)

Thanks for the quick bug fixes over the last few days including new features.
Currently the new features like pinned messages, fav messages and member list showing:
`Cloud not load your request. Make sure your RC server version is up to date`

Is there any requirement for this feature to work beside RC latest version as our RC server is at the latest stable version. OR this feature is still WIP?

**Comment by rafaelks** [comment]
Yes, you need to run RC 0.59+ to have the members/pinned & favorited members list. We'll try to include the required version next release. 👍
