### ISSUE TITLE
[BUG] Pinned messages, favorite messages and member list crash app

### ISSUE THREAD

**Issue by Alhrath** [RocketChat/Rocket.Chat.Android#496]
Your Rocket.Chat.Android version: 1.0.20-DEBUG
Mobile device model and OS version: Galaxy A3 - Android 6.0.1

The new menu with pinned messages, favorite messages and member list does open, but clicking any of them cause a crash of Rocket Chat with a "Rocket.Chat+ stopped working" message.

Here is a [log file](https://github.com/RocketChat/Rocket.Chat.Android/files/1347085/log.txt) when I try to get the member list.

**Comment by rafaelks** [comment]
This crash was fixed already, can you try pulling the changes and try again?

**Comment by Alhrath** [comment]
Done thx, I now have #495 issue, but the server is still in 0.58.2 so probably normal.

I still have to get used to github and Android Studio to become efficient here, it has been a long time I didn't used compiled language :p
