### ISSUE TITLE
[QUESTION] Get roomid after show users for send message

### ISSUE THREAD

**Issue by pishguy** [RocketChat/Rocket.Chat.Android#499]
after search user in `sendDirectMessage` fragment how can i get `roomId` from selected user? that means after select user to send direct message i want to get roomId of this user to show activity for sending message, my problem is getting roomId from this code:

```
  protected final void createRoom() {
    showOrHideWaitingView(true);

    getMethodCallForSubmitAction().continueWith(task -> {
      showOrHideWaitingView(false);
      if (task.isFaulted()) {
        Toast.makeText(getContext(), task.getError().getMessage(), Toast.LENGTH_SHORT).show();
      } else {
        dismiss();
      }
      return null;
    });
  }
```

of this class as `AbstractAddRoomDialogFragment.java`

`task` doesn't have any method to get `roomId`?

i'm trying to open chat window like with channel window to send message and i need to have roomId of user to open that

**Comment by MrSagarShah** [comment]
I think following steps can give you what you want.
	
	1. MethodCallHepler.java
	public Task<Void> createChannel(final String name, final boolean readOnly) {
        return call("createChannel", TIMEOUT_MS, () -> new JSONArray()
        .put(name)
        .put(new JSONArray())
        .put(readOnly))
        .onSuccessTask(task -> Task.forResult(null));
	}
	
	Replace with
	
	public Task<String> createChannel(final String name, final boolean readOnly) {
        return call("createChannel", TIMEOUT_MS, () -> new JSONArray()
        .put(name)
        .put(new JSONArray())
        .put(readOnly))
        .onSuccessTask(task -> Task.forResult(task.getResult()));
	}
	
	public Task<Void> createPrivateGroup(final String name, final boolean readOnly) {
        return call("createPrivateGroup", TIMEOUT_MS, () -> new JSONArray()
        .put(name)
        .put(new JSONArray())
        .put(readOnly))
        .onSuccessTask(task -> Task.forResult(null));
	}
	
	Replace with
	
	public Task<String> createPrivateGroup(final String name, final boolean readOnly) {
        return call("createPrivateGroup", TIMEOUT_MS, () -> new JSONArray()
        .put(name)
        .put(new JSONArray())
        .put(readOnly))
        .onSuccessTask(task -> Task.forResult(task.getResult()));
	}

	2. AbstractAddRoomDialogFragment.java
	protected abstract Task<Void> getMethodCallForSubmitAction(); 
        Replace With
        protected abstract Task<String> getMethodCallForSubmitAction();
	
	In the createRoom method inside else part add the following line.
	Log.e("this", "this is tag"+ task.getResult()); // It will print the roomid 
		
	3. AddChannelDialogFragment.java
	protected Task<Void> getMethodCallForSubmitAction 
        Replace With
        protected Task<String> getMethodCallForSubmitAction
	
	4. AddDirectMessageDialogFragment.java
	protected Task<Void> getMethodCallForSubmitAction() 
        Replaced With
        protected Task<String> getMethodCallForSubmitAction() 
	
	return methodCall.createDirectMessage(username).onSuccess(task -> null);
        Replace With
        return methodCall.createDirectMessage(username);
        
	I hope this answered your question.

**Comment by pishguy** [comment]
@arrowoliver Thank you very much, my problem resolved

**Comment by arrowoliver** [comment]
@MahdiPishguy 
Please let us know if the above comment answered your question so that @rafaelks can close the thread.
If not, Please let add more details to your questions.

**Comment by MrSagarShah** [comment]
@MahdiPishguy  Happy to help..!!
