### ISSUE TITLE
Support handwriting input

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat.Android#5]
On phones and tablets that have this capability.   Can bring new group of mobile users to Rocket.Chat.

**Comment by laggedHero** [comment]
@Sing-Li Keyboards that supports handwriting will provide us with the characters... no need for any special flags (well, at least with the Google one).

Do you know of any special case? Were you thinking of something else?

**Comment by philipbrito** [comment]
Handwriting input is supported (see the image bellow). :white_check_mark:

Feel free to open it again if you are facing any issue with that.

![photo_2017-09-27_13-12-22](https://user-images.githubusercontent.com/11776825/30924572-864e344e-a385-11e7-9f97-9218743ac29a.jpg)
