### ISSUE TITLE
[NEW] Search for member on a room

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#501]
Your Rocket.Chat.Android version: 1.0.20

Since #421 is already implemented from #454 we should have the possibility to search for member on a room. This is particularly useful if we need to know whether or not a user is in a channel.

**Comment by pratickRoy** [comment]
Hi. Can I work on this issue?

**Comment by philipbrito** [comment]
Hi @pratickRoy! Feel free to work on this issue.
How do you plan to work with?

**Comment by pratickRoy** [comment]
@filipedelimabrito I didn't go through the code yet, wanted to understand the issue a bit more. Are we talking about adding search to member list here? or some place else, and is the current search for all members irrespective of rooms?. Any overwiew you can give on this will help a lot. Thanks.

**Comment by philipbrito** [comment]
To search all members on the server we go to the spotlight (on the sidebar, under the current avatar and its username) directly - it is already implemented. On a specific room, tapping on the member list option, we can add a search widget (on the toolbar) to query all member of the specific room (using our REST API).

**Comment by estevanfick** [comment]
I didn't found the api rest for search users on channels api.
I'm linking the source code, because the documentation is outdated.

https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/channels.js

**Comment by leonardoaramaki** [comment]
Already implemented on the new app.
