### ISSUE TITLE
[NEW] Search for file on a room

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#502]
Your Rocket.Chat.Android version: 1.0.20

Since #424 is already implemented from #491 we should have the possibility to search for file on a room (for example, by its name).

**Comment by LulaV14** [comment]
Hi @filipedelimabrito, can I try this one?

**Comment by philipbrito** [comment]
Of course! Feel free to do that @LulaV14! You can try putting a search icon in the toolbar and do the rest :)

**Comment by leonardoaramaki** [comment]
Closing this due to the new app issue https://github.com/RocketChat/Rocket.Chat.Android/issues/1205.
