### ISSUE TITLE
[QUESTION] How can i access to channel into room

### ISSUE THREAD

**Issue by pishguy** [RocketChat/Rocket.Chat.Android#510]
like with `telegram` or `whatsApp` my questions is how can i use `@` before some channels and other member can be access them without search or join that?

when we click on channels link like with `@general` we can show room of that and we can join into that, i just read this issues #274, #233 but they aren't answer of my question

**Comment by rafaelks** [comment]
@MahdiPishguy Today this isn't possible. We'll be implementing this feature in future releases.
