### ISSUE TITLE
[BUG] When app re-connects , scroll position is lost

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.Android#528]
Version: 1.0.2

If you close the app (not kill), re-open, click to re-connect, the scroll position goes back to the bottom. It should stay in the same position after re-connecting.

**Comment by rafaelks** [comment]
@danieljhochman Are you using `1.0.2` or `1.0.22`?

**Comment by danieljhochman** [comment]
I saw this on 1.0.2 I think. Was this fixed?

**Comment by rafaelks** [comment]
@danieljhochman I don't know... `1.0.2` is from ~ 6 months ago.

**Comment by philipbrito** [comment]
Current version (1.0.22) keeps the scroll position when `resuming` the app. The scroll position goes to the bottom when `opening` (after killed) the app.
