### ISSUE TITLE
[BUG] When opening an app from Notification, it does not load new messages

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#529]
@RocketChat/android 

- Your Rocket.Chat.Android app version: 1.0.22 (44)
- Your Rocket.Chat server version: 0.59

# Description

When you tap in a Notification, it opens the app in the correct room, but it doesn't load new messages. Also, when the room is new (you don't have the Room on device yet), the app just opens a blank screen with no title or messages.

**Comment by danieljhochman** [comment]
@rafaelks any ETA on this? This bug is killing us.

**Comment by rafaelks** [comment]
@danieljhochman This feature is work in progress right now, don't want to say exactly ETA because we're doing a refactor in the notification handler code (it was needed), but it's gonna look good after that 👍. Keep watching, as soon as we fix this, we'll send a beta version of the app.

**Comment by danieljhochman** [comment]
Thanks! Do you ever sleep?

**Comment by rafaelks** [comment]
@danieljhochman Yes!!! 😂😂 😂
