### ISSUE TITLE
App wont connect to my Server

### ISSUE THREAD

**Issue by Dirk23** [RocketChat/Rocket.Chat.Android#532]
- Your Rocket.Chat app version: 1.0.22 (44)
- Your Rocket.Chat server version: 0.58.4
- Device (or Simulator) you're running with: PC (Windows 10)/iPhone (iOS11.0.3)/Samsung S8 (Android 7)

I setup a chat Server and installed a Apache Reverse Proxy to terminate SSL there. I try to connect the app to my domain: https://chat.giesemann.gmbh but the app ends in endless spinner and does not connect to the server. I setup the reverse proxy like teh Rocketchat Documents told me to do. I checked my configuration with ssllabs.com and everythings looks fine. I also asked for help in demo.rocket.chat and they guys there told me that it looks like a but in the App.
As next, i used a Letsencrypt certificate, but it is the same error, endless spinner after entering the hostname.
Maybe the TLD (.gmbh) is the problem?

Any help would be appreciated.

Regards

Dirk

**Comment by Dirk23** [comment]
Ok, i did some testing:
i changed certificate to letstencrypt -> Apps dont connect
i changed URL to chat.citrap.de (and used a letsencrypt cert for that domain) -> Apps wont connect

What is wrong here?

**Comment by philipbrito** [comment]
Hello @Dirk23!

`chat.citrap.de` isn't a valid server (I just checked from the web browser and I only get a "Apache2 Ubuntu Default Page"). I'm able to see the login screen on the Rocket.Chat+ when setting the ` https://chat.giesemann.gmbh`. Are you seeing that screen at least?

**Comment by Dirk23** [comment]
I changed back to the Domain i want to use, that’s why chat.citrap.de is not a valid Server anymore. I could See the Login Page on my PC when the vhost was configured to this Domain, yes.

**Comment by rafaelks** [comment]
@Dirk23 Something in your WebSocket configuration is wrong in Apache... can you compare to some others that we have in other issues or in our docs? Look at the requests... (it stays on the last line forever until time out).

```shell
➜  ~  curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: chat.giesemann.gmbh" -H "Origin: chat.giesemann.gmbh" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://chat.giesemann.gmbh/websocket --verbose
*   Trying 94.125.27.100...
* TCP_NODELAY set
* Connected to chat.giesemann.gmbh (94.125.27.100) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.giesemann.gmbh
*  start date: Oct  6 05:22:47 2017 GMT
*  expire date: Oct  7 05:22:47 2018 GMT
*  subjectAltName: host "chat.giesemann.gmbh" matched cert's "*.giesemann.gmbh"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
> GET /websocket HTTP/1.1
> Host: chat.giesemann.gmbh
> User-Agent: curl/7.54.0
> Accept: */*
> Connection: Upgrade
> Upgrade: websocket
> Origin: chat.giesemann.gmbh
> Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==
> Sec-WebSocket-Version: 13
> 
```

**Comment by Dirk23** [comment]
Well, looks pretty the same as here: https://docs.rocket.chat/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-an-apache-ssl-reverse-proxy

My config:
```
<VirtualHost *:443>

ServerAdmin info@giesemann.gmbh
ServerName chat.giesemann.gmbh
ErrorLog /var/log/chat.giesemann.gmbh_error.log
TransferLog /var/log/chat.giesemann.gmbh_access.log
LogLevel info
SSLEngine On
SSLCertificateFile /etc/ssl/private/star.giesemann.gmbh/giesemann.gmbh.crt.pem
SSLCertificateKeyFile /etc/ssl/private/star.giesemann.gmbh/star.giesemann.gmbh.key
SSLCertificateChainFile /etc/ssl/private/star.giesemann.gmbh/Intermediate_CA_Bundle.crt
<Location />
        Order allow,deny
        Allow from all
</Location>
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*) ws://192.168.7.57:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade}           !=websocket [NC]
RewriteRule /(.*) http://192.168.2.57:3000/$1 [P,L]
ProxyPassReverse /           http://192.168.2.57:3000/
</VirtualHost>
```

**Comment by Dirk23** [comment]
Uh, i found a bug. I have a typo in the IP Adress of the RewriteRule! I changed it and now everythings fine. Thanks!

**Comment by rafaelks** [comment]
Excellent. Thank you! :v:
