### ISSUE TITLE
Online Status - Always disconnects after 5 minutes

### ISSUE THREAD

**Issue by skbach** [RocketChat/Rocket.Chat.Android#534]
I'm using the Android app 0.56 on a Galaxy S7.  I have push notifications working, but the app only stays connected for about 5 minutes on the phone.  Website users nearly ALWAYS see "Click here to leave as message" instead of "Chat live" since the Android app never stays connected in the background.

Is there anything I can do to tell Rocket.Chat to stay connected always?  It's virtually unusable as is since I need to constantly access the mobile app (triggerring a "Connecting..." message at the top) which then enables LiveChat on my website for another 5 minutes until the mobile app disconnects.

Thanks.

**Comment by skbach** [comment]
The Android version is 2.5.0.

**Comment by philipbrito** [comment]
What app are you using? The Cordova app or the native app (Rocket.Chat+)?

**Comment by skbach** [comment]
Doh...it's Cordova.  Just installed the Android app suppose I need to reconfigure push notifications now.  Thanks.

**Comment by rafaelks** [comment]
Closing it 👍
