### ISSUE TITLE
 When opening an app from Notification, it does not bring you to specific message

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat.Android#536]
Your Rocket.Chat.Android app version: 1.0.22 (44)

When opening a push notification it should bring you directly to the message. For example, someone did @all in the room which generated a push notification. After that, 30 other messages were written. When tapping on the notification, it should bring me to the @all message and not the bottom of the chat.

**Comment by rafaelks** [comment]
@danieljhochman Thank you, but it duplicates #529 (already being fixed).

**Comment by danieljhochman** [comment]
@rafaelks  - I saw that one, but it said "new messages" - I'm talking about old messages. The message is loaded, but the user does not see it because it's behind history. If it's the same issue- you should clarify in #529

**Comment by rafaelks** [comment]
@danieljhochman Yes, it actually doesn't load any new messages when you tap in the notification.

**Comment by danieljhochman** [comment]
When it's fixed will it scroll up to the specific message or only load the
latest message?

**Comment by rafaelks** [comment]
@danieljhochman Well... @leonardoaramaki may have a better answer, but I believe it should scroll to the position of the message you tapped, unless it's too difficult to do that right now.
