### ISSUE TITLE
Cropped UI pages for Profile and New Channel

### ISSUE THREAD

**Issue by lankygit** [RocketChat/Rocket.Chat.Android#540]
![screenshot_20171023-133845](https://user-images.githubusercontent.com/5887569/31889443-c4698220-b7f7-11e7-8172-c2ca6b650544.jpg)
- Your Rocket.Chat.Android app version: 2.5.0

- Your Rocket.Chat server version: your demo server 

- Device model (or emulator): OnePlus 5 - Android 7.1.1 
also tried on  Umidigi Max - Android 7.0

- Steps to reproduce:
Phone locked or not to portrait, 
access `+` next to channel search - observe that UI is off the screen to the right.

**Comment by leonardoaramaki** [comment]
This issue regards to the Cordova app and not the native Android app. Please reopen this issue on the respective [repository](https://github.com/RocketChat/Rocket.Chat.Cordova) if you feel this issue is still happening to you.
