### ISSUE TITLE
[QUESTION] ordering by roomSidebarList 

### ISSUE THREAD

**Issue by pishguy** [RocketChat/Rocket.Chat.Android#542]
As we know we have some `channels` and `direct messages` on sidebar, I'm trying to know how can i use `order by` when fetch data from database by date to sort them when listed on siderbar?

**Comment by rohitkmr** [comment]
you can sort room list according to your sorting order,just change your logic in method sortRoomList() in class RoomListAdapter .

**Comment by rafaelks** [comment]
This issue is no longer valid for 2.0.0.
