### ISSUE TITLE
[UX/UI] message context menu

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#543]
One have to press and hold the message for message context menu to appear.
Just a suggestion, would be more user friendly if it have some sort of indicator to press and open the menu. Something like this which is implemented in the web ui(0.59.x).
![selection_002](https://user-images.githubusercontent.com/1280585/32048419-083f0840-ba7c-11e7-8f83-8f4aea1a0002.png)

**Comment by leonardoaramaki** [comment]
I particularly dislike the UI like this and how it's presented on the web. Anyway, all the UI/UX is being redesigned for the v2 release of the Android client. 
Thank you for your suggestion! But I'll be closing this issue until we get to our new version redesign available.
