### ISSUE TITLE
[NEW][REWRITE] Authentication screens

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#544]
# Description

 Write the layout for our authentication process.

## Progress

- [x] Connect to the server
- [x] Authentication
  - [x] Auth with username / email
  - [x] Signup with email
  - [x] Login/Signup with social networks
  - [x] 2FA code screen
  - [x] Register username

## Some things to pay attention

- The colors needs to be in a separated file, to be shared all over the app and easy to changed;
- All strings needs to be i18n;

**Comment by philipbrito** [comment]
Closed from #547
