### ISSUE TITLE
[NEW][REWRITE] Chats list

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#545]
# Description

Write the layout of list of chats.

## Progress

- [x] Chats list;
- [x] Sort by latest message;
- [x] Unread state;
- [x] Use date format from device;

## References

- WhatsApp;
- Telegram;

## Questions

- For tablets, can we fix the list on the left and show the messages on the right? That would be amazing I think;

## Date format

- We need to use the date format from device settings (for now, use a Date() object with random date and try to format it correctly);
- If date is from "Today", show the time (e.g 10:21 AM)
- If date is from "Yesterday", show the "Yesterday"
- If date is from last Friday, show the "Friday"
- If date is from more than a week ago, show the date in device date format (e.g 12/25/2017)

## Mock (iOS WIP)

![img_1833](https://user-images.githubusercontent.com/551004/32057130-234f28f4-ba45-11e7-9858-1e8c759c0195.png)

**Comment by pishguy** [comment]
and latest message of post in channels list or direct messages list for example below timestamp, like with telegram to show that

**Comment by pishguy** [comment]
@rafaelks hi, did you change and implemented this or some futures for yourself? i'm trying to show user avatars and date on list, thanks is advance
