### ISSUE TITLE
[QUESTION] Issues with setting up Android Push notification of Rocket.Chat

### ISSUE THREAD

**Issue by tabrez7311** [RocketChat/Rocket.Chat.Android#548]
i'm stuck in a problem which i have described below.i would be very much thankful if you can help me solve it.

I am not able to understand How to setup Rocket.Chat Push Notification for android.

I have already gone through this page:-
https://docs.rocket.chat/administrator-guides/notifications/push-notifications/

And have inserted my server key and project number in rocket chat administration panel
My current Push setting is:-
Enable: True
Debug: True
Enable sdk : false
Production: True
GCM API Key:- the api key obtained from firebase cloud messaging Legacy server key
GCM Project number: The project number which i got after creating project on  https://console.developers.google.com/

But i am not receiving any notification.If you need more details or you have any solution please reply.

Thanks.

**Comment by rafaelks** [comment]
@tabrez7311 What version of the app are you using? Is the server sending the notification message?

**Comment by atc07** [comment]
@rafaelks I am having the same issue. Putting in the same information as @tabrez7311 and not getting any push notifications. The server is setup for push and doing so successfully for the iOS app. We are using the latest version.

**Comment by rafaelks** [comment]
@atc07 Are you using our gateway?

**Comment by atc07** [comment]
@rafaelks yes we are using your gateway.

**Comment by rafaelks** [comment]
@atc07 Is this one still happening for you?

**Comment by atc07** [comment]
@rafaelks yes it was, we had to get a developer to fix the issue. Once we got the push notifications working, we also fixed the push notifications logic. There were use cases where the user was chatting in a room and while the user was receiving the message, the user would also get a push notification. We do not see the need for double notification so included a change where the app would not give notifications for a room if the user was currently chatting in it. We updated for both the Android and iOS apps.

You can see the changes in this pull request: https://github.com/RocketChat/Rocket.Chat/pull/9887

**Comment by rafaelks** [comment]
@atc07 I see! So, can I close the issue for now? Since you already made the PRs and it is working for you... we'll have to wait for this method to get merged in our back-end in order to support it on the mobile apps.

**Comment by atc07** [comment]
@rafaelks yes.  Hopefully this can get merged soon so we can see if it fixes the issue for everyone.
