### ISSUE TITLE
App crash in File List when scrolling for more files

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#574]
- Your Rocket.Chat.Android app version: 1.0.26 (beta)

While in the file list, when scrolling to show more files the app crash.

**Comment by leonardoaramaki** [comment]
@mmarif4u Are you using our open server? If so, which channel(s) you caught this issue?

**Comment by mmarif4u** [comment]
@leonardoaramaki we are using self hosted RC. It does occur on almost every channel with long file list which need scroll, and i assume happens with API call to load the data.

**Comment by rafaelks** [comment]
Closing it since this won't happen in version 2.0.0.
