### ISSUE TITLE
[NEW] Set custom User-Agent

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#578]
Currently user agent shows up as okhttp/3.9.0

Would be better to actually set a user agent.  👍

**Comment by rafaelks** [comment]
@leonardoaramaki Can you confirm what User Agent are we using now? Would also be nice to have other information, such like: `X-App-Version` and `X-Platform`. 🤔

**Comment by rafaelks** [comment]
We defined what's the `User-Agent` to be used:

> RC Mobile; Android (systemVersion); v(appVersion) ((bundleVersion))"
