### ISSUE TITLE
Oath callbacks not being processed

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat.Android#579]
- Your Rocket.Chat.Android app version: 1.0.22
- Your Rocket.Chat server version: demo/open.rocket.chat
- Device model (or emulator) you're running with: Google Pixel 1, Android 8.0.0
- Steps to reproduce: see attached

I can't use the Oauth providers to login. Tried Twitter and Github. My Github requires 2FA so that could be a more complex issue, but Twitter should definitely work. After authorising the app it returns to the callback URL, which is just an endless white screen.

![1 - press twitter](https://user-images.githubusercontent.com/1774379/33047118-3bda73ca-cea8-11e7-83ed-fceb33c78156.png)
![2 - authorise app](https://user-images.githubusercontent.com/1774379/33047119-3c0ca98a-cea8-11e7-80fe-20e4e517e49c.png)
![3 - redirection](https://user-images.githubusercontent.com/1774379/33047120-3c3da436-cea8-11e7-90b9-78956adb2d02.png)
![4 - wsod](https://user-images.githubusercontent.com/1774379/33047121-3c70b84e-cea8-11e7-86e0-02eadd6dacf5.png)

**Comment by rafaelks** [comment]
@timkinnane This is going to be addressed in 2.0.0 OAuth issue, closing it for now.
