### ISSUE TITLE
Dead-end flow if login fails on selected server

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat.Android#580]
It seems the only way to return to the initial server selection screen is to logout of all instances.
Once you've entered a server address, if there's a problem logging in (e.g. you don't have credentials or the server has an error processing them), you're stuck on the login screen forever - or have to re-install the app.

- Your Rocket.Chat.Android app version: 3.2
- Your Rocket.Chat server version: N/A
- Device model (or emulator) you're running with: Google Pixel 1, Android 8.0.0
- Steps to reproduce...

1. Log out of all instances
2. Enter server address
3. Assume you can't login
4. No escape

**Comment by rafaelks** [comment]
@timkinnane Hey! What's the app version you're using? I don't recognize any Android app with 3.2 as version.

**Comment by timkinnane** [comment]
My bad, version **1.0.22** - Don't know where I found the other number.

**Comment by timkinnane** [comment]
It probably is in multiple version though. How do you exit this screen without logging in...

![1 - press twitter](https://user-images.githubusercontent.com/1774379/33047118-3bda73ca-cea8-11e7-83ed-fceb33c78156.png)

**Comment by rafaelks** [comment]
Sounds good! We're working on a new release that is fixing this bugs already. Thank you!

**Comment by timkinnane** [comment]
I'm not sure what about this sounds good? Wouldn't you leave the issue so you can reference it when it's fixed? Or are you saying it's already fixed in development branch?

**Comment by rafaelks** [comment]
Oh, sorry, forgot to mention the PR: #581. This is being fixed already.

**Comment by timkinnane** [comment]
OK thanks, looking forward to it.
