### ISSUE TITLE
[CRASH] Broken App Update 1.0.29 - Instant crash

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.Android#582]
- Your Rocket.Chat.Android app version: 1.0.29
- Your Rocket.Chat server version: 0.59.3
- Device model (or emulator) you're running with: OnePlus 3T with Android 8.0
- Steps to reproduce:
The newest Update is crashing instantly after starting the App.
For a short amout of time you can see "connection error" and then the App crashes.
I reinstalled the App and restarted the phone, but the App crashes no matter what.
There is no difference between WLAN and LTE connection - i cant start the App.
I also send a Feedback-Report after a crash.
The behavior is reproducible on another device - Moto G5 with Android 7.0

**Comment by mmarif4u** [comment]
I can confirm this. it happened on my Samsung S8. I completely removed the app cache, data and then the app itself. Installed again and it worked. But still its a bug.

**Comment by ArchimedesFM** [comment]
I also removed the app cache, the app data and the app itself, but it is still crashing instantly after reinstall.

**Comment by rafaelks** [comment]
@mmarif4u @ArchimedesFM I'm really sorry for that, we got the crash and we're working on the fix. In the meantime, if you can, please leave the "Beta" program and install our stable version. We'll probably release another fix later today and I'll let you guys know.

**Comment by rafaelks** [comment]
@mmarif4u @ArchimedesFM This is happening because you guys had `1.0.27` or `1.0.28` before, then a migration in DB is causing it. If you install the `Stable` and then install the `Beta` now, it'll work just fine.

**Comment by leonardoaramaki** [comment]
@mmarif4u @ArchimedesFM Can you guys install the last production version, that would be 1.0.22 (this might require that you leave the Beta program first) and then enter Beta again and install version 1.0.29 and please report back again here?

**Comment by ArchimedesFM** [comment]
For me this works. After the update from 1.0.22 directly to beta 1.0.29 i can start and use the app.

**Comment by mmarif4u** [comment]
I was on 1.0.27 or 1.0.28 (cant exactly remember), but upgraded today to 1.0.29.
For me after reinstalling again, it worked. But still i guess it is a bug somehow in the migration.

**Comment by rafaelks** [comment]
Yes, the crash happens because the migration was trying to be executed in a database that already had the field.
