### ISSUE TITLE
Create channels from mobile application.

### ISSUE THREAD

**Issue by W0olFy** [RocketChat/Rocket.Chat.Android#587]
Hello!

I could not create channels from the mobile application. It would be great if this feature would be implemented.

**Comment by rafaelks** [comment]
@W0olFy Yes you can, just go to the channels list and you'll see a "+" button, tap on it and you can create channels :-)

**Comment by W0olFy** [comment]
@rafaelks Thanks! Found it. This little "+" button was not obvious for me... Thanks again!

**Comment by rafaelks** [comment]
@W0olFy Yes, I know... we're going to improve the UI soon.
