### ISSUE TITLE
invite to newly created channel

### ISSUE THREAD

**Issue by W0olFy** [RocketChat/Rocket.Chat.Android#589]
Hello!

I was unable to invite people to newly created channel from mobile application (Rocket.Chat+).

However, in other mobile application - Rocket.Chat (without plus sign) i was able to invite, but unable to create channel.

Am i missing something?

**Comment by rafaelks** [comment]
@W0olFy You're right, there's no way to invite people from the `Rocket.Chat+` yet. You'll have to access from browser and type `/invite @username` for now. Sorry about that.

**Comment by W0olFy** [comment]
@rafaelks Thanks for the answer!

Are you planning to add this feature in future releases? Switching between browser and mobile application only for inviting someone is quite painfull...

**Comment by rafaelks** [comment]
Yes, we do plan to add all this features. We're working in a version 2.0.0 that will use our new SDK (also being written in Kotlin) and it'll support all this.
