### ISSUE TITLE
[NEW] Support Push Notification

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#607]

**Comment by HarveyDoom** [comment]
I have set up a server running rocketchat.
I want to white label the ios and android apps, having them connect directly to my rocket chat instance.

Is it possible to set up push notifications using these apps now? Or is this a feature that is not supported yet at all?

**Comment by rafaelks** [comment]
@HarveyDoom Yes, both iOS & Android versions on the store are ready to push notification.

**Comment by HarveyDoom** [comment]
@rafaelks Thanks for the reply, however I am not using the version on the store, I am building my own version replacing logos, connecting directly to my server etc. Is there a guide or an example of anyone who has push notifications working when not using the versions from the store?

**Comment by rafaelks** [comment]
@HarveyDoom Yes, you can find everything in our [docs](https://rocket.chat/docs/administrator-guides/notifications/push-notifications/#push-notifications). Are you using the gateway?

**Comment by philipbrito** [comment]
Closed by #680
