### ISSUE TITLE
[NEW] Support uploading a document

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#612]
It needs to support uploading any kind of document: image, documents, videos, etc.

**Comment by aniketsingh03** [comment]
@rafaelks I would like to work upon this issue, can yo assign it to me??

**Comment by rafaelks** [comment]
@aniketsingh03 This one is actually already in progress for version 2.0.0, sorry about that!

**Comment by aniketsingh03** [comment]
Ok, so the issues with 2.0.0 milestone are already in progress? I should pick up some other or some new issues, right?

**Comment by rafaelks** [comment]
@aniketsingh03 Actually, there are a few issues for 1.1.0 opened yet that we need to address (bugs). 2.0.0 is still WIP and in a definition process right now. It will be open for contributions I would say, in a month.

**Comment by aniketsingh03** [comment]
Is anyone working on this issue @rafaelks @filipedelimabrito ?

**Comment by rafaelks** [comment]
@aniketsingh03 Yes, @filipedelimabrito is working and the PR is opened.

**Comment by philipbrito** [comment]
Closed by #741
