### ISSUE TITLE
[BUG] Error attaching audio record from voice recorder

### ISSUE THREAD

**Issue by Sveer** [RocketChat/Rocket.Chat.Android#630]
Error attaching audio record directly from voice recorder.

Rocket.Chat.Android app version: 1.0.33-DEBUG
- Device model (or emulator) you're running with: Xiaomi Mi6
- Steps to reproduce:
1. Start application
2. Select any channel
3. Click to "clip" icon
4. Select "Audio"
5. Select "Voice Recorder" or "Dictaphone"
6. Record some message and click OK
7. Receive error "[Invalid file name]"

**Comment by rafaelks** [comment]
This issue isn't valid anymore for version 2.0.0.
