### ISSUE TITLE
[BUG] Keyboard still visible after pressing connect button in server url fragment 

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#632]
- My Rocket.Chat.Android app version: 1.0.33-DEBUG
- Device model (or emulator) I'm running with: HTC Desire 628 (physical device)
- Steps to reproduce:
1. Enter server url to connect to.
2. Press the connect button.
3. We see that the keyboard is intact, occupying half of the screen instead of disappearing away.

**Comment by aniketsingh03** [comment]
@rafaelks I am working on this issue.

**Comment by rafaelks** [comment]
@aniketsingh03 Great, thank you! 👍
