### ISSUE TITLE
[IMPROVEMENT] Need of Back button in login fragment

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#633]
- My Rocket.Chat.Android app version:1.0.33-DEBUG
I feel that there is a need of a back button in the login screen (fragment) of the app so that the user may go back to the server url fragment in case he/she wishes to change the chat room.

**Comment by aniketsingh03** [comment]
@rafaelks shall I work on this issue?

**Comment by rafaelks** [comment]
@aniketsingh03 Thanks for opening the issue, this is already in progress by @leonardoaramaki. 👍

**Comment by aniketsingh03** [comment]
Cool

**Comment by rafaelks** [comment]
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).
