### ISSUE TITLE
[BUG] The server url view appears after the loading view even after entering correct url

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#636]
-  Rocket.Chat.Android app version: 1.0.33-DEBUG
- Device model (or emulator) you're running with: HTC Desire 628 (Physical Device)
- Steps to reproduce:
1. Enter the **correct** server url and press connect button.
2. The server url view appears after the loading view even when correct url is entered which is a bug.

The following gif demonstrates this bug:

![login_error](https://user-images.githubusercontent.com/22763626/33948865-089ba5bc-e04e-11e7-9c34-f95c9352b059.gif)

**Comment by aniketsingh03** [comment]
@rafaelks I am working on this issue.

**Comment by rafaelks** [comment]
@aniketsingh03 Excellent! Thank you!

**Comment by leonardoaramaki** [comment]
@aniketsingh03 Just a remark: the default server is already `open.rocket.chat` so you don't have to type it all the time. :)
Another thing is:  if you just type the subdomain ie. `open`, the app automatically adds the `.rocket.chat` suffix :+1:
