### ISSUE TITLE
[QUESTION] Multiple servers not working on lineageos 14.1

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#638]
- Your Rocket.Chat.Android app version: ####

0.31

- Your Rocket.Chat server version: ####

0.59 and 0.60

Hello Devs.

I'm trying to use the multiple server feature but i can't get it woking. I'm connected fine to the first server (0.59) but when i try to add the second i'm able to enter the URL and the credentials to the second server but after that i only see the three black dots moving and the app never recovers from that.  Any idea how to solve this?

thanks and cheers
t.

**Comment by rafaelks** [comment]
@himbeere If you clean install your app and try to connect to this server, does it work fine? Also, why don't you give a try in our latest version: 1.0.33?

**Comment by ghost** [comment]
Yes. Tried 1.0.33 and just 5 minutes ago compiled 1.1.0. Does not work. But the problem seems to be the 0.60.0-rc2 server. Just configured that one first and i got still the same behaviour. App asks for credentials but never recovers from that. The logs of the 0.60.0 server say:

```
Meteor ➔ method UserPresence:away -> userId: Cgp24ud5ioNszeHgR , arguments:  { '0': null }
Meteor ➔ method spotlight -> userId: Cgp24ud5ioNszeHgR , arguments:  { '0': '',
  '1': 
   [ { _id: 'Cgp24ud5ioNszeHgR',
       emails: [Array],
       username: 'user1',
       services: [Object],
       status: 'away',
       active: true,
       name: 'Name',
       roles: [Array],
       statusConnection: 'away',
       utcOffset: 1,
       settings: [Object],
       language: 'af' },
     'user1',
     'user2' ],
  '2': { users: true, rooms: true } }
```

**Comment by ghost** [comment]
This is actually the same as https://github.com/RocketChat/Rocket.Chat.Android/issues/671
