### ISSUE TITLE
[v1.0-beta] Setting Status "invisible" Doesn't Reflect in App

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Android#64]
Your Rocket.Chat.Android version: Build #100 

When you set your status from Online to Invisible, the Android application doesn't update to reflect the change but the browsers show the change.

**Comment by YusukeIwaki** [comment]
Thank you for your bug reporting.

Yes, it is because `invisible` is not notified with `activeUsers` ddp subscription... 😢
Another ddp subscription seems to be required, but I couldn't find it...

**Comment by graywolf336** [comment]
In the websocket connection I see:

```json
{
   "msg": "changed",
   "collection": "users",
   "id": "gHwBwDomPrCoQj7i2",
   "fields": {
      "status": "offline"
   }
}
```

**Comment by YusukeIwaki** [comment]
`activeUsers` subscription notify only statuses except for `offline`

```
Meteor.publish 'activeUsers', ->
	unless this.userId
		return this.ready()

	RocketChat.models.Users.findUsersNotOffline
		fields:
			username: 1
			status: 1
			utcOffset: 1
```

So another subscription seems to be required for observing offline status...

**Comment by YusukeIwaki** [comment]
`userData` subscription does!

```
< {"msg":"changed","collection":"users","id":"wffqrSXNojgMnuz8v","fields":{"statusDefault":"offline"}}
< {"msg":"changed","collection":"users","id":"wffqrSXNojgMnuz8v","fields":{"status":"offline"}}
```
