### ISSUE TITLE
[IMPROVEMENT] No indication of error when sign in button is pressed without entering username in register screen

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#640]
- Rocket.Chat.Android app version: 1.0.33-DEBUG
- Device model (or emulator): HTC Desire 628(Physical device)
- Steps to reproduce:
1. Enter the server url, which opens the register screen.
2. On pressing the "sign in" button without entering the username, there is no indication like an error message below the edit text.

This is a bad UI/UX practice and I feel that the following changes can be made to improve this:
1. Keeping the sign in button disabled until username and password are entered.
2. Another way could be to display an error message at the bottom of the edit texts in case button is pressed when username/password field is empty.

The following gif demonstrates this bug:

![sign_in_error](https://user-images.githubusercontent.com/22763626/34031525-d2685f08-e197-11e7-9353-578f745b48e0.gif)

**Comment by aniketsingh03** [comment]
@rafaelks I am working on this issue.

**Comment by rafaelks** [comment]
Great, thank you!!!

**Comment by leonardoaramaki** [comment]
@rafaelks This issue is indeed very relevant and thank you for working on this one too @aniketsingh03! But I think it's more likely an UI/UX improvement than a bug, what do you think?

**Comment by rafaelks** [comment]
@leonardoaramaki Yeah, sounds good to me! :)
