### ISSUE TITLE
[IMPROVEMENT] Need of password toggle feature in register screen

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#644]
- Rocket.Chat.Android app version: 1.0.33
- Device model (or emulator): HTC Desire 628

There is a need of password toggle feature in register screen. Although this is a very minor improvement, but it needed for good ui/ux.

**Comment by aniketsingh03** [comment]
@rafaelks @leonardoaramaki some other small features like disabling keyboard in register screen and in signup dialog on pressing signin/next buttons respectively, are also there. Shall I work on them while working on this one or shall I make separate issues for them?

**Comment by aniketsingh03** [comment]
@rafaelks @leonardoaramaki  is #645 opened for covering this issue??

**Comment by leonardoaramaki** [comment]
@aniketsingh03 It's better if you create a separate issue for each one. Feature #645 is not related since it's for the 2.0 version of the app.

**Comment by rafaelks** [comment]
@aniketsingh03 I'm not sure what you mean by `Password Toggle`... can you explain a little more?

**Comment by aniketsingh03** [comment]
@rafaelks I meant a button to toggle between visibility and non visibility of password (we usually see this button at the end of password edit texts)

**Comment by rafaelks** [comment]
@aniketsingh03 Got it! Makes sense to me.
