### ISSUE TITLE
[BUG] App crashes when back button is pressed after trying to sign in with any of the available options ie twitter,facebook,etc  

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#648]
- Rocket.Chat.Android app version:1.1.0-DEBUG
- Device model (or emulator): HTC Desire 628
- Steps to reproduce:
1. Connect to the server
2. Try one of the sign in methods by pressing facebook,twitter,google,github placeholders.
3. Press the android back button, and the app crashes.  

The following gif demonstrates the error:

![app_crashed](https://user-images.githubusercontent.com/22763626/34118813-f758f72c-e445-11e7-9551-64acc7781c00.gif)

**Comment by aniketsingh03** [comment]
@rafaelks can you assign this to me?

**Comment by rafaelks** [comment]
@aniketsingh03 Sure thing, thank you!

**Comment by saketkumar** [comment]
@aniketsingh03 Are you still working on this?

**Comment by aniketsingh03** [comment]
Yeah @saketkumar95, I have nearly fixed this, I'll push the code soon!
