### ISSUE TITLE
[BUG] The main activity screen pops up in between add server and login screen

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#649]
- Rocket.Chat.Android app version: 1.1.0-DEBUG
- Device model (or emulator): HTC Desire 628
- Steps to reproduce:
After connecting to the server, before the login screen opens up, there is a flash of the main activity.

The following gif demonstrates this : 

![bug](https://user-images.githubusercontent.com/22763626/34175235-cb02e6d8-e521-11e7-9df8-9e5debd75702.gif)

**Comment by aniketsingh03** [comment]
@leonardoaramaki @rafaelks when a user has already logged in last time he opened the app, then is the app supposed to open the main activity (chat screen) or the login screen again??

**Comment by rafaelks** [comment]
@aniketsingh03 If user is authenticated, the app needs to open the chat screen.

**Comment by aniketsingh03** [comment]
https://github.com/RocketChat/Rocket.Chat.Android/blob/a260363037a1a4193354a53249ecb0f424da9c1d/app/src/main/java/chat/rocket/android/activity/MainPresenter.java#L191-L201
@rafaelks the app opens the chat screen just after the server screen and then is redirected to the login screen due to this part of code in the MainPresenter.java file. Can you once tell me what this part of code   is for?

**Comment by rafaelks** [comment]
@leonardoaramaki ?

**Comment by rafaelks** [comment]
This bug isn't valid anymore for version 2.0.0.
