### ISSUE TITLE
[IMPROVEMENT] Open the chat screen directly when a user has already logged in once.

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#650]
- Rocket.Chat.Android app version: 1.1.0-DEBUG

Presently it seems like the app opens up the 'Enter server url' screen every time the app opens. I feel that it would be a good practice if we open up the chat screen directly if a user has already logged in once. This would prevent much of the effort made by the user to login again and again.

@rafaelks @leonardoaramaki what do you guys think?

**Comment by rafaelks** [comment]
@aniketsingh03 In my use, the app always open the chat screen when user is logged in. I think you're in an edge case. 🤔
