### ISSUE TITLE
[BUG] App freezes after Sign in

### ISSUE THREAD

**Issue by tmarkson** [RocketChat/Rocket.Chat.Android#653]
- Your Rocket.Chat.Android app version: **1.0.33, downloaded today.** 
- Your Rocket.Chat server version: **Connected to https://open.rocket.chat. The version will be whatever version the community team was using on 12/20.**
- Device model (or emulator) you're running with: **Pixel, Android 8.1.0.**
- Steps to reproduce: **Open the app from app list, fill User and Pass, Press Sign in button.** 

![2017-12-20 13 13 16](https://user-images.githubusercontent.com/896199/34222455-9a4b8834-e589-11e7-84a7-8c300d7eb15d.png)

**Comment by tmarkson** [comment]
Also left message in #support at https://open.rocket.chat/channel/support.

**Comment by rafaelks** [comment]
@tmarkson Thank you for opening the issue. What's the server/server version you're connecting to?

**Comment by tmarkson** [comment]
I was connecting to open.rocket.chat, not sure of the server version. I'd guess the latest? @rafaelks

**Comment by rafaelks** [comment]
@tmarkson It's possible that the server was offline at the time... is it still happening to you? We've tons of people using the app in `open.rocket.chat` right now on the Android app. Let me know if it's fixed or still happening for you please.

**Comment by tmarkson** [comment]
I can log in via browser but not mobile on this device. Perhaps it could be my Rocket.chat account? I'll try a password reset or making a new account shortly. @rafaelks

**Comment by tmarkson** [comment]
Good news, see below. It has been 3 days since making the account. I uninstalled the app, reinstalled, tried to sign in, and failed. 

Then I reset my password on open.rocket.chat and attempted signin again, success! Thanks for the time @rafaelks

**Comment by rafaelks** [comment]
@tmarkson Hum... that's weird! Was your account created with email or some OAuth?

**Comment by tmarkson** [comment]
Strange indeed! Just email.
