### ISSUE TITLE
[BUG] The signup screen freezes after pressing the next button.

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#659]
- Rocket.Chat.Android app version: 1.1.0-DEBUG
- Device model (or emulator): HTC Desire 628
- Steps to reproduce:
1. After entering the server url, press the sign up button.
2. After entering details, press the sign up button.
3. The app in the state shown below for a long time, it kind of freezes!

![signup_error](https://user-images.githubusercontent.com/22763626/34325892-5dbb4a14-e8c5-11e7-81e5-c63ef60c1ab8.png)

**Comment by rafaelks** [comment]
@aniketsingh03 But does it create the user? Do you always reproduce this? What's the server version?

**Comment by aniketsingh03** [comment]
I tried this out with an incorrect email address, and it didn't display any error message. It just freezes everytime I try to signup. Well, I'm not using any local server currently, was trying out without it @rafaelks !

**Comment by rafaelks** [comment]
Gotcha! So the issue happens when you've an error?

**Comment by rafaelks** [comment]
Not valid anymore for version 2.0.0.
