### ISSUE TITLE
[IMPROVEMENT] Making the UI of android app same as of the web app

### ISSUE THREAD

**Issue by saketkumar** [RocketChat/Rocket.Chat.Android#661]
- Rocket.Chat.Android app version: 1.1.0-DEBUG
- Device model (or emulator): One Plus 3 - Android 8

 We can make the UI of the Login and Signup screen same as that on the web.

Web Screenshot : 

<img width="1280" alt="screen shot 2017-12-24 at 11 09 46 pm" src="https://user-images.githubusercontent.com/21558765/34328248-8c441a1a-e900-11e7-93fc-dab2c8db906a.png">

Android App screenshot : 

![26036589_1578455768897998_883844619_o](https://user-images.githubusercontent.com/21558765/34328256-bf293c1c-e900-11e7-86c5-59084212d26c.jpg)

We can add the rocket.chat logo and also the  **Terms of Service** and **Privacy Policy** in the app. and changing the background color to match with the web app. 
Same goes for the signup page too.

@leonardoaramaki What do you think? Can I start working on this?

**Comment by rafaelks** [comment]
@saketkumar95 Thank you for your interest in doing this... but we're already working in a new version of the app (2.0) that has a complete new auth flow. If you want to take a look, go to the branch `develop-2.x`. Thanks!

**Comment by rafaelks** [comment]
Issue is not valid anymore for version 2.0.0.
