### ISSUE TITLE
[BUILD ISSUE] Android Studio can't resolve project :core 

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#663]
- Rocket.Chat.Android app version: 2.x

While trying to build the project from the **develop-2.x** branch in android studio, I constantly get the error-
`Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :core.`

Am I doing something wrong/missing something or is this really an issue.

Here is the screenshot for the same
![screenshot from 2017-12-25 02-08-33](https://user-images.githubusercontent.com/22763626/34329123-51572c80-e919-11e7-9ab7-8aee941399cb.png)

**Comment by luciofm** [comment]
Hi @aniketsingh03...

You must checkout the Rocket.Chat.Kotlin.Sdk repo also

You will need a structure like this:
`Parent dir/`
`-----------\Rocket.Chat.Android`
`-----------\Rocket.Chat.Kotlin.SDK`

Make sure to make a `git pull` on the Android repo also, because I've changed the SDK directory.
