### ISSUE TITLE
[IMPROVEMENT] Adding animations in custom tabs

### ISSUE THREAD

**Issue by saketkumar** [RocketChat/Rocket.Chat.Android#664]
- Rocket.Chat.Android app version: 1.1.0-DEBUG
- Device model (or emulator): One Plus 3 - Android 8

I think It would be a better flow by adding slide in and out animations for opening up the chrome custom tabs.

@leonardoaramaki @rafaelks Any suggestions?

**Comment by rafaelks** [comment]
Sounds good to me.

**Comment by saketkumar** [comment]
@rafaelks I have opened up the PR for this. Do review!
