### ISSUE TITLE
android app (10.0.33) not working with server 0.60.0

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#671]
Hello Devs.

Just switched to server 0.60.0. The android app is not working anymore. Can't connect. Neither on my android 7.1 tab nor on my 7.1 phone. Connecting to a 0.59.x server works just fine. 

Is that a known issue?

thanks and cheers

**Comment by rafaelks** [comment]
@himbeere I'm able to connect in my Android phone over here. What issues are you having?

**Comment by ghost** [comment]
I enter the server name followed by username and password and then nothing happens anymore aside from the three dots. I set the server to debug but the log remains empty.

**Comment by ghost** [comment]
Is your demo server running on 0.60.0. Maybe i can try this one too.

I'm on CET here in europe. See you tomorrow.

**Comment by rafaelks** [comment]
@himbeere Yes, you can try: `open.rocket.chat`.

**Comment by reza899** [comment]
this issue is happen for me.
after upgrade to 0.60 can't open rocket on android app. the white page show and not any action.
ps. before upgrading works.

**Comment by ghost** [comment]
Tried open.rocket.chat. Same picture. One little difference. I could not sign-up at first. Then i tried to sign up via Google. That worked actually. Allthough i could not create a room. Is that supposed to work?

Maybe a litte bit more information about my phone. It's lineageos 7.1.2 *without* *any* google stuff installed. Can that be a problem? Do i need some google services with 0.60.0?

Question. Does the app logging locally somewhere? Maybe logs could shed some light on that case.

thanks and cheers
t.

**Comment by anatoly-khomenko** [comment]
![screenshot_20171228-082402](https://user-images.githubusercontent.com/4006428/34413551-321a160c-ebb2-11e7-892d-27175bc23b4c.png)
Here is the message I have seen after tapping back button while on white screen.
I have Samsung Galaxy A5 (2017) with Android 7.0, Rocket Chat application version 2.5.0.
Clearing cache and data and reinstalling the application does not help.

**Comment by Wouter0100** [comment]
Hmm, here it seems to be working correctly after upgrading to 0.60.1.

**Comment by TomaszDom** [comment]
I've made version 1.0.33 work by clearing app data and cache. Can anyone check if it works for them?

**Comment by ghost** [comment]
Updating to 0.60.1 does not solve the problem for me. @TomaszDom how did you clean the app data and cache?

**Comment by Epicanis** [comment]
Getting this here myself. Clearing app data and cache reconnects to the server when I re-enter it and shows it re-downloading the 118 files, then halting on the blankwhite screen again.

This is the rocket.chat app from "Google Play" store, claiming to be version "2.5.0"

**Comment by TomaszDom** [comment]
@Epicanis I meant the "Rocket.Chat+" version 1.0.33.

@himbeere Every phone is different, just find Settings, from there go to Applications, find "Rocket.Chat+" (not Rocket.Chat - that one won't work), look for Storage section and from there Clear data or something similar.

**Comment by ghost** [comment]
Ok. Found it. Cleaning Up App Data and Cache does not solve the problem for me.

**Comment by TomaszDom** [comment]
@himbeere if your server is running behind a reverse proxy, then take a look here https://github.com/RocketChat/Rocket.Chat.Android/issues/375

It may or may not be completely unrelated but it's worth a try.

**Comment by ghost** [comment]
@TomaszDom Does it mean you are able to connect to a 0.60.x server with rocketchat+? can you provide your nginx config?

**Comment by TomaszDom** [comment]
@himbeere Here's my 2-instance setup on Nginx that's provided in Ubuntu 16.04 LTS:
```
# Upstreams
upstream backend {
    server 127.0.0.1:3001;
    server 127.0.0.1:3002;
}

server {
    server_name REDACTED;
    listen 80;
    # return 301 https://$host$request_uri;
    location / {
        return 301 https://$host$request_uri;
    }

    location /api/info {
        proxy_pass http://backend/api/info;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }

    location /websocket {
        proxy_pass http://backend/websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}

# HTTPS
server {
    listen 443 ssl http2 default_server;
    server_name REDACTED;

    error_log /var/log/nginx/rocketchat.access.log;

    ssl on;
    ssl_certificate /etc/ssl/private/REDACTED.pem;
    ssl_certificate_key /etc/ssl/private/REDACTED.key;
    ssl_protocols TLSv1.2;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    resolver REDACTED REDACTED valid=300s;
    resolver_timeout 5s;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    location / {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # proxy_set_header Host $http_host;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}
```

**Comment by ghost** [comment]
Thank you very much. Will try that 2018. :)

**Comment by ghost** [comment]
Nice. Your nginx.conf works. Thanks. I'm not quite sure what the problem is but your config solves it. 

cheers
t.

**Comment by TomaszDom** [comment]
No problem. I think the issue is that Ubuntu 16.04 provides an older Nginx version which doesn't fully support websocket. Obviously I'm not willing to go the PPA route because of security updates, so I'm not entirely sure who else made Rocket.Chat work in an enterprise-type environment with Nginx ;)

Also I've read some comments about self-signed certs being an issue, but I'm using a paid certificate, so that theory goes out the window.

**Comment by ghost** [comment]
I'm not on ubuntu. Also I used apache beforehand.  Well anyways, thanks again.

**Comment by rafaelks** [comment]
Thanks a lot for the support guys! Glad the issue got resolved. Closing this one.

**Comment by smaragd** [comment]
@TomaszDom , you wrote 

> not Rocket.Chat - that one won't work

Does that mean the RocketChat Android app (without the "plus", version 2.5.0) is no longer working with RocketChat 0.60 and above? Ever since updating to 0.60.0, that was broken for my users with the symptoms described above (white screen after downloading the 118 files after entering the server name). The RocketChat+ app seems to work, but does not have the emoji support the users crave. :(

**Comment by rafaelks** [comment]
Guys, we just started releasing our Android App version 1.1.0 to 20% of our users (and our Beta channel). Tomorrow if crashes are OK we'll release to everyone. This version includes many fixes and improvements, including the better support to 0.60. Thank you very much for your all your help.
