### ISSUE TITLE
[QUESTION] How to update the message list screen?

### ISSUE THREAD

**Issue by sachinrkeche** [RocketChat/Rocket.Chat.Android#673]
Hello Developers, 
  I am using this API [https://ctsichat.mvoipctsi.com/api/v1/im.history](url) to get the list of messages of particular user and I am getting the list of messages but, when I am on  the message list screen of particular  user at that time he sends me new message I didn't got that message before going back from message list screen that means the message list screen is not updating when the user send me the message, I have to update it , How can i achieve this feature? please help me out. 
Thanks in Advance.

**Comment by rafaelks** [comment]
@sachinrkeche Thanks for opening the issue. Can you specify a little more of your environment? Are you running our `develop` branch or our `2.0` branch? How are you using this API? Is it from our Kotlin SDK?

**Comment by sachinrkeche** [comment]
Hello, @rafaelks  thanks for your valuable time, I am using rocket chat core SDK using this dependency 

    compile('com.rocketchat.core:rocketchat-core:0.7.1') {
        exclude group: 'org.json', module: 'json'
    }
 I  using Rest API  [from](https://rocket.chat/docs/developer-guides/rest-api/im/)  to get the history against the particular user.

**Comment by rafaelks** [comment]
@sachinrkeche REST API will only return a list of messages. To get updates you'll have to subscribe for updates via WebSocket.

**Comment by sachinrkeche** [comment]
Hello, @rafaelks  I gone through the script [https://github.com/jszaszvari/rocketchat-ddp-listener](url) its working ,  this script is written in Node js , now my question is, How to use this script in the Android project?  alternate How subscribe for updates via WebSocket , How can i play it with  within the Android framework?

**Comment by rafaelks** [comment]
@sachinrkeche Not sure I'm following your questions... where are you trying this? The app already subscribe updates via WebSocket in many different places.

**Comment by sachinrkeche** [comment]
Hello @rafaelks,  I am trying with the [https://ctsichat.mvoipctsi.com/](url), in that we integrate jitsi meet android SDK , and used rocket chat dependencies,

compile('com.rocketchat.core:rocketchat-core:0.7.1') {
    exclude group: 'org.json', module: 'json'
} 

everything i am doing here with our own coding now I'm  facing this issue chat layout is not refreshed automatically, i got this example [ https://github.com/jszaszvari/rocketchat-ddp-listener ](url) its working in our case but this is in node js also i tried  some example on Android DDP for websocket connection but couldn't  able connect with our server. What is wrong going here my approach to use roocket chat or anything else? Thanks advance.
