### ISSUE TITLE
[NEW] Support Google Smart Lock for passwords

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#674]

**Comment by aniketsingh03** [comment]
@filipedelimabrito I would like to work on this one.

**Comment by philipbrito** [comment]
Great! 💯 
Do you need any info about how making this?
Thanks for your interest!

**Comment by aniketsingh03** [comment]
Yeah a little info about the flow would be great. I'll be referring to https://developers.google.com/android/reference/com/google/android/gms/auth/api/credentials/package-summary and https://developers.google.com/identity/smartlock-passwords/android/ btw :smiley:

**Comment by philipbrito** [comment]
Hi @aniketsingh03 How is the progress of this issue? Any news? :)

**Comment by aniketsingh03** [comment]
I am working on this, and will let you know about this soon @filipedelimabrito . Does it sound good?

**Comment by rafaelks** [comment]
@aniketsingh03 Are you still working on this one?

**Comment by aniketsingh03** [comment]
@rafaelks I have added this as one of my tasks for gsoc and will be completing it accordingly, this feature will also be useful for the wear app which I will be working on in the summers.
