### ISSUE TITLE
Google authentication

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat.Android#68]
I see in your planning docs and initial support will include Twitter, github and email. But in the future other services will be considered based in feedback.

I put forward Google auth since every single Android user already has a Google account.

**Comment by YusukeIwaki** [comment]
@mrplow Now you can login with Google Account. Please try it 😆

**Comment by mrplow** [comment]
Thanks @YusukeIwaki !!

I'll try rebuilding next week when I have some free time
