### ISSUE TITLE
[BUG] Same picture is uploaded twice

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Android#683]
- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: 0.60.2
- Device model (or emulator) you're running with: Nexus 5 - Android 7.1.2
- Steps to reproduce:
1. Open the app
2. Switch into a private channel
3. Upload a picture - its uploaded twice (like in the screenshots)

![screenshot_20180106-144321](https://user-images.githubusercontent.com/5877910/34640512-3c01f0ec-f2f4-11e7-9eca-14f309d39352.png)

![screenshot_20180106-144327](https://user-images.githubusercontent.com/5877910/34640519-48e20432-f2f4-11e7-86cb-739ad918add0.png)

![screenshot_20180106-144444](https://user-images.githubusercontent.com/5877910/34640522-51147496-f2f4-11e7-9e1e-b1eb1688d667.png)

(This was just one try to upload)

**Comment by rafaelks** [comment]
@TheReal1604 Thank you!

**Comment by VinArt** [comment]
I don't know if it helps, but when after this happens I delete the _second_ message with the picture, somehow the _first_ gets removed.

**Comment by magnetic5355** [comment]
+1

**Comment by ArchimedesFM** [comment]
any updates on this? :)

**Comment by philipbrito** [comment]
This will be fixed on the v2 app.

**Comment by ArchimedesFM** [comment]
When is it expected?

**Comment by mmarif4u** [comment]
@ArchimedesFM In one of the issues i asked the same question a month or so ago, and @rafaelks replied to be mid Jan 18. But as we can see the current issues attached to 2.0 milestone, i don't think it will be so soon. Unless the plan change and the RC team split the issues to different milestones like 2.1, 2.2 etc.

**Comment by rafaelks** [comment]
@ArchimedesFM @mmarif4u We don't have a fixed release date, but we're expecting to have a version in our Beta channel by the end of this month already. 👍

**Comment by mmarif4u** [comment]
@rafaelks thanks for the heads up. Good luck all with the development.

**Comment by philipbrito** [comment]
From the `v2` (https://github.com/RocketChat/Rocket.Chat.Android/pull/741 and https://github.com/RocketChat/Rocket.Chat.Android/pull/750) this issue isn't happening anymore.
