### ISSUE TITLE
[IMPROVEMENT] User experience - creating a channel - no confirmation message

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Android#684]
- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: 0.60.2
- Device model (or emulator) you're running with: Nexus 5 - Android 7.1.2
- Steps to reproduce:
1. Open the app
2. open the create a new channel ui
3. enter a channel name and set a tick at "private"
4. press the confirm button

-> There is a short loading indicator but nothing happens. (In background the channel is created correct. 👍 )

For a better user experience the menu should closed with a confirmation message that the channel is created correctly.

![screenshot_20180106-144155](https://user-images.githubusercontent.com/5877910/34640570-1b3f5e5c-f2f5-11e7-8978-f693fb91bed2.png)

**Comment by joeljacobdev** [comment]
Can I fix this bug?

**Comment by rafaelks** [comment]
This is not valid in version 2.0.0. anymore.
