### ISSUE TITLE
[QUESTION] Slash commands and bots do not work from app

### ISSUE THREAD

**Issue by magnetic5355** [RocketChat/Rocket.Chat.Android#685]
- Your Rocket.Chat.Android app version: 1.1

- Your Rocket.Chat server version: .60.2
- Device model (or emulator) you're running with: Android 8.1

- Steps to reproduce: use /invite @member or bot help

Text is entered into the chat room without execution of the command.

Commands work in browser.

**Comment by rafaelks** [comment]
@caesarcxiv Unfortunately the commands needs to be handled client-side, and our Android app currently doesn't have the support. We'll have support for this feature in a near future. Thanks for opening the issue.
