### ISSUE TITLE
[QUESTION] Only Last Attachment is displayed

### ISSUE THREAD

**Issue by sscholl** [RocketChat/Rocket.Chat.Android#686]
Hello, im running the latest Version of the server and app. We can not see multiple attachments of one message. Only the last is displayed! Hopefully easy to fix...

Thanks!

Btw: why ist there another Rocket Chat App (reactjs)? This one isnt even finished.

**Comment by rafaelks** [comment]
@sscholl Curious to know how you're sending multiple attachments to the same message. AFAIK the web/apps only support one per message. What are the steps that you're using to send this attachments?

**Comment by sscholl** [comment]
I am sending messages by REST API https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/ and Outgoing Webhook https://rocket.chat/docs/administrator-guides/integrations/. 

Both can produce multiple attachments, but only the **last** is displayed. As you see in the documentation, the attachments fild is an array of multiple elements.

Everything is displayed fine in the Webapp and the old App. Do you need a screenshot?


Thanks for bothering about my problem! ;)

**Comment by sscholl** [comment]
@rafaelks I am sending messages by REST API https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/ and Outgoing Webhook https://rocket.chat/docs/administrator-guides/integrations/.

Both can produce multiple attachments, but only the **last** is displayed. As you see in the documentation, the attachments fild is an array of multiple elements.

Everything is displayed fine in the Webapp and the old App. Do you need a screenshot?

Thanks for bothering about my problem! ;)

**Comment by sscholl** [comment]
As you see, also the implementation supports multiple attachments, but the view seems to be overridden?:

https://github.com/RocketChat/Rocket.Chat.Android/blob/fcc9a2a5ce5508d9d93ee76fbe20a6c6fb4a2454/rocket-chat-android-widgets/src/main/java/chat/rocket/android/widget/message/RocketChatMessageAttachmentsLayout.java#L76-L105
  
This line seems wrong for me AND is would explain, why only the last attachment is showed and not the first:
https://github.com/RocketChat/Rocket.Chat.Android/blob/fcc9a2a5ce5508d9d93ee76fbe20a6c6fb4a2454/rocket-chat-android-widgets/src/main/java/chat/rocket/android/widget/message/RocketChatMessageAttachmentsLayout.java#L92
