### ISSUE TITLE
[NEW] Support OTR

### ISSUE THREAD

**Issue by decus** [RocketChat/Rocket.Chat.Android#691]
- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: 0.60.3
- Device model (or emulator) you're running with: Samsung S8
- Steps to reproduce:

1. On desktop start a direct conversation
2. On desktop enable/start OTR for that conversation
3. On mobile view that conversation. 
3a. There is a place holder (profile image & datetime) for every encrypted message but no text.
3b. There is no notification saying the conversation is OTR (desktop shows a green key icon)
3c. Any messages sent from the mobile app appear to be sent within the app but are not (do not show on desktop)

I think 3c is the most severe - if OTR can't be supported the app should block attempts to send messages

**Comment by rafaelks** [comment]
@decus This is a feature request, thank you.

**Comment by lorek123** [comment]
any updates on this?

**Comment by rafaelks** [comment]
This is not valid anymore because E2E will be implemented instead.
