### ISSUE TITLE
The server is running an out of date version

### ISSUE THREAD

**Issue by bukkits-** [RocketChat/Rocket.Chat.Android#7]
When logging into a fresh install (using the official ansible role) the android app reports that the server is an out of date version. Desktop apps are able to connect, and mobile can still access rocket.chat through the mobile web site. Is this actually due to an out-of-date mobile app?

**Comment by bukkits-** [comment]
Issue resolved. Server address needed to be typed out in a very specific way.

**Comment by neohitokiri** [comment]
Tell me how

**Comment by CharlesOy** [comment]
Same problem here.
