### ISSUE TITLE
Uploading image attachments bricks app

### ISSUE THREAD

**Issue by rustychopsticks** [RocketChat/Rocket.Chat.Android#704]
- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: 0.60.3
- Device model (or emulator) you're running with: Samsung Galaxy S7 Edge (SM-G935F), Android 7.0

- Steps to reproduce:

1. Fresh install app 
2. Open direct message with another user
3. Attempt to attach an image
4. Allow app to access device images/videos permissions

At this point, the app shows the image upload progress bar momentarily, then shows a black notification bar in the top while looping messages "Authenticating..." and "Your connection seems a bit off"  (or similar, I forget the exact wording of that message)
Subsequent messages do not send and instead show a "Not Sycned" error message, and messages cannot be received either.
Other channels do not update (assume this ties in with not being able to receive messages)

Additional settings if relevant:
Auto Load Images: True
Save Mobile Bandwidth: True

**Comment by philipbrito** [comment]
Hi @rustychopsticks 
From the `v2` (https://github.com/RocketChat/Rocket.Chat.Android/pull/741 and https://github.com/RocketChat/Rocket.Chat.Android/pull/750) this issue isn't happening anymore.
