### ISSUE TITLE
Push notification not sending for private message. Works fine for chat rooms.

### ISSUE THREAD

**Issue by ouoertheo** [RocketChat/Rocket.Chat.Android#707]
- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: 0.60.4
- Device model (or emulator) you're running with: LG G4 (H811).  Android 6.0
- Steps to reproduce:
Receive a private message. No push notification.
Push notifications work fine in chat rooms though.

I tried this with the Cordova version too, it has the same issue.

**Comment by ouoertheo** [comment]
I checked the Push notifications section for some more info.
Gateway is: https://gateway.rocket.chat
'Send a test push to my user' fails to push notification to my phone.

When I enable debug for push notifications, I don't see any errors when sending a test push, it just says 'Push: send message "@jamin" via query { userId: 'XPtXEh95gNzvsSxu3' } ' and then 'Push: send to token { gcm: [some key here]}'.
I do have rocket.chat logged in via browser on two other computers.

**Comment by leonardoaramaki** [comment]
You said you have rocket.chat logged in on two other computers.
Are all of them logged with the same user?

**Comment by ouoertheo** [comment]
Yeah, it's the same user on the other computers. Full disclosure - I'm not familiar with what to expect when I have multiple sessions open like this or options available to configure that behavior.

**Comment by leonardoaramaki** [comment]
Can you try logging out from all computers and just leave the Android app logged? 
Your case seems to be that the backend thinks you're always online because you're logged on many computers, hence it doesn't send you a push.

**Comment by ouoertheo** [comment]
I'll do some testing with multiple sessions soon.
Some behavior that I see with a single session on my phone to get a good baseline for what to expect.
* Notifications work when status is yellow or black (away/offline) only. They will not occur when status is green.

Since status seems to determine push notification, I took some notes on status behaviors that I see.
* Bringing the app to the foreground immediately sets status to green (online)
* Pressing back in the app sends app to background, status blinks to yellow for a millisecond, then what seems an arbitrary amount of time under a minute, status goes to yellow. 
* The above behavior is the same for when I shut the phone cover or sleep the phone except shortly after it goes to yellow status, it goes to black status.

I'll keep an eye on the status and how multiple sessions impacts them. 

Is there a way to enable logging of status changes?
Is it possible to have the web client not update status? 

Edit: Looks like push notification debug logging is capturing good info. Could still use status change logs.

**Comment by ouoertheo** [comment]
I'm going to look for a way to log the status changes outside of this ticket. 

My issue description is definitely not accurate, as the behavior I see is due to user presence and not private/public chat channels.

Thanks for your time.
