### ISSUE TITLE
[BUG] New user DM doesn't appear on the list

### ISSUE THREAD

**Issue by mineZcash** [RocketChat/Rocket.Chat.Android#708]
New user Direct Message not found

- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: 0.60.3
- Device model (or emulator) you're running with: LG V20
- Steps to reproduce:

Existing user can login to server as usual, read through channels and DMs fine.

On separate device (PC browser) create _new account_ and login to server.

With New user send Direct Message to Existing user. 

Existing user receives push notification that DM has been received in notification bar.

Existing user clicks notification bar to be taken to DM.

Rocket chat opens to default channel, DM and New user do not appear on the DM list. New user can be seen in default channel, click on New user name returns "User does not exist"

Close Native app, clear Cache and app Data. Re-sign in with Native app and the DM and New user will appear on unread list.

**Comment by rafaelks** [comment]
@mineZcash Is it always reproducible for you? We'll investigate the issue.

**Comment by rafaelks** [comment]
Issue is not valid anymore in version 2.0.0.

**Comment by mineZcash** [comment]
Thanks for closing this issue, I had forgotten about it. 

The problem has been resolved in 2.0.0
