### ISSUE TITLE
[NEW] Show/update user profile

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#710]
Creates a view to show to the user its profile (displaying its email address, real name, username and avatar). Also enables to the user the possibility to update the mentioned fields plus reseting the avatar.

**Comment by SyamSundarKirubakaran** [comment]
@filipedelimabrito I would wish to work on this issue.

**Comment by philipbrito** [comment]
Hi @SyamSundarKirubakaran Currently this issue is almost done. We need only to update/reset the user avatar. Can you work on #752, #753 or #754 ?

**Comment by SyamSundarKirubakaran** [comment]
Ok @filipedelimabrito , I'll look into those.

**Comment by rafaelks** [comment]
This one can be closed already.
