### ISSUE TITLE
[FEATURE] need of typing status.

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#714]
- Rocket.Chat.Android app version:1.1.0 
The app requires a feature of showing the user who is typing a message. It can be integrated into the app by following the end point mentioned in the doc [here](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/notify-room-

@filipedelimabrito @leonardoaramaki , I would like to work on this one, also I wished to integrate this feature into the v2.x if it has become stable enough.

**Comment by philipbrito** [comment]
Duplicated: #116
