### ISSUE TITLE
[DOCS] Improve "How to start" in our README

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#716]
- How to setup the development env;
- How to send PRs ([NEW], [FIX], [IMPROVEMENT]...);
- Community (#androidnativeapp);
- About Rocket.Chat (link to: https://github.com/RocketChat/Rocket.Chat/#about-rocketchat);
- How to report issues;
- How to request beta access;
- Codestyle;
- Features;
- Features (Need help);
- StackOverflow;
- Screenshots;
- How to contribute;
- Donate;

**Comment by leonardoaramaki** [comment]
Who is working on this? No one is assigned.

**Comment by rafaelks** [comment]
@leonardoaramaki At the moment, nobody is doing it.
