### ISSUE TITLE
[NEW] Emoji Keyboard support

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#722]

**Comment by sharmamohit123** [comment]
I want to work on this issue.

**Comment by rafaelks** [comment]
Sounds good @sharmamohit123 👍

**Comment by suyash0103** [comment]
I have made a sample app which includes emojis in keyboard. But I am not understanding the correct file in Rocket Chat app to put this code in. Can I get some help?
