### ISSUE TITLE
Can't login with rocket.chat+ on server 0.61.0

### ISSUE THREAD

**Issue by inksis** [RocketChat/Rocket.Chat.Android#726]
Hello, first of all thanks for all the work done on RC !
But I have some trouble to connect with my (and other) android device.
When I try ton connect my mobile I've got the message `"There's connection error. Please try later"`. I've tried on 0.60.4 server version and the message is the same after updating the server.

- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device model : Samsung Galaxy S8

- Nginx version : 1.10.3 in separate VM
<details><summary>Nginx Config</summary><p>

---
server {
 listen         80;
 server_name    rocket.mycompany.com;
 server_name    chat.mycompany.com;
 server_name    rocketchat.mycompany.com;

  location / {
   return         301 https://rocket.mycompany.com$request_uri;
  }

}

server {
 listen         443 ssl;
 server_name    rocket.mycompany.com;
 server_name    chat.mycompany.com;
 server_name    rocketchat.mycompany.com;

  if ($host != $server_name) {
   rewrite ^ https://$server_name/$1 permanent;
  }
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
  ssl on;
  ssl_session_cache  builtin:1000  shared:SSL:10m;
  ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';

  #Cle personnalise Diffie-Helman
  ssl_ecdh_curve secp384r1;
  ssl_dhparam /etc/nginx/ssl/dhparam.pem;

  ssl_certificate /etc/nginx/ssl/wildcard_mycompany/cert.pem;
  ssl_certificate_key /etc/nginx/ssl/wildcard_mycompany/cert.key;

  #Ticket de session
  ssl_session_timeout 24h;
  ssl_session_tickets on;
  ssl_session_ticket_key /etc/nginx/ssl/ticket.key;

  location / {
   proxy_pass         http://IP:3000;
   proxy_http_version 1.1;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "upgrade";
   proxy_set_header Host $host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forward-Proto http;
   proxy_set_header X-Nginx-Proxy true;
   
   proxy_redirect off;
   access_log /var/log/nginx/rocket-access.log;
   error_log  /var/log/nginx/rocket-error.log;
 }
}

---

</p></details>

<br>
I have no log on RC or on my Nginx and iPhone can connect without troubles.

Any ideas ? 

**EDIT : I forgot to precise that i use SAML connection**

**EDIT 2 :**
- Huawei Mate 7 with Android 6 : _can connect but without SAML part, only basic ldap_
- Sony Xperia Z2 with Android 6 : _same as Huawei_
- Samsung Galaxy A5 with Android 7 : _same as Samsung Galaxy S8_
- OnePlus 5 Android 8 : _i can saw the form ldap but message "LDAP Authentification succeded, but there's already an existing user with provided username [user.name] in..._

The issue seems to be related to the android version ?

**Comment by inksis** [comment]
I've try with lighter nginx config and the issue seems to be caused by the parameter of the Diffie-Hellman Key exchange :
old param :
`ssl_ecdh_curve secp384r1;`
new param :
`ssl_ecdh_curve prime256v1;`
<br>
I can now connect with my Samsung S8 but always with the LDAP form and not my SAML idp

**Comment by rafaelks** [comment]
@inksis SAML is not supported in our Android version yet.

**Comment by rafaelks** [comment]
This issue is not valid anymore for version 2.0.0.
