### ISSUE TITLE
can i know what type and connection use for the database

### ISSUE THREAD

**Issue by anonymous1445** [RocketChat/Rocket.Chat.Android#728]
Before writing an issue, please make sure you're talking about the native application and not the Cordova one. If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat.Android app version: ####

- Your Rocket.Chat server version: ####
- Device model (or emulator) you're running with: ####

- Steps to reproduce:

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by philipbrito** [comment]
Could you elaborate your question? Also, next time make sure to **fill the issue template**.
