### ISSUE TITLE
[BUG] The action bar is not persistent

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#730]
- Rocket.Chat.Android app version: **Milestone** v2.0.0
The action bar should be persistent.
The screenshot below shows the error correctly.

![screenshot_2018-02-02-19-52-16](https://user-images.githubusercontent.com/22763626/35738885-1354af14-0856-11e8-9323-5ae089dddd74.png)

**Comment by aniketsingh03** [comment]
This issue is fixed in #725

**Comment by philipbrito** [comment]
As said before, closed by #725
