### ISSUE TITLE
[INVESTIGATE] Can't login with rocket.chat+ on server 0.61.0 

### ISSUE THREAD

**Issue by abifrance** [RocketChat/Rocket.Chat.Android#735]
Hello,

I have updated my server to 0.61.0 but i can't login to my server with android device

- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: ####
- Device model (or emulator) you're running with: Xiaomi Redmi 4A

- Steps to reproduce:
i have installed the android app but i can't login to my server (v0.61.0), i receive response message : invalid server version.
I can login to my server with Web navigator

Best Regard

**Comment by rafaelks** [comment]
@abifrance Were you able to login in our Android app before updating the server?

**Comment by abifrance** [comment]
I was not abling to connect with the old version (i don't remember the version), I have not updated it for 1 year.
I tested with another phone : Samsung Galaxy S2 Android 7 > Same problem : invalid server version

Can the problem come from the Nginx configuration?

Best Regard

**Comment by rafaelks** [comment]
@abifrance Yes, that's possible. What's your server URL?

**Comment by abifrance** [comment]
https://exchange.groupe-abi-france.com/

Best Regard

**Comment by rafaelks** [comment]
@abifrance Looks like your version of Nginx is not supported to use WebSockets... can you tell me what version are you using?

**Comment by abifrance** [comment]
I use this version

nginx version: nginx/1.10.3 (Ubuntu)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads

Best Regard

**Comment by rafaelks** [comment]
@abifrance When I try to simulate the upgrade (from HTTP to WebSocket) request:

```shell
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: exchange.groupe-abi-france.com" -H "Origin: exchange.groupe-abi-france.com" -H "Sec-WebSocket-Key: fVXESE8fjBMx8HheW0YlZQ==" -H "Sec-WebSocket-Version: 13" https://exchange.groupe-abi-france.com/websocket
HTTP/2 400 
server: nginx
date: Tue, 20 Feb 2018 13:44:00 GMT

Not a valid websocket request
```

@geekgonecrazy Do you have any idea what could be on their end?

**Comment by geekgonecrazy** [comment]
I'd have to see the config file.  Please feel free to shoot me a message on our community server: `aaron.ogle`. Make sure to link to this issue for context ;)

**Comment by rafaelks** [comment]
Issue is not valid anymore in version 2.0.0.
