### ISSUE TITLE
[QUESTION] Can you send us crash reports of our rocket.chat project in which we have used your fabric api key?

### ISSUE THREAD

**Issue by ArtiMane** [RocketChat/Rocket.Chat.Android#739]
Before writing an issue, please make sure you're talking about the native application and not the Cordova one. If you are looking to open an issue to the Cordova application, go to this URL: https://github.com/RocketChat/Rocket.Chat.Cordova.

- Your Rocket.Chat.Android app version: ####

- Your Rocket.Chat server version: ####
- Device model (or emulator) you're running with: ####

- Steps to reproduce:

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by rafaelks** [comment]
You have to update your key here:

https://github.com/RocketChat/Rocket.Chat.Android/blob/cc23374c2106d55180e422b177a823116560dbb5/app/src/main/AndroidManifest.xml#L113-L115
