### ISSUE TITLE
[NEW] Draw feature 

### ISSUE THREAD

**Issue by Rish02Sharma** [RocketChat/Rocket.Chat.Android#740]
@filipedelimabrito @rafaelks @leonardoaramaki @saketkumar95 @rodrigok 

This issue is from the GSoC ideas page of this year. I will be working on this issue from now only.

Some research work which I did for this : 

I will be using this [library](https://github.com/ArthurHub/Android-Image-Cropper) for editing the image. 
This library include Zoom, Rotation, Multi-Source, Shape, Limits, Style Async, Sampling, Matrix of the image.
For marking tools : There is an inbuilt libraries for Graphics like 

1. android.graphics.Bitmap;
2. android.graphics.Canvas;
3. android.graphics.Color;
4. android.graphics.Point;
5. android.graphics.drawable.Drawable;
6. android.graphics.drawable.GradientDrawable;

which can used for drawing anything on the image. 

Apart from this , I have the idea to edit the image after it was sent. 
Also adding some filters in the image using this [library](https://github.com/Zomato/AndroidPhotoFilters) 

For any improvement, Suggestions are welcome. :)

**Comment by philipbrito** [comment]
Thanks for your interest! It was a good start point. I'd like to only recommend your searching others libraries to make a comparison between them (maybe is there a better library? With better performance and memory usage? - only good questions that help us decide for the better).

Thank you @Rish02Sharma !

**Comment by Rish02Sharma** [comment]
@filipedelimabrito yeah sure! I will look into it. 👍

**Comment by anandwana001** [comment]
@Rish02Sharma How much you have done? I am looking forward to the same contribution.

**Comment by agampreetsingh** [comment]
@filipedelimabrito @rafaelks @leonardoaramaki @saketkumar95 @rodrigok @Sing-Li 

Hi, I am interested to work on this issue as well. I have already started practicing my hands on Rocket,Chat.Android.

I have researched about tools to achieve the required results as mentioned in the description and found the standard Google API and [library](https://google-developer-training.gitbooks.io/android-developer-advanced-course-practicals/content/unit-5-advanced-graphics-and-views/lesson-11-canvas/11-1c-p-apply-clipping-to-a-canvas/11-1c-p-apply-clipping-to-a-canvas.html) the best. 
I'll be using the [Canvas Class](https://google-developer-training.gitbooks.io/android-developer-advanced-course-concepts/unit-5-advanced-graphics-and-views/lesson-11-canvas/11-1-c-the-canvas-class/11-1-c-the-canvas-class.html) for the same. I also have gone through the Google Advance Developer training [kit](https://google-developer-training.gitbooks.io/android-developer-advanced-course-practicals/content/unit-5-advanced-graphics-and-views/lesson-11-canvas/11-1b-p-draw-on-a-canvas/11-1b-p-draw-on-a-canvas.html)  and have hands on experience with it.

As of now I am thinking of adding the required functionality of drawing as an activity passed by an intent.
Is it required to add a functionality that allows the same with an overlay or something like that?

Please share your valuable suggestions.

**Comment by philipbrito** [comment]
The feature is already present on the current app version.
Thank you guys.
