### ISSUE TITLE
[BUG] Can't connect to Server if URL contains custom Port

### ISSUE THREAD

**Issue by j0hannesr0th** [RocketChat/Rocket.Chat.Android#742]
Hello,
it's not possible to connect with the Rocket.Chat+ app to an Rocket.Chat server behind nginx which listens on custom port.

- Your Rocket.Chat.Android app version: 1.1.0
- Your Rocket.Chat server version: latest from snap
- Device model (or emulator) you're running with: Honor 9 - Android 7.0
- Steps to reproduce:
Try to run rocket chat behind nginx SSL Proxy which listens on Port 33333. The Webinterface works fine at https://rocketchat.mydomain.tld:33333 - This app just gives and alert saying "Invalid server version".

**Comment by rafaelks** [comment]
Thank you! Is this fixed for v2 already @luciofm?

**Comment by rafaelks** [comment]
Issue is not valid anymore in version 2.0.0.
