### ISSUE TITLE
embedded tabbed browsing

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#743]
I posted this idea here https://github.com/RocketChat/Rocket.Chat/issues/9668 but maybe its better to post it in this repo since it is a client-side feature?

Thanks for consideration,

Peter

**Comment by bizzbyster** [comment]
Also I am happy to work on this one and/or potentially sponsor it. At this point I'm really interested in hearing what the development community thinks of the idea.

**Comment by bizzbyster** [comment]
I've posted a bounty on this issue: https://www.bountysource.com/issues/54866558-embedded-tabbed-browsing. Let me know if there are any questions.

**Comment by rafaelks** [comment]
Closing this one, since referenced issue was also closed.
