### ISSUE TITLE
Improvement: Check if Server URLs are valid on login

### ISSUE THREAD

**Issue by derjohn** [RocketChat/Rocket.Chat.Android#744]
If you enter (by accident) a blank in the server URL like "https://foo.bar. com" it will drop a DNS error.

It would be more customer friendly, to check if the url is a valid RFC URL.

Just a #wish .

**Comment by philipbrito** [comment]
Yes! On the version 2 we are checking if the server [URL is valid](https://github.com/RocketChat/Rocket.Chat.Android/blob/7455ab37c5900c5c702c0fd37d67fc31afc3d831/app/src/main/java/chat/rocket/android/helper/UrlHelper.kt#L51).

Thanks for opening this issue.
