### ISSUE TITLE
[INVESTIGATE] Rocket.Chat+ invalid server version for SSL

### ISSUE THREAD

**Issue by pfunk1978** [RocketChat/Rocket.Chat.Android#745]
Rocket.Chat+: 1.1.0
Rock.Chat Server: 0.60.4
Nexus X
### Issue
I've setup Apache in reverse SSL Proxy mode listening on 8443 w/ self signed certs. I've installed the CA, and Auth Provider certs on the phone. Phone shows that the certs are trusted.

### Setup
The Business end of my Apache Config:
```
SSLEngine On
SSLCertificateFile /etc/ssl/certs/custom.provider.cert.pem
SSLCertificateKeyFile /etc/ssl/private/custom.provider.key.pem
SSLCertificateChainFile /etc/ssl/certs/custom.root.cert.pem

<Location />
        Order allow,deny
        Allow from all
</Location>

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://localhost:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
```
* Apache `ServerName` and the `CN` of custom.provider.cert.pem are the same string

### Reproduction
Attempt to connect RocketChat+ to `https://my_server:8443`.
### Epected Results
Connection to Server
### Actual Rresults
Keep getting `Invalid server version`
### Other Notes
* I can connect with original Rocket.Chat mobile and the Rocket.Chat React Native Android apps.
* Server is still available in the clear at :3000. Rocket.Chat+ can connect there.

**Comment by rafaelks** [comment]
@pfunk1978 Can you provide us your server URL?

**Comment by pfunk1978** [comment]
@rafaelks Unfortunately, I can not provide that as it's an internal only. Also I should say that the reason I'm using 8443 instead of 443 is because we have another service using that port, and changing it would wreck a lot of things. 

However, after hours I did switch our RC instance to 443 as a test and Rocket.Chat+ gave me a `connection error`. 

I'm now wondering if my certificates are correctly loaded on Android. I created and email them to myself as two PEM encoded files and they wouldn't initially load. There were some hoops I had to go through to load them. I'm now wondering if I need to use either a single PEM tree stack or a DER encoded PKC7 tree, because maybe Android isn't linking those certs correctly?

**Comment by pfunk1978** [comment]
OK,
So I've done a lot of things to change the situation.
* I setup 10.0.5.199 as an eth0 alias and set Apache to use that address as a virtual host w/ port 443
* I also remade my certs and reimported my CA into Android.

Here's where things get weird.
* I imported the CA into firefox and every thing seems great.
* Chrome on the other hand gives me a ERR_CERT_COMMON_NAME_INVALID. With the explanation of:
```
This server could not prove that it is 10.0.5.199; its security certificate is from 10.0.5.199. This may be caused by a misconfiguration or an attacker intercepting your connection.
```

So I'm also assuming that Android is throwing the same error, because I keep getting `There's a connection error. Please try later` error from the app.

I've been reading that Chrome now uses the alt DNS name instead of the CN to validate certificates. However, my CN is `Rocket.Chat Server` and my alt DNS name is `10.0.5.199` I don't understand why I'm getting that error. Any thoughts?

**Comment by pfunk1978** [comment]
Turns out that for chrome, if the SAN DNS is an IP then SAN IP must also be included. So now I have certs set up and working properly in FireFox, Chrome and Chrome on Android. Still getting connection errors with the Android app. @rafaelks What gives?

**Comment by pfunk1978** [comment]
I did a packet trace from my phone, here is what I got:
```
GET /api/info HTTP/1.1
Host: 10.0.5.199
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.9.0

HTTP/1.1 302 Found
Date: Fri, 16 Feb 2018 19:13:15 GMT
Server: Apache/2.4.7 (Ubuntu)
Location: https://10.0.5.199/api/info
Content-Length: 286
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://10.0.5.199/api/info">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at 10.0.5.199 Port 80</address>
</body></html>
```
And Apache error logs
```
[Fri Feb 16 15:14:01.049475 2018] [ssl:info] [pid 20816] [client 10.0.7.14:41366] AH01964: Connection to child 5 established (server 10.0.5.199:443)
[Fri Feb 16 15:14:01.084240 2018] [ssl:info] [pid 20816] [client 10.0.7.14:41366] AH02008: SSL library error 1 in handshake (server 10.0.5.199:443)
[Fri Feb 16 15:14:01.084289 2018] [ssl:info] [pid 20816] SSL Library Error: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown (SSL alert number 46)
[Fri Feb 16 15:14:01.084302 2018] [ssl:info] [pid 20816] [client 10.0.7.14:41366] AH01998: Connection closed to child 5 with abortive shutdown (server 10.0.5.199:443)
```

It looks like Rocket.Chat+ isn't using certs from the Android User Certificate Store

**Comment by rafaelks** [comment]
Looks like your HTTPS is redirecting to HTTP (port 80)?

**Comment by pfunk1978** [comment]
Based on this?
> `<address>Apache/2.4.7 (Ubuntu) Server at 10.0.5.199 Port 80</address>`

That's a response from rocketchat server. I'm not sure why it's sending that.

What I am curious about is the SSL 46 alert from Apache. 46 means that the client could not validate the server certificate and closed the connection. Could this be relevant? https://blog.jeroenhd.nl/article/android-7-nougat-and-certificate-authorities

**Comment by robertwessen** [comment]
#793 Error 46 is the error addressed in this issue and PR, these are likely duplicate issues.

**Comment by pfunk1978** [comment]
@rafaelks I'm closing this issue as what I think i'm seeing is actually #793

**Comment by asadmukhtar28** [comment]
After adding my host and SSL certificate IOS app is working fine but Android App signin, signup not working?
