### ISSUE TITLE
[NEW] Ability to override language in the client

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#747]
Currently the Rocket.chat+ client does not allow users to change to a different language than the one set by the administrator. This feature would add support for this configuration option.

**Comment by philipbrito** [comment]
Note: Language is set by the one that is used in the user device (defaults to English). We'll add an option to the user be able to change the app language instead of changing the device language to do so.

**Comment by GOVINDDIXIT** [comment]
@filipedelimabrito  can I work on this issue?

**Comment by bizzbyster** [comment]
@filipedelimabrito @rafaelks Has this been designed yet? @Shailesh351 is wondering how we'll be able to get the override language setting? Where will that be located in the code?

**Comment by rafaelks** [comment]
@bizzbyster There's a PR opened for that: https://github.com/RocketChat/Rocket.Chat.Android/pull/1918

**Comment by tpjods** [comment]
I am also eager to have this feature added.  Has work begun or can I assist?

**Comment by GOVINDDIXIT** [comment]
@tpjods The PR #1918 is finalized and very close to get merged. Only It need is to get reviewed and approved.

**Comment by tpjods** [comment]
> 
> 
> @tpjods The PR #1918 is finalized and very close to get merged. Only It need is to get reviewed and approved.

Sorry. I noticed right after I commented. Great work. Thank you
