### ISSUE TITLE
[NEW] Tutorial Screen for users logging in the app for the first time

### ISSUE THREAD

**Issue by Rish02Sharma** [RocketChat/Rocket.Chat.Android#748]
We can highlight some features for users on the first start of app. Which will contain guideline for how to use the app and get started with some instructions for the new users.
@filipedelimabrito Can I work on this?

**Comment by saketkumar** [comment]
That's great feature @Rish02Sharma 
@filipedelimabrito What do you think about this?

**Comment by philipbrito** [comment]
When comparing with Slash and Telegram it is a good improvement (these apps add an on-boarding screen). But we need to ensure what we should put on that screens, the number of on-boarding screen, etc.

**Comment by philipbrito** [comment]
@rafaelks What do you think?

**Comment by Rish02Sharma** [comment]
@filipedelimabrito We can add like from where and how we can create private rooms or streams, How to search any user for DM and many more which we can add.

**Comment by philipbrito** [comment]
@Rish02Sharma This is a great idea, but I think that this improvement suits better for the [v2](https://github.com/RocketChat/Rocket.Chat.Android/tree/develop-2.x) and from that we don't have that features implemented (yet).

Btw, you can take a look to see the `v2` features (and the next to be developed) [here](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).

**Comment by SyamSundarKirubakaran** [comment]
@Rish02Sharma @filipedelimabrito Can I work on this issue..

**Comment by SyamSundarKirubakaran** [comment]
Is there any specifics that you would wish to have on the Tutorial Splash screen in addition to the tutorials for basic functionalities.. @Rish02Sharma @filipedelimabrito @saketkumar95

**Comment by aniketsingh03** [comment]
@filipedelimabrito @rafaelks @Rish02Sharma don't you think that the `v2` of the app needs to be more stable and needs more features before implementing this feature?

**Comment by philipbrito** [comment]
@aniketsingh03 Yes, `v2` lacks some features, but there are things already on it, that (at this time) worths to mention, like: sending any file type and updating the user profile (which isn't in previous versions).

**Comment by aniketsingh03** [comment]
Yeah, that's great @filipedelimabrito . Can this feature be implemented right away or do we need to wait for some time until someone starts working on this?

**Comment by Rish02Sharma** [comment]
@filipedelimabrito Yeah for now , These should be implemented. After when other features are implemented for tutorial , I will add those too. 
So Can I start working on this?

**Comment by philipbrito** [comment]
Great @Rish02Sharma !
Yes, you can start working on it :)
Thank you! 😄

**Comment by SyamSundarKirubakaran** [comment]
@Rish02Sharma Are you working on this?

**Comment by rafaelks** [comment]
This ones duplicates #1053
