### ISSUE TITLE
[IMPROVEMENT] Size of the elements, spacing & colors

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#751]
- [x] Reduce size of the font of the chats screen to something very similar to Telegram;
- [x] Reduce size of the font of the messages screen to something very similar to Telegram; Make the same font size as the text box;
- [x] Change color of mentions on reply/quote banner to something a blue lighter. Right now is almost impossible to read it;
- [x] Use different font style for read/unread channels on the chats list; Here you can use bold in the name of the channel when there's any unread message and change the date label color to the same blue we have in the "unread bubble" and if the chat has no unread messages you simply use semi-bold font and the same color you're using today for date on the date label;
- [x] Change animation to open/close an activity to something faster (see how Telegram is doing);
- [x] Support dragging from left to right to close messages activity;

**Comment by Rish02Sharma** [comment]
@rafaelks @filipedelimabrito Can I work on this?

**Comment by rafaelks** [comment]
@Rish02Sharma @filipedelimabrito Is already on it. But feel free to work in other-related improvements!
