### ISSUE TITLE
[NEW] Update user avatar

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#752]
From the profile view, allow to the user change its avatar picture. The idea is simple: have a action to open the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html) (only - obvious - for images) and call the [client.setAvatar(file: File, mimeType: String)](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt#L93)

Tip: see the existing upload file feature.

**Comment by Rish02Sharma** [comment]
@filipedelimabrito Should I try this?

**Comment by aniketsingh03** [comment]
@filipedelimabrito ,I'll work on this one.

**Comment by philipbrito** [comment]
Nice @aniketsingh03! It is your issue :)

**Comment by aniketsingh03** [comment]
@filipedelimabrito , is it convenient to add image cropping feature as well? I'll be using [this](https://github.com/ArthurHub/Android-Image-Cropper) library for the same.

**Comment by saketkumar** [comment]
> is it convenient to add image cropping feature as well?

@aniketsingh03 You mean cropping the avatar before uploading it? 

Also Can you search for some other library with better performance and memory usage?

**Comment by Rish02Sharma** [comment]
@aniketsingh03 You can use this library instead : https://github.com/avito-tech/krop

**Comment by philipbrito** [comment]
@aniketsingh03 That's a great idea, but you can solve this issue without it and we can create another issue with that image cropping feature - for the avatar (in that way, you can also work in this issue or leave it for someone else). 

Thanks @saketkumar95 for remembering about always searching for a better performance and memory usage library - it is important to have an awesome Rocket.Chat Android app client. :)

@aniketsingh03 What do you think? Could someone here work on image cropping feature?

**Comment by aniketsingh03** [comment]
Yeah, that's absolutely fine @filipedelimabrito . I'll try to implement this one without the cropping feature. An issue regarding the cropping feature can be opened separately :smiley:

**Comment by philipbrito** [comment]
Thank you @aniketsingh03 !!! 
Just created that issue: https://github.com/RocketChat/Rocket.Chat.Android/issues/756

**Comment by aniketsingh03** [comment]
@filipedelimabrito shall I add a choice to choose image from camera or from internal storage?

**Comment by philipbrito** [comment]
It'll be great if the user have the possibility to get the picture from the gallery or instantly from the camera :)

**Comment by Rish02Sharma** [comment]
@aniketsingh03 Just to let you know, Try focusing more on the corner cases like how the app will respond when the image uploads fails or network fails while uploading the image. Also a progress bar to show the uploading details to the user.

**Comment by aniketsingh03** [comment]
@filipedelimabrito I am getting the following exception while trying to set user avatar-
`HTTP FAILED: java.io.IOException:NO_ERROR`. Is it because the form value requires an `@` before the file name or is there any other reason.
