### ISSUE TITLE
[NEW] Reset user avatar

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#753]
From the profile view, allow to the user reset its avatar. The idea is simple: have a action to reset the avatar calling the [client.resetAvatar(userId: String)](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt#L72).

**Comment by Rish02Sharma** [comment]
@filipedelimabrito Should I try this?

**Comment by philipbrito** [comment]
Hi @Rish02Sharma :)
Sure! You can try this issue! 
It is your issue! :)

**Comment by rishabhkalra96** [comment]
I would like to claim this issue.

**Comment by saketkumar95** [comment]
Hi @rishabhkalra96 I'm already working on this issue. :)

**Comment by aniketsingh03** [comment]
@Rish02Sharma are you still working on this one?
