### ISSUE TITLE
[NEW] Update user avatar via URL

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#754]
From the profile view, allow to the user update its avatar via URL. The idea is simple: have a action to update the avatar and an input to the user insert that URL, after all call the [client.setAvatar(avatarUrl: String)](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt#L117).

**Comment by philipbrito** [comment]
@SyamSundarKirubakaran Could you try this issue?

**Comment by singhsegv** [comment]
@filipedelimabrito Can i work on this issue ?

**Comment by SyamSundarKirubakaran** [comment]
@filipedelimabrito Yes, I'll take this up..
