### ISSUE TITLE
[NEW] Update user password

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#755]
From the setting menu (yeah, we need to add this to our navigation drawer), allow to the user update its password through [client.updateProfile(...)](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt#L47).

Tip: see the `updateProfile()` in action [here](https://github.com/RocketChat/Rocket.Chat.Android/blob/befa16fcbb18a5c862222ff0303c2ea2f6cc7f62/app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt#L52).

**Comment by samrmur** [comment]
@filipedelimabrito I would like to work on this issue. In terms of requirements, what would you like to see? 
1. Should the user have to enter their password twice to avoid screw ups?
2. Should the user have to confirm their identity before changing their password?
3. Should the user be able to "change" their password to the password that their account is currently protected by?

**Comment by rafaelks** [comment]
@samrmur @filipedelimabrito I would say:

1. Yes, let's ask twice for now;
2. No, if user has access to the device, I don't think we need to require another verification;
3. Yes; Let's leave this kind of validation to the API;

**Comment by SyamSundarKirubakaran** [comment]
@filipedelimabrito @rafaelks I would wish to take this issue up.. BTW, is there any constraints that the password should meet (e.g., atleast one numeric character, atleast one capital letter or something like that..)

**Comment by rafaelks** [comment]
@samrmur Are you going to work on this issue?

**Comment by samrmur** [comment]
@rafaelks Yes, I am currently working on this issue.

**Comment by rafaelks** [comment]
@samrmur Sounds good, thanks!
