### ISSUE TITLE
[NEW] Image cropping

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#756]
Let the user crop its avatar image when choosing to update it.
~~Blocked by: https://github.com/RocketChat/Rocket.Chat.Android/issues/752~~

**Comment by joeljacobdev** [comment]
Can I start working on this issue after #752 is solved?

**Comment by shubhamprasad0** [comment]
@filipedelimabrito Can I work on this issue?

**Comment by Aashishgtbit** [comment]
@filipedelimabrito  Can I work on this issue ?

**Comment by philipbrito** [comment]
You can start working on this issue after #752 is solved @pcforgeek 
Thank you!

@tonystark11 @Aashishgtbit Could you guys try to solve other issues from the [current milestone](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6)?
Thank you.

**Comment by joeljacobdev** [comment]
Sure, I will start working after the blocking issue is closed.
