### ISSUE TITLE
Unable to connect to server using Android 4.2

### ISSUE THREAD

**Issue by syntrydy** [RocketChat/Rocket.Chat.Android#758]
Your Rocket.Chat.Android version: 1.1.0

We have Rocket Chat setup with our external OAuth provider. Login against the external provider is working fine on other Android version but not working on Android 4.2(JellyBean). 

Steps to reproduce:
 1. Install Rocket.chat.Android
 1. Open the Android Rocket Chat+ app
 1. Provide the server url(for example https://chat.example.com) as required.
 1. Try to connect and i will get an error message "There is a connection error.Please try later."

**Comment by rafaelks** [comment]
This issue isn't valid anymore in version 2.0.0.
