### ISSUE TITLE
[BUG] Exception while trying to update profile

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#762]
Rocket.Chat.Android version: 2.0.0 (milestone version)

While trying to update profile, an exception occurs which says , `The following properties were null: errorType`

This exception is occuring at https://github.com/RocketChat/Rocket.Chat.Android/blob/befa16fcbb18a5c862222ff0303c2ea2f6cc7f62/app/src/main/java/chat/rocket/android/profile/presentation/ProfilePresenter.kt#L52

Here is a screenshot of the same:

![error](https://user-images.githubusercontent.com/22763626/36291007-8c904c38-12ee-11e8-842f-4cee5ba8c5b8.png)

**Comment by aniketsingh03** [comment]
@leonardoaramaki I was trying to solve #752 and found out this, any insight on this one??

**Comment by aniketsingh03** [comment]
@leonardoaramaki @rafaelks any update on this one?

**Comment by aniketsingh03** [comment]
The logcat gives the following error
 `{"success":false,"error":"Match error: Unknown key in field email"}`

**Comment by rafaelks** [comment]
@aniketsingh03 What request are you doing to update the avatar?

**Comment by aniketsingh03** [comment]
@rafaelks the code seems to use the following function of the sdk to update the user profile.
https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt#L47

Anyways, I was using the following sdk function to update the user avatar.
https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/blob/99b4ce6c2e79a7c6f7a4d2a9e3a8b2b719b94720/core/src/main/kotlin/chat/rocket/core/internal/rest/User.kt#L93

**Comment by luciofm** [comment]
@aniketsingh03 could you provide the payload sent to the server?

**Comment by aniketsingh03** [comment]
@luciofm I am sending `userId`, `email`, `name`, and `username` to the server

**Comment by aniketsingh03** [comment]
@luciofm @filipedelimabrito I feel that it is somewhat related to [#70](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/issues/70) in the kotlin sdk.

**Comment by aniketsingh03** [comment]
@luciofm @filipedelimabrito any update on this one?

**Comment by leonardoaramaki** [comment]
@aniketsingh03 This issue should be fixed after https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/84 is merged.

**Comment by aniketsingh03** [comment]
Cool @leonardoaramaki :+1:

**Comment by aniketsingh03** [comment]
Fixed by [#84](https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/84)

**Comment by leonardoaramaki** [comment]
I'm closing this since https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/84 is now merged.
