### ISSUE TITLE
[Bug] Wrong error message at login

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#763]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**When inserting a wrong password the app displays `User not found`**
If you enter a wrong password when connecting to a new server, you get the error message `User not found`. This is semantically not correct.

**Comment by Rish02Sharma** [comment]
@saketkumar95 Can I work on this?

**Comment by rishabhkalra96** [comment]
Is the issue taken by anyone else? @saketkumar95 Are you still working on this ?  If not, can i take on this issue?

**Comment by janrudolph** [comment]
I posted the same issue for the iOS app: https://github.com/RocketChat/Rocket.Chat.iOS/issues/1266

They closed it because of a bug in the API. I guess this will apply here as well?

**Comment by rafaelks** [comment]
@janrudolph Yes, the issue can be closed, since it's in our API.
