### ISSUE TITLE
[UX] When inserting a team URL at login without https no connection is established

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#764]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**As user you do not get a hint to enter `https` in front of the URL** 
When you enter a team URL without `https` the login screen just reloads and you have to insert the URL again. However you do not get any hint to add `https` to your URL. This is a bad user experience because the user does not have a clue how to proceed. Moreover, the sample `open.rocketchat` URL does not show a `https` as well.

**Comment by rafaelks** [comment]
This one can be closed for 2.0.0.
