### ISSUE TITLE
[Bug] Stuck in "create channel" dialog 

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#765]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**When creating a channel the user is not forwarded to the channel**
If you create a new channel via the app, the channel will be created on the server. However as Android user you are stuck in the channel creation dialog. As user I expect to be forwarded to the newly created channel. This does not happen. There is even no success message, that the channel has been created on the server.

**Comment by rafaelks** [comment]
This issue is not valid anymore in version 2.0.0.
