### ISSUE TITLE
[IMPROVEMENT] No video preview picture is rendered

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#766]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**When uploading a video file, no preview picture is created**
The video upload works fine (.3gp file), but you do not see a preview picture and an in-app video player. Rather just a link i shown. The download of the file works as expected.

**Comment by abdulwd** [comment]
@janrudolph May I work on this issue?

**Comment by janrudolph** [comment]
@abdulwd from my point of view, why not? ;-) start working and open a PR. The core team will check your work then, I guess.

**Comment by abdulwd** [comment]
@janrudolph Thanks. I will send the PR soon. :)

**Comment by rafaelks** [comment]
Closing this issue in favor of our milestone 2.0.0 that is almost completed. More information here: https://github.com/RocketChat/Rocket.Chat.Android/milestone/6

**Comment by wajahatshaw** [comment]
@rafaelks @abdulwd Do we have this IMPROVEMENT inside rocketchat? Because i don't see it still.
