### ISSUE TITLE
[Bug] Favorite / Pinned messages with attachments (videos) are not displayed correctly in list

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#768]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**The attachment is not displayed in the list of favorite messages**
Upload a file and add the file to the favorites via the RocketChat web interface. Then have a look on the favorite message list in the Android app. You will find the message but no hint about the attached file. 

**Same issue applies to pinned messages.**

Android
![android](https://user-images.githubusercontent.com/3596824/36298293-b5110b08-12f7-11e8-851f-d6d5362fa6a0.png)

Web
<img width="195" alt="rocket_chat_" src="https://user-images.githubusercontent.com/3596824/36298328-e221490a-12f7-11e8-8335-7d96413b7b6d.png">

**Comment by rafaelks** [comment]
Issue is not valid anymore in version 2.0.0.
