### ISSUE TITLE
[Bug] Notification about pinned message is not displayed

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#769]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**If a user pins a message via web, an Android user will see an empty message**

Web:
<img width="307" alt="web" src="https://user-images.githubusercontent.com/3596824/36300684-791f2bc4-1302-11e8-9495-a2ac210a0c5e.png">

Android:
![screenshot_2018-02-16-22-13-00](https://user-images.githubusercontent.com/3596824/36300767-c1dcd08c-1302-11e8-8dab-aab09e6d9c01.png)

**Comment by leonardoaramaki** [comment]
Thanks for reporting! 
This issue is fixed on upcoming v2.0.0.
