### ISSUE TITLE
Push notifications technically impossible?

### ISSUE THREAD

**Issue by kramer65** [RocketChat/Rocket.Chat.Android#77]
Since push notifications with FCM are not supported in the Cordova Android app (and new GCM tokens are not distributed anymore) I was stoked to see the development of a native Android app. So I was following the development closely, when I just found this little note at the [end of the feature list](https://github.com/RocketChat/Rocket.Chat.Android/blob/doc/feature.md#wont-be-supported):

> ## won't be supported
>  - push notification via FCM (technically impossible)
> 

I'm really puzzled by this. Next to the fact that push notifications are the main reason we're waiting for this native app, I am also wondering; why are push notifications for this app specifically technically impossible. Seeing that there are about a million apps out there supporting push notifications, I wouldn't know why this would be technically impossible for this specific app.

Any info on this would be very welcome!

**Comment by YusukeIwaki** [comment]
It is possible to implement notification using continuous WebSocket connection and will be supported in v1.0-beta (#72)

But we cannot implement it using FCM.

For implementing it, we have to build app with **one** FCM sender id. And we can't configure multiple FCM sender ids for one app.
But each Rocket.Chat server has different FCM sender id...

So we can't implement app with FCM push notification that can be used for arbitrary servers.

**Comment by Sing-Li** [comment]
@YusukeIwaki    we understand that there maybe problem in supporting notification Gateway with the native app (although admittedly difficult to understand why since the Cordova app already does it)

@engelgabriel   but we DO need to be able to use FCM for any community-user-private build (or white label) of the native app  ... that *is* the official Android means of mobile notification intake

Also, please test the battery drain characteristics of a "continuous websocket notification scheme" before committing to develop it.    Battery drain is the NUMBER ONE reason why users perfer native app over Cordova.    (many can put up with the slightly laggish performance)

**Comment by geekgonecrazy** [comment]
@YusukeIwaki The no multiple FCM sender id is for sure a problem.  To get around this with our cordova apps on Android and iOS we had to use a gateway.  All Rocket.Chat Servers out of the box point to the gateway server.  This allows people to right off the bat use our Official mobile apps.

So every rocket.chat server sends to our gateway.  The Cordova app has our GCM sender id compiled in.  The gateway relays to GCM and then it delivers.  This prevents any need for us to introduce any sort of continuous connection.

**Comment by graywolf336** [comment]
Yes, I feel we should continue with this model for the native applications because that's the number one reason people use mobile applications.

**Comment by laggedHero** [comment]
@YusukeIwaki let me hand it.

Let's use GCM with the gateway. We should probably start thinking about FCM and implement a gateway solution with it. Google may start to phase out GCM.

**Comment by YusukeIwaki** [comment]
@laggedHero Thank you!

I agree with the solution with the gateway server, it should be the best if it is feasible.
Continuous WebSocket connection must drain the battery life, as Lily app actually did. It is not smart really.

I will modify background service not to be activated so often, relying on FCM listener.

**Comment by YusukeIwaki** [comment]
By the way, some devices don't have Google Play. We can't push-notify them via FCM.
Do we support such devices in future?

If cordova app can help them, we don't have to support them, I think.

**Comment by laggedHero** [comment]
I think it's OK to not support it. At least as of now.

Maybe we could look out for alternatives in the future (China probably has its own solution).

**Comment by YusukeIwaki** [comment]
As of android, FCM push is just a sign to sync with server.
It is not so difficult to support the devices without Google Play.


with GooglePlay service:

```
RocketChatFCMListenerService.onFcmMessageReceived
-> RocketChatService.keepalive()
 -> reflect `stream-notify-all` state automatically (notification is shown and dismissed if necessary)
```


wothout Google play service:

```
periodical alarm triggered
-> RocketChatService.keepalive()
 -> reflect `stream-notify-all` state automatically (notification is shown and dismissed if necessary)
```

**Comment by kramer65** [comment]
@laggedHero - Great that you've started working on this. The problem with GCM however, is that no new accounts can be opened for that anymore. We would like to release a white labeled version of this Android app, which means we need to use our own FCM account.

How dificult would it be to also support FCM?

**Comment by YusukeIwaki** [comment]
For creating white labeled version, it will be impossible to use Firebase features (currently crash-reporting and analytics are used) for our development.

Of cource it is not a big problem. Just migrating to Crashlytics or another service.
I will configure crashlytics with the same account used in Lily app, if needed. :)

**Comment by laggedHero** [comment]
@engelgabriel maybe we should start working on the FCM gateway. Per @kramer65's comment GCM may not be a solution going forward.

**Comment by laggedHero** [comment]
About the app: in order to support both (GCM and FCM) I'll build two modules. We may choose which to use on the build. I'll update here as I work on it (including if it works xD ).

**Comment by laggedHero** [comment]
The first step into the push notification world is here. There's a lot to discuss (I imagine) and then there's FCM to work with.

After #124 is closed I shall add FCM support.

**Comment by laggedHero** [comment]
@YusukeIwaki We are still missing FCM. So this is not closed yet.

**Comment by laggedHero** [comment]
FCM has a legacy server support. From some tests, everything worked out.

@kramer65 I'll close this one.

**Comment by kramer65** [comment]
@laggedHero - So does that mean I can now use FCM with the Cordova app? Or with this Android app? Or both? I'm kinda lost in this story..

**Comment by laggedHero** [comment]
@kramer65 With both of them.

Sorry. I failed to be more informative. :(

**Comment by aenonGit** [comment]
@laggedHero Hi, I've noticed that even after logout  I keep receiving notifications, I keep receiveing them even after I remove the hostname server.

**Comment by aenonGit** [comment]
@laggedHero Hi, I've noticed that even after logout  I keep receiving notifications, I keep receiveing them even after I remove the hostname server.
