### ISSUE TITLE
[IMPROVEMENT] Channel Search is case sensitive

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#771]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**Channel search is case sensitive**
Imagine you like to search for your channel `Team-chat`. If you insert `team-chat` in your channel search, Rocket.Chat+ will not find any match. Instead you have to search for the exact term (case sensitivity). Same applies if you search for users in the channel search. This is not user friendly.

**Comment by shriomtri** [comment]
i would like to work on this

**Comment by abdulwd** [comment]
@janrudolph I've tried to reproduce this issue but searching for **General** and **general** both shows the search result.

**Comment by shriomtri** [comment]
If search is not case sensitive then then its ok but why it is in issue?

**Comment by abdulwd** [comment]
@jay006 You can try to reproduce the issue. :)

**Comment by janrudolph** [comment]
Well from a user point of view, a search should not be case sensitive. Users find searches everywhere and nearly all common searches are not sensitive (see Google, Bing, Spotlight on Mac...). 

@abdulwd Have you tried reproducing the issue with other channels than **general**?

**Comment by abdulwd** [comment]
@janrudolph Yes, I have tried multiple channels. For example:
![screenshot_2018-02-19-12-51-44-409_chat rocket android dev 1](https://user-images.githubusercontent.com/20206262/36366538-9bdd31be-1574-11e8-9551-f98de43fadab.jpg)

**Comment by rafaelks** [comment]
The issue is referring to 1.1.0 and not 2.0.0 @abdulwd.

**Comment by abdulwd** [comment]
@rafaelks My bad. :(

**Comment by rafaelks** [comment]
Closing this issue in favor of our milestone 2.0.0 that is almost completed. More information here: https://github.com/RocketChat/Rocket.Chat.Android/milestone/6
