### ISSUE TITLE
[Bug] Logout from one team prevents access to other team

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#772]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**If you have joined multiple teams, you cannot access any team after you performed a logout in a team**
Imagine you joined two teams in the Android app. Now you logout from one team. By this, you are forwarded to a login form. The form does not have a description which indicates the team name it belongs to (= another UX bug). However, you cannot even access the other team you joined previously. By the logout of one team, you do not have a chance to go back to the other teams. 
In my opinion, there should be at least a redirect to a team list after you perform a logout or, like in the iOS app, a redirect to another team. 

Interestingly, you get still push notifications of the chat you have not logged out before. But in order to access this chat you have to insert your credentials. => It is not clear whether you are still logged in or not (this is quite similar to https://github.com/RocketChat/Rocket.Chat.Android/issues/336)

**Comment by rafaelks** [comment]
This issue is not valid anymore in version 2.0.0.
