### ISSUE TITLE
[IMPROVEMENT] Markdown hyperlinks inside messages don't open

### ISSUE THREAD

**Issue by shriakhilc** [RocketChat/Rocket.Chat.Android#777]
Your Rocket.Chat.Android version: Latest build from the `develop-2.x` branch
Mobile device model and OS version: OnePlus One, Android 7.1.2

Clicking a message normally opens a menu with additional options such as Reply, Quote and Edit. If a URL is sent as part of the message body, clicking it opens the site on the device browser. This is compliant with the expected behaviour.

However, if the message uses Markdown formatting to have hyperlinked text, it isn't clickable. 

**Willing to work on this issue?** Yes

**Comment by shriakhilc** [comment]
Upon examining the logs a bit, I found that the click itself was registered and produced a log warning
```
W/LinkResolverDef: Actvity was not found for intent, Intent { act=android.intent.action.VIEW dat=[https://facebook.com](https://facebook.com) (has extras) }
```
When the markdown text was linked to a site (Facebook in this case), irrespective of text. 

I made a separate app to test, and it doesn't seem to be due to the call originating in an adapter. Further, since LinkMovementMethod also worked fine there (and is also detecting the URL properly here), I don't think that is where the problem is arising. 

This leads me to believe the issue may be stemming from the custom `MessageParser` being used. The test app handled the links properly when the default `Markwon`parser was being used.

**Comment by rafaelks** [comment]
@leonardoaramaki Could you help @TheGamer007 on this one?

**Comment by leonardoaramaki** [comment]
@rafaelks I'll take a look on the logs here

**Comment by shriakhilc** [comment]
@leonardoaramaki  were you able to find anything?

**Comment by shriakhilc** [comment]
I checked against the latest code, and it seems to be working fine now. Closing the issue.
