### ISSUE TITLE
[DOCS] Build instruction for develop-2.x are incomplete

### ISSUE THREAD

**Issue by joeljacobdev** [RocketChat/Rocket.Chat.Android#780]
The build instruction of develop-2.x branch is incomplete as it doesn't specify how to get core and common jar file in Rocket.Chat.Android/app/libs directory.

I would like to work on this issue.

**Comment by aniketsingh03** [comment]
@pcforgeek assembling, cleaning the sdk and then importing the android project in android studio would do the same (these details are already there in the readme).

**Comment by joeljacobdev** [comment]
@aniketsingh03 These steps only create the jar file. For the jar file to be usable they need to be in Rocket.Chat.Android/app/libs folder.

**Comment by aniketsingh03** [comment]
@pcforgeek this line in the `build.gradle` already does this task for you. 
https://github.com/RocketChat/Rocket.Chat.Android/blob/befa16fcbb18a5c862222ff0303c2ea2f6cc7f62/app/build.gradle#L129
You do not need to run the script manually. Only importing it in android studio does the job for you!

**Comment by joeljacobdev** [comment]
Ok
