### ISSUE TITLE
[BUG] Pushed message is not displayed without refresh

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat.Android#782]
- Your Rocket.Chat app version: 1.1.0
- Your Rocket.Chat server version: 0.61.0
- Device (or Simulator) you're running with: Motorola Moto G

**After getting a push notification, you cannot see the new message in the channel**
When clicking on a push notification, you jump in the related channel. However, you cannot see the new message. The message is not displayed. You have to switch to another channel and come back. After this action all messages are displayed. 
I suggest there is a refresh missing when you jump from the "outside" in the app.

**Comment by rafaelks** [comment]
Closing this issue in favor of our milestone 2.0.0 that is almost completed. More information here: https://github.com/RocketChat/Rocket.Chat.Android/milestone/6
