### ISSUE TITLE
[FIX] Social accounts interface is show after going to TwoFAFragment

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#789]
Even hidden (this happens when a server does not allow the authentication via social accounts - Github, Meteor, Facebook, Twitter and so on) the social accounts interface is show after going to TwoFAFragment.

To see this issue your account must be with Two-Factor Authentication enabled: enable it from the server web app (`My Account>Security`).

**Comment by singhsegv** [comment]
Hey @filipedelimabrito i would like to work on this issue.

**Comment by rafaelks** [comment]
@filipedelimabrito Can this one be closed already?

**Comment by philipbrito** [comment]
@rafaelks Closing it. Already fixed.
