### ISSUE TITLE
[BUG] Can't login with rocket.chat+ on server 0.61.0 

### ISSUE THREAD

**Issue by der-eismann** [RocketChat/Rocket.Chat.Android#790]
Your Rocket.Chat.Android version: 1.1.0
Mobile device model and OS version: LG G6 - Android 7.0

Hey everyone,
we plan on using Rocket.Chat in our company, however I can't get the app to run on my phone. After validating the address and entering my credentials I press "SIGN IN" and get the following error:
`chat.rocket.android_ddp.DDPClientCallback$Closed`

A colleague with a Sony Xperia XZ1 & Android 8.0 joined the team without any problems. Can you help me with this? 

//Edit: Just to add more information: We're running Rocket.Chat as a snap on Ubuntu 16.04 with an Apache Proxy in front of it, configured like advised [here](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/).

**Comment by der-eismann** [comment]
Okay, it's working fine now. The problem was a faulty Apache configuration because we forgot to activate the `proxy_wstunnel` module. Using the [config from the documentation](https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/) everything's fine:
```
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /(.*)           ws://{IP address}:3000/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /(.*)           http://{IP address}:3000/$1 [P,L]

ProxyPassReverse / http://{IP address}:3000/
```
We could still discuss if the error message could be done better, but it shouldn't happen in the first place if you follow the instructions.

**Comment by rafaelks** [comment]
@der-eismann Great, thanks for letting us know and closing the issue 👍
