### ISSUE TITLE
[FIX] Chat list scrolls down when a new message arrives in a channel.

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#791]
Even on top of the list (I men, seeing the first channel on the screen) the chat list scrolls down when a new message arrives in a channel.

**Comment by harisankerPradeep** [comment]
@filipedelimabrito  I'd like to work on this :D

**Comment by philipbrito** [comment]
Hi @harisankerPradeep You can start working on this issue :)
Thank you!

**Comment by harisankerPradeep** [comment]
@filipedelimabrito do we have any mock channels where I can send dummy messages to test the behavior of the app when new messages are received?

**Comment by philipbrito** [comment]
You can have your own local server. But you can test sending dummy messages to the [general channel](https://open.rocket.chat/channel/general).

Do these steps to test:

- Connect the Android app with the [open server](https://open.rocket.chat).
- Connect with the [open server](https://open.rocket.chat) from the browser.
- From the browser send a dummy message (like `"testing..."`) in the[general channel](https://open.rocket.chat/channel/general).
- See the behaviour of this reported issue on the Android app.

**Comment by harisankerPradeep** [comment]
Thanks @filipedelimabrito I will post some updates soon.

**Comment by harisankerPradeep** [comment]
@filipedelimabrito Just a clarification : The bug is that when a new message is received the chat scrolls down to the new message, right?

From what I can see all that has to be done to fix this is remove a line of code: 
```
override fun showNewMessage(message: MessageViewModel) {
        adapter.addItem(message)
        recycler_view.scrollToPosition(0)// remove this line
    }
```
Am I getting this right?

Thanks in advance!

**Comment by harisankerPradeep** [comment]
@filipedelimabrito  awaiting your reply.
