### ISSUE TITLE
[NEW] Cannot connect to TLS protected servers with non-public CA signed certificate

### ISSUE THREAD

**Issue by robertwessen** [RocketChat/Rocket.Chat.Android#793]
Your Rocket.Chat.Android version: 1.1.0

Mobile device model and OS version: Nexus 6 - Android 7.1.1

Reproduction:
1) Create a private CA (common for internal organization applications)
2) Import the new Root CA certificate as a trusted User CA
2a) Settings->Security->Install From Storage
2b) Verify: Settings->Security->Trusted Credentials->User
3) Sign and install a certificate on an internal RockerChat server
4) Connect to the internal RocketChat server

Expected behavior: 
the connection succeeds.

Actual Behavior:
"There's a connection error. Please try again later."
packet capture shows a TLS connection is initiated, Client Hello succeeds, Server Hello succeeds, Server certificate is presented, then the client responds with "Fatal Alert, Certificate Unknown"

This can be reproduced with multiple certs/servers, the same certs work from the native Android browser on the same device, the same certs work form the Cordova version on the same device. The same install of Rocket.Chat.Android works for public RocketChat instances signed with certificate from a public CA.

**Comment by robertwessen** [comment]
suspect this may be related to targeting API above 24 and this: https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

**Comment by robertwessen** [comment]
Confirmed that adding `networkSecurityConfig` line to the Manifest 
```
<application
        android:name=".app.RocketChatApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        **android:networkSecurityConfig="@xml/network_security_config"**>
```

and new `res/xml/network_security_config.xml` config containing:

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```
fixes this issue.

**Comment by robertwessen** [comment]
If this version is scheduled to replace Cordova as the "official" RC Android client in less than a month, this isn't really a [NEW] improvement, its a fix to get feature parity with the current official client.

**Comment by rafaelks** [comment]
@robertwessen The issue you opened is not a bug, so there's no reason to be a **FIX** or a **BUG** tag. I understand that this is a required thing and we'll look into your PR. This is not something that's broken, this is something new to the application.

**Comment by robertwessen** [comment]
I disagree about it not being a bug. All other RC clients can use a private CA certificate, the native android client is the only interface which cannot.

**Comment by pfunk1978** [comment]
Any movement on this issue? I would also like to be able to use p12/pfx keys.

**Comment by rafaelks** [comment]
@robertwessen @pfunk1978 I'm sorry on the delay here guys, we'll review this PR shortly. Thank you for your patience!
