### ISSUE TITLE
[NEW] Support authentication with LDAP, CAS & SAML

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#798]
- [x] LDAP
- [x] CAS
- [x] SAML

**Comment by ChessSpider** [comment]
Hi guys, is there an ETA for SAML support login for the Android App?

**Comment by rafaelks** [comment]
@ChessSpider Very soon, we're just waiting for a rollout with a fix in our APIs to start working on it.

**Comment by rafaelks** [comment]
@filipedelimabrito Removing the blocked tag, since the PR was merged in 0.64.0.

**Comment by ChessSpider** [comment]
Hi guys, any update on the very soon ? 👍

**Comment by rafaelks** [comment]
@ChessSpider We're still waiting for @RocketChat/core to release the snap updates for 0.64+. :-(

**Comment by ChessSpider** [comment]
thx, this is probably discussed in  https://github.com/RocketChat/Rocket.Chat/issues/10656  ?

**Comment by rafaelks** [comment]
@ChessSpider Correct!

**Comment by ChessSpider** [comment]
I am already running  0.64.2 .. (Continuous integration with Docker, livin'on the edge).. Is there a Beta .apk we can install or something?

**Comment by rafaelks** [comment]
@ChessSpider Do you have any server for us to test the implementation?

**Comment by ChessSpider** [comment]
Not one I can give you access to unfortunately, but I can test it. Well, at least to validate if it works or not. I don't have time right now to do a lot of debugging unfortunately

**Comment by rafaelks** [comment]
@ChessSpider Then we'll need to wait on the snap update, because there are some public servers (updated via snap) that we can test it.

**Comment by ChessSpider** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/10656#issuecomment-391432192 It's live in snap!

**Comment by rafaelks** [comment]
We're going o support it on the app very soon. 🎉

**Comment by philipbrito** [comment]
@ChessSpider SAML supported by https://github.com/RocketChat/Rocket.Chat.Android/pull/1326

**Comment by philipbrito** [comment]
All (LDAP, CAS & SAML) are supported now.
