### ISSUE TITLE
[NEW] Show user status in the chat list (DMs).

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#800]

**Comment by SyamSundarKirubakaran** [comment]
@rafaelks I would wish to work on this.. 
4 possible status 
- Online 
- Away
- Busy 
- Invisible

Assign appropriate coloured dot near the name like the one on the stable channel i.e., Rocket.Chat+ 
Does that meet specifications @rafaelks

**Comment by rafaelks** [comment]
@SyamSundarKirubakaran Yes, but we don't have the support on the SDK yet.

**Comment by mmarif4u** [comment]
Can we have a mock for this. As currently `@` are implemented in front of user names. Maybe make `@` green, orange etc for different status.

**Comment by mmarif4u** [comment]
Any updates on this.

Just for my info, is this about the user logged in(which is already implemented some other PR) OR is this for all the users in the chat window?
