### ISSUE TITLE
[NEW] Ability to change user's status

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#801]

**Comment by Shailesh351** [comment]
@rafaelks I have sent PR to add realtime api for changing user status https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK/pull/67. We can use that for it.

**Comment by rafaelks** [comment]
@Shailesh351 Great, thank you! Yes, let's use it.

**Comment by rafaelks** [comment]
Closing this one, was done by @filipedelimabrito already.
