### ISSUE TITLE
[NEW] Add Swipe to refresh in ChatRooms

### ISSUE THREAD

**Issue by Shailesh351** [RocketChat/Rocket.Chat.Android#808]
Your Rocket.Chat.Android version: 2.0.0dev6

**Actual behaviour**
Currently there is no option to refresh ChatRooms. Suppose user has slow internet connection then sometimes it becomes hectic to restarting app or switching between fragment.

**Expected behaviour**
Add feature to refresh ChatRooms on swipe

**Willing to work on this issue?**
Yes

**Comment by rafaelks** [comment]
We don't plan to add this feature soon.
