### ISSUE TITLE
jsonreader error and upload not succeed

### ISSUE THREAD

**Issue by konishi-t** [RocketChat/Rocket.Chat.Android#818]
develop-2.x ( git pull 2018/02/27 0:00 UTC)
Android 7

Error:
use jsonreader.setlenient(true) to accept malformed json at path $
on
Open channel page,
Open DM page
and Upload big picture file(3MB)

channel page and DM page: 
Error is displayed, but the latest message is also displayed without problems
Upload big picture file:
Error is displayed, and Upload did not succeed.

No Error: 
Upload small picture file(300KB)
Send text message.

**Comment by rafaelks** [comment]
@konishi-t You have to make sure that you're using latest server version. This version of the app requires 0.62+.

Thank you!
