### ISSUE TITLE
[IMPROVEMENT] Social accounts interface is shown even when it should be hidden

### ISSUE THREAD

**Issue by philipbrito** [RocketChat/Rocket.Chat.Android#819]
- When you enter a wrong username/password on the login screen the social accounts interface is shown (even when it should be hidden) -> we should fix it 

- After entering a valid username and password the screen goes to the TwoFA or Chat List screen but the social interface that was hidden is shown at this time -> we should fix it.

**Comment by samrmur** [comment]
@filipedelimabrito Can I work on this issue?

**Comment by philipbrito** [comment]
Yes @samrmur. It is your issue :)
Thank you!
