### ISSUE TITLE
[BUG] Orientation Change on ProfileFragment 

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [RocketChat/Rocket.Chat.Android#824]
On viewing the user's profile .i.e., **ProfileFragment** and on **orientation change** from the same leads to the **chatrooms** and not to the Profile Fragment.

![issue_1](https://user-images.githubusercontent.com/26897680/36772596-d70fc900-1c7b-11e8-89c7-70b286bf439b.gif)

**Comment by philipbrito** [comment]
Issue already fixed by #1337
