### ISSUE TITLE
[NEW] Add day marker for messages in chatroom

### ISSUE THREAD

**Issue by joeljacobdev** [RocketChat/Rocket.Chat.Android#825]
Implement a day marker for messages in the chatroom so that it will display Today, Yesterday or date according to the requirement (like the one implemented in version 1.1.0).

I would like to work on this feature.

**Comment by rafaelks** [comment]
@pcforgeek In version 1.1.0 or 2.0.0? Version 1.1.0 won't receive new features/improvements, only 2.0.0 will.

**Comment by joeljacobdev** [comment]
@rafaelks I was saying that I will implement this feature in 2.0.0.

**Comment by rafaelks** [comment]
@pcforgeek Yes, for 2.0.0 feel free to work on it please.
