### ISSUE TITLE
[NEW] Auto detect tagging when @ is typed in a message 

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#826]
Rocket.Chat.Android version: latest build from `develop-2.x` branch
**DESCRIPTION**
In order to tag someone, one needs to type his/her full name. The app needs to have a feature where as soon as the user types **@** the app pops up a list of members of the channel which keeps on filtering as the user types further and the user can select the desired person from the list.

Are you willing to work on this issue?
**Yes**

**Comment by aniketsingh03** [comment]
@filipedelimabrito @rafaelks can you assign this issue to me?

**Comment by aniketsingh03** [comment]
May I work on this @filipedelimabrito ?

**Comment by luciofm** [comment]
@aniketsingh03 this is already in the works, @leonardoaramaki is working on it.
Thanks for your interest...
