### ISSUE TITLE
[LAYOUT] GitLab's logo is upside down in authentication screen

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#834]
![screenshot_20180302-001201](https://user-images.githubusercontent.com/551004/36881738-7fc6d664-1dae-11e8-8561-8e148142c897.png)

**Comment by Shailesh351** [comment]
@rafaelks Can i work on this?

**Comment by rafaelks** [comment]
@Shailesh351 Yes, please.

**Comment by mmarif4u** [comment]
@rafaelks the gitlab auth will work how it works on the web?. I mean not authenticating against gitlab.com only but self hosted custom servers too. Which we are using right now and RC logins through it.

**Comment by rafaelks** [comment]
@mmarif4u Yes, it will. All methods that are supported on the web will be supported on the apps as well.

**Comment by rafaelks** [comment]
Closing, was already merged.
