### ISSUE TITLE
[NEW] Display Chat Room Information

### ISSUE THREAD

**Issue by samrmur** [RocketChat/Rocket.Chat.Android#835]
**Feature**
Add a room option which displays in a _small pop-up window_ the information about a public chat room (such as its topic, last announcement, creator, etc.)

**Willing to work on this**
Yes

**Comment by rafaelks** [comment]
@samrmur Yes, please. Can you provide us a mock of what you’re planning so we can discuss before you send us the PR? Thank you!

**Comment by samrmur** [comment]
@rafaelks 

## **Mock**
**Steps** 

- Add user option inside [ChatRoomFragment](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt#L129) to view room information.
  - This option is displayed based on the value of the [Room Type](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt#L139), meaning private direct messages will not have this option.
- Create Room Information View & Presenter
  - Pass [Room ID](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/app/src/main/java/chat/rocket/android/chatroom/ui/ChatRoomFragment.kt#L138) into the view and use it in the presenter
  - Get data from the [ChatRoomRepository](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/app/src/main/java/chat/rocket/android/server/infraestructure/MemoryChatRoomsRepository.kt) using the [ChatRoomInteractor](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/app/src/main/java/chat/rocket/android/server/domain/GetChatRoomsInteractor.kt). 


**Implementation of the View**
- The view itself can be done in a number of ways. Here are all I have thought of 
 - A _Pull-Down Fragment_ that would pop up from behind the toolbar which will have basic information to start, then can be pulled down to view the rest or canceled (by clicking the cancel button or by clicking elsewhere on the screen).
- A _BottomSheet Fragment_ that would pop up from the bottom of the page.
- A _Pop-Up Dialog_ displaying all the of the chat room.
- A new _Activity_ to display all the information.

**Information to be included**
- All need to be checked in case null
  - Topic
  - Announcement
  - Description
  - Room Creator
  - Read-Only Status
  - List of Muted Users (Might be too much for one screen though, can be added as another option)

**_Very Simple_ Photoshopped Views of Pop-Up and Dialog**
<img src="https://user-images.githubusercontent.com/17170253/36887478-72dd787a-1dbf-11e8-8cad-d83ce39bc7b7.png" width="35%" height="35%"> <img src="https://user-images.githubusercontent.com/17170253/36887526-a85bdd8e-1dbf-11e8-8610-ea7cbb05e280.png" width="33%" height="33%">

**Comment by aniketsingh03** [comment]
@samrmur I think that we should have a new fragment for channel info as later on more functionalities in the sdk would be required in the app also, and a bottom sheet fragment or dialog won't suffice imo, what do you think @rafaelks ?

**Comment by Shailesh351** [comment]
Yes I agree with @aniketsingh03 . We can add other features in future to change room information if user have rights

**Comment by rafaelks** [comment]
@Shailesh351 @aniketsingh03 @samrmur Thanks for the mocks @samrmur! I think that as @aniketsingh03, we'll need to have a new fragment because soon we'll have tons of features to be viewed (and some actions) from the Room. Can you create a new Fragment, displaying all this information for us?

Thank you all guys! 👍

**Comment by samrmur** [comment]
@rafaelks Sure, would you like it to take up the whole screen,make like what the 1.0 version has (which takes up close to 90%), or have it sit in the fragment container above the ChatRoomFragment.

**Comment by rafaelks** [comment]
@samrmur 100%, please.

**Comment by rafaelks** [comment]
@samrmur Are you still working on this one?

**Comment by samrmur** [comment]
@rafaelks Yes, sorry it's taking awhile, just been held up by school. It's mostly finished, just need to tweak.

**Comment by rafaelks** [comment]
Here are the mocks to be implemented...
 
![screen shot 2018-11-01 at 16 06 46](https://user-images.githubusercontent.com/551004/47873506-26582300-ddf0-11e8-8052-41cfd3be8c56.png)

**Comment by samrmur** [comment]
@rafaelks See #925 for update

**Comment by rafaelks** [comment]
@samrmur Can you open the PR again so we can review & merge?
