### ISSUE TITLE
[UI/UX] Member info bottomsheet poses problems 

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#836]
Rocket.Chat.Android version: latest build from `release/2.0.0-beta7` branch 
Mobile device model and OS version: HTC Desire 628 (Android v5.1)

**Description**
Presently the bottomsheet to show the info of a member of a channel is producing some problems.The following screenshot shows how it looks presently:

![members](https://user-images.githubusercontent.com/22763626/36892179-f7810974-1e29-11e8-8e51-7d474d977e02.png)

It faces the following issues presently:
- It is not elevated in comparison to the other elements of the activity.
- It cannot be dismissed on touching outside the bottomsheet surface.
- It is has a transparent background for the region except the avatar.

**Possible Solution**
The correct method to implement a **modal bottomsheet** is to create a dialog by extending the `BottomSheetDialogFragment` class and inflating a layout for it. It would solve all the above issues. 

Willing to work on this?
**Yes**

**Comment by aniketsingh03** [comment]
@filipedelimabrito @rafaelks shall I work on this?

**Comment by rafaelks** [comment]
@aniketsingh03 I believe @filipedelimabrito is working on it already. If not, go ahead please! :-)

**Comment by philipbrito** [comment]
Closed by: https://github.com/RocketChat/Rocket.Chat.Android/pull/843
