### ISSUE TITLE
[INVESTIGATE] Logs me out whenever the app is closed

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Android#846]
Whenever I close the app, I'm logged off and have to log back in, which is very tedious. Is there a way to make it keep me logged in?

**Comment by rafaelks** [comment]
@laptopdude90 Your issue is very broad. :-)

Can you please describe for us what version of the app are you using, what method did you use to install and what Android version are you using?

**Comment by ghost** [comment]
Turns out I had the server configured wrong. I thought the account expire time was the time before the user was removed, so I set it to an exceptionally high value. Unfortunately, since there was no limit on the size, the number I chose caused issues and people were logged out instantly. I had to change the value back, and also had to reboot the server.
