### ISSUE TITLE
Social account login is not working

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#850]
**Rocket.Chat.Android version:** 
versionCode 1009
versionName "2.0.0-dev7" 

**Device**
Device Name - Nexus 6
Android Version - 7.1.1

# Description
Whenever trying to log in via Social accounts nothing is happening.

![](https://im.ezgif.com/tmp/ezgif-1-858186d821.gif)

**Comment by rafaelks** [comment]
@divyanshub024 The support for Social, LDAP, CAS and SAML authentication is in progress.

**Comment by divyanshub024** [comment]
@rafaelks Thanks but even the sign up is also not working.

**Comment by rafaelks** [comment]
@divyanshub024 Yes, Signup & Login are being implemented. 👍

**Comment by divyanshub024** [comment]
@rafaelks is there anyway I can sign in to the app?

**Comment by rafaelks** [comment]
@divyanshub024 Yes, for now you can use the username/password or email/password, filling the text fields.
