### ISSUE TITLE
Profile Layout is going out of screen in Landscape View

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#851]
**Rocket.Chat.Android version:**
versionCode 1009
versionName "2.0.0-dev7"

**Device**
Device Name - Nexus 6
Android Version - 7.1.1

# Description
open profile in landscape view. The email edittext will go out of bounds. 
**Possible solution** make layout scrollable.

![device-2018-03-05-215430](https://user-images.githubusercontent.com/16731434/36986760-a9427be6-20c0-11e8-8c7d-630bb55ead34.png)

**Comment by SyamSundarKirubakaran** [comment]
@divyanshub024 There is another editText that is added in addition to the available 3 .i.e., an editText to change the Avatar using URL. [#754](https://github.com/RocketChat/Rocket.Chat.Android/issues/754) which shall fix this.

**Comment by divyanshub024** [comment]
@SyamSundarKirubakaran It's ok then.

**Comment by divyanshub024** [comment]
@SyamSundarKirubakaran shall I close this issue then?

**Comment by SyamSundarKirubakaran** [comment]
@divyanshub024 I've not added a scrollView in my PR.. If you would wish go for it.. 
Have a word with @filipedelimabrito for conformation.

**Comment by divyanshub024** [comment]
@filipedelimabrito can I take this issue?

**Comment by shriakhilc** [comment]
@divyanshub024 are you working on this, or can I send a fix?

**Comment by divyanshub024** [comment]
@TheGamer007 if someone can assign it to you then definitely you can work on this.

**Comment by shriakhilc** [comment]
@rafaelks @filipedelimabrito can this issue be assigned to me? I'll get started on the layout. Along with using a `ScrollView`, I think having a separate `layout-land` is better. There is too much free space to the left and right of the profile image, so aligning it to the `start` will let the 4 `EditText`(s) comfortably fit within the screen bounds for medium and larger screens. This way, only users with smaller screens will need to scroll.
