### ISSUE TITLE
[New] [UX] There should be an option to unpin the pinned messages from "Pinned Message" activity

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#852]
**Rocket.Chat.Android version:**
versionCode 1009
versionName "2.0.0-dev7"

# Description
Option to unpin the messages pinned by you is not there in pinned message activity.

**Willing to work on it?** YES

**Comment by leonardoaramaki** [comment]
@divyanshub024 Thanks for opening this and willing to work on it. Please feel free to work on this one :)

**Comment by divyanshub024** [comment]
@leonardoaramaki thanks. I'll start working on it.

**Comment by divyanshub024** [comment]
@leonardoaramaki please assign it to me.

**Comment by leonardoaramaki** [comment]
Done

**Comment by divyanshub024** [comment]
@leonardoaramaki there are two ways to unpin the pinned messages. One way is to select multiple items and unpin all of them. Another way is to long-click on an item and an alert dialog will pop up to unpin the message. Which way you think is best?
