### ISSUE TITLE
Spacing in RTL layout is incorrect

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#854]
**Rocket.Chat.Android version:**
versionCode 1009
versionName "2.0.0-dev7"

**Device**
Device Name - Nexus 6
Android Version - 7.1.1

# Description
change Layout from LTR to RTL. Spacing is incorrect between images and text.

# Image
![device-2018-03-05-225008](https://user-images.githubusercontent.com/16731434/36989563-0e9eec34-20c8-11e8-8e51-ce5af4b83a35.png)

**Comment by eliezer-of** [comment]
@filipedelimabrito Can I work on this issue?

**Comment by leonardoaramaki** [comment]
@eliezer-of yes, please :relaxed:
