### ISSUE TITLE
Rocket Chat Non-Native Android App uses Media Volume Instead of Ringer/Notification Volume

### ISSUE THREAD

**Issue by mddvul22** [RocketChat/Rocket.Chat.Android#856]
Your Rocket.Chat.Android version: 2.7.0

On Android, the non-native app uses the media volume for notifications and not the actual ringer/notification volume like, I believe apps are supposed to. This results in the user getting notification sounds even when their ringer is set to silent.

**Comment by leonardoaramaki** [comment]
This one refers to the [Cordova](https://github.com/RocketChat/Rocket.Chat.Cordova) app.
