### ISSUE TITLE
[NEW] Allow the user to create a new channel

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#857]
Rocket.Chat.Android version: latest build from `develop-2.x` branch.

**Description**
Presently the app does not allow the user to create (neither public/nor private) channels in the app.

**How can it be done**
This can be accomplished by adding a `FAB` to the chat rooms list fragment and then opening a new fragment where the user is asked about channel info (name, when was it created, who created it), and whether it must be private or public. The design will be quite similar to the web app.    

Would you like to work on this one?
**Yes**

**Comment by aniketsingh03** [comment]
@rafaelks @filipedelimabrito can I work on this one?

**Comment by aniketsingh03** [comment]
@filipedelimabrito is this in progress already?

**Comment by rafaelks** [comment]
@filipedelimabrito @aniketsingh03 It's not in progress yet, you can start working on it! Thank you!
