### ISSUE TITLE
[BUG] The emoji bar is not opening in landscape view

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#858]
**Rocket.Chat.Android version:**
versionCode 1009
versionName "2.0.0-dev7"

**Device**
Device Name - Nexus 6
Android Version - 7.1.1

# Description
When you open emoji bar to add emojis in a message, the bar won't open in landscape view. Even if you open it in portrait view and change it to landscape view it automatically hides.

**Willing to work on it?** Yes

**Comment by leonardoaramaki** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/1426
