### ISSUE TITLE
[New] Click on user avatar to view user profile/info

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#860]
when you click on the user avatar in a channel message, a screen should appear showing the users profile/info.
**An inspiration from slack**
![device-2018-03-06-115828](https://user-images.githubusercontent.com/16731434/37017256-f4892d82-2135-11e8-81f4-e3c806e3f955.png)

**Comment by divyanshub024** [comment]
@filipedelimabrito can I work on this?

**Comment by divyanshub024** [comment]
@leonardoaramaki can you please see this issue. Can I work on this?

**Comment by rafaelks** [comment]
This is partially done already, so let's close the issue for now.
