### ISSUE TITLE
 [BUG] Chat view reload when go back from member list in a channel

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#861]
Your Rocket.Chat.Android version: **2.0.0-beta7**

Mobile device model and OS version: **Samsung S8 Android 7.1**

Build against **2.0.0-beta7 branch**.

While inside a channel, after checking its member list. The chat view for that channel reload. Which means that, if you were reading messages half way up, you will be presented with the latest messages on exiting member list.

**Comment by rafaelks** [comment]
Thanks for opening the issue @mmarif4u! This issue is not reproducible anymore in latest `develop-2.x`. 👍
