### ISSUE TITLE
Warm Chrome Custom Tabs when inserting messages with hyperlinks

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#863]
https://developer.chrome.com/multidevice/android/customtabs#warm-up chrome to make pages load faster

Shows how embedded webviews can be loaded faster via "warming". The Android Rocket.chat client can perform this warming when a hyperlink is added to a conversation to result in really fast loading pages.

**Comment by leonardoaramaki** [comment]
@bizzbyster which build version are you using?

**Comment by bizzbyster** [comment]
My understanding is that Android client will soon use Chrome Custom Tabs to view clicked links as embedded in Rocket.chat. I heard this from @rafaelks in an offline conversation. When I mentioned warming to Rafael he agreed it was a good idea so I added this issue for tracking purposes. Does that answer your question?

**Comment by bizzbyster** [comment]
But looking at the develop-2.x source code I'm not seeing anything that uses Chrome Custom Tabs in there yet so not sure where this stands.

**Comment by leonardoaramaki** [comment]
That makes sense. I was just trying to be certain we're not talking about the v1 since on the v2 we're still not using it. It's on the roadmap though. Thanks for keeping record of it.

**Comment by rafaelks** [comment]
We're already using this in 2.1.0.
