### ISSUE TITLE
[UI] More vibrant color scheme for unread messages/channels etc

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#864]
Your Rocket.Chat.Android version: **2.0.0 beta 7**

Mobile device model and OS version: Android 7.1 Samsung S8

Build against **2.0.0 beta 7** branch.

Right now for new messages the color become black when there are new messages. It might be ok to some, but i feel it need more vibrant either color or font size(like bold) to make it stand out of the rest. Just a UI enhancement suggestion.

**Comment by mmarif4u** [comment]
@rafaelks what you think about this enhancement?

**Comment by rafaelks** [comment]
@mmarif4u I agree! Look at this mock that we're working on:

![screen shot 2018-04-12 at 10 31 02](https://user-images.githubusercontent.com/551004/38680395-9dbfc302-3e3c-11e8-801c-c31a07f647ab.png)

**Comment by mmarif4u** [comment]
@rafaelks wow... I love that design. Its clean. That is completely a different beast. Is it for 2.0.0 or in the near future?.

**Comment by rafaelks** [comment]
@mmarif4u Near future. 2.0.0 will be released very soon, this changes will get started after 2.0.0 hits the store. 👍

**Comment by mmarif4u** [comment]
@rafaelks thanks. Looking forward to this change.
