### ISSUE TITLE
[UI] Day marker or date with time.

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#865]
Your Rocket.Chat.Android version: **2.0.0 beta 7**

Mobile device model and OS version: Android 7.1 Samsung S8

Build against **2.0.0 beta 7** branch.

Referring to this PR #845, which will add day marker to the chats. At times there maybe hundreds of messages where after scrolling can get lost in the messages that a specific message was sent when unless you scroll up or down to check the date.

Just a suggestion to add date beside time instead of just markers to make scrolling less for better UI/UX.

**Comment by joeljacobdev** [comment]
@mmarif4u For messages older than one week it adds date. For the rest of the messages received within the week the marker show week days or Yesterday or Today.

**Comment by mmarif4u** [comment]
@pcforgeek i do understand your stand on this.

I was just highlighting the point that there could be hundreds of messages for a given day and will be hard to scroll up or down to only find out which date messages i am looking into.

**Comment by joeljacobdev** [comment]
@mmarif4u Adding the date along with time for every message seems unnecessary information to me and most users wouldn't like seeing date for every message again and again. You should find some other way to resolve the issue.

**Comment by mmarif4u** [comment]
> Adding the date along with time for every message seems unnecessary information to me

> For messages older than one week it adds date.

Well, that two lines contradict each other.

But i guess i will leave it as it is for now as if most users are happy with this approach.

**Comment by joeljacobdev** [comment]
@mmarif4u By that I meant about the marker which show only once for all messages of that particular day. I wasn't that clear as you have already seen the issue.

**Comment by mmarif4u** [comment]
@pcforgeek i guess the PR is not merged yet. I was thinking would it be possible to implement what is currently WhatsApp and Signal have, like the date/day marker stick to the top if scroll up for that same day. And change eventually if the messages belong to another day.

What you think?

**Comment by RichardFoxworthy** [comment]
@pcforgeek I cannot see any such date or day markers in Android v2.0.0 - must I do something to enable this?

**Comment by mmarif4u** [comment]
The PR is not merged to 2.0.0 version.

**Comment by RichardFoxworthy** [comment]
when will https://github.com/RocketChat/Rocket.Chat.Android/pull/845 be merged?

**Comment by jaytat0** [comment]
@rafaelks is this day/date marker going to make it onto the road map? It's kind of a big one from a user experience perspective. Thanks.

**Comment by rafaelks** [comment]
@jaytat0 It's already merged/working... it has a bug on the first time you open the room, and this is going to be fixed for next release.
