### ISSUE TITLE
[BUG] Build error

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#869]
For latest develop-2.x branch, I followed the readme to get it to compile and I get this error:

/Users/pete/github/Rocket.Chat.Android/app/src/main/res/layout/fragment_profile.xml
Error:(50) error: resource style/EditText.Profile (aka chat.rocket.android.dev:style/EditText.Profile) not found.
Error:(50) resource style/EditText.Profile (aka chat.rocket.android.dev:style/EditText.Profile) not found.

Ideas?

**Comment by aniketsingh03** [comment]
@bizzbyster this is an issue as `EditText.Profile` is not a valid style, it should be `Profile.EditText` instead. It is fixed in https://github.com/RocketChat/Rocket.Chat.Android/pull/775.

**Comment by SyamSundarKirubakaran** [comment]
@bizzbyster @aniketsingh03 ,
@luciofm has already fixed it with a commit please make a pull. Thanks.
https://github.com/RocketChat/Rocket.Chat.Android/blob/c1871a62843714c8fadffb3f97e8fa358b3c1efb/app/src/main/res/layout/fragment_profile.xml#L52

**Comment by bizzbyster** [comment]
that worked thank you! Closing the issue.
