### ISSUE TITLE
Perma online status

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat.Android#87]
Your Rocket.Chat.Android version: Latest

I've been scratching my head trying to figure this one out.

Steps to reproduce:

* Sign out of all sessions.  (Killed on desktop / all mobile devices) Logged in with another user and confirmed it does show I am signed out.
* Login using the Mobile app
* Close the Mobile app.  I swiped it away.  I noticed immediately it shows i'm offline.  But then a few seconds later it shows that i'm online again.

If I then Force Quit I go completely offline.

Currently using the other app for push notifications, so when this shows me as connected Rocket.Chat doesn't send push notifications.  I'm not sure if its opening a new connection as a service in the background?

Oddly looking at app info it says 0% of battery used by this.

**Comment by sampaiodiego** [comment]
I think the app should implement the same logic as [used for cordova app](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/lib/cordova/user-state.js):

- set the connection as away at "onPause"
- disconnect from the server after one minute

**Comment by Sing-Li** [comment]
Yes.  Seems to be missing status sync on one of the app lifecycle state transitions  :(

**Comment by laggedHero** [comment]
The connection happens on a service that's not bonded to the app lifecycle. I'll add the `UserPresence` method in order to change the online status.

Later on we'll change the service to disconnect after a timeout (1 minute?)
