### ISSUE TITLE
[ENHANCEMENT] Messages goes hidden when trigger keyboard for new message

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#872]
Your Rocket.Chat.Android version: **2.0.0-dev9**

Mobile device model and OS version: Samsung S8

Noticed this, when typing new message/reply in channel/dm the keyboard hide the chat view. It suppose should push the chat view up to see the latest messages.

**Comment by shriakhilc** [comment]
One case I can see where this behaviour is not desired is when the user scrolls up to refer to a certain message, and then starts typing. If it auto-scrolls back down, they'd have to scroll up again. 

Apart from this, since a floating "↓" button is provided to scroll to bottom with just a click, I think it isn't too hard for the user to quickly reach the latest messages. 

However, if you still think it's worth keeping, I'd like to work on implementing this.

**Comment by mmarif4u** [comment]
> One case I can see where this behaviour is not desired is  when the user scrolls up to refer to a certain message, and then starts  typing. If it auto-scrolls back down, they'd have to scroll up again.

This is a valid point.

> Apart from this, since a floating "↓" button is provided to scroll to bottom with just a click, I think it isn't too hard for the user to quickly reach the latest messages.

The scroll-down arrow does not appear if someone start writing immediately unless you touch the chat view and scroll it up or down a bit. This may also need to look into.

One suggestion would be to keep the current behavior, but implement another on top of it. If the chat is at the bottom and keyboard is triggered, move the chat view up. And if the chat view is already up where the scroll-down arrow appear, keep the chat view intact. e.g: Whatsapp.

**Comment by shriakhilc** [comment]
That's a workable compromise. I'll take a look at the current condition for the scroll down button and try adding the suggested behaviour.

**Comment by mmarif4u** [comment]
@TheGamer007 i have just compiled the app(beta6) and this is implemented now.

Active unmerged PR : https://github.com/RocketChat/Rocket.Chat.Android/pull/889.

**Comment by shriakhilc** [comment]
Alright, I'll close the PR. I guess this issue can also be closed in that case.

**Comment by mmarif4u** [comment]
I will close this issue.

Thanks @TheGamer007 for the work though.
