### ISSUE TITLE
[BUG] Cant login to Server

### ISSUE THREAD

**Issue by DoM1niC** [RocketChat/Rocket.Chat.Android#873]
### Problem: ![Issue](http://cloud.3dns.eu/pics/c7998343-9f06-486e-8c06-24b4fb74266c.jpg)

**Comment by DoM1niC** [comment]
I tried to merge some new Stuff from SDK Stuff & CAS login without success, I don't know where the Problem is. xD

**Comment by rafaelks** [comment]
@DoM1niC I believe this is related to some setting in your server that has this huge number (not support for normal Int format)? Can you take a look on that @luciofm, please? Maybe we need to change our Int values to something bigger to avoid this situations.

**Comment by DoM1niC** [comment]
I dont know about this Int Number, I dont changed this.

**Comment by DoM1niC** [comment]
@luciofm some Idea to fix my issue, the client is useless now 4 me -.- :(

**Comment by rafaelks** [comment]
@DoM1niC What's your server URL?

**Comment by rafaelks** [comment]
@DoM1niC Just checked your server... is not required to authenticate on it? What authentication methods are you guys using?

**Comment by DoM1niC** [comment]
@rafaelks just LDAP

**Comment by luciofm** [comment]
We use a Integer for FileSize, so this is to big to fit (MAX_INT 2147483647)
```
    {
      "_id": "FileUpload_MaxFileSize",
      "value": 1000000000000000000,
      "type": "int"
    }
```

**Comment by luciofm** [comment]
We could change the internal representation to a Long (even with the type as int)

**Comment by DoM1niC** [comment]
@luciofm WOW THX <3 my Misstake now all works :)

**Comment by naveen-nrj** [comment]
Can I work on this ? Or is this fixed? (eventhough its tag says open) ?
