### ISSUE TITLE
[NEW] Support Sorting on the list of chats

### ISSUE THREAD

**Issue by Drangleic** [RocketChat/Rocket.Chat.Android#880]
Description:
Rocket Chat web and desktop allow for users to choose how to sort channels/DMs by activity/alphabetical/etc as well as how to group channels/DMs. The native Rocket Chat + Android/iOS mobile apps have no such control over sorting/grouping. This is highly desired by our users and impacts the way they communicate from their mobile devices.

Expected behavior:
Android/iOS mobile apps should at least replicate what users have set as their preference in the Desktop client, or allow them to configure sorting/grouping how they want.

Actual behavior:
Users have no control over sorting/grouping in the Rocket Chat + Android/iOS mobile apps.

I didn't include server details/logs as this isn't a bug or problem with the installation, but please let me know if they are required within the issue. Thanks!

**Comment by philipbrito** [comment]
We plan to support it like the web app does.
Thanks for creating this issue.

**Comment by Shailesh351** [comment]
@filipedelimabrito Anyone working on this issue? If not then i would like to work on it :smile:

**Comment by bizzbyster** [comment]
This is no doubt an additional feature but I'm curious @Shailesh351 and @rafaelks what you think about having a read only "news feed" room that shows all active chats in a single room with the ability to click a #roomname link to go to that room. This gives the user the ability to monitor activity in a single room and not have to click around to see all the recent activity he/she may be interested in. I'll put this in a new issue so ignore commenting on it here since it does not relate to sorting rooms.

**Comment by bizzbyster** [comment]
@filipedelimabrito question about this feature. Will the 2.x version eventually have the group type labels like the 1.x version, IOS, and Web have?

Right now I'm able to "group by type" as seen below:
![image](https://user-images.githubusercontent.com/4001792/37364622-64308982-26d1-11e8-88d3-52f7e8ebf646.png)

But I do not see the type labels like "direct message" and "private groups" etc.

Also, will the 2.x version bring back the thumb swipe as a way to gradually move between the "chats" view and an individual chat? That user experience (which is in the 1.x version and the IOS client) is very powerful in my opinion.

Thanks!

**Comment by jyellick** [comment]
Adding some additional flexibility for sorting would be great.

I'd also mention that the default sorting decision seems very odd to me.  As best as I can tell, in the v2.0.0-alpha1 release, the 'chats' are sorted from least-recently-access to most-recently-accessed, meaning when you open the app, you must scroll through dozens or hundreds of entries to get to your most recent conversation.  I would have expected the opposite to be true.

In the RC web-app, I'm also a big fan of the 'favorites' feature that allows me to pin certain channels and users to the top of my list, so it's easier for me to find them.

**Comment by bizzbyster** [comment]
@jyellick you might want to create an issue in this repo for the favorites feature. I agree that's a nice one.

**Comment by jyellick** [comment]
Thanks @bizzbyster good idea, I've created #988 to track the 'favorites' feature.

**Comment by rafaelks** [comment]
@jyellick The default sort of the list is by activity, so the most recent conversations will always stay in the top. If you're not seeing that behaviour, check if you're running 0.63+ on your server please.

**Comment by jyellick** [comment]
@rafaelks The server version is indeed "0.62.0", guess I will need to wait for our admins to upgrade, thanks!
