### ISSUE TITLE
[IMPROVEMENT] Show empty view on pinned messages screen

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#895]

**Comment by aniketsingh03** [comment]
A view needs to be displayed when there are no pinned messages available, right @leonardoaramaki ? Is there anything else that needs to be done?

**Comment by leonardoaramaki** [comment]
I'd rather have an image only or along with a text line. I'll see if I can have the image here.

**Comment by divyanshub024** [comment]
@leonardoaramaki @aniketsingh03 maybe we can do something like this.

![empt pin design](https://user-images.githubusercontent.com/16731434/37416927-14389bcc-27d5-11e8-9409-6d3cc2f26cf2.png)

**Comment by rafaelks** [comment]
@divyanshub024 Looks nice! 👍

**Comment by divyanshub024** [comment]
@rafaelks Thanks a lot! I start working on it. Can you please assign it to me?

**Comment by rafaelks** [comment]
@divyanshub024 Go ahead. I cannot assigned now because you didn't create the issue and you're not from the organisation, but go for it!

**Comment by divyanshub024** [comment]
@rafaelks sure :+1:
