### ISSUE TITLE
[IMPROVEMENT] Show empty view on chat rooms screen

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#896]

**Comment by shriakhilc** [comment]
@leonardoaramaki Will a `TextView` displaying "No messages to view in this channel" suffice? Should I also make it display a generic network error message when there is a failure, rather than the current `Toast` usage?

**Comment by leonardoaramaki** [comment]
I'd rather have an image only or along with a text line. I'll see if I can have the image here.
