### ISSUE TITLE
[IMPROVEMENT] Show empty view on Recents emoji picker category

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#897]

**Comment by abdulwd** [comment]
@leonardoaramaki I can fix this. Should I add a simple text "**No recent emoji**" to the center of recent emoji picker category if it is empty or do you have any other suggestions?

**Comment by philipbrito** [comment]
@abdulwd I think that the Leonardo's idea is to show an image that actually represents the "no recent emoji".
