### ISSUE TITLE
Fabric Integration Test

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat.Android#9]
#### in some_crashed_method
- Number of crashes: 0
- Impacted devices: 0

There's a lot more information about this crash on crashlytics.com:
[http://example.com/path/to/fabric/issue](http://example.com/path/to/fabric/issue)

**Comment by YusukeIwaki** [comment]
Currently with the configuration in [Application.java](https://github.com/RocketChat/Rocket.Chat.Android.Lily/blob/develop/app/src/main/java/chat/rocket/android/RocketChatApplication.java#L32), Crashlytics feature doesn't work in DEBUG build.

```
        CrashlyticsCore core = new CrashlyticsCore.Builder().disabled(BuildConfig.DEBUG).build();
        Fabric.with(this, new Crashlytics.Builder().core(core).build());
```

Crashlytics will work with RELEASE build, but I'm not ready for generating it now...

**Comment by YusukeIwaki** [comment]
For RELEASE build, we need RocketChat.keystore used in building Rocket.Chat.Cordova with storePassword, alias, password. (Or we have to generate new keystore.)

I think it is better to share keystore file among all Rocket.Chat Android products.

**Comment by engelgabriel** [comment]
OK, i'll send you the keystore

**Comment by YusukeIwaki** [comment]
Now RELEASE build has been started.
Some APK distributed by Fabric beta send crash information actually.
