### ISSUE TITLE
[BUG] New messages aren't being set as "read" when they arrive

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#900]
Your Rocket.Chat.Android version: 2.0.0
Mobile device model and OS version: Sony Xperia

When I receive new messages and I'm inside of the chat, the chat isn't marking the messages as read. It should mark them as read.

This video shows the bug happening:

![2018-03-13 06 49 02](https://user-images.githubusercontent.com/551004/37334478-c05d99d0-268a-11e8-910b-8643151ac683.gif)

**Comment by leonardoaramaki** [comment]
I also think that the unread message should appear in the center of the marker.

**Comment by shriakhilc** [comment]
@rafaelks I'd like to work on this. I have a rough idea of where the problem is and what needs to be done to fix it.
@leonardoaramaki I kept the text right aligned since that is how it was in the web app. I'll shift it to the center .
