### ISSUE TITLE
[IMPROVEMENT] Open the specific chat room/dm from the notifications

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#901]
Your Rocket.Chat.Android version: 2.0.0-dev9

Mobile device model and OS version: Android 7.1 on Samsung S8

Currently any notification in the notification shade open the app, not that specific channel or dm where it arrived.

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/1322
