### ISSUE TITLE
[QUESTION] Encrypt of all dialogues at the master key. Is it available?

### ISSUE THREAD

**Issue by sttyru** [RocketChat/Rocket.Chat.Android#902]
Your Rocket.Chat.Android version: 0.60.3

Mobile device model and OS version: Android 7

Hello!

I need to improve secure of communication in my team and encrypt of all dialogue messages at the master key (maybe by symmetric encryption?) Is it feature available in current version of Rocket.Chat? Or maybe is it available like a feature by 3rd party software?
I use RC 0.60.3 und MongoDB 2.6 (for compatibility with another legacy applications).

Thank you!

**Comment by rafaelks** [comment]
@sttyru I'm not sure I follow your question... what do you need to encrypt?
