### ISSUE TITLE
[REQUEST] Read only "my activity" room

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#903]
I'm curious @Shailesh351 and @rafaelks what you think about having a read only "news feed" room that shows all active chats in a single room with the ability to click a #roomname link to go to that room. This gives the user the ability to monitor activity in a single room and not have to click around to see all the recent activity he/she may be interested in. On mobile in particular its convenient to only have to monitor one place. Maybe instead of "news feed" it would be called "my activity"?

**Comment by rafaelks** [comment]
@bizzbyster Please, move your feature request to our forums: https://forums.rocket.chat/c/feature-requests.
