### ISSUE TITLE
[TESTS] screenshot tests

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#905]
Has this team considered using something like this?

https://facebook.github.io/screenshot-tests-for-android/

Would allow reviewers to see screenshots when views change without having to pull the code and run it for themselves.

I'm new to working on this team so forgive me if this has been proposed and discussed elsewhere.

**Comment by leonardoaramaki** [comment]
I was thinking about putting something such as this and adding to the CI. That's something we definitely want to have at some point.

**Comment by rafaelks** [comment]
Thanks for bringing this topic to our attention @bizzbyster, we'll come back here once we have UI tests. 👍
