### ISSUE TITLE
[BUG] Build error

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#907]
I was building successfully but now get the following when I pull the latest of the develop-2.x branch.

/Users/pete/github/Rocket.Chat.Android/app/src/main/java/chat/rocket/android/authentication/login/presentation/LoginPresenter.kt
Error:(166, 45) Unresolved reference: loginWithCas

Any ideas?

**Comment by leonardoaramaki** [comment]
Have you also updated the SDK?

**Comment by bizzbyster** [comment]
ah thanks!
