### ISSUE TITLE
[I18N] Localization in Hindi

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#912]
It's noticeable that we have a very large community around us from India 🇮🇳 so I thought it would be a good idea to have in our app localization support for Hindi.

**Comment by divyanshub024** [comment]
@leonardoaramaki That's a great idea. Let me know if I can help anyway.

**Comment by leonardoaramaki** [comment]
@divyanshub024 sure, you can work on this anytime you want. We need Hindi speakers here :relaxed:

**Comment by divyanshub024** [comment]
@leonardoaramaki I'm a Hindi speaker and will be grateful to work on this.

**Comment by leonardoaramaki** [comment]
@divyanshub024 Thank you! Consider this assigned to you :)

**Comment by divyanshub024** [comment]
@leonardoaramaki Welcome! Is there any timeline for this? Till when you want this to be completed?

**Comment by leonardoaramaki** [comment]
@divyanshub024 Not at the moment. That's why I didn't added to the 2.0 release milestone just yet. Feel free to work on your own pace if you've been busy :-)

**Comment by naveen-nrj** [comment]
I am also from India . CAN I work too?

**Comment by leonardoaramaki** [comment]
Sure @naveen-nrj, go on. @divyanshub024 did you started this already?

**Comment by divyanshub024** [comment]
@leonardoaramaki Not yet I'm working on another issue. I think its good if @naveen-nrj can help.

**Comment by leonardoaramaki** [comment]
@naveen-nrj Please go on with this! Thanks :)

**Comment by naveen-nrj** [comment]
@divyanshub024  @leonardoaramaki  So how can I start?

**Comment by divyanshub024** [comment]
@naveen-nrj yes go on. Let me know if you need any help.

**Comment by divyanshub024** [comment]
@naveen-nrj have you started working on this?
