### ISSUE TITLE
[BUG] Presenter Jobs continue to run after Fragment destruction

### ISSUE THREAD

**Issue by samrmur** [RocketChat/Rocket.Chat.Android#915]
**Issue**
Jobs/Coroutines in most presenter objects will continue to run even after fragment destruction even when the co-routine is launched with a `CancelStrategy`. 

**Replication**
From either the navigation menu or the chat room activity, switch fragments while the data is being loading (when the loading view is shown). The presenter will still think the view is present and invoke its view operations on it.

**Willing to work on this**
Yes, but it would have to be after I finish #835.

**Comment by rafaelks** [comment]
This one can be closed for now, already fixed in 2.1.0.
