### ISSUE TITLE
[IMPROVEMENT] Show version name/number under settings

### ISSUE THREAD

**Issue by leonardoaramaki** [RocketChat/Rocket.Chat.Android#920]

**Comment by abdulwd** [comment]
I would like to solve this. I would just like to know that whether the version name/number has to be shown in a dialog when the user taps on **Version** in the **ListView**. Or we can show the version name/number below **Version** (text) as in Android settings but then we should use a Preference Screen as the items in the ListView cannot be used to show two strings one below the other.
