### ISSUE TITLE
UI Improvement : Add files from phone.

### ISSUE THREAD

**Issue by naveen-nrj** [RocketChat/Rocket.Chat.Android#922]
Your Rocket.Chat.Android version: (make sure you are running the latest)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

When we click the + button to send some file it is showing add files from Computer. It should be Add file from phone.

**Comment by mmarif4u** [comment]
@naveen-nrj Which app you are using.

**Comment by leonardoaramaki** [comment]
@naveen-nrj I can't see this happening anywhere else here. Are sure that you're testing from the Rocket.Chat+ alpha version (or dev)? If you're unsure on what version/app you're testing post a screenshot and we can check it for you.

**Comment by naveen-nrj** [comment]
Seems like I am not using the Rocket Chat+ instead just the "Rocket Chat" ver:2.7.0 . Sorry for the inconvenience.

**Comment by leonardoaramaki** [comment]
No problem @naveen-nrj. Seems like you're using the Cordova version. Post this issue on their repo: https://github.com/RocketChat/Rocket.Chat.Cordova/issues

**Comment by naveen-nrj** [comment]
@leonardoaramaki  Ok thanks for the info .
