### ISSUE TITLE
[BUG] The alpha crashes when starting a search

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat.Android#926]
Your Rocket.Chat.Android version: Version: 2.0.0-alpha1

Mobile device model and OS version: LG G4 (Android 6.0)

1. Open the app & login
2. Start a search over the Chats
3. Beginn typing 'app'

**Comment by leonardoaramaki** [comment]
Hi @ruKurz! Thanks for reporting. 
We did a fix on this yesterday. On the next release it shouldn't happen again. 
Closing for now but feel free to reopen it if it happens again on next alpha release.

**Comment by ruKurz** [comment]
thx @leonardoaramaki
