### ISSUE TITLE
[FEATURE] Can not login on open.rocket.chat using social accounts

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat.Android#927]
Your Rocket.Chat.Android version: alpha1

Mobile device model and OS version: LG G4 - Android 6.0

Use open.rocket.chat as server to connect to, hit one of the social accounts, nothing happens at all.

**Comment by philipbrito** [comment]
@ruKurz This is on our roadmap and will be implemented soon.

**Comment by rafaelks** [comment]
This one can be closed already, most of the social accounts are implemented in 2.0.0. Requires server version 0.63+.
