### ISSUE TITLE
[BUG] Mention a username starting with an 'a' dors not work propably

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat.Android#928]
Your Rocket.Chat.Android version: alpha1

Mobile device model and OS version: LG G4 (Android 6.0)

Start typing a message with '@a' resulting in '@@a'

**Comment by leonardoaramaki** [comment]
@ruKurz We couldn't reproduce the issue yet. Can you describe some steps to reproduce it or maybe a gif showing it happening?

**Comment by ruKurz** [comment]
I'm not able anymore to reproduce this issue. Therefore I'll close it.
