### ISSUE TITLE
[BUG] Channel name cannot display Chinese characters

### ISSUE THREAD

**Issue by maxdang365** [RocketChat/Rocket.Chat.Android#932]
We use the Android version of the client, but the channel name and user name are displayed in English, but the iOS version does not

**Comment by leonardoaramaki** [comment]
@maxdang365 Thanks for reporting!

1. Which version of the Android app are you using?
2. Chinese characters are not displayed only on channel name and user name?

**Comment by maxdang365** [comment]
@leonardoaramaki 

My Android Version: 6.0.1 Rocket.Chat+ Version: 1.1.0. 
And it can't display chinese characters only on channel name and user name.

but Rocket.Chat+ app for iOS is OK.

**Comment by leonardoaramaki** [comment]
@maxdang365 Version 1.1.0 is not supported anymore. We're rewriting the app entirely and we already have an early alpha on the Play Store. Can you try it on the new version?

**Comment by maxdang365** [comment]
@leonardoaramaki 
I can't search newest version on google play store. 
I find RocketChatRN and Install the App, but still display channel's English code.

**Comment by philipbrito** [comment]
@maxdang365 Could you please report the this issue status? Did you try the new Android app (version 2+) on the Play Store? It this issue happening for that version?

Thanks.

**Comment by rafaelks** [comment]
Could not be reproducible by us now, let's close it.

**Comment by maxdang365** [comment]
Hello  @rafaelks 

Just like the picture below, we really need to display the channel name. I use Android rocket.chat+ 2.0.4. All of our employees have this problem.

![image](https://user-images.githubusercontent.com/37443075/39394908-3e547fcc-4b0a-11e8-8b04-541d07d753e5.png)

**Comment by leonardoaramaki** [comment]
@maxdang365 Thanks for reporting the status of the issue on the current version. Reopened :relaxed:

**Comment by rafaelks** [comment]
@maxdang365 Looks like you also have the setting "Store Last Message" disable. Make sure you enable it to have a better experience on the mobile apps please. It's under Administration -> General. 👍

**Comment by rafaelks** [comment]
@maxdang365 Can you check if this is fixed in 2.1.0? We just released to the store.

**Comment by rafaelks** [comment]
Just created an issue to fix it, now that we know how it works: #1283.
