### ISSUE TITLE
[FEATURE] Save unfinished message in chat room

### ISSUE THREAD

**Issue by Pancor** [RocketChat/Rocket.Chat.Android#933]
Currentlny, when user writtes a message and then decides to leave a chat room without sending a message, the message disaperas. It could be saved and when user reopen a chat room, written message would be shown again with auto focus on the text field. For example, similar feature is in Messenger. 

Current situation:
![current2](https://user-images.githubusercontent.com/24636767/37554635-e332b32e-29db-11e8-8b7f-7915665089fd.gif)

Feature implemented in Messenger:
![solution2](https://user-images.githubusercontent.com/24636767/37554634-db633a74-29db-11e8-8a73-b2011dad7f38.gif)

I think, that I could work on that feature, but there is a question that need to be answered before writting an implementation. Should unfinished message be stored in `SharedPreference ` or maybe in local database with use of `Andorid-Room` library?

**Comment by leonardoaramaki** [comment]
@Pancor Yes, you should save it on `SharedPreferences`.  Have a look on this class https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/app/src/main/java/chat/rocket/android/infrastructure/SharedPrefsLocalRepository.kt if you want to work on it.

**Comment by daniel-lerch** [comment]
Does this issue also address the lose of a message when changing to another app and back to Rocket.Chat?
This always happens to me using Rocket.Chat+/1.1.0 on a Samsung Galaxy S6 (Android 7.0).
