### ISSUE TITLE
[BUG] sending empty message while attaching zip file

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#936]
Rocket.Chat.Android version: (make sure you are running the latest)

2.0.0-alpha1

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

Nexus 6 - Android 7.1

## Description
while selecting zip file as a file attachments, it sends an empty message.

**Comment by leonardoaramaki** [comment]
Actually, it crashed here. Marked as bug.

**Comment by divyanshub024** [comment]
@leonardoaramaki same problem is occurring when I'm attaching a pdf file.

**Comment by mvp-sales** [comment]
@leonardoaramaki @divyanshub024 I found the same problem after uploading a `.pdf` file. It seems the `RocketChatClient.messages()` method is returning messages with their attachments' contents as `null`.

I tested on a LG tablet, Android 5.0.1

**Comment by rafaelks** [comment]
Closed by #1195
