### ISSUE TITLE
Can't specify server in the server list

### ISSUE THREAD

**Issue by virtualwatt** [RocketChat/Rocket.Chat.Android#937]
It is not possible to specify server in the server list, see video attached.
Reproduced on several devices at least Samsung S7 and Samsung S9+ (Android 8.0, see screenshot)
Application version latest available now in the Google play (screenshot attached), I can't find it in the menu nearby the username.
Steps to reproduce: in the newly installed application (or remove all data in "applications" settings) click on "server list" or swipe with two fingers. Click either on the empty list item or the "+" button.
Actual: see what's happening in the attached video, the list just disappears.
Expected: user is able to specify server address in the list successfully.

Video accessed here: https://1drv.ms/v/s!AlsU4wa12aVTu0XgkKEVApX25CwE
![screenshot_20180318-144511_settings](https://user-images.githubusercontent.com/25531009/37593538-fab79582-2b7a-11e8-8100-5889b4fe9f90.jpg)
![screenshot_20180318-144943_google play store](https://user-images.githubusercontent.com/25531009/37593539-fad339a4-2b7a-11e8-8c0a-3f5786559d48.jpg)

**Comment by leonardoaramaki** [comment]
@virtualwatt Thanks for reporting! But this issue seems to be related to the Cordova app and not the native one. This repo is the native's one. Please repost your issue here: https://github.com/RocketChat/Rocket.Chat.Cordova
