### ISSUE TITLE
[FEATURE] Embedded browser action button should enable sharing to other Rocket.chat users

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#938]
Here's an example Chrome Custom Tab with a "SHARE" action button at the top left:

<img src="https://user-images.githubusercontent.com/4001792/37602742-69f3a674-2b63-11e8-8611-802e8d9c2ce1.png" width="200"/>

By doing this for our Android client we'll make it easy for our users to share with each other and not have to jump out to the OS sharing functionality if they want to stay within Rocket. If they want to share outside of rocket, they can hit the hamburger button and there is another share option there.

Of course, this feature is only relevant after this (https://github.com/RocketChat/Rocket.Chat.Android/pull/917) has been merged.

**Comment by rafaelks** [comment]
This is done already I guess @bizzbyster, correct me if I'm wrong.
