### ISSUE TITLE
[NEW] Allow sending photos directly via the camera

### ISSUE THREAD

**Issue by exhuma** [RocketChat/Rocket.Chat.Android#940]
Your Rocket.Chat.Android version: 1.1.0

Currently it is only possible to send photos by selecting them from the gallery. So you have to open the camera, take the picture and finally get back to Rocket.Chat and attach the image manually. This is quite cumbersome.

**Comment by divyanshub024** [comment]
@filipedelimabrito can I work on this issue?

**Comment by luciofm** [comment]
@divyanshub024 I'm already working on this issue. For photos and videos.

**Comment by divyanshub024** [comment]
@luciofm ok, thanks for informing.

**Comment by yodiwo-sa** [comment]
Hello, is anyone still working on this issue? @divyanshub024 @luciofm

**Comment by philipbrito** [comment]
We are working on new features and bugs fixes for the current version @yodiwo-sa. No one is working on this feature right now.

**Comment by avzverkov** [comment]
> We are working on new features and bugs fixes for the current version @yodiwo-sa. No one is working on this feature right now.

Hi, Have any update for this issue? Thank you.

**Comment by yodiwo-sa** [comment]
Hi there, no further updates received.

**Comment by sandys** [comment]
any update on this ?

**Comment by philipbrito** [comment]
Hi guys, we were working on other improvements and features, but I want to let you know that this feature will be delivered on our next release (3.1.0).

Thanks for your patient and comprehension.
