### ISSUE TITLE
[NEW] Allow sending message with attachments

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#944]

**Comment by philipbrito** [comment]
We are supporting sending an attachment with message in our SDK already, but we need to implement this in the Android app.

Thanks for opening this issue.

**Comment by divyanshub024** [comment]
Is someone working on this or should I start working on it?

**Comment by rafaelks** [comment]
This is already done in version 2.0.0.

**Comment by divyanshub024** [comment]
@rafaelks I think this feature is still not implemented

**Comment by philipbrito** [comment]
@divyanshub024 That's is true. This feature is still not implemented. 
@rafaelks The feature is: Before choosing a file, the user should be able to send a message along with. 

Images worth more than words, so here is my idea in picture:

![demo](https://user-images.githubusercontent.com/11776825/40978463-11903702-68aa-11e8-8d63-abe256b088d5.png)

See, after choosing this cute puppy from my gallery the app shows me a view with the chosen image and the possibility to send a message with the attachment (like the RC web app does). 

Note: This is not only for images, we should show this view for any picked file (but for images it shows a preview).

@divyanshub024 Do you like to work on this feature?

**Comment by divyanshub024** [comment]
@filipedelimabrito Sure! I'll start working on it.

**Comment by philipbrito** [comment]
Thank you @divyanshub024!
