### ISSUE TITLE
Periodically check for new messages

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat.Android#945]
Rocket.Chat.Android version: 2.0.0-alpha1
 
Is there a way to get new messages without push notifications and manually check the apps ?

I'd like to avoid the use of Google services and I didn't find a way to periodically pull new messages.

Riot for Android do it with a warning about battery life :
https://matrix.org/docs/guides/faq.html#i-installed-riot-via-f-droid-why-is-it-draining-my-battery

Cheers

**Comment by leonardoaramaki** [comment]
@magicbelette Do you mean getting notified of new messages without resorting to push?

**Comment by magicbelette** [comment]
Yes that's it

**Comment by luciofm** [comment]
Currently we have no plans to poll for new messages in the background. We rely on Push notifications for that.

**Comment by magicbelette** [comment]
Thanks for you answer.

**Comment by leonardoaramaki** [comment]
Polling for messages is not viable but it could be done during app usage in foreground when getting updates on socket subscriptions but that would work only until the socket gets closed/process gets killed.

**Comment by sschueller** [comment]
The Rocket Chat app on f-droid (https://f-droid.org/en/packages/chat.rocket.android/) does not have google services which means there is no way to get notified when you have a new message. Polling would be the only solution, therefore I recommend reopening this and considering implementing such a feature even if it is only for those who get the app from f-droid.

Alternatively, would you accept a pull request for this feature all though it is not on your roadmap?

**Comment by rafaelks** [comment]
@sschueller Yes, we're open for PRs that implement such thing (may receive technical feedbacks that needs to be addressed). Also, it needs to be a second option instead of the default one. Thank you!

**Comment by gerroon** [comment]
This would be so nice since I use the F-droid version too. Does anyone have any news or recommendations for this?

I do not even mind using Tasker or something like this to poll the new messages. As of now the app has to be in the fg to get the messgaes


thanks
