### ISSUE TITLE
[BUG] Content not shifted up when keyboard shows in chat rooms

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#951]
Rocket.Chat.Android version: latest build from the `develop-2.x` branch

Emulator: Pixel 2 (API level 26)
The following screenshots clarify the issue:

The keyboard hides the content:
 
![bug](https://user-images.githubusercontent.com/22763626/37776699-e1705314-2e0b-11e8-8cf5-f4336ebdb922.png)

After being fixed, it looks like this:

![fix](https://user-images.githubusercontent.com/22763626/37776748-ff8cc0bc-2e0b-11e8-9688-329d1c78125d.png)

**Comment by aniketsingh03** [comment]
@filipedelimabrito @rafaelks @leonardoaramaki, since this is a minor issue, so I'll be fixing this in https://github.com/RocketChat/Rocket.Chat.Android/pull/775 itself.

**Comment by leonardoaramaki** [comment]
@aniketsingh03 is it already fixed on that PR?

**Comment by aniketsingh03** [comment]
Yeah, I have already fixed it @leonardoaramaki , do you want me to submit a new pr for it?

**Comment by leonardoaramaki** [comment]
@aniketsingh03 No, but I was going to address this issue on a branch I'm working on. But since you did that, better yet. This is an annoying behavior. I'll have a look at your PR. Thanks!

**Comment by leonardoaramaki** [comment]
This is already fixed on the develop-2x branch.
