### ISSUE TITLE
[NEW] User status in the bottomsheet fragment for a user in the members list of a channel

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#953]
Rocket.Chat.Android version: latest build from `develop-2.x` branch

The bottom sheet fragment for member info in a chat room does not have a status (online, offline, etc) indicator for the user.

![status_before](https://user-images.githubusercontent.com/22763626/37785624-a37da952-2e20-11e8-830e-fb7b09259886.png)

**Comment by rafaelks** [comment]
This one can be closed for now.
