### ISSUE TITLE
[NEW] Invite users via a "share" type button

### ISSUE THREAD

**Issue by bizzbyster** [RocketChat/Rocket.Chat.Android#960]
In order to increase the adoption of Rocket.chat, I think it's really important to make it easy to invite non-rocket users. I'm opening this issue for Android specifically. The issue across all platforms is #2181.

**Comment by bizzbyster** [comment]
@rafaelks can you clarify what you mean by needing an API? I think this can be done inside the Android client only. See my comment at the end of this issue: https://github.com/RocketChat/Rocket.Chat/issues/2181.

**Comment by rafaelks** [comment]
@bizzbyster How do you think the link should be on an invitation? What message? All these can be shared between all clients when we have something via APIs. With an API we can also have a state of "user invited" instead of just shooting an email.

**Comment by bizzbyster** [comment]
@rafaelks 

That approach definitely has some benefits but also some drawbacks and so let's discuss the two approaches. @graywolf336 has asked us to move feature discussions to the forum so I will do that and post the link back here.

**Comment by bizzbyster** [comment]
https://forums.rocket.chat/t/invite-new-users-feature/668

**Comment by bizzbyster** [comment]
I'm fine with closing this and continuing the discussion there.
