### ISSUE TITLE
[BUG] No response on clicking "change password" in Portuguese language

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#962]
Rocket.Chat.Android version: (make sure you are running the latest)

2.0.0-alpha1

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

Nexus 6 - Android 7.1

![](https://im3.ezgif.com/tmp/ezgif-3-7956dc08d4.gif)

**Comment by samrmur** [comment]
Found the [error](https://github.com/RocketChat/Rocket.Chat.Android/blob/develop-2.x/app/src/main/java/chat/rocket/android/settings/ui/SettingsFragment.kt#L36). I forgot to account for other langauges, will have this fixed asap.

**Comment by divyanshub024** [comment]
@samrmur thanks but I have already fixed it.

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/989
