### ISSUE TITLE
Invalid Server version issue

### ISSUE THREAD

**Issue by renuraj18** [RocketChat/Rocket.Chat.Android#963]
Your Rocket.Chat.Android version: Rocketchat+ latest version on Playstore V:1.1.0
Mobile device model and OS version: Honor 7x
Rocketchat server version: 0.61.0-develop

Nginx config:

    set $upstream_rocketchat http://rocketchat.svc.cluster.local:3000;
    location ~ (/rocketchat|/livechat/|/sounds/|/websocket/) {
        auth_ldap off;
        rewrite /livechat/(.*)$ /rocketchat/livechat/$1 break;
        rewrite /sounds/(.*)$ /rocketchat/sounds/$1 break;
        proxy_pass $upstream_rocketchat;
	proxy_buffers 8 32k;
        proxy_buffer_size 64k;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-NginX-Proxy true;
        # enables WS support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 999999999;
     }

Nginx configured with AWS ELB and loaded with lets encrypt cert

When i connect to the app using the endpoint url its  throwing "invalid server version"

**Comment by TENsaga** [comment]
Same issue here. This may be related to #793

**Comment by rafaelks** [comment]
This issue is not valid anymore for version 2.0.0.
