### ISSUE TITLE
Uploading images results in it being uploaded twice

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat.Android#974]
Your Rocket.Chat.Android version: 1.1.0

Mobile device model and OS version: Every Android device available to us across many different OS versions

1. Upload an image.
2. Watch it upload then upload a second time.
3. Result is duplicated image. Irritating!

**Comment by rafaelks** [comment]
@HammyHavoc This is already fixed in 2.0.0, that's why I'm closing the issue.
