### ISSUE TITLE
[URGENT][BUG] Tapping on "Members" list navigates to the right with the icon of the room

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat.Android#985]
@leonardoaramaki Let's just do the same as we do on "Pinning message"

**Comment by leonardoaramaki** [comment]
@rafaelks Shouldn't we just remove/hide that icon? I think that will suffice. The sliding to the right is pretty intuitive. :)

**Comment by rafaelks** [comment]
Closing this one.
