### ISSUE TITLE
[NEW] Support 'favorites' for channels and users in chat list

### ISSUE THREAD

**Issue by jyellick** [RocketChat/Rocket.Chat.Android#988]
Your Rocket.Chat.Android version: v2.0.0-alpha1

The standard 'chats' view is a list of all users and channels that the current user has participated in.  There is currently no way to pin a particular user or channel to the top of this list like there is in the web-UI.  The web-UI uses the 'favorites' notion to create this pinned list, and it would be natural to extend this to the Android app.

This is related to, but different from #880 which addresses the order in which the chats are sorted (independent of 'favorites').

**Comment by FaizanZahid** [comment]
i am unable to see online users in android app, why?

**Comment by rafaelks** [comment]
Duplicates #1395
